### PR TITLE
[RTR] StochastiOCP merge

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/715)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 51 of 52 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/715)* status: all files reviewed, 17 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/examples/getting_started/pendulum.py` line 97 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_EMcr6-yopU5SBiVUk:-N_EMcr6-yopU5SBiVUl:b-a5woxa) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/examples/getting_started/pendulum.py#L97)):*
> ```Python
> 
>     s_bounds = BoundsList()
>     s_init = InitialGuessList()
> ```

Do not modify not relevent examples
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py` line 46 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_EN6kP-0UFyhpqR5n4:-N_EN6kP-0UFyhpqR5n5:b-4co0qr) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py#L46)):*
> ```Python
> 
> 
> class LeuvenArmModel:
> ```

This can be moved to a file next to this one to reduce the example file
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py` line 392 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_ENUAx68ARcbFqeBmj:-N_ENUAx68ARcbFqeBmk:b-qdwtwj) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py#L392)):*
> ```Python
> 
> 
> def get_ee(controller: PenaltyController, q, qdot) -> cas.MX:
> ```

end_effector
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py` line 839 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_ENjhn1L1yvs2MFdw2:-N_ENjhn1L1yvs2MFdw3:b-yus1cn) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py#L839)):*
> ```Python
>     stochastic_min = np.ones((n_stochastic, 3)) * -cas.inf
>     stochastic_max = np.ones((n_stochastic, 3)) * cas.inf
>     if not input_sol_FLAG:
> ```

do not capitalize
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py` line 953 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_ENrSX6r6BbU7rxOKp:-N_ENrSX6r6BbU7rxOKq:b-yus1cn) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py#L953)):*
> ```Python
>     RUN_OPTIM_FLAG = True  # False
>     PLOT_SOL_FLAG = False  # True
>     VIZUALIZE_SOL_FLAG = False  # True
> ```

do not capitalize
___
*[`bioptim/gui/plot.py` line 25 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_EP-qk-L9Y3bnu8Zwk:-N_EP-qk-L9Y3bnu8Zwl:bb7phvt) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/gui/plot.py#L25)):*
> ```Python
>     Attributes
>     ----------
>     function: Callable[states, controls, parameters, stochasti_variables]
> ```

typo
___
*[`bioptim/interfaces/solver_options.py` line 293 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_EQD92-bSflemDE2Jf:-N_EQD92-bSflemDE2Jg:b-5lpdqh) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/interfaces/solver_options.py#L293)):*
> ```Python
> 
>         def set_nlp_scaling_method(self, val: str):
>             self._nlp_scaling_method = val
> ```

Add this to the abstract and implement it into ACADOS as well (NotImplementError)
___
*[`bioptim/limits/multinode_constraint.py` line 103 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_EQbTJEVMG4CaYlpUh:-N_EQbTJEVMG4CaYlpUi:b-phdqhe) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/limits/multinode_constraint.py#L103)):*
> ```Python
>     COM_VELOCITY_EQUALITY = (MultinodeConstraintFunctions.Functions.com_velocity_equality,)
>     TIME_CONSTRAINT = (MultinodeConstraintFunctions.Functions.time_equality,)
>     M_EQUALS_INVERSE_OF_DG_DZ = (MultinodeConstraintFunctions.Functions.m_equals_inverse_of_dg_dz,)
> ```

CONTINUITY_FOR_STOCHASTIC_PROGRAM
___
*[`bioptim/limits/multinode_penalty.py` line 317 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_EQwhq05xOSEaOxSKf:-N_EQwhq05xOSEaOxSKg:b8tz8rk) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/limits/multinode_penalty.py#L317)):*
> ```Python
>         ):
>             """
>             ...
> ```

Explain what it does
___
*[`bioptim/limits/objective_functions.py` line 317 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_ER2E91S_lZnqmaAuX:-N_ER2E91S_lZnqmaAuY:b7c6qi4) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/limits/objective_functions.py#L317)):*
> ```Python
>         MINIMIZE_CONTROL = (PenaltyFunctionAbstract.Functions.minimize_controls,)
>         TRACK_CONTROL = (PenaltyFunctionAbstract.Functions.minimize_controls,)
>         MINIMIZE_STOCHASTIC_VARIABLE = (PenaltyFunctionAbstract.Functions.minimize_stochastic_variables,)
> ```

STOCHASTIC_MINIMIZE_VARIABLE
___
*[`bioptim/limits/penalty_controller.py` line 156 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_ERaKN2wshMS1O3zmH:-N_ERaKO5n4NKXrE6cW9:b-3u6yy1) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/limits/penalty_controller.py#L156)):*
> ```Python
> 
>     @property
>     def stochastic_variables(self) -> OptimizationVariableList:
> ```

Add a TODO to rename for algebraic
___
*[`bioptim/optimization/optimal_control_program.py` line 267 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_ES_4C2s5hGpLISCXy:-N_ES_4C2s5hGpLISCXz:bpmskve) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/optimization/optimal_control_program.py#L267)):*
> ```Python
>             x_bounds,
>             u_bounds,
>             s_bounds,
> ```

Add a TODO so OCP is unaware of s
___
*[`bioptim/optimization/optimization_vector.py` line 504 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_ETBpr3bwCWfCln3tO:-N_ETBpr3bwCWfCln3tP:b-olu2fu) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/optimization/optimization_vector.py#L504)):*
> ```Python
>                     s_array = v_array[offset : offset + nstochastic].reshape(
>                         (nlp.stochastic_variables.shape, -1), order="F"
>                     )  # @pariterre "F" seems like an interpolation?
> ```

F is for Fortran
___
*[`bioptim/optimization/problem_type.py` line 4 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_EVsGX6vADK7d-aLbC:-N_EVsGX6vADK7d-aLbD:b98up2i) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/optimization/problem_type.py#L4)):*
> ```Python
> 
> 
> class OcpType:
> ```

StochastiqueOcpType
___
*[`bioptim/optimization/stochastic_optimal_control_program.py` line 258 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_ETotd4G-QzGDmuOrB:-N_ETotd4G-QzGDmuOrC:bc3da7d) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/bioptim/optimization/stochastic_optimal_control_program.py#L258)):*
> ```Python
>                 )
> 
>         # Constrain P
> ```

Contraint
___
*[`tests/test_global_stochastic.py` line 94 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_EU5876DM5SZUBDVSb:-N_EU5876DM5SZUBDVSc:b5qfluq) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/tests/test_global_stochastic.py#L94)):*
> ```Python
> # 2  1.9623501e+00 1.98e+03 1.29e+03  -1.0 4.68e+00   3.3 1.13e-01 4.06e-03h  1
> # 3  4.0176536e+00 1.88e+03 1.24e+03  -1.0 4.55e+00   2.9 3.66e-01 5.30e-02h  1
> # 4  8.4440161e+00 1.65e+03 1.78e+03  -1.0 3.35e+00   3.3 2.20e-01 1.19e-01h  1
> ```

Do not keep
___
*[`tests/utils.py` line 65 at r2](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_EUqeu-diBzVw_hs7M:-N_EUqeu-diBzVw_hs7N:bu19si2) ([raw file](https://github.com/pyomeca/bioptim/blob/4004e44bc8e7ddfd6d821acb30f7bc7069997361/tests/utils.py#L65)):*
> ```Python
>         # @ Pariterre, merge problem ?
>         # os.remove(f"{file_path}.bo")
>         # os.remove(f"{file_path}_sa.bo")
> ```

This should be good

**Comment by EveCharbie** [comment]
@pariterre think we could merge?

**Review by pariterre — CHANGES_REQUESTED** [review]
Only two minors comment and we are good to go!

> Reviewed 33 of 33 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/715#-:-N_dIlgP5v87dTbKKROu:bylfeea)* status: all files reviewed, 4 unresolved discussions (waiting on @EveCharbie)

___
*[`OCP_equation.png` line 0 at r3](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_dF0kS-noyGRqhdSvG:-N_dF0kS-noyGRqhdSvH:bxrjjqn) ([raw file](https://github.com/pyomeca/bioptim/blob/7ef44d4d56b324dea3c605fd4f4a08f9deb498ae/OCP_equation.png#L0)):*
Is this useful/mandatory? If so, could it be replaced by a <100kB file?
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py` line 53 at r3](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_dFTzd51mK4GGbDZSr:-N_dFTzd51mK4GGbDZSs:b3fc35q) ([raw file](https://github.com/pyomeca/bioptim/blob/7ef44d4d56b324dea3c605fd4f4a08f9deb498ae/bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py#L53)):*
> ```Python
>     nlp: NonLinearProgram,
>     motor_noise,
>     sensory_noise,
> ```

I love those names!
___
*[`bioptim/examples/stochastic_optimal_control/LeuvenArmModel.py` line 5 at r3](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_dG4gPDc1jCydLSIBy:-N_dG4gPDc1jCydLSIBz:b71e4wo) ([raw file](https://github.com/pyomeca/bioptim/blob/7ef44d4d56b324dea3c605fd4f4a08f9deb498ae/bioptim/examples/stochastic_optimal_control/LeuvenArmModel.py#L5)):*
> ```Python
> """
> 
> from typing import Callable
> ```

Quick change can you name the file as snake_case_file?

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/715)* status: all files reviewed, 4 unresolved discussions (waiting on @pariterre)

___
*[`OCP_equation.png` line  at r3](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_dF0kS-noyGRqhdSvG:-N_dN0bv1vfGPnT5LzsB:b32w0x) ([raw file](https://github.com/pyomeca/bioptim/blob/7ef44d4d56b324dea3c605fd4f4a08f9deb498ae/OCP_equation.png#L)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is this useful/mandatory? If so, could it be replaced by a <100kB file?
</blockquote></details>

OK
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py` line 53 at r3](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_dFTzd51mK4GGbDZSr:-N_dNF4R0cwa5Zy1VKH0:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/7ef44d4d56b324dea3c605fd4f4a08f9deb498ae/bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py#L53)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I love those names!
</blockquote></details>

Done.
___
*[`bioptim/examples/stochastic_optimal_control/LeuvenArmModel.py` line 5 at r3](https://reviewable.io/reviews/pyomeca/bioptim/715#-N_dG4gPDc1jCydLSIBy:-N_dNXxjBoAVBeJ8X22F:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/7ef44d4d56b324dea3c605fd4f4a08f9deb498ae/bioptim/examples/stochastic_optimal_control/LeuvenArmModel.py#L5)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Quick change can you name the file as snake_case_file?
</blockquote></details>

Done.

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/715#-:-N_e3un52imRHwZdQ15L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
