### PR TITLE
[RTR] adressing node specific dynamics

### PR DESCRIPTION
**Pull request by Ipuch**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request? #621 
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/624)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/624)* status: all files reviewed, 4 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/dynamics/ode_solver.py` line 74 at r1](https://reviewable.io/reviews/pyomeca/bioptim/624#-NP-AJ0W7I2eO5sci8qM:-NP-AJ0W7I2eO5sci8qN:bu1c52j) ([raw file](https://github.com/pyomeca/bioptim/blob/79646b17cfa61086e28982c2e308a8d9d935d498/bioptim/dynamics/ode_solver.py#L74)):*
> ```Python
>         if len(nlp.dynamics) != 1 and ocp.n_threads != 1:
>             raise NotImplementedError("n_threads > 1 with external_forces is not implemented yet")
>         # if len(nlp.dynamics) == 1:
> ```

This should be kept



_Code quote:_
```Python
        # if len(nlp.dynamics) == 1:
        #     nlp.dynamics = nlp.dynamics * nlp.ns
```
___
*[`bioptim/examples/getting_started/example_external_forces.py` line 78 at r1](https://reviewable.io/reviews/pyomeca/bioptim/624#-NP-4pVQ0pu-aJne6YUl:-NP-4pVQ0pu-aJne6YUm:bdtc3ax) ([raw file](https://github.com/pyomeca/bioptim/blob/79646b17cfa61086e28982c2e308a8d9d935d498/bioptim/examples/getting_started/example_external_forces.py#L78)):*
> ```Python
>     external_forces = [[np.array([[0, 0, 0, 0, 0, -2], [0, 0, 0, 0, 0, 5]]).T for _ in range(n_shooting)]]
>     external_forces[0][2] = np.array([[0, 0, 0, 0, 0, -22], [0, 0, 0, 0, 0, 52]]).T
>     # external_forces[0][5] = np.array([[0, 0, 500, 0, 0, -2], [0, 0, 500, 0, 0, 5]]).T
> ```

Don't forget to clean up



_Code quote:_
```Python
    external_forces[0][2] = np.array([[0, 0, 0, 0, 0, -22], [0, 0, 0, 0, 0, 52]]).T
    # external_forces[0][5] = np.array([[0, 0, 500, 0, 0, -2], [0, 0, 500, 0, 0, 5]]).T
    # external_forces[0][8] = np.array([[0, 0, 500, 0, 0, -2], [0, 0, 500, 0, -1000, 5]]).T
    # external_forces[0][11] = np.array([[0, 0, 500, 0, 0, -2], [0, 0, 500, 0, 0, 5]]).T
    external_forces[0][14] = np.array([[0, 0, 0, 0, 0, 100], [0, 0, 0, 0, 0, -6]]).T
    # external_forces[0][17] = np.array([[0, 0, 500, 0, 0, -2], [0, 0, 500, 0, 0, 5]]).T
    # external_forces[0][20] = np.array([[0, 0, 500, 0, 0, -2], [0, 0, 500, 0, -1000, 5]]).T
```
___
*[`bioptim/limits/objective_functions.py` line 297 at r1](https://reviewable.io/reviews/pyomeca/bioptim/624#-NP-AiG4E9q9rtn7J319:-NP-AiG4E9q9rtn7J31A:b9vbt5o) ([raw file](https://github.com/pyomeca/bioptim/blob/79646b17cfa61086e28982c2e308a8d9d935d498/bioptim/limits/objective_functions.py#L297)):*
> ```Python
>         # Dynamics must be sound within phases
>         for nlp in ocp.nlp:
>             if len(nlp.dynamics) > 1:
> ```

This will always be the case



_Code quote:_
```Python
if len(nlp.dynamics) > 1:
```
___
*[`bioptim/optimization/solution.py` line 1032 at r1](https://reviewable.io/reviews/pyomeca/bioptim/624#-NP-BTgHAdXdU6J5Upkt:-NP-BTgHAdXdU6J5Upku:bo4dky8) ([raw file](https://github.com/pyomeca/bioptim/blob/79646b17cfa61086e28982c2e308a8d9d935d498/bioptim/optimization/solution.py#L1032)):*
> ```Python
> 
>             else:
>                 dynamics_func = nlp.dynamics * nlp.ns if len(nlp.dynamics) == 1 else nlp.dynamics
> ```

This will not be necessary

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/624)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/ode_solver.py` line 74 at r1](https://reviewable.io/reviews/pyomeca/bioptim/624#-NP-AJ0W7I2eO5sci8qM:-NP-DeAA3v_nvVFFb-oY:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/79646b17cfa61086e28982c2e308a8d9d935d498/bioptim/dynamics/ode_solver.py#L74)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should be kept
</blockquote></details>

Done
___
*[`bioptim/examples/getting_started/example_external_forces.py` line 78 at r1](https://reviewable.io/reviews/pyomeca/bioptim/624#-NP-4pVQ0pu-aJne6YUl:-NP-ROAt3MLlslHU6RfN:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/79646b17cfa61086e28982c2e308a8d9d935d498/bioptim/examples/getting_started/example_external_forces.py#L78)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Don't forget to clean up
</blockquote></details>

Done
___
*[`bioptim/limits/objective_functions.py` line 297 at r1](https://reviewable.io/reviews/pyomeca/bioptim/624#-NP-AiG4E9q9rtn7J319:-NP-DTsY17fw3aXi2OCH:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/79646b17cfa61086e28982c2e308a8d9d935d498/bioptim/limits/objective_functions.py#L297)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This will always be the case
</blockquote></details>

Done
___
*[`bioptim/optimization/solution.py` line 1032 at r1](https://reviewable.io/reviews/pyomeca/bioptim/624#-NP-BTgHAdXdU6J5Upkt:-NP-DUrI0x3uFJ8CFQDY:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/79646b17cfa61086e28982c2e308a8d9d935d498/bioptim/optimization/solution.py#L1032)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This will not be necessary
</blockquote></details>

Done

**Comment by Ipuch** [comment]
@pariterre PR ready to merge to me.

**Comment by Ipuch** [comment]
rk8 didn't fail but test_cyclic_nmpc failed this time .

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/624)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`tests/test_global_getting_started.py` line 860 at r6](https://reviewable.io/reviews/pyomeca/bioptim/624#-NPI74eN8GgFjrT7RlY1:-NPI74eN8GgFjrT7RlY2:bff716e) ([raw file](https://github.com/pyomeca/bioptim/blob/3e50f6225313072a31855bff7b2ab1cba3546135/tests/test_global_getting_started.py#L860)):*
> ```Python
>     f = np.array(sol.cost)
>     np.testing.assert_equal(f.shape, (1, 1))
>     np.testing.assert_almost_equal(f[0, 0], 7067.851604540213)
> ```

Is this expected?



_Code quote:_
```Python
7067.851604540213
```

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/624#-:-NPYwvgy4CojivY8wXzo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Pull request merged**
