### PR TITLE
[RTM] multi-start values testing

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/570)

### CODE REVIEW

**Review by EveCharbie — COMMENTED** [review]
This PR was not RTR. Yes I merged Rapidnico's branch into mine in the mean time. But I will surely wait until his PR is accepted before asking you to review ;)

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/570#-:-NFxh4GWCqoMsxRdtUld:b7t0d7b)* status: all files reviewed, 3 unresolved discussions (waiting on @EveCharbie)

**Review by pariterre — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/570)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/570#-:-NGWxI5cCmxYrRdUpN47:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Comment by pariterre** [comment]
@EveCharbie  RTM?

**Comment by EveCharbie** [comment]
@pariterre yep :)

**Pull request merged**
