### PR TITLE
Implemented time in dynamic

### PR DESCRIPTION
**Pull request by pariterre**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/843)

### CODE REVIEW

**Review by EveCharbie — COMMENTED** [review]
Thanks a lot for this PR :)

> Reviewed 25 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/843#-:-NqcTmxQ5RVylmkpe0fN:b-sxskam)* status: 25 of 30 files reviewed, 5 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/limits/penalty_controller.py` line 135 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcK0zF-Y--ETMZE2c2:-NqcK0zGD2f-dzAQAPqx:bt40iji) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/bioptim/limits/penalty_controller.py#L135)):*
> ```Python
>         mx = vertcat(self.time.mx, dt_mx)
>         dt_cx = self.dt.cx
>         cx = vertcat(self.time.cx, dt_cx)
> ```

This would be easier for me to understand:
```
mx = vertcat(self.time.mx, self.dt.mx)
cx = vertcat(self.time.cx, self.dt.cx)
```



_Code quote:_
```Python
        dt_mx = self.dt.mx
        mx = vertcat(self.time.mx, dt_mx)
        dt_cx = self.dt.cx
        cx = vertcat(self.time.cx, dt_cx)
```
___
*[`bioptim/limits/penalty_controller.py` line 182 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcLlqNEbIY8fymy_9i:-NqcLlqNEbIY8fymy_9j:bxog7bz) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/bioptim/limits/penalty_controller.py#L182)):*
> ```Python
> 
>         tp = OptimizationVariableList(self._nlp.cx, self._nlp.phase_dynamics == PhaseDynamics.SHARED_DURING_THE_PHASE)
>         n_val = self._nlp.time_mx.shape[0]
> ```

I thought time.mx was going to replace completely time_mx?



_Code quote:_
```Python
time_mx
```
___
*[`bioptim/limits/penalty_controller.py` line 198 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcLuvL-PYUUYq4Tjt3:-NqcLuvL-PYUUYq4Tjt4:b-7jl26k) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/bioptim/limits/penalty_controller.py#L198)):*
> ```Python
> 
>         tp = OptimizationVariableList(self._nlp.cx, self._nlp.phase_dynamics == PhaseDynamics.SHARED_DURING_THE_PHASE)
>         n_val = self._nlp.tf_mx.shape[0]
> ```

same?



_Code quote:_
```Python
tf_mx
```
___
*[`tests/shard2/test_cost_function_integration.py` line 262 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcShLbAcXLXKrVqcb_:-NqcShLbAcXLXKrVqcba:blqqsx2) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/tests/shard2/test_cost_function_integration.py#L262)):*
> ```Python
>                 np.testing.assert_almost_equal(j_printed, 34.52084504124038)
>             else:
>                 np.testing.assert_almost_equal(f[0, 0], 17.72098984554101)
> ```

Is that the bug that was fixed for trapezoidal integration of penalties ?



_Code quote:_
```Python
17.72098984554101
```
___
*[`tests/shard4/test_solution.py` line 36 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcTbvH4IrZ67SB_Uki:-NqcTbvH4IrZ67SB_Ukj:b-dunmph) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/tests/shard4/test_solution.py#L36)):*
> ```Python
>         np.testing.assert_almost_equal(time[4], 0.8)
>     else:
>         np.testing.assert_almost_equal(time.shape, (51, 1))
> ```

Could you explain why the shape of the time vector has changed not by x2 ? 



_Code quote:_
```Python
(51, 1)
```

**Review by pariterre — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/843)* status: 20 of 31 files reviewed, 9 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/limits/penalty_controller.py` line 135 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcK0zF-Y--ETMZE2c2:-NqcWBH1CanHqjQoTX_s:bvrs21s) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/bioptim/limits/penalty_controller.py#L135)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

This would be easier for me to understand:
```
mx = vertcat(self.time.mx, self.dt.mx)
cx = vertcat(self.time.cx, self.dt.cx)
```
</blockquote></details>

Indeed, done
___
*[`bioptim/limits/penalty_controller.py` line 182 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcLlqNEbIY8fymy_9i:-NqcWDur0ua-_l7BGzLQ:b-yfesid) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/bioptim/limits/penalty_controller.py#L182)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

I thought time.mx was going to replace completely time_mx?
</blockquote></details>

`nlp.time_mx`is what is return by the controller. From the user standpoint, they should indeed not use `time_mx` but they should use `time.mx` (or .cx) but this value still need to be attached to the actual variable of the problem, which are still stored in nlp.
In brief, this means even though `nlp.time_mx` exists, here is the only place that it should be referenced
___
*[`bioptim/limits/penalty_controller.py` line 198 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcLuvL-PYUUYq4Tjt3:-NqcWsfO9wfhjct5h0Mj:b-bixvkt) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/bioptim/limits/penalty_controller.py#L198)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

same?
</blockquote></details>

Same answer, this is to contruct the `tf` OptimizationVariable. Another way could have been to directly store this `OptimizationVariable` in nlp.tf, which would be a good idea to standardize the use of time accross bioptim. This required a bit of extra work that I did not put in, and decided it was okay to simply create an interface on the spot each time tf is called. But I agree this would be cleaner to store tf (and other time related variables) in nlp in the first place!  Maybe a "good first issue"?
___
*[`bioptim/optimization/solution/solution.py` line 10 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcBiHf7ny0C3tahhJ6:-NqcBiHf7ny0C3tahhJ7:bwrd2il) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/bioptim/optimization/solution/solution.py#L10)):*
> ```Python
> from matplotlib import pyplot as plt
> 
> from .solution_data import SolutionData, SolutionMerge, TimeAlignment, TimeResolution
> ```

TimeResolution is not necessary anymore
Done
___
*[`bioptim/optimization/solution/solution.py` line 336 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcBfzH9y36_A8VH9l4:-NqcBfzH9y36_A8VH9l5:bmllo2m) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/bioptim/optimization/solution/solution.py#L336)):*
> ```Python
>         to_merge: SolutionMerge | list[SolutionMerge] = None,
>         continuous: bool = True,
>     ) -> list | np.ndarray:
> ```

Remove this interface
Done
___
*[`bioptim/optimization/solution/solution.py` line 563 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcBZMCDb-OLnqhmwCC:-NqcBZMCDb-OLnqhmwCD:bmllo2m) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/bioptim/optimization/solution/solution.py#L563)):*
> ```Python
>             raise NotImplementedError("NODE_SPAN is not implemented for states")
>         else:
>             raise ValueError("Unrecognized time_resolution")
> ```

Remove this interface
Done
___
*[`bioptim/optimization/solution/solution.py` line 612 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcBbes47gzgbQqkAQ0:-NqcBbes47gzgbQqkAQ1:bbgk37y) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/bioptim/optimization/solution/solution.py#L612)):*
> ```Python
>         return data if len(data) > 1 else data[0]
> 
>     def controls(
> ```

Remove this interface

**Review by pariterre — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/843)* status: 20 of 31 files reviewed, 9 unresolved discussions (waiting on @EveCharbie)

___
*[`tests/shard2/test_cost_function_integration.py` line 262 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcShLbAcXLXKrVqcb_:-NqcwDdfAB04siZKiL02:bguygbl) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/tests/shard2/test_cost_function_integration.py#L262)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

Is that the bug that was fixed for trapezoidal integration of penalties ?
</blockquote></details>

Yes, this value has changed from the old_master to the new_master. I double checked by computing the value using the LINEAR_CONTINUOUS as if it was CONSTANT and compared with CONSTANT and the new values correspond. Since I haven't done such testing previously, I trust more the new values
___
*[`tests/shard4/test_solution.py` line 36 at r1](https://reviewable.io/reviews/pyomeca/bioptim/843#-NqcTbvH4IrZ67SB_Uki:-NqcwcfDEjuBgdTQ-3-X:bh5so96) ([raw file](https://github.com/pyomeca/bioptim/blob/8caa5f19ada633baf8541e630926c4c75e18c404/tests/shard4/test_solution.py#L36)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

Could you explain why the shape of the time vector has changed not by x2 ?
</blockquote></details>

Because time is now fully alligned with its underlying structure. So I you align with DECISION_STATES for RK4, you expect only one value per node. Previously it was always returning t_span, that is initial time of the node and final time of the node. This does not correspond with the expected alignment of states. If `time` was retrieved using `t_span` then it would be 101.

**Review by pariterre — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/843#-:-NqdCDn1Du1Rs8N8uPx1:bnfp4nl)* status: 20 of 31 files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
