### PR TITLE
Fixing some problem MULTIPROCESS_SERVER

### PR DESCRIPTION
**Pull request by pariterre**
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/888)

### CODE REVIEW

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/888)* status: all files reviewed, 10 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/gui/online_callback_server.py` line 41 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3n6jqREhWqPK895WCc:-O3n6jqREhWqPK895WCd:b2ufqnb) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L41)):*
> ```Python
> 
> 
> class _HeaderMessage(StrEnum):
> ```

_HeaderResponse ?
___
*[`bioptim/gui/online_callback_server.py` line 73 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3n7C1b0HIFeQANnKaE:-O3n7C1b0HIFeQANnKaF:b-m4r8k7) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L73)):*
> ```Python
>     @intstaticproperty
>     def header_generic_len() -> int:
>         return 1024
> ```

HEADER_GENERIC_LENGTH = 1024
___
*[`bioptim/gui/online_callback_server.py` line 332 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nAQL-6OOpaljyAj9z:-O3nAQL-6OOpaljyAjA-:bdndx8h) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L332)):*
> ```Python
>             for phase_times in data_json["dummy_phase_times"]:
>                 dummy_time_vector.append([DM(v) for v in phase_times])
>             del data_json["dummy_phase_times"]
> ```

comprehension list 



_Code quote:_
```Python
            dummy_time_vector = []
            for phase_times in data_json["dummy_phase_times"]:
                dummy_time_vector.append([DM(v) for v in phase_times])
            del data_json["dummy_phase_times"]
```
___
*[`bioptim/gui/online_callback_server.py` line 480 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nBIDYEox3dAB4pUsA:-O3nBIDYEox3dAB4pUsB:brx99gy) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L480)):*
> ```Python
> 
>         self._host = host if host else _DEFAULT_HOST
>         self._port = port if port else _DEFAULT_PORT
> ```

initialize with super the object first



_Code quote:_
```Python
        self._host = host if host else _DEFAULT_HOST
        self._port = port if port else _DEFAULT_PORT
```
___
*[`bioptim/gui/online_callback_server.py` line 521 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nBU7m-yiTipE_K5up:-O3nBU7m-yiTipE_K5uq:b3kqx) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L521)):*
> ```Python
>                     "Could not connect to the plotter server, make sure it is running by calling 'PlottingServer()' on "
>                     "another python instance or allowing for automatic start (Linux or Windows) of the server setting "
>                     "the online_option to 'OnlineOptim.MULTIPROCESS_SERVER' when instantiating your solver"
> ```

.
___
*[`bioptim/gui/online_callback_server.py` line 611 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nBp4FDoFHV7FfcHGw:-O3nBp4FDoFHV7FfcHGx:b-pqqee) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L611)):*
> ```Python
>         if (
>             self._should_wait_ok_to_client_on_new_data
>             and self._socket.recv(_HeaderMessage.header_len).decode() != _HeaderMessage.OK
> ```

has_received_OK
___
*[`bioptim/gui/online_callback_server.py` line 619 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nCAOT2b81NB1jv-Xh:-O3nCAOU8t1Vd2ipaH3o:bb6xlm0) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L619)):*
> ```Python
>         if (
>             self._should_wait_ok_to_client_on_new_data
>             and self._socket.recv(_HeaderMessage.header_len).decode() != _HeaderMessage.OK
> ```

Idem
___
*[`bioptim/gui/utils.py` line 1 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nD6C340hoyzyTeEdD:-O3nD6C340hoyzyTeEdE:bqqdqce) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/utils.py#L1)):*
> ```Python
> class strstaticproperty:
> ```

"""custom decorators for str"""
___
*[`bioptim/gui/utils.py` line 9 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nDAto9LX2WiD29pLf:-O3nDAtp2v9c2BGll3nq:blwo0tc) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/utils.py#L9)):*
> ```Python
> 
> 
> class intstaticproperty:
> ```

"""custom decorators for int"""
___
*[`bioptim/interfaces/interface_utils.py` line 36 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nDeaN8Hk41ZanhSCK:-O3nDeaN8Hk41ZanhSCL:bn4qwwp) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/interfaces/interface_utils.py#L36)):*
> ```Python
> 
>     online_optim = interface.opts.online_optim.get_default()
>     if online_optim == OnlineOptim.MULTIPROCESS:
> ```

map_onlineoptim_to_online_callback = {
OnlineOptim.MULTIPROCESS: OnlineCallbackMultiprocess,
OnlineOptim.MULTIPROCESS_SERVER : OnlineCallbackServer,
...,
}

online_callback = map_onlineoptim_to_online_callback.get(online_optim, None)

if online_callback is None:
    raise ....

**Comment by Ipuch** [comment]
Minimal test if needed.

**Review by pariterre — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/888)* status: 11 of 14 files reviewed, 10 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/gui/online_callback_server.py` line 41 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3n6jqREhWqPK895WCc:-O3nKn_L4cVnaVrZG_Nd:b-ntvn36) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L41)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

_HeaderResponse ?
</blockquote></details>

_ResponseHeader done
And found a way to do what should have been done previously
___
*[`bioptim/gui/online_callback_server.py` line 73 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3n7C1b0HIFeQANnKaE:-O3nTrdP-o8mAX2dw-4z:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L73)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

HEADER_GENERIC_LENGTH = 1024
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 332 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nAQL-6OOpaljyAj9z:-O3nL3qX-xAPWAg7nn1K:b-3ug40m) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L332)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

comprehension list
</blockquote></details>

This would be a double list comprehension, it is probably clearer to keep it as is
___
*[`bioptim/gui/online_callback_server.py` line 480 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nBIDYEox3dAB4pUsA:-O3nLCl-8LplYSQRuPcI:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L480)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

initialize with super the object first
</blockquote></details>

Done
___
*[`bioptim/gui/online_callback_server.py` line 521 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nBU7m-yiTipE_K5up:-O3nLFAZCAzN9RPhW9iv:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L521)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 611 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nBp4FDoFHV7FfcHGw:-O3nLn0eClPqswSVfSt2:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L611)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

has_received_OK
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 619 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nCAOT2b81NB1jv-Xh:-O3nLnnPDMW167bSA0_8:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/online_callback_server.py#L619)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Idem
</blockquote></details>

Done.
___
*[`bioptim/interfaces/interface_utils.py` line 36 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nDeaN8Hk41ZanhSCK:-O3nNEGJ9v3qATZlPLRP:bhfnngu) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/interfaces/interface_utils.py#L36)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

map_onlineoptim_to_online_callback = {
OnlineOptim.MULTIPROCESS: OnlineCallbackMultiprocess,
OnlineOptim.MULTIPROCESS_SERVER : OnlineCallbackServer,
...,
}

online_callback = map_onlineoptim_to_online_callback.get(online_optim, None)

if online_callback is None:
    raise ....
</blockquote></details>

This looks much more confusing to me, while taking more lines, sticking with previous :P
___
*[`bioptim/gui/utils.py` line 1 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nD6C340hoyzyTeEdD:-O3nLwTJ1QUb18jfeaEA:ba3dfob) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/utils.py#L1)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

"""custom decorators for str"""
</blockquote></details>

Removed
___
*[`bioptim/gui/utils.py` line 9 at r2](https://reviewable.io/reviews/pyomeca/bioptim/888#-O3nDAto9LX2WiD29pLf:-O3nLwe6-5uCKH21Un4e:ba3dfob) ([raw file](https://github.com/pyomeca/bioptim/blob/a688b91947b9a3a3fd1e28938236c02344da36ff/bioptim/gui/utils.py#L9)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

"""custom decorators for int"""
</blockquote></details>

Removed

**Review by Ipuch — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/888#-:-O3neWBo2xAru6INUzxo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pariterre)

**Pull request merged**
