### PR TITLE
[RTR] Refactor Integration

### PR DESCRIPTION
**Pull request by Ipuch**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/534)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
Check the tests and there we are happy!

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/534#-:-NC1mGZI6edA8pmxe7bE:b-j48qsx)* status: all files reviewed, 9 unresolved discussions (waiting on @Ipuch)

___
*[`README.md` line 1364 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1fAMf65O3rn07eJXn:-NC1fAMf65O3rn07eJXo:b-34rfup) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/README.md#L1364)):*
> ```Markdown
> # single-phase case
> q = sol.states["q"]  # generalized coordinates
> q = sol.states["all"] # all states
> ```

There should be two spaces (all"]  # all) between the code and the comments



_Suggestion:_
```Markdown
]  # all state
```
___
*[`README.md` line 1423 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1fpEiCIxNLsgji25b:-NC1fpEj7ZFkpWP-Lqbw:undefined) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/README.md#L1423)):*
> ```Markdown
> 
> Let's finish with `shooting_type = Shooting.MULTIPLE`,
> please not that this cannot be used with `keep_intermediates_points=False`.
> ```





_Suggestion:_
```Markdown
note
```
___
*[`bioptim/examples/torque_driven_ocp/models/slider.bioMod` line 7 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1gj90B2yK2aLGgzPD:-NC1gj90B2yK2aLGgzPE:b-bh4ac8) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/bioptim/examples/torque_driven_ocp/models/slider.bioMod#L7)):*
> ```
> segment Seg1
>     translations y
>     ranges 	-1 1
> ```

Please be coherent :P
___
*[`bioptim/gui/plot.py` line 643 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1hJPmDAnMt_U-PMfw:-NC1hJPmDAnMt_U-PMfx:b-vfv9o5) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/bioptim/gui/plot.py#L643)):*
> ```Python
>                 else nlp.ode_solver.steps + 1
>             )
>             # n_elements = nlp.ns * step_size + 1
> ```

Remove comments



_Code quote:_
```Python
            # n_elements = nlp.ns * step_size + 1
            # n_elements = nlp.ns * step_size  # seems like it could work in DMS but no in DC
```
___
*[`bioptim/optimization/solution.py` line 701 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1j81pDUhLlek_gzbg:-NC1j81pDUhLlek_gzbh:undefined) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/bioptim/optimization/solution.py#L701)):*
> ```Python
>         return out
> 
>     def _generate_ocp_time(
> ```





_Suggestion:_
```Python
_generate_time
```
___
*[`bioptim/optimization/solution.py` line 759 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1iuMy8WXJQ8JIkGqx:-NC1iuMy8WXJQ8JIkGqy:b-px7vhx) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/bioptim/optimization/solution.py#L759)):*
> ```Python
>             # add the final time of the phase
>             if shooting_type == Shooting.MULTIPLE:
>                 # flat_time[-1] = np.concatenate((flat_time[-1], np.array([nlp.ns * dt_ns])))
> ```

keep this?



_Code quote:_
```Python
# flat_time[-1] = np.concatenate((flat_time[-1], np.array([nlp.ns * dt_ns])))
```
___
*[`tests/test_simulate.py` line 344 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1ky9UBFFg2u6TzpB0:-NC1ky9UBFFg2u6TzpB1:b91l0l9) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/tests/test_simulate.py#L344)):*
> ```Python
>         np.testing.assert_almost_equal(
>             sol_integrated.states["q"][:, [0, -1]],
>             # np.array([[0.0, -0.40229917], [0.0, 2.66577734]]),
> ```

This is unlikely that it should change: either explain why (and remove the comment) or correct your code!



_Code quote:_
```Python
# np.array([[0.0, -0.40229917], [0.0, 2.66577734]]),
```
___
*[`tests/test_simulate.py` line 561 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1lrszB5RBxUMosct7:-NC1lrszB5RBxUMosct8:b45h) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/tests/test_simulate.py#L561)):*
> ```Python
> @pytest.mark.parametrize("merge", [False, True])
> @pytest.mark.parametrize("integrator", [SolutionIntegrator.OCP, SolutionIntegrator.SCIPY_RK45])
> def test_integrate_2(shooting, merge, integrator, ode_solver):
> ```





_Suggestion:_
```Python
test_integrate_all_cases
```
___
*[`tests/test_simulate.py` line 571 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1lFMl7MN8exe-5mVC:-NC1lFMl7MN8exe-5mVD:bcb7xux) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/tests/test_simulate.py#L571)):*
> ```Python
>     ocp = ocp_module.prepare_ocp(
>         biorbd_model_path=bioptim_folder + "/models/pendulum.bioMod",
>         final_time=1,
> ```

Make sure this test works with 0.9



_Code quote:_
```Python
final_time=1,
```

**Review by pariterre — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/534)* status: all files reviewed, 12 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/interfaces/solve_ivp_interface.py` line 145 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1t20sAJ-kI1BTZl9L:-NC1t20t1c1wf1fZUPPg:undefined) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/bioptim/interfaces/solve_ivp_interface.py#L145)):*
> ```Python
> 
> 
> def piecewise_constant_u(t: float, t_eval: Union[np.ndarray, List[float]], u: np.ndarray) -> float:
> ```





_Suggestion:_
```Python
t: float, t_u: Union[np.ndarray, List[float]]
```
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 202 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1t8gnAlFufgdiN2Jx:-NC1t8gnAlFufgdiN2Jy:bc90ret) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/bioptim/interfaces/solve_ivp_interface.py#L202)):*
> ```Python
>             index of the closest previous time in t_eval to t
>         """
>         return previous_t(t, t_eval) - 1 if previous_t(t, t_eval) == len(t_eval) - 1 else previous_t(t, t_eval)
> ```

```python
out = previous_t(t, t_eval)
if out == len(t_eval):
    out = out[:-1]
return out
```



_Code quote:_
```Python
return previous_t(t, t_eval) - 1 if previous_t(t, t_eval) == len(t_eval) - 1 else previous_t(t, t_eval)
```
___
*[`tests/test_simulate.py` line 337 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1oKC5CWHtjm3fo2TC:-NC1oKC5CWHtjm3fo2TD:b-sb661l) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/tests/test_simulate.py#L337)):*
> ```Python
>     sol_integrated = sol.integrate(**opts)
>     shapes = (4, 2, 2)
>     assert np.shape(sol_integrated.states["all"])[1] == np.shape(sol_integrated._time_vector)[1]
> ```

Each time this appears, make sure it is intended that the internal time vector should be that size (as opposed to the time vector provided by the API)



_Code quote:_
```Python
assert np.shape(sol_integrated.states["all"])[1] == np.shape(sol_integrated._time_vector)[1]
```

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/534)* status: 13 of 15 files reviewed, 12 unresolved discussions (waiting on @pariterre)

___
*[`README.md` line 1364 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1fAMf65O3rn07eJXn:-NC6Jpqb0fbu0396Q_wB:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/README.md#L1364)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

There should be two spaces (all"]  # all) between the code and the comments
</blockquote></details>

Done
___
*[`README.md` line 1423 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1fpEiCIxNLsgji25b:-NC6JxMsEgQcuTenv-D-:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/README.md#L1423)):*
> ```Markdown
> 
> Let's finish with `shooting_type = Shooting.MULTIPLE`,
> please not that this cannot be used with `keep_intermediates_points=False`.
> ```

Done
___
*[`bioptim/examples/torque_driven_ocp/models/slider.bioMod` line 7 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1gj90B2yK2aLGgzPD:-NC6KOWp9XRKRlo7rat3:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/bioptim/examples/torque_driven_ocp/models/slider.bioMod#L7)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please be coherent :P
</blockquote></details>

Done
___
*[`bioptim/gui/plot.py` line 643 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1hJPmDAnMt_U-PMfw:-NC6KT9o08ssxo43KP4_:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/bioptim/gui/plot.py#L643)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Remove comments
</blockquote></details>

Done
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 145 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1t20sAJ-kI1BTZl9L:-NC6KWBS16lbxqQJ0Nd-:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/bioptim/interfaces/solve_ivp_interface.py#L145)):*
> ```Python
> 
> 
> def piecewise_constant_u(t: float, t_eval: Union[np.ndarray, List[float]], u: np.ndarray) -> float:
> ```

Done
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 202 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1t8gnAlFufgdiN2Jx:-NC6KXECAPsHRByxcxZj:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/bioptim/interfaces/solve_ivp_interface.py#L202)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

```python
out = previous_t(t, t_eval)
if out == len(t_eval):
    out = out[:-1]
return out
```

</blockquote></details>

done
___
*[`bioptim/optimization/solution.py` line 701 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1j81pDUhLlek_gzbg:-NC6Kuo6BR6yBm-SZ-PY:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/bioptim/optimization/solution.py#L701)):*
> ```Python
>         return out
> 
>     def _generate_ocp_time(
> ```

done
___
*[`bioptim/optimization/solution.py` line 759 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1iuMy8WXJQ8JIkGqx:-NC6Kw5YEZKnjUIuLTJ6:b-hfpv0l) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/bioptim/optimization/solution.py#L759)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

keep this?
</blockquote></details>

removed
___
*[`tests/test_simulate.py` line 337 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1oKC5CWHtjm3fo2TC:-NC6LMqb83wrqUEcz1EF:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/tests/test_simulate.py#L337)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Each time this appears, make sure it is intended that the internal time vector should be that size (as opposed to the time vector provided by the API)
</blockquote></details>

done
___
*[`tests/test_simulate.py` line 344 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1ky9UBFFg2u6TzpB0:-NC6Lfii0ovHqqospFVE:bumj8gr) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/tests/test_simulate.py#L344)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This is unlikely that it should change: either explain why (and remove the comment) or correct your code!
</blockquote></details>

restored
___
*[`tests/test_simulate.py` line 561 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1lrszB5RBxUMosct7:-NC6LPn-4_aJz4jenkWC:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/tests/test_simulate.py#L561)):*
> ```Python
> @pytest.mark.parametrize("merge", [False, True])
> @pytest.mark.parametrize("integrator", [SolutionIntegrator.OCP, SolutionIntegrator.SCIPY_RK45])
> def test_integrate_2(shooting, merge, integrator, ode_solver):
> ```

done
___
*[`tests/test_simulate.py` line 571 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1lFMl7MN8exe-5mVC:-NC6LXTV4Dpa6K6jcrQA:bbzqar8) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/tests/test_simulate.py#L571)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Make sure this test works with 0.9
</blockquote></details>

It does either with .9 and 1 sec.

**Comment by Ipuch** [comment]
RTM @pariterre ?

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/534#-:-NCL5R1M-1eERYzHzHNO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`tests/test_simulate.py` line 344 at r1](https://reviewable.io/reviews/pyomeca/bioptim/534#-NC1ky9UBFFg2u6TzpB0:-NCL5I6ZDPYeTjgkXEEf:b-7xteif) ([raw file](https://github.com/pyomeca/bioptim/blob/eee6e42ef39acc97ab34688de3e83d74a77d3ea7/tests/test_simulate.py#L344)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

restored
</blockquote></details>

Yeah!

**Pull request merged**
