### PR TITLE
[RTR] Maintain biorbdModel and MultiBiorbdModel health

### PR DESCRIPTION
**Pull request by Ipuch**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

Small refactor, everything looks cleaner, and better looking to track potential bugs.
Also spots some errors.

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/662)

### CODE REVIEW

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/662)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/interfaces/biorbd_model.py` line 53 at r1](https://reviewable.io/reviews/pyomeca/bioptim/662#-NUbIKUP167tlsYQBrQX:-NUbIKUP167tlsYQBrQY:by3kb4l) ([raw file](https://github.com/pyomeca/bioptim/blob/f9eeb635d3f1a39fb8a5d8c4cc116cdd0b22769d/bioptim/interfaces/biorbd_model.py#L53)):*
> ```Python
>             if "q" not in mapping:
>                 mapping["q"] = BiMapping(range(model.nb_q), range(model.nb_q))
>             mapping["qdot"] = mapping["q"]
> ```

I think we should not imply links between the q and qdot mappings.
Maybe I forgot to remove it there when I did my last PR removing think artificial link between q and qdot



_Code quote:_
```Python
            if "q" not in mapping:
                mapping["q"] = BiMapping(range(model.nb_q), range(model.nb_q))
            mapping["qdot"] = mapping["q"]
```
___
*[`bioptim/interfaces/biorbd_model.py` line 75 at r1](https://reviewable.io/reviews/pyomeca/bioptim/662#-NUbIz2EAQ0an4P2UOxH:-NUbIz2EAQ0an4P2UOxI:bb7od0r) ([raw file](https://github.com/pyomeca/bioptim/blob/f9eeb635d3f1a39fb8a5d8c4cc116cdd0b22769d/bioptim/interfaces/biorbd_model.py#L75)):*
> ```Python
>                     mapping["q"] = BiMapping(range(model.nb_q), range(model.nb_q))
>                 mapping["qdot"] = mapping["q"]
>                 mapping["qddot"] = mapping["qdot"]
> ```

same



_Code quote:_
```Python
        elif "qdot" not in mapping:
            if model.nb_quaternions > 0:
                mapping["qdot"] = BiMapping(range(model.nb_qdot), range(model.nb_qdot))
                mapping["qddot"] = mapping["qdot"]
            else:
                if "q" not in mapping:
                    mapping["q"] = BiMapping(range(model.nb_q), range(model.nb_q))
                mapping["qdot"] = mapping["q"]
                mapping["qddot"] = mapping["qdot"]
```
___
*[`bioptim/interfaces/biorbd_model.py` line 280 at r1](https://reviewable.io/reviews/pyomeca/bioptim/662#-NUbJS8a-YP-QN1d6SRW:-NUbJS8bEQKo7tIsRfQo:bgz81gm) ([raw file](https://github.com/pyomeca/bioptim/blob/f9eeb635d3f1a39fb8a5d8c4cc116cdd0b22769d/bioptim/interfaces/biorbd_model.py#L280)):*
> ```Python
>         qdot_biorbd = GeneralizedVelocity(qdot)
>         qddot_joints_biorbd = GeneralizedAcceleration(qddot_joints)
>         return self.model.ForwardDynamicsFreeFloatingBase(q_biorbd, qdot_biorbd, qddot_joints_biorbd).to_mx()
> ```

This will be in conflict with lsechoir's and AnaisFarr's PRs, please wait before merging



_Code quote:_
```Python
    def forward_dynamics_free_floating_base(self, q, qdot, qddot_joints) -> MX:
        q_biorbd = GeneralizedCoordinates(q)
        qdot_biorbd = GeneralizedVelocity(qdot)
        qddot_joints_biorbd = GeneralizedAcceleration(qddot_joints)
        return self.model.ForwardDynamicsFreeFloatingBase(q_biorbd, qdot_biorbd, qddot_joints_biorbd).to_mx()
```

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/662)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/interfaces/biorbd_model.py` line 53 at r1](https://reviewable.io/reviews/pyomeca/bioptim/662#-NUbIKUP167tlsYQBrQX:-NUbOvGC4Ew8hoMqW63j:bl40ino) ([raw file](https://github.com/pyomeca/bioptim/blob/f9eeb635d3f1a39fb8a5d8c4cc116cdd0b22769d/bioptim/interfaces/biorbd_model.py#L53)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

I think we should not imply links between the q and qdot mappings.
Maybe I forgot to remove it there when I did my last PR removing think artificial link between q and qdot
</blockquote></details>

Discussed.
___
*[`bioptim/interfaces/biorbd_model.py` line 75 at r1](https://reviewable.io/reviews/pyomeca/bioptim/662#-NUbIz2EAQ0an4P2UOxH:-NUbOwku8gtCIMvAKnmt:bf6fkly) ([raw file](https://github.com/pyomeca/bioptim/blob/f9eeb635d3f1a39fb8a5d8c4cc116cdd0b22769d/bioptim/interfaces/biorbd_model.py#L75)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

same
</blockquote></details>

Discussed.
___
*[`bioptim/interfaces/biorbd_model.py` line 280 at r1](https://reviewable.io/reviews/pyomeca/bioptim/662#-NUbJS8a-YP-QN1d6SRW:-NUbOrnL6ItvHPJc0aO0:b-aagbl8) ([raw file](https://github.com/pyomeca/bioptim/blob/f9eeb635d3f1a39fb8a5d8c4cc116cdd0b22769d/bioptim/interfaces/biorbd_model.py#L280)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

This will be in conflict with lsechoir's and AnaisFarr's PRs, please wait before merging
</blockquote></details>

I'll wait. (y)

**Review by pariterre — DISMISSED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/662)* status: all files reviewed, 3 unresolved discussions (waiting on @EveCharbie)

**Comment by Ipuch** [comment]
@lsechoir Could you please try your example on my branch
multimode + freefloatingbase + mappings :)

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r3, 3 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/662#-:-NUc_50-EPN_YOYK_XWq:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @EveCharbie)

**Pull request merged**
