### PR TITLE
[RTR] s_scaling good version

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/734)

### CODE REVIEW

**Comment by EveCharbie** [comment]
@pariterre test problem, we might have to wait to see if @mickaelbegon fixes it in his PR.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/734)* status: all files reviewed, 6 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/dynamics/configure_problem.py` line 912 at r1](https://reviewable.io/reviews/pyomeca/bioptim/734#-NavbFYSBkW7LpKUEhDX:-NavbFYSBkW7LpKUEhDY:b3kre) ([raw file](https://github.com/pyomeca/bioptim/blob/2efeec066561bf11f0c1bf1a8be64805b2daf797/bioptim/dynamics/configure_problem.py#L912)):*
> ```Python
>                 ConfigureProblem.append_faked_optim_var(name, nlp.controls.scaled, var_names_with_suffix)
>                 ConfigureProblem.append_faked_optim_var(name, nlp.controls.unscaled, var_names_with_suffix)
>                 # Nope
> ```

?
___
*[`bioptim/dynamics/configure_problem.py` line 917 at r1](https://reviewable.io/reviews/pyomeca/bioptim/734#-NavbGmk8TIxAj0jvG2a:-NavbGmk8TIxAj0jvG2b:b3kre) ([raw file](https://github.com/pyomeca/bioptim/blob/2efeec066561bf11f0c1bf1a8be64805b2daf797/bioptim/dynamics/configure_problem.py#L917)):*
> ```Python
>                     ConfigureProblem.append_faked_optim_var(meta_suffix, nlp.controls.scaled, [name])
>                     ConfigureProblem.append_faked_optim_var(meta_suffix, nlp.controls.unscaled, [name])
>                     # Nope
> ```

?
___
*[`bioptim/optimization/optimal_control_program.py` line 731 at r1](https://reviewable.io/reviews/pyomeca/bioptim/734#-NavdEdf2jZ779IpTjTW:-NavdEdf2jZ779IpTjTX:b2a7t2b) ([raw file](https://github.com/pyomeca/bioptim/blob/2efeec066561bf11f0c1bf1a8be64805b2daf797/bioptim/optimization/optimal_control_program.py#L731)):*
> ```Python
>             self.nlp[i].ode_solver.prepare_dynamic_integrator(self, self.nlp[i])
>             if (
>                 isinstance(bio_model, HolonomicBiorbdModel) or isinstance(bio_model, VariationalBiorbdModel)
> ```

remove test on Holonomic
Change `VariationalBiorbdModel` for `VariationalBioModel`
___
*[`bioptim/optimization/optimal_control_program.py` line 733 at r1](https://reviewable.io/reviews/pyomeca/bioptim/734#-NavdYni7AgDhO6hezyw:-NavdYni7AgDhO6hezyx:bt0iifo) ([raw file](https://github.com/pyomeca/bioptim/blob/2efeec066561bf11f0c1bf1a8be64805b2daf797/bioptim/optimization/optimal_control_program.py#L733)):*
> ```Python
>                 isinstance(bio_model, HolonomicBiorbdModel) or isinstance(bio_model, VariationalBiorbdModel)
>             ) and self.nlp[i].stochastic_variables.shape > 0:
>                 raise RuntimeError(
> ```

NotImplementedError
___
*[`bioptim/optimization/optimal_control_program.py` line 734 at r1](https://reviewable.io/reviews/pyomeca/bioptim/734#-NavdUo06u8QyycQiIMG:-NavdUo06u8QyycQiIMH:bpws0ne) ([raw file](https://github.com/pyomeca/bioptim/blob/2efeec066561bf11f0c1bf1a8be64805b2daf797/bioptim/optimization/optimal_control_program.py#L734)):*
> ```Python
>             ) and self.nlp[i].stochastic_variables.shape > 0:
>                 raise RuntimeError(
>                     "Stochastic variables are not supported with holonomic constraints / variational integrator yet"
> ```

Adjust this
___
*[`tests/test_penalty.py` line 75 at r1](https://reviewable.io/reviews/pyomeca/bioptim/734#-NaveTyu2ZqadcMTJwEp:-NaveTyv-C7E4s9ZCOLq:b9wpsmn) ([raw file](https://github.com/pyomeca/bioptim/blob/2efeec066561bf11f0c1bf1a8be64805b2daf797/tests/test_penalty.py#L75)):*
> ```Python
> def get_penalty_value(ocp, penalty, t, x, u, p, s):
>     val = penalty.type(penalty, PenaltyController(ocp, ocp.nlp[0], t, x, u, [], [], [], [], s, 0), **penalty.params)
>     # changed only this one
> ```

Really?

**Comment by pariterre** [comment]
Waiting for #733

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/734)* status: all files reviewed, 6 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 912 at r1](https://reviewable.io/reviews/pyomeca/bioptim/734#-NavbFYSBkW7LpKUEhDX:-NavtYuU18jLPQnU9QJG:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/2efeec066561bf11f0c1bf1a8be64805b2daf797/bioptim/dynamics/configure_problem.py#L912)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 917 at r1](https://reviewable.io/reviews/pyomeca/bioptim/734#-NavbGmk8TIxAj0jvG2a:-NavtZRT3ezAxd0y7THF:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/2efeec066561bf11f0c1bf1a8be64805b2daf797/bioptim/dynamics/configure_problem.py#L917)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 731 at r1](https://reviewable.io/reviews/pyomeca/bioptim/734#-NavdEdf2jZ779IpTjTW:-Navu6mhAdc-v023YNPv:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/2efeec066561bf11f0c1bf1a8be64805b2daf797/bioptim/optimization/optimal_control_program.py#L731)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

remove test on Holonomic
Change `VariationalBiorbdModel` for `VariationalBioModel`
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 733 at r1](https://reviewable.io/reviews/pyomeca/bioptim/734#-NavdYni7AgDhO6hezyw:-NavuluS0R1YXb-ZYiEu:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/2efeec066561bf11f0c1bf1a8be64805b2daf797/bioptim/optimization/optimal_control_program.py#L733)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

NotImplementedError
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 734 at r1](https://reviewable.io/reviews/pyomeca/bioptim/734#-NavdUo06u8QyycQiIMG:-NavumPh-6qbPr4cCcwv:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/2efeec066561bf11f0c1bf1a8be64805b2daf797/bioptim/optimization/optimal_control_program.py#L734)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Adjust this
</blockquote></details>

Done.
___
*[`tests/test_penalty.py` line 75 at r1](https://reviewable.io/reviews/pyomeca/bioptim/734#-NaveTyu2ZqadcMTJwEp:-NavxgL2ChKviqYxsRLt:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/2efeec066561bf11f0c1bf1a8be64805b2daf797/tests/test_penalty.py#L75)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Really?
</blockquote></details>

Done.

**Comment by EveCharbie** [comment]
@pariterre this should be good :)

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/734#-:-NbFJ2g-7ejGdWP7zW0X:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
