### PR TITLE
[RTM if tests pass] Cholesky decomposition of the covariance matrix

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/731)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
RTM when all the comments are answered

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/731#-:-NaDyJZe-Mu9nvl4dv-Z:b9lxwmz)* status: all files reviewed, 7 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py` line 6 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDwXY95xcT7_qIRSVd:-NaDwXY95xcT7_qIRSVe:bkgr4b4) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py#L6)):*
> ```Python
> This formulation allow to decouple the covariance matrix with the previous states reducing the comlexity of resolution,
> but increases largely the number of variables to optimize.
> Decomposing the covariance matrix using Cholesky L @ @.T allors to reduce the number of variables and ensures that the
> ```

allows?
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py` line 156 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDwgAADNOGRUueMZ9T:-NaDwgAADNOGRUueMZ9U:b-qidtda) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py#L156)):*
> ```Python
> 
> def configure_stochastic_optimal_control_problem(
>     ocp: OptimalControlProgram, nlp: NonLinearProgram, motor_noise, sensory_noise, cholesky_flag
> ```

To be more coherent with the rest of bioptim, I'd go with : `use_cholesky` or `with_cholesky`
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py` line 424 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDwuvs6GuoszEVLeEM:-NaDwuvs6GuoszEVLeEN:be7vmdd) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py#L424)):*
> ```Python
>     sensory_noise_magnitude: cas.DM,
>     force_field_magnitude: float = 0,
>     problem_type: str = "CIRCLE",
> ```

I know this is not part of the current PR, but I ask anyway. Would that make sense to use an Enum for that so it is easier to know which one can be sent? If so, you can add it at the top of the current file
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py` line 580 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDxCp-09nBiL1v8jNW:-NaDxCp-09nBiL1v8jNX:bne9ilh) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py#L580)):*
> ```Python
>     n_stochastic = n_tau * (n_q + n_qdot) + n_q + n_qdot + n_states * n_states
>     if not cholesky_flag:
>         n_stochastic += n_states * n_states  # + cov(4, 4)
> ```

Should this comment be reintroduced?
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py` line 586 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDxHBl2uo9XTc4sOlD:-NaDxHBl2uo9XTc4sOlE:bne9ilh) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py#L586)):*
> ```Python
>             for j in range(i + 1):
>                 n_cholesky_cov += 1
>         n_stochastic += n_cholesky_cov  # + cholesky_cov(10)
> ```

Should this comment be reintroduced?
___
*[`tests/test_global_stochastic.py` line 592 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDxmhe05LIL6kd0cjX:-NaDxmhe05LIL6kd0cjY:b-xcu0v6) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/tests/test_global_stochastic.py#L592)):*
> ```Python
>         # detailed cost values
>         np.testing.assert_almost_equal(sol.detailed_cost[0]["cost_value_weighted"], 273.5544356233155)
>         np.testing.assert_almost_equal(sol.detailed_cost[1]["cost_value_weighted"], 0.00632179936471477)
> ```

To be sure, is the sum of these two lines equal f[0, 0]? It feels that it should and actually feels that it is. Add this test?
___
*[`tests/test_global_stochastic.py` line 607 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDy1zh7Qib_Z7DaM56:-NaDy1zh7Qib_Z7DaM57:bmp62i) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/tests/test_global_stochastic.py#L607)):*
> ```Python
>         np.testing.assert_almost_equal(q[:, 0], np.array([0.34906585, 2.24586773]))
>         np.testing.assert_almost_equal(q[:, -2], np.array([0.92561033, 1.29037199]))
>         np.testing.assert_almost_equal(qdot[:, 0], np.array([1.17396838e-10, 3.20866997e-11]))
> ```

I sugget to compare these value to 0 with decimal=6, which has less chances to fail on the CI

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/731)* status: all files reviewed, 7 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py` line 6 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDwXY95xcT7_qIRSVd:-NalN6fw4RMgkfPZrbml:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py#L6)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

allows?
</blockquote></details>

Done.
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py` line 156 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDwgAADNOGRUueMZ9T:-NalNIhZ55SOrqv9E9EN:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py#L156)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be more coherent with the rest of bioptim, I'd go with : `use_cholesky` or `with_cholesky`
</blockquote></details>

Done.
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py` line 424 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDwuvs6GuoszEVLeEM:-NalOXDG3gu4faLhSzNr:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py#L424)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I know this is not part of the current PR, but I ask anyway. Would that make sense to use an Enum for that so it is easier to know which one can be sent? If so, you can add it at the top of the current file
</blockquote></details>

Done.
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py` line 580 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDxCp-09nBiL1v8jNW:-NalOZSV7Wbrt8hzGl8q:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py#L580)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Should this comment be reintroduced?
</blockquote></details>

Done.
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py` line 586 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDxHBl2uo9XTc4sOlD:-NalO__7-YsZ0VrHrN4Q:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py#L586)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Should this comment be reintroduced?
</blockquote></details>

Done.
___
*[`tests/test_global_stochastic.py` line 592 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDxmhe05LIL6kd0cjX:-NalPKg02HKHVrdE73qn:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/tests/test_global_stochastic.py#L592)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be sure, is the sum of these two lines equal f[0, 0]? It feels that it should and actually feels that it is. Add this test?
</blockquote></details>

Done.
___
*[`tests/test_global_stochastic.py` line 607 at r1](https://reviewable.io/reviews/pyomeca/bioptim/731#-NaDy1zh7Qib_Z7DaM56:-NalRiIBA8Q-l9FjWnQw:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9cb15195729910f6c8a6d425f6c621224ea2a487/tests/test_global_stochastic.py#L607)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I sugget to compare these value to 0 with decimal=6, which has less chances to fail on the CI
</blockquote></details>

Done.

**Review by pariterre — DISMISSED** [review]
Waiting for #733 

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/731#-:-Navabnu6oJGo_4SMYIx:bpl4dgd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Comment by EveCharbie** [comment]
@pariterre please merge this PR first and then ping me so that I can resolve the conflicts between my PRs.

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/731#-:-Naw950C8N8tDsYjqYtx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
