### PR TITLE
[RTM when tests pass] Breaking up solution in multiple scripts

### PR DESCRIPTION
**Pull request by Ipuch**
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/790)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/790)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`bioptim/optimization/solution/solution.py` line 10 at r1](https://reviewable.io/reviews/pyomeca/bioptim/790#-NiKAaAH89NDpOl9WHPT:-NiKAaAH89NDpOl9WHPU:b-ydldk1) ([raw file](https://github.com/pyomeca/bioptim/blob/5d0c54348e15c189b0c3c3de6dc3b286059bfd3a/bioptim/optimization/solution/solution.py#L10)):*
> ```Python
> from matplotlib import pyplot as plt
> 
> from bioptim.limits.objective_functions import ObjectiveFcn
> ```

I disagree with this. Relative path ensures that the path used is the one in the development directory. If versions of bioptim are installed in the environment it may chose the file in the installed folder, especially if the file is moved, making it very hard to debug.

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/790)* status: 14 of 17 files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/optimization/solution/solution.py` line 10 at r1](https://reviewable.io/reviews/pyomeca/bioptim/790#-NiKAaAH89NDpOl9WHPT:-NiKO7cC0F2_eiW4wgLD:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/5d0c54348e15c189b0c3c3de6dc3b286059bfd3a/bioptim/optimization/solution/solution.py#L10)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I disagree with this. Relative path ensures that the path used is the one in the development directory. If versions of bioptim are installed in the environment it may chose the file in the installed folder, especially if the file is moved, making it very hard to debug.
</blockquote></details>

Done

**Review by pariterre — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/790#-:-NiKOTRbCYDJZ4GifE5Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/790#-:-NiKdzof4eP17uv0444n:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Pull request merged**
