### PR TITLE
[RTM] Change solver option set and turn back to the initial set convergence. 

### PR DESCRIPTION
**Pull request by aceglia**
To respond to the issue #493.

### All Submissions:

* [ x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ x] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

---
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/502)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/502)* status: all files reviewed, 1 unresolved discussion (waiting on @aceglia)

___
*[`bioptim/interfaces/solver_options.py` line 570 at r1](https://reviewable.io/reviews/pyomeca/bioptim/502#-N84rpPL8jWvSrHfxOCG:-N84rpPL8jWvSrHfxOCH:b-nsix9x) ([raw file](https://github.com/pyomeca/bioptim/blob/d9a2b6e94aa893dc89e0025446dd3086e7734e5d/bioptim/interfaces/solver_options.py#L570)):*
> ```Python
> 
>         def set_convergence_tolerance(self, val: Union[float, int, list, tuple]):
>             if isinstance(val, (float, int)):
> ```

Please revert the capability to send a float or an int 



_Code quote:_
```Python
        def set_convergence_tolerance(self, val: Union[float, int, list, tuple]):
            if isinstance(val, (float, int)):
                val = [val] * 4
```

**Review by aceglia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/502)* status: all files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/interfaces/solver_options.py` line 570 at r1](https://reviewable.io/reviews/pyomeca/bioptim/502#-N84rpPL8jWvSrHfxOCG:-N84uNGC9W0u0ldz70AO:b-pdd42a) ([raw file](https://github.com/pyomeca/bioptim/blob/d9a2b6e94aa893dc89e0025446dd3086e7734e5d/bioptim/interfaces/solver_options.py#L570)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please revert the capability to send a float or an int 
</blockquote></details>

Already done in the commit #a27c3c.

**Comment by Ipuch** [comment]
Related to #493

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/502)* status: all files reviewed, 1 unresolved discussion (waiting on @aceglia)

___
*[`bioptim/interfaces/solver_options.py` line 570 at r1](https://reviewable.io/reviews/pyomeca/bioptim/502#-N84rpPL8jWvSrHfxOCG:-N8e33L0083JKvusBqGQ:b-rxuspq) ([raw file](https://github.com/pyomeca/bioptim/blob/d9a2b6e94aa893dc89e0025446dd3086e7734e5d/bioptim/interfaces/solver_options.py#L570)):*
<details><summary><i>Previously, aceglia wrote…</i></summary><blockquote>

Already done in the commit #a27c3c.
</blockquote></details>

Not done :P

**Review by aceglia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/502)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/interfaces/solver_options.py` line 570 at r1](https://reviewable.io/reviews/pyomeca/bioptim/502#-N84rpPL8jWvSrHfxOCG:-N8e5eF6Eq8BBEjxsS1J:bi82ctf) ([raw file](https://github.com/pyomeca/bioptim/blob/d9a2b6e94aa893dc89e0025446dd3086e7734e5d/bioptim/interfaces/solver_options.py#L570)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Not done :P
</blockquote></details>

Done now ^^

**Review by pariterre — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/502)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aceglia)

**Pull request merged**
