### PR TITLE
[RTR] check if code is blacked independantly in github actions

### PR DESCRIPTION
**Pull request by Ipuch**
Test if we can autoblack

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/530)

### CODE REVIEW

**Comment by Ipuch** [comment]
I've tested it here https://github.com/Ipuch/ode-solvers/pull/1  it worked like this. :+1:

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/530)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`.github/workflows/autoblack.yml` line 18 at r2](https://reviewable.io/reviews/pyomeca/bioptim/530#-NC1_nATAMHwXu5BkifI:-NC1_nAU2X-_5bMwgpCu:b-pigc6k) ([raw file](https://github.com/pyomeca/bioptim/blob/8e67e43a6bbee9862a8de68fb5b7404cdf60e5e0/.github/workflows/autoblack.yml#L18)):*
> ```YAML
>           python-version: 3.7
>       - name: Install Black
>         run: pip install black
> ```

Change pip for conda
___
*[`bioptim/examples/getting_started/pendulum.py` line 26 at r1](https://reviewable.io/reviews/pyomeca/bioptim/530#-NBT9ABVCNQ15Gfw4QOc:-NBT9ABVCNQ15Gfw4QOd:bp50hdo) ([raw file](https://github.com/pyomeca/bioptim/blob/3efb17e86178b00d177279f43022bb177eedd898/bioptim/examples/getting_started/pendulum.py#L26)):*
> ```Python
>     Solver,
>     IntegralApproximation,
>     DefectType,
> ```

To revert 



_Code quote:_
```Python
    IntegralApproximation,
    DefectType,
```

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/530)* status: all files reviewed, 2 unresolved discussions (waiting on @Ipuch)

___
*[`.github/workflows/autoblack.yml` line 33 at r3](https://reviewable.io/reviews/pyomeca/bioptim/530#-NC1d4ix2-t8mwezI7-a:-NC1d4ix2-t8mwezI7-b:b22quet) ([raw file](https://github.com/pyomeca/bioptim/blob/dbdc37b8a285ee89860c906d9ac13f590c06335d/.github/workflows/autoblack.yml#L33)):*
> ```YAML
>           git config --global user.email 'ipuch@users.noreply.github.com'
>           git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
>           git checkout $GITHUB_HEAD_REF
> ```

Remove this



_Code quote:_
```YAML
          git config --global user.name 'autoblack'
          git config --global user.email 'ipuch@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: Format Python code with Black"
          git push
```

**Comment by Ipuch** [comment]
RTM @pariterre

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/530)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`.github/workflows/autoblack.yml` line 33 at r3](https://reviewable.io/reviews/pyomeca/bioptim/530#-NC1d4ix2-t8mwezI7-a:-NC6dhPV8YVZFiS3dVbm:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/dbdc37b8a285ee89860c906d9ac13f590c06335d/.github/workflows/autoblack.yml#L33)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Remove this
</blockquote></details>

Done
___
*[`bioptim/examples/getting_started/pendulum.py` line 26 at r1](https://reviewable.io/reviews/pyomeca/bioptim/530#-NBT9ABVCNQ15Gfw4QOc:-NC6diPM1nytG0-NlVnc:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/3efb17e86178b00d177279f43022bb177eedd898/bioptim/examples/getting_started/pendulum.py#L26)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To revert 
</blockquote></details>

done

**Review by pariterre — APPROVED** [review]
Let's try. Worst case scenario, we can remove this later!
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/530#-:-NCL5iaz6sRACe0kL-v2:bppeqzh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Pull request merged**
