### PR TITLE
[RTM when tests pass] external forces moved out of ocp too

### PR DESCRIPTION
**Pull request by Ipuch**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?  #729 
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/779)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/779)* status: all files reviewed, 4 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/dynamics/configure_problem.py` line 190 at r1](https://reviewable.io/reviews/pyomeca/bioptim/779#-Ngxd7P_0L_LJVFzCD9y:-Ngxd7P_0L_LJVFzCD9z:b78ikw3) ([raw file](https://github.com/pyomeca/bioptim/blob/b8247b7719fd2a96b0a3c03fcd40da5cde836179/bioptim/dynamics/configure_problem.py#L190)):*
> ```Python
>         """
> 
>         _check_contacts_in_biorbd_model(with_contact, nlp.model.nb_contacts, nlp.phase_idx)
> ```

in bio_model?
___
*[`bioptim/dynamics/dynamics_functions.py` line 947 at r1](https://reviewable.io/reviews/pyomeca/bioptim/779#-NgxdfgW3P3P65-5wxW0:-NgxdfgW3P3P65-5wxW1:b8wyz64) ([raw file](https://github.com/pyomeca/bioptim/blob/b8247b7719fd2a96b0a3c03fcd40da5cde836179/bioptim/dynamics/dynamics_functions.py#L947)):*
> ```Python
> 
>             return qdot_var.mapping.to_first.map(qddot)
>         else:
> ```

This (and the for loop associated) should probably not rely on this check anymore thanks to phase_dynamics...
___
*[`bioptim/optimization/optimal_control_program.py` line 168 at r1](https://reviewable.io/reviews/pyomeca/bioptim/779#-NgxeTDS0p-aMbqOw4ML:-NgxeTDS0p-aMbqOw4MM:bj5i0qk) ([raw file](https://github.com/pyomeca/bioptim/blob/b8247b7719fd2a96b0a3c03fcd40da5cde836179/bioptim/optimization/optimal_control_program.py#L168)):*
> ```Python
>         #             The external_forces should be of format tuple[tuple[Any]] where the outer list is the number of "
>         #             "phases, the inner list is the number of shooting points of each phase and the dict is the Any is "
>         #             "the specific way to add external_force for the specific implementation of the biomodel
> ```

to be removed?
___
*[`bioptim/optimization/optimal_control_program.py` line 660 at r1](https://reviewable.io/reviews/pyomeca/bioptim/779#-NgxeZ2kEu03RWKXMTfF:-NgxeZ2kEu03RWKXMTfG:be695ha) ([raw file](https://github.com/pyomeca/bioptim/blob/b8247b7719fd2a96b0a3c03fcd40da5cde836179/bioptim/optimization/optimal_control_program.py#L660)):*
> ```Python
>         #                 "is the specific way to add external_force for the specific implementation of the biomodel"
>         #             )
>         #     NLP.add(self, "external_forces", external_forces, False)
> ```

Part of this check is probably needed to dispatch properly the external forces for each node?

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/779)* status: all files reviewed, 4 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/dynamics_functions.py` line 947 at r1](https://reviewable.io/reviews/pyomeca/bioptim/779#-NgxdfgW3P3P65-5wxW0:-NgyTsYb7XVhUpJRDYWk:b-ctk476) ([raw file](https://github.com/pyomeca/bioptim/blob/b8247b7719fd2a96b0a3c03fcd40da5cde836179/bioptim/dynamics/dynamics_functions.py#L947)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This (and the for loop associated) should probably not rely on this check anymore thanks to phase_dynamics...
</blockquote></details>

Do you agree with a check the common use of phase_dynamics and external_forces  ?

**Review by pariterre — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/779)* status: all files reviewed, 4 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/dynamics/dynamics_functions.py` line 947 at r1](https://reviewable.io/reviews/pyomeca/bioptim/779#-NgxdfgW3P3P65-5wxW0:-Ngymf4VEVvl2fXCcRQO:b6nxzq8) ([raw file](https://github.com/pyomeca/bioptim/blob/b8247b7719fd2a96b0a3c03fcd40da5cde836179/bioptim/dynamics/dynamics_functions.py#L947)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Do you agree with a check the common use of phase_dynamics and external_forces  ?
</blockquote></details>

I think checking for phase_dynamics make sense. A check on external_forces could be check (and raise?). I don't what I prefer... Raising has the advantage of removing adverse effect of ignoring the values not a [0], while not raising make sense went external_forces are optimized or when a single value of external_forces is actually expected

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/779)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 190 at r1](https://reviewable.io/reviews/pyomeca/bioptim/779#-Ngxd7P_0L_LJVFzCD9y:-NgzRK5K8eRr_WlR1VNX:b-teg8d0) ([raw file](https://github.com/pyomeca/bioptim/blob/b8247b7719fd2a96b0a3c03fcd40da5cde836179/bioptim/dynamics/configure_problem.py#L190)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

in bio_model?
</blockquote></details>

I partly disagree because the error message has to return the phase idx where there is an error.
I partly agree if we decide to move the feature 'with_XXX' in the models that this would be directly raised in the biorbdModel.
___
*[`bioptim/dynamics/dynamics_functions.py` line 947 at r1](https://reviewable.io/reviews/pyomeca/bioptim/779#-NgxdfgW3P3P65-5wxW0:-NgzQgtWA_hcJeYi_y9x:ba4yxrg) ([raw file](https://github.com/pyomeca/bioptim/blob/b8247b7719fd2a96b0a3c03fcd40da5cde836179/bioptim/dynamics/dynamics_functions.py#L947)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I think checking for phase_dynamics make sense. A check on external_forces could be check (and raise?). I don't what I prefer... Raising has the advantage of removing adverse effect of ignoring the values not a [0], while not raising make sense went external_forces are optimized or when a single value of external_forces is actually expected
</blockquote></details>

But I feel like there is no case where we want to apply a constant external force ...


I'm kind not satisfied with such an implentation because there is no concept of series dispatched over the phase nodes yet. This would look like this ...
```python3
        if nlp.phase_dynamics == PhaseDynamics.SHARED_DURING_THE_PHASE:
            if with_contact:
                qddot = nlp.model.constrained_forward_dynamics(q, qdot, tau)
            else:
                qddot = nlp.model.forward_dynamics(q, qdot, tau)

            return qdot_var.mapping.to_first.map(qddot)

        elif nlp.phase_dynamics == PhaseDynamics.ONE_PER_NODE:
            dxdt = MX(len(qdot_var.mapping.to_first), nlp.ns)
            for i, f_ext in enumerate(external_forces):
                if with_contact:
                    qddot = nlp.model.constrained_forward_dynamics(q, qdot, tau, f_ext)
                else:
                    qddot = nlp.model.forward_dynamics(q, qdot, tau, f_ext)
                dxdt[:, i] = qdot_var.mapping.to_first.map(qddot)
            return dxdt

        else:
            raise RuntimeError(f"PhaseDynamics {nlp.phase_dynamics} not implemented yet")
```
___
*[`bioptim/optimization/optimal_control_program.py` line 168 at r1](https://reviewable.io/reviews/pyomeca/bioptim/779#-NgxeTDS0p-aMbqOw4ML:-NgzQqn23buCicr-iqE4:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/b8247b7719fd2a96b0a3c03fcd40da5cde836179/bioptim/optimization/optimal_control_program.py#L168)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

to be removed?
</blockquote></details>

Done
___
*[`bioptim/optimization/optimal_control_program.py` line 660 at r1](https://reviewable.io/reviews/pyomeca/bioptim/779#-NgxeZ2kEu03RWKXMTfF:-NgzQyHwD3N3xcoaZ1zu:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/b8247b7719fd2a96b0a3c03fcd40da5cde836179/bioptim/optimization/optimal_control_program.py#L660)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Part of this check is probably needed to dispatch properly the external forces for each node?
</blockquote></details>

Done

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/779#-:-Nh8Ea-U4nInhocrjnR9:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/dynamics/configure_problem.py` line 1719 at r3](https://reviewable.io/reviews/pyomeca/bioptim/779#-Nh8ByB92lThg2pb6dUs:-Nh8ByB92lThg2pb6dUt:bn267r4) ([raw file](https://github.com/pyomeca/bioptim/blob/597d30e1b29e41f54b8fe1553c1f5a1ed5990aa0/bioptim/dynamics/configure_problem.py#L1719)):*
> ```Python
> ):
>     """If external_forces is not None, phase_dynamics should be PhaseDynamics.ONE_PER_NODE"""
>     if external_forces is not None and phase_dynamics != PhaseDynamics.ONE_PER_NODE:
> ```

add a comment to explain why even though this is not a fundamental reason why external_forces necessitate ONE_PER_NODE, we made it anyway
___
*[`bioptim/dynamics/dynamics_functions.py` line 947 at r1](https://reviewable.io/reviews/pyomeca/bioptim/779#-NgxdfgW3P3P65-5wxW0:-Nh8CyBB-Y1RGbSAld5u:b-afix0w) ([raw file](https://github.com/pyomeca/bioptim/blob/b8247b7719fd2a96b0a3c03fcd40da5cde836179/bioptim/dynamics/dynamics_functions.py#L947)):*
> nlp.model.constrained\_forward\_dynamics

A todo should be added to pass f_ext in controls?
___
*[`tests/shard1/test_dynamics.py` line 42 at r3](https://reviewable.io/reviews/pyomeca/bioptim/779#-Nh8E7o2EC1MAHCmwowu:-Nh8E7o2EC1MAHCmwowv:b1yuos4) ([raw file](https://github.com/pyomeca/bioptim/blob/597d30e1b29e41f54b8fe1553c1f5a1ed5990aa0/tests/shard1/test_dynamics.py#L42)):*
> ```Python
>     "with_external_force",
>     [
>         # False,
> ```

Reinsert False

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/779)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 1719 at r3](https://reviewable.io/reviews/pyomeca/bioptim/779#-Nh8ByB92lThg2pb6dUs:-Nh8OIAADwx5GZ5SKUWS:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/597d30e1b29e41f54b8fe1553c1f5a1ed5990aa0/bioptim/dynamics/configure_problem.py#L1719)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

add a comment to explain why even though this is not a fundamental reason why external_forces necessitate ONE_PER_NODE, we made it anyway
</blockquote></details>

Done.
___
*[`bioptim/dynamics/dynamics_functions.py` line 947 at r1](https://reviewable.io/reviews/pyomeca/bioptim/779#-NgxdfgW3P3P65-5wxW0:-Nh8OlcN9EmpFW6z2fTO:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/b8247b7719fd2a96b0a3c03fcd40da5cde836179/bioptim/dynamics/dynamics_functions.py#L947)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

> nlp.model.constrained\_forward\_dynamics

A todo should be added to pass f_ext in controls?
</blockquote></details>

Done

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/779)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @pariterre)

___
*[`tests/shard1/test_dynamics.py` line 42 at r3](https://reviewable.io/reviews/pyomeca/bioptim/779#-Nh8E7o2EC1MAHCmwowu:-Nh8PARY6nrocyjwpV2Z:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/597d30e1b29e41f54b8fe1553c1f5a1ed5990aa0/tests/shard1/test_dynamics.py#L42)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Reinsert False
</blockquote></details>

Done

**Comment by Ipuch** [comment]
all green @pariterre

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/779#-:-NhDH3644yGl8m42DW03:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Review by pariterre — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/779)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Pull request merged**
