### PR TITLE
[RTR] contact force at the end of interval for takeoff

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/891)

### CODE REVIEW

**Comment by EveCharbie** [comment]
@Ipuch could you review the logic please?
@pariterre could you please review this textually, so that @AnaisFarr can use it quickly?

**Review by Ipuch — CHANGES_REQUESTED** [review]
Otherwise looks good to me

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/891#-:-O4wJzKD8kM1Sx7rIU_q:byeebb)* status: all files reviewed, 3 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/limits/penalty.py` line 839 at r1](https://reviewable.io/reviews/pyomeca/bioptim/891#-O4wJ8fHAOTj0WTXItBx:-O4wJ8fHAOTj0WTXItBy:b-su5xnd) ([raw file](https://github.com/pyomeca/bioptim/blob/e60a393d974b29fe9d100d1fb9485b17f90070e8/bioptim/limits/penalty.py#L839)):*
> ```Python
>                 cx = horzcat(*([controller.states.cx_start] + controller.states.cx_intermediates_list))
> 
>                 states_integrated = controller.integrate(
> ```

I think `end_interval_states`is more accurate
___
*[`bioptim/limits/penalty.py` line 847 at r1](https://reviewable.io/reviews/pyomeca/bioptim/891#-O4wJ2XO-ZOZcV7mqayg:-O4wJ2XO-ZOZcV7mqayh:bzauyai) ([raw file](https://github.com/pyomeca/bioptim/blob/e60a393d974b29fe9d100d1fb9485b17f90070e8/bioptim/limits/penalty.py#L847)):*
> ```Python
>                     d=controller.numerical_timeseries.cx,
>                 )["xf"]
>                 penalty.integrate = True
> ```

I'm not sure what it is for.



_Code quote:_
```Python
penalty.integrate = True
```
___
*[`tests/shard4/test_penalty.py` line 1172 at r1](https://reviewable.io/reviews/pyomeca/bioptim/891#-O4wJhMT--l8E0gdMWfc:-O4wJhMU0UPHtgX7D610:b-hi3n3p) ([raw file](https://github.com/pyomeca/bioptim/blob/e60a393d974b29fe9d100d1fb9485b17f90070e8/tests/shard4/test_penalty.py#L1172)):*
> ```Python
>             contact_index=0,
>             node=Node.PENULTIMATE,
>         )
> ```

Just to say something:

```python
if penalty_origin == ObjectiveFcn.Mayer:
        penalty_type = ObjectiveFcn.Mayer.MINIMIZE_CONTACT_FORCES_END_OF_INTERVAL
        penalty_object = Objective
    else:
        penalty_type = ConstraintFcn.TRACK_CONTACT_FORCES_END_OF_INTERVAL
        penalty = Constraint

penalty = penalty_object(
            penalty_type,
            contact_index=0,
            node=Node.PENULTIMATE,
        )
```



_Code quote:_
```Python
    if penalty_origin == ObjectiveFcn.Mayer:
        penalty_type = ObjectiveFcn.Mayer.MINIMIZE_CONTACT_FORCES_END_OF_INTERVAL
        penalty = Objective(
            penalty_type,
            contact_index=0,
            node=Node.PENULTIMATE,
        )
    else:
        penalty_type = ConstraintFcn.TRACK_CONTACT_FORCES_END_OF_INTERVAL
        penalty = Constraint(
            penalty_type,
            contact_index=0,
            node=Node.PENULTIMATE,
        )
```

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/891)* status: all files reviewed, 3 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/limits/penalty.py` line 839 at r1](https://reviewable.io/reviews/pyomeca/bioptim/891#-O4wJ8fHAOTj0WTXItBx:-O4zJRFx64viZDmzqeQj:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/e60a393d974b29fe9d100d1fb9485b17f90070e8/bioptim/limits/penalty.py#L839)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I think `end_interval_states`is more accurate
</blockquote></details>

Done.
___
*[`bioptim/limits/penalty.py` line 847 at r1](https://reviewable.io/reviews/pyomeca/bioptim/891#-O4wJ2XO-ZOZcV7mqayg:-O4zJqZCAKvaCF0fgAq6:b-fj2lvu) ([raw file](https://github.com/pyomeca/bioptim/blob/e60a393d974b29fe9d100d1fb9485b17f90070e8/bioptim/limits/penalty.py#L847)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I'm not sure what it is for.
</blockquote></details>

I removed it since it is a Mayer term, @pariterre need confirmation.
___
*[`tests/shard4/test_penalty.py` line 1172 at r1](https://reviewable.io/reviews/pyomeca/bioptim/891#-O4wJhMT--l8E0gdMWfc:-O4zKkI-DazrOGxG8gPD:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/e60a393d974b29fe9d100d1fb9485b17f90070e8/tests/shard4/test_penalty.py#L1172)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Just to say something:

```python
if penalty_origin == ObjectiveFcn.Mayer:
        penalty_type = ObjectiveFcn.Mayer.MINIMIZE_CONTACT_FORCES_END_OF_INTERVAL
        penalty_object = Objective
    else:
        penalty_type = ConstraintFcn.TRACK_CONTACT_FORCES_END_OF_INTERVAL
        penalty = Constraint

penalty = penalty_object(
            penalty_type,
            contact_index=0,
            node=Node.PENULTIMATE,
        )
```
</blockquote></details>

Done.

**Review by Ipuch — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/891)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @pariterre)

**Review by Ipuch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/891)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/limits/penalty.py` line 847 at r1](https://reviewable.io/reviews/pyomeca/bioptim/891#-O4wJ2XO-ZOZcV7mqayg:-O4zWSr76Zm3KpnZGbdH:brlcknw) ([raw file](https://github.com/pyomeca/bioptim/blob/e60a393d974b29fe9d100d1fb9485b17f90070e8/bioptim/limits/penalty.py#L847)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

I removed it since it is a Mayer term, @pariterre need confirmation.
</blockquote></details>

Last comment before @pariterre pops. CodeClimate describe a coginitive complexity of 6 (allowed 5)

Here is my proposition:

```python

            if controller.get_nlp.contact_forces_func is None:
                raise RuntimeError("minimize_contact_forces requires a contact dynamics")

            if controller.control_type != ControlType.CONSTANT:
                raise NotImplementedError(
                    f"This constraint is only useful for ControlType.CONSTANT controls. For any other dynamics, you should constraint the contact at the begining of the interval."
                )

            if controller.algebraic_states.cx_start.shape[0] != 0:
                raise NotImplementedError(
                    "This constraint is not implemented for problems with algebraic states as you should provide their dynamics to integrate it as well."
                )

            PenaltyFunctionAbstract.set_axes_rows(penalty, contact_index)
            penalty.quadratic = True if penalty.quadratic is None else penalty.quadratic

            t_span = controller.t_span.cx
            cx = horzcat(*([controller.states.cx_start] + controller.states.cx_intermediates_list)) if controller.get_nlp.ode_solver.is_direct_collocation else controller.states.cx_start

            end_of_interval_states = controller.integrate(
                    t_span=t_span,
                    x0=cx,
                    u=controller.controls.cx_start,
                    p=controller.parameters.cx,
                    a=controller.algebraic_states.cx_start,
                    d=controller.numerical_timeseries.cx,
                )["xf"]

            contact_force = controller.get_nlp.contact_forces_func(
                controller.time.cx,
                end_of_interval_states,
                controller.controls.cx_start,
                controller.parameters.cx,
                controller.algebraic_states.cx_start,
                controller.numerical_timeseries.cx,
            )

            return contact_force


```

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/891)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Ipuch and @pariterre)

___
*[`bioptim/limits/penalty.py` line 847 at r1](https://reviewable.io/reviews/pyomeca/bioptim/891#-O4wJ2XO-ZOZcV7mqayg:-O4zY05mB_NCU_x3_U4H:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/e60a393d974b29fe9d100d1fb9485b17f90070e8/bioptim/limits/penalty.py#L847)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Last comment before @pariterre pops. CodeClimate describe a coginitive complexity of 6 (allowed 5)

Here is my proposition:

```python

            if controller.get_nlp.contact_forces_func is None:
                raise RuntimeError("minimize_contact_forces requires a contact dynamics")

            if controller.control_type != ControlType.CONSTANT:
                raise NotImplementedError(
                    f"This constraint is only useful for ControlType.CONSTANT controls. For any other dynamics, you should constraint the contact at the begining of the interval."
                )

            if controller.algebraic_states.cx_start.shape[0] != 0:
                raise NotImplementedError(
                    "This constraint is not implemented for problems with algebraic states as you should provide their dynamics to integrate it as well."
                )

            PenaltyFunctionAbstract.set_axes_rows(penalty, contact_index)
            penalty.quadratic = True if penalty.quadratic is None else penalty.quadratic

            t_span = controller.t_span.cx
            cx = horzcat(*([controller.states.cx_start] + controller.states.cx_intermediates_list)) if controller.get_nlp.ode_solver.is_direct_collocation else controller.states.cx_start

            end_of_interval_states = controller.integrate(
                    t_span=t_span,
                    x0=cx,
                    u=controller.controls.cx_start,
                    p=controller.parameters.cx,
                    a=controller.algebraic_states.cx_start,
                    d=controller.numerical_timeseries.cx,
                )["xf"]

            contact_force = controller.get_nlp.contact_forces_func(
                controller.time.cx,
                end_of_interval_states,
                controller.controls.cx_start,
                controller.parameters.cx,
                controller.algebraic_states.cx_start,
                controller.numerical_timeseries.cx,
            )

            return contact_force


```
</blockquote></details>

Done.

**Review by Ipuch — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/891#-:-O5EsJbz9MAuj3ZeqKeB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
