### PR TITLE
[RTR] Stochastic variables should not be inputs of OCP

### PR DESCRIPTION
**Pull request by Ipuch**
It always confuses me and it broke all my older ocps.
- #711

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/765)

### CODE REVIEW

**Comment by pariterre** [comment]
[ ] Add a method `dynamic_eval` in ocp so we can have a signature for the custom dynamic function that changes depending on the type of ocp (for instance including (or not) stochatic_variable for problem where it makes sense to have them)
[ ] Add a super.init() in StochasticOCP to ensure a sane ocp
[ ] Factor common methods of StochasticsOCP and OCP and intercept what should not be performed in SOCP by an empty method

**Comment by Ipuch** [comment]
> * [ ]  Add a method `dynamic_eval` in ocp so we can have a signature for the custom dynamic function that changes depending on the type of ocp (for instance including (or not) stochatic_variable for problem where it makes sense to have them)
> * [x]  Add a super.init() in StochasticOCP to ensure a sane ocp
> * [x]  Factor common methods of StochasticsOCP and OCP and intercept what should not be performed in SOCP by an empty method

I propose to let the first bullet point for another PR to not grow this PR.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/765)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`bioptim/optimization/optimal_control_program.py` line 318 at r3](https://reviewable.io/reviews/pyomeca/bioptim/765#-Ngxhw8U3TxFHdchri56:-Ngxhw8V6w7HSHQQTQa-:b-tgpbcu) ([raw file](https://github.com/pyomeca/bioptim/blob/2918a294c4f315794384089e9a529ce6094274e1/bioptim/optimization/optimal_control_program.py#L318)):*
> ```Python
>             s_init,
>             s_scaling,
>         )
> ```

self._prepare_all_decision_variables should prepare them, but I don't see the point returning them (I know that you did not introduce that, but since we are refactoring...). If we don't return them, it allows an overriden method to actually prepare what they want (and need) without worrying of the return signature of the method. 

And if an inherited class need to change the behavior of a particular value, they can call super on this and change the specific one they need

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/765)* status: all files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/optimization/optimal_control_program.py` line 318 at r3](https://reviewable.io/reviews/pyomeca/bioptim/765#-Ngxhw8U3TxFHdchri56:-NgySvSC7qdtatPhi-Dz:bkxgnz5) ([raw file](https://github.com/pyomeca/bioptim/blob/2918a294c4f315794384089e9a529ce6094274e1/bioptim/optimization/optimal_control_program.py#L318)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

self._prepare_all_decision_variables should prepare them, but I don't see the point returning them (I know that you did not introduce that, but since we are refactoring...). If we don't return them, it allows an overriden method to actually prepare what they want (and need) without worrying of the return signature of the method. 

And if an inherited class need to change the behavior of a particular value, they can call super on this and change the specific one they need
</blockquote></details>

I need a small talk. I took the easiest path, but maybe i can do better.

**Review by pariterre — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/765#-:-Nh81hYq3SEFYqsgZgCK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Pull request merged**
