### PR TITLE
feat: test_entry_size; bound_checking biorbd_model

### PR DESCRIPTION
**Pull request by Infa60**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/832)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/832)* status: all files reviewed, 9 unresolved discussions (waiting on @Infa60)

___
*[`bioptim/models/biorbd/biorbd_model.py` line 107 at r1](https://reviewable.io/reviews/pyomeca/bioptim/832#-Np_bqxXCCbhufGJmkDe:-Np_bqxXCCbhufGJmkDf:b-p6c957) ([raw file](https://github.com/pyomeca/bioptim/blob/3e5ecb72d8b92c2b7fb6101b394020da3c5d3cc5/bioptim/models/biorbd/biorbd_model.py#L107)):*
> ```Python
>     def check_q_size(self, q):
>         if q.shape[0] > self.nb_q:
>             raise ValueError(f"Length of q is too big. Expected size: {self.nb_q}, but got: {q.shape[0]}")
> ```

is too large? 
Is not the right size? (what happens if too small... it does not seem to raise)
___
*[`bioptim/models/biorbd/biorbd_model.py` line 634 at r1](https://reviewable.io/reviews/pyomeca/bioptim/832#-Np_cLW-B7O5WMDAAOSR:-Np_cLW-B7O5WMDAAOSS:b-jjovzq) ([raw file](https://github.com/pyomeca/bioptim/blob/3e5ecb72d8b92c2b7fb6101b394020da3c5d3cc5/bioptim/models/biorbd/biorbd_model.py#L634)):*
> ```Python
>     @staticmethod
>     def animate(
>         solution: Any, show_now: bool = True, tracked_markers: list[np.ndarray, ...] = None, **kwargs: Any
> ```

If you cannot import "SolutionData" then do not write anything. It is not "Any" type
___
*[`bioptim/models/biorbd/biorbd_model.py` line 643 at r1](https://reviewable.io/reviews/pyomeca/bioptim/832#-Np_cIFi0A7Av243-Gfi:-Np_cIFi0A7Av243-Gfj:b-2dmjq) ([raw file](https://github.com/pyomeca/bioptim/blob/3e5ecb72d8b92c2b7fb6101b394020da3c5d3cc5/bioptim/models/biorbd/biorbd_model.py#L643)):*
> ```Python
>         check_version(bioviz, "2.0.0", "2.4.0")
> 
>         states = solution.states
> ```

This will not work... as states does not return "q" by itself 
___
*[`tests/shard1/test_entry_size.py` line 1 at r1](https://reviewable.io/reviews/pyomeca/bioptim/832#-Np_cwvPCyYbEB70M9w9:-Np_cwvPCyYbEB70M9wA:bu9suej) ([raw file](https://github.com/pyomeca/bioptim/blob/3e5ecb72d8b92c2b7fb6101b394020da3c5d3cc5/tests/shard1/test_entry_size.py#L1)):*
> ```Python
> import pytest
> ```

Please rename the file for `test_biorbd_model_size.py`
___
*[`tests/shard1/test_entry_size.py` line 5 at r1](https://reviewable.io/reviews/pyomeca/bioptim/832#-Np_YAWQEOJgZlYLFvSu:-Np_YAWQEOJgZlYLFvSv:bsuex03) ([raw file](https://github.com/pyomeca/bioptim/blob/3e5ecb72d8b92c2b7fb6101b394020da3c5d3cc5/tests/shard1/test_entry_size.py#L5)):*
> ```Python
> from casadi import MX
> 
> BIORBD_MODEL_PATH = "/home/lim/Documents/Bioptim/bioptim/bioptim/examples/muscle_driven_with_contact/models/2segments_4dof_2contacts_1muscle.bioMod"
> ```

This does not make sense
___
*[`tests/shard1/test_entry_size.py` line 193 at r1](https://reviewable.io/reviews/pyomeca/bioptim/832#-Np_clhICgFW9Z7iS1y9:-Np_clhICgFW9Z7iS1yA:bcmwg22) ([raw file](https://github.com/pyomeca/bioptim/blob/3e5ecb72d8b92c2b7fb6101b394020da3c5d3cc5/tests/shard1/test_entry_size.py#L193)):*
> ```Python
> # # q and qdot valid but tau_activations not valid
> #     with pytest.raises(ValueError, match="Length of tau is too big"):
> #         model.torque(tau_activations_too_large, q_valid, qdot_valid)
> ```

Why is this commented?
___
*[`tests/shard1/test_entry_size.py` line 315 at r1](https://reviewable.io/reviews/pyomeca/bioptim/832#-Np_cooH5iwpjauLJpEO:-Np_cooH5iwpjauLJpEP:bcmwg22) ([raw file](https://github.com/pyomeca/bioptim/blob/3e5ecb72d8b92c2b7fb6101b394020da3c5d3cc5/tests/shard1/test_entry_size.py#L315)):*
> ```Python
> # # muscle not valid
> #     with pytest.raises(ValueError, match="Length of muscle is too big"):
> #         model.muscle_activation_dot(muscle_too_large)
> ```

Why is this commented?
___
*[`tests/shard1/test_entry_size.py` line 358 at r1](https://reviewable.io/reviews/pyomeca/bioptim/832#-Np_crEW-fm7zWyMECNH:-Np_crEW-fm7zWyMECNI:bcmwg22) ([raw file](https://github.com/pyomeca/bioptim/blob/3e5ecb72d8b92c2b7fb6101b394020da3c5d3cc5/tests/shard1/test_entry_size.py#L358)):*
> ```Python
> # # q and qdot valid but qddot not valid
> #     with pytest.raises(ValueError, match="Length of qddot is too big"):
> #         model.muscle_joint_torque(muscle_too_large, q_valid, qdot_valid)
> ```

Why is this commented?
___
*[`tests/shard1/test_entry_size.py` line 427 at r1](https://reviewable.io/reviews/pyomeca/bioptim/832#-Np_ct_5ArtmpcCXCFUk:-Np_ct_5ArtmpcCXCFUl:bcmwg22) ([raw file](https://github.com/pyomeca/bioptim/blob/3e5ecb72d8b92c2b7fb6101b394020da3c5d3cc5/tests/shard1/test_entry_size.py#L427)):*
> ```Python
> # # q valid but qdot not valid
> #     with pytest.raises(ValueError, match="Length of qdot is too big"):
> #         model.tau_max(q_valid, qdot_too_large)
> ```

Why is this commented?

**Comment by EveCharbie** [comment]
@pariterre there is a problem with black could we merge anyway? Worst case scenario, my next PR will resolve the black issue.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/832)* status: all files reviewed, 2 unresolved discussions (waiting on @Infa60)

___
*[`bioptim/models/biorbd/biorbd_model.py` line 107 at r1](https://reviewable.io/reviews/pyomeca/bioptim/832#-Np_bqxXCCbhufGJmkDe:-Nq8J3h-6XeDdG1_BjBQ:b-ahh6m4) ([raw file](https://github.com/pyomeca/bioptim/blob/3e5ecb72d8b92c2b7fb6101b394020da3c5d3cc5/bioptim/models/biorbd/biorbd_model.py#L107)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

is too large? 
Is not the right size? (what happens if too small... it does not seem to raise)
</blockquote></details>

change > for ==
___
*[`bioptim/models/biorbd/biorbd_model.py` line 151 at r3](https://reviewable.io/reviews/pyomeca/bioptim/832#-Nq8JAwDDKPL_91lN6AK:-Nq8JAwECjTdJkp2oYBt:b-yjk55v) ([raw file](https://github.com/pyomeca/bioptim/blob/2a81e46f592676fcfe2f1dbe3ead5188b9685a7e/bioptim/models/biorbd/biorbd_model.py#L151)):*
> ```Python
> 
>         if muscle_size > self.nb_muscles:
>             raise ValueError(f"Length of muscle is too big. Expected size: {self.nb_muscles}, but got: {muscle_size}")
> ```

The ">" should be a "=="

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/832#-:-Nq8bgC1AUascktjTiIR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Infa60)

**Comment by pariterre** [comment]
@mickaelbegon  @Infa60 @EveCharbie 
This example seems to have been modified by both of you. Which is the (see the conflict). Which version is the expected one?

**Comment by EveCharbie** [comment]
It was not purposely changed by Infa60, his modifications are due to the merging problem we talked about.
Between my changes and mickaelbegon's changes, mickaelbegon should be kept (I will reintroduce root_torque_dynamics elsewhere).

**Pull request merged**
