### PR TITLE
holonomic graph multiphase multi all combinations

### PR DESCRIPTION
**Pull request by Ipuch**
@SamHybz, @AnaisFarr 

This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/885)

### CODE REVIEW

**Comment by Ipuch** [comment]
okay guys @SamHybz @AnaisFarr , It seems like show_bounds works back !!

```python3

sol = ocp.solve(Solver.IPOPT(show_online_optim=False, show_options={show_bounds: True}))
sol.graphs(show_bounds=True)

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/885)* status: all files reviewed, 5 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/dynamics/configure_problem.py` line 1017 at r2](https://reviewable.io/reviews/pyomeca/bioptim/885#-O26GVz58W4yfEUFIWtd:-O26GVz58W4yfEUFIWte:bjedbl3) ([raw file](https://github.com/pyomeca/bioptim/blob/5036feeea2c309c3680305ae1d25c7166917c5e7/bioptim/dynamics/configure_problem.py#L1017)):*
> ```Python
>         all_multipliers_names = []
>         for nlp_i in ocp.nlp:
>             if hasattr(nlp_i.model, "_dependent_joint_index"):  # making sure we have a HolonomicBiorbdModel
> ```

`if hasattr(nlp_i.model, "is_holonomic" and nlp_i.model.is_holonomic):`
___
*[`bioptim/dynamics/configure_problem.py` line 1081 at r2](https://reviewable.io/reviews/pyomeca/bioptim/885#-O26H7Z_4jLgWzWxnUbj:-O26H7Z_4jLgWzWxnUbk:bjedbl3) ([raw file](https://github.com/pyomeca/bioptim/blob/5036feeea2c309c3680305ae1d25c7166917c5e7/bioptim/dynamics/configure_problem.py#L1081)):*
> ```Python
>         all_multipliers_names = []
>         for nlp_i in ocp.nlp:
>             if hasattr(nlp_i.model, "_dependent_joint_index"):  # making sure we have a HolonomicBiorbdModel
> ```

`if hasattr(nlp_i.model, "is_holonomic" and nlp_i.model.is_holonomic):`
___
*[`bioptim/dynamics/configure_problem.py` line 1099 at r2](https://reviewable.io/reviews/pyomeca/bioptim/885#-O26Idex5jw1Av67AQCA:-O26Idex5jw1Av67AQCB:bpidp5i) ([raw file](https://github.com/pyomeca/bioptim/blob/5036feeea2c309c3680305ae1d25c7166917c5e7/bioptim/dynamics/configure_problem.py#L1099)):*
> ```Python
>             plot_type=PlotType.INTEGRATED,
>             axes_idx=axes_idx,
>             legend=all_multipliers_names,
> ```

combine_to="q",
___
*[`bioptim/dynamics/configure_problem.py` line 1144 at r2](https://reviewable.io/reviews/pyomeca/bioptim/885#-O26HIEt4pOVbCgU8Zx5:-O26HIEt4pOVbCgU8Zx6:bjedbl3) ([raw file](https://github.com/pyomeca/bioptim/blob/5036feeea2c309c3680305ae1d25c7166917c5e7/bioptim/dynamics/configure_problem.py#L1144)):*
> ```Python
>         all_multipliers_names = []
>         for nlp_i in ocp.nlp:
>             if hasattr(nlp_i.model, "_dependent_joint_index"):  # making sure we have a HolonomicBiorbdModel
> ```

`if hasattr(nlp_i.model, "is_holonomic" and nlp_i.model.is_holonomic):`
___
*[`bioptim/dynamics/configure_problem.py` line 1346 at r2](https://reviewable.io/reviews/pyomeca/bioptim/885#-O26HOVy-S7Itq_rf64O:-O26HOVy-S7Itq_rf64P:btlfcpe) ([raw file](https://github.com/pyomeca/bioptim/blob/5036feeea2c309c3680305ae1d25c7166917c5e7/bioptim/dynamics/configure_problem.py#L1346)):*
> ```Python
>         nlp.plot["contact_forces"] = CustomPlot(
>             lambda t0, phases_dt, node_idx, x, u, p, a, d: nlp.contact_forces_func(
>                 np.concatenate([t0, t0 + phases_dt[nlp.phase_idx]]), x, u, p, a, d
> ```

np.array() ?

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/885)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 1017 at r2](https://reviewable.io/reviews/pyomeca/bioptim/885#-O26GVz58W4yfEUFIWtd:-O26TwOBClJPH_2i0wbM:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/5036feeea2c309c3680305ae1d25c7166917c5e7/bioptim/dynamics/configure_problem.py#L1017)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`if hasattr(nlp_i.model, "is_holonomic" and nlp_i.model.is_holonomic):`
</blockquote></details>

Done
___
*[`bioptim/dynamics/configure_problem.py` line 1081 at r2](https://reviewable.io/reviews/pyomeca/bioptim/885#-O26H7Z_4jLgWzWxnUbj:-O26Tx3x0xK62GsVLe8q:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/5036feeea2c309c3680305ae1d25c7166917c5e7/bioptim/dynamics/configure_problem.py#L1081)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`if hasattr(nlp_i.model, "is_holonomic" and nlp_i.model.is_holonomic):`
</blockquote></details>

Done
___
*[`bioptim/dynamics/configure_problem.py` line 1099 at r2](https://reviewable.io/reviews/pyomeca/bioptim/885#-O26Idex5jw1Av67AQCA:-O26VCsp4vgChyiHN67y:bwluz75) ([raw file](https://github.com/pyomeca/bioptim/blob/5036feeea2c309c3680305ae1d25c7166917c5e7/bioptim/dynamics/configure_problem.py#L1099)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

combine_to="q",
</blockquote></details>

Didnt work
___
*[`bioptim/dynamics/configure_problem.py` line 1144 at r2](https://reviewable.io/reviews/pyomeca/bioptim/885#-O26HIEt4pOVbCgU8Zx5:-O26TyLsDB1LF9o380Ck:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/5036feeea2c309c3680305ae1d25c7166917c5e7/bioptim/dynamics/configure_problem.py#L1144)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`if hasattr(nlp_i.model, "is_holonomic" and nlp_i.model.is_holonomic):`
</blockquote></details>

Done
___
*[`bioptim/dynamics/configure_problem.py` line 1346 at r2](https://reviewable.io/reviews/pyomeca/bioptim/885#-O26HOVy-S7Itq_rf64O:-O26Vynh7d2sCKq6rPYp:b-4j1qza) ([raw file](https://github.com/pyomeca/bioptim/blob/5036feeea2c309c3680305ae1d25c7166917c5e7/bioptim/dynamics/configure_problem.py#L1346)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

np.array() ?
</blockquote></details>

finally concatenate was the good shot

**Review by pariterre — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/885)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Review by pariterre — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/885#-:-O2BFVNU62LnixKnmWuC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Pull request merged**
