### PR TITLE
[RTM] graphs uneven number of variables

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

related to issue : plots with different nx/nu #341

---
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/483)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/483)* status: all files reviewed, 7 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/dynamics/configure_problem.py` line 665 at r1](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4Sbbt84Z0uaP6sn_un:-N4Sbbt84Z0uaP6sn_uo:b-um5ivz) ([raw file](https://github.com/pyomeca/bioptim/blob/eb3b692afa3fd32d6f319ed338ac17fbc2f21bf2/bioptim/dynamics/configure_problem.py#L665)):*
> ```Python
>                 for i, nlp_ in enumerate(ocp.nlp):
>                     for j in range(nlp_.model.nbQ()):
>                         legend = nlp_.model.nameDof()[j].to_string()
> ```

Passing `ocp` in that function is a major change in the API, as it is a function which is exposed to lay users. 
Doing that code in OCP (before calling configure), would allow to not change the API, while making sure phase_mappings is not uselessly recomputed over and over. 
Also, it feels that you are assuming `configure_new_variables` implies that it is a Generalized coordinate (or one of its derivative), while it can be basically anything (for instance muscle states, muscle or joint fatigue, etc.). Adding a `plot_mapping` (or equivalent naming) field to NLP and only filling it for kinematic states (with None for other states) would allow to pass: `axes_idx=plot_mappings` as you did without restriction (since it would be None for where it is not applicable)



_Code quote:_
```Python
            if f"{name}_states" in nlp.plot_mapping:
                phase_mappings = nlp.plot_mapping[f"{name}_states"]
            else:
                dof_names = []
                dof_mapping_all_phases = [[] for _ in range(len(ocp.nlp))]
                for i, nlp_ in enumerate(ocp.nlp):
                    for j in range(nlp_.model.nbQ()):
                        legend = nlp_.model.nameDof()[j].to_string()
                        if legend in dof_names:
                            dof_mapping_all_phases[i] += [dof_names.index(legend)]
                        else:
                            dof_names += [legend]
                            dof_mapping_all_phases[i] += [len(dof_names) - 1]

                phase_mappings = Mapping(dof_mapping_all_phases[nlp.phase_idx])
```
___
*[`bioptim/dynamics/configure_problem.py` line 757 at r1](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4S_e9AALaORy_uaAnY:-N4S_e9AALaORy_uaAnZ:b6vyqbe) ([raw file](https://github.com/pyomeca/bioptim/blob/eb3b692afa3fd32d6f319ed338ac17fbc2f21bf2/bioptim/dynamics/configure_problem.py#L757)):*
> ```Python
>             for i in range(nlp.model.nbQ()):
>                 if nlp.model.nameDof()[i].to_string()[-4:-1] == "Rot" or nlp.model.nameDof()[i].to_string()[-6:-1] == "Trans":
>                     name_qdot += [nlp.model.nameDof()[i].to_string()]
> ```

Can you make a private function for this with input 'type' that one can pass: either 'omega', 'omegadot', 'omegaddot', etc. (instead of copy-pasting that snippet on all the configure functions



_Code quote:_
```Python
        if nlp.model.nbQuat() == 0:
            name_qdot = [name.to_string() for name in nlp.model.nameDof()]
        else:
            name_qdot = []
            for i in range(nlp.model.nbQ()):
                if nlp.model.nameDof()[i].to_string()[-4:-1] == "Rot" or nlp.model.nameDof()[i].to_string()[-6:-1] == "Trans":
                    name_qdot += [nlp.model.nameDof()[i].to_string()]
                else:
                    if nlp.model.nameDof()[i].to_string()[-5:] != "QuatW":
                        name_qdot += [nlp.model.nameDof()[i].to_string()[:-5] + "omega" + nlp.model.nameDof()[i].to_string()[-1]]
```
___
*[`bioptim/dynamics/configure_problem.py` line 789 at r1](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4ScsZo1qDS7VxMPV82:-N4ScsZo1qDS7VxMPV83:b6vyqbe) ([raw file](https://github.com/pyomeca/bioptim/blob/eb3b692afa3fd32d6f319ed338ac17fbc2f21bf2/bioptim/dynamics/configure_problem.py#L789)):*
> ```Python
>                     name_qddot += [nlp.model.nameDof()[i].to_string()]
>                 else:
>                     if nlp.model.nameDof()[i].to_string()[-5:] != "QuatW":
> ```

Can you make a private function for this with input 'type' that one can pass: either 'omega', 'omegadot', 'omegaddot', etc. (instead of copy-pasting that snippet on all the configure functions



_Code quote:_
```Python
        if nlp.model.nbQuat() == 0:
            name_qddot = [name.to_string() for name in nlp.model.nameDof()]
        else:
            name_qddot = []
            for i in range(nlp.model.nbQ()):
                if nlp.model.nameDof()[i].to_string()[-4:-1] == "Rot" or nlp.model.nameDof()[i].to_string()[-6:-1] == "Trans":
                    name_qddot += [nlp.model.nameDof()[i].to_string()]
                else:
                    if nlp.model.nameDof()[i].to_string()[-5:] != "QuatW":
                        name_qddot += [nlp.model.nameDof()[i].to_string()[:-5] + "omegadot" + nlp.model.nameDof()[i].to_string()[-1]]
```
___
*[`bioptim/dynamics/configure_problem.py` line 814 at r1](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4ScuFD0ESSmHPkV8ui:-N4ScuFD0ESSmHPkV8uj:b6vyqbe) ([raw file](https://github.com/pyomeca/bioptim/blob/eb3b692afa3fd32d6f319ed338ac17fbc2f21bf2/bioptim/dynamics/configure_problem.py#L814)):*
> ```Python
>             name_qdddot = [name.to_string() for name in nlp.model.nameDof()]
>         else:
>             name_qdddot = []
> ```

Can you make a private function for this with input 'type' that one can pass: either 'omega', 'omegadot', 'omegaddot', etc. (instead of copy-pasting that snippet on all the configure functions



_Code quote:_
```Python
        if nlp.model.nbQuat() == 0:
            name_qdddot = [name.to_string() for name in nlp.model.nameDof()]
        else:
            name_qdddot = []
            for i in range(nlp.model.nbQ()):
                if nlp.model.nameDof()[i].to_string()[-4:-1] == "Rot" or nlp.model.nameDof()[i].to_string()[-6:-1] == "Trans":
                    name_qdddot += [nlp.model.nameDof()[i].to_string()]
                else:
                    if nlp.model.nameDof()[i].to_string()[-5:] != "QuatW":
                        name_qdddot += [nlp.model.nameDof()[i].to_string()[:-5] + "omegadotdot" + nlp.model.nameDof()[i].to_string()[-1]]
```
___
*[`bioptim/dynamics/configure_problem.py` line 820 at r1](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4S_xpl-7AcaKFvhnMm:-N4S_xpmEa_Gj0G-Cnaf:bzigogq) ([raw file](https://github.com/pyomeca/bioptim/blob/eb3b692afa3fd32d6f319ed338ac17fbc2f21bf2/bioptim/dynamics/configure_problem.py#L820)):*
> ```Python
>                 else:
>                     if nlp.model.nameDof()[i].to_string()[-5:] != "QuatW":
>                         name_qdddot += [nlp.model.nameDof()[i].to_string()[:-5] + "omegadotdot" + nlp.model.nameDof()[i].to_string()[-1]]
> ```

To be consistent with the rest of bioptim, I'd make it omegaddot



_Code quote:_
```Python
omegadotdot
```
___
*[`bioptim/dynamics/configure_problem.py` line 848 at r1](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4ScvS48_IxtJXv_PNu:-N4ScvS48_IxtJXv_PNv:b6vyqbe) ([raw file](https://github.com/pyomeca/bioptim/blob/eb3b692afa3fd32d6f319ed338ac17fbc2f21bf2/bioptim/dynamics/configure_problem.py#L848)):*
> ```Python
>         else:
>             name_tau = []
>             for i in range(nlp.model.nbQ()):
> ```

Can you make a private function for this with input 'type' that one can pass: either 'omega', 'omegadot', 'omegaddot', etc. (instead of copy-pasting that snippet on all the configure functions



_Code quote:_
```Python
        if nlp.model.nbQuat() == 0:
            name_tau = [name.to_string() for name in nlp.model.nameDof()]
        else:
            name_tau = []
            for i in range(nlp.model.nbQ()):
                if nlp.model.nameDof()[i].to_string()[-4:-1] == "Rot":
                    name_tau += [nlp.model.nameDof()[i].to_string()]
                else:
                    if nlp.model.nameDof()[i].to_string()[-5:] != "QuatW":
                        name_tau += [nlp.model.nameDof()[i].to_string()]
```
___
*[`bioptim/dynamics/configure_problem.py` line 902 at r1](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4ScxI6EKUsZCRRM253:-N4ScxI6EKUsZCRRM254:b6vyqbe) ([raw file](https://github.com/pyomeca/bioptim/blob/eb3b692afa3fd32d6f319ed338ac17fbc2f21bf2/bioptim/dynamics/configure_problem.py#L902)):*
> ```Python
>         else:
>             name_taudot = []
>             for i in range(nlp.model.nbQ()):
> ```

Can you make a private function for this with input 'type' that one can pass: either 'omega', 'omegadot', 'omegaddot', etc. (instead of copy-pasting that snippet on all the configure functions



_Code quote:_
```Python
        if nlp.model.nbQuat() == 0:
            name_taudot = [name.to_string() for name in nlp.model.nameDof()]
        else:
            name_taudot = []
            for i in range(nlp.model.nbQ()):
                if nlp.model.nameDof()[i].to_string()[-4:-1] == "Rot":
                    name_taudot += [nlp.model.nameDof()[i].to_string()]
                else:
                    if nlp.model.nameDof()[i].to_string()[-5:] != "QuatW":
                        name_taudot += [nlp.model.nameDof()[i].to_string()]
```

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/483)* status: all files reviewed, 4 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/dynamics/configure_problem.py` line 80 at r3](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4hc76H8xjfPVs5nOIc:-N4hc76H8xjfPVs5nOId:bh0qupi) ([raw file](https://github.com/pyomeca/bioptim/blob/38a5a67bb9ecb63d8c20e18cb564438cc8e139dd/bioptim/dynamics/configure_problem.py#L80)):*
> ```Python
> 
>         if hasattr(nlp, "phase_mapping"):
>             idx = nlp.phase_mapping.map_idx
> ```

Add this to the NLP class (and this if it is None) instead of hasattr



_Code quote:_
```Python
        if hasattr(nlp, "phase_mapping"):
            idx = nlp.phase_mapping.map_idx
```
___
*[`bioptim/dynamics/configure_problem.py` line 786 at r3](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4hcYCM7EMf8bYW8wgI:-N4hcYCOCwyKp23FYP1x:bz1h7lj) ([raw file](https://github.com/pyomeca/bioptim/blob/38a5a67bb9ecb63d8c20e18cb564438cc8e139dd/bioptim/dynamics/configure_problem.py#L786)):*
> ```Python
> 
>         name = "qddot"
>         name_qddot = ConfigureProblem._modifying_variable_names(nlp, name)
> ```

`_get_kinematics_based_names`?



_Code quote:_
```Python
_modifying_variable_names
```
___
*[`bioptim/dynamics/configure_problem.py` line 978 at r3](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4hcoI3DEF2zoc2zsCx:-N4hcoI3DEF2zoc2zsCy:btj3b6s) ([raw file](https://github.com/pyomeca/bioptim/blob/38a5a67bb9ecb63d8c20e18cb564438cc8e139dd/bioptim/dynamics/configure_problem.py#L978)):*
> ```Python
>                 double_mapping = nlp.variable_mappings[name].to_first.map(nlp.phase_mapping.map_idx).T.tolist()[0]
>                 double_mapping = [int(double_mapping[i]) for i in range(len(double_mapping))]
>                 # double_mapping = [nlp.phase_mapping.map_idx.index(nlp.variable_mappings[name].to_first.map_idx[i]) for i in range(len(nlp.variable_mappings[name].to_first.map_idx))]
> ```

to remove



_Code quote:_
```Python
  # double_mapping = [nlp.phase_mapping.map_idx.index(nlp.variable_mappings[name].to_first.map_idx[i]) for i in range(len(nlp.variable_mappings[name].to_first.map_idx))]
```
___
*[`bioptim/gui/plot.py` line 392 at r3](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4hd93b9jVfAX-rHDWg:-N4hd93b9jVfAX-rHDWh:b-bci2v3) ([raw file](https://github.com/pyomeca/bioptim/blob/38a5a67bb9ecb63d8c20e18cb564438cc8e139dd/bioptim/gui/plot.py#L392)):*
> ```Python
> 
>                 mapping = nlp.plot[variable].phase_mappings.map_idx
>                 for ctr, k in enumerate(mapping):
> ```

`range(len(mapping))`
ou
`ctr, _ in enumerate(mapping)`



_Code quote:_
```Python
ctr, k in enumerate(mapping)
```

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/483)* status: all files reviewed, 4 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 665 at r1](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4Sbbt84Z0uaP6sn_un:-N4buyCfEXZrK3hloI3i:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/eb3b692afa3fd32d6f319ed338ac17fbc2f21bf2/bioptim/dynamics/configure_problem.py#L665)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Passing `ocp` in that function is a major change in the API, as it is a function which is exposed to lay users. 
Doing that code in OCP (before calling configure), would allow to not change the API, while making sure phase_mappings is not uselessly recomputed over and over. 
Also, it feels that you are assuming `configure_new_variables` implies that it is a Generalized coordinate (or one of its derivative), while it can be basically anything (for instance muscle states, muscle or joint fatigue, etc.). Adding a `plot_mapping` (or equivalent naming) field to NLP and only filling it for kinematic states (with None for other states) would allow to pass: `axes_idx=plot_mappings` as you did without restriction (since it would be None for where it is not applicable)
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 757 at r1](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4S_e9AALaORy_uaAnY:-N4SmwLZ5GPrVT9DI9vZ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/eb3b692afa3fd32d6f319ed338ac17fbc2f21bf2/bioptim/dynamics/configure_problem.py#L757)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Can you make a private function for this with input 'type' that one can pass: either 'omega', 'omegadot', 'omegaddot', etc. (instead of copy-pasting that snippet on all the configure functions
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 789 at r1](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4ScsZo1qDS7VxMPV82:-N4SmzbjE_2unfN2pAlz:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/eb3b692afa3fd32d6f319ed338ac17fbc2f21bf2/bioptim/dynamics/configure_problem.py#L789)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Can you make a private function for this with input 'type' that one can pass: either 'omega', 'omegadot', 'omegaddot', etc. (instead of copy-pasting that snippet on all the configure functions
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 80 at r3](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4hc76H8xjfPVs5nOIc:-N51Ily1-s-wjlHdsr0c:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/38a5a67bb9ecb63d8c20e18cb564438cc8e139dd/bioptim/dynamics/configure_problem.py#L80)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Add this to the NLP class (and this if it is None) instead of hasattr
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 786 at r3](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4hcYCM7EMf8bYW8wgI:-N51IoEs3l1pBuXaxB6S:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/38a5a67bb9ecb63d8c20e18cb564438cc8e139dd/bioptim/dynamics/configure_problem.py#L786)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`_get_kinematics_based_names`?
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 978 at r3](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4hcoI3DEF2zoc2zsCx:-N51IvAB2Qpzf8Or9Xri:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/38a5a67bb9ecb63d8c20e18cb564438cc8e139dd/bioptim/dynamics/configure_problem.py#L978)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

to remove
</blockquote></details>

Done.
___
*[`bioptim/gui/plot.py` line 392 at r3](https://reviewable.io/reviews/pyomeca/bioptim/483#-N4hd93b9jVfAX-rHDWg:-N51IwpC7u981Zlc2e1o:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/38a5a67bb9ecb63d8c20e18cb564438cc8e139dd/bioptim/gui/plot.py#L392)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`range(len(mapping))`
ou
`ctr, _ in enumerate(mapping)`
</blockquote></details>

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/483)* status: all files reviewed, 11 unresolved discussions (waiting on @EveCharbie)

___
*[`tests/test_dynamics.py` line 41 at r4](https://reviewable.io/reviews/pyomeca/bioptim/483#-N6xPSOHEau8_ct0JFWa:-N6xPSOHEau8_ct0JFWb:b-51vwc8) ([raw file](https://github.com/pyomeca/bioptim/blob/25f2926bb935c9e3e2e68319bbc3eb8a9093cd22/tests/test_dynamics.py#L41)):*
> ```Python
>     nlp.u_bounds = np.zeros((nlp.model.nbQ(), 1))
>     ocp = OptimalControlProgram(nlp)
>     nlp.phase_mapping = None
> ```

If you have to add it by hand here, it means it is probably not in the NonLinearProgram, you can move it in the __init__() of NLP and remove it in here.
___
*[`tests/test_dynamics.py` line 100 at r4](https://reviewable.io/reviews/pyomeca/bioptim/483#-N6xQX-SDWYgJIdSgo3w:-N6xQX-SDWYgJIdSgo3x:bz2p2pu) ([raw file](https://github.com/pyomeca/bioptim/blob/25f2926bb935c9e3e2e68319bbc3eb8a9093cd22/tests/test_dynamics.py#L100)):*
> ```Python
>     nlp.u_bounds = np.zeros((nlp.model.nbQ() * 2, 1))
>     ocp = OptimalControlProgram(nlp)
>     nlp.phase_mapping = None
> ```

You should be able to remove this also
___
*[`tests/test_dynamics.py` line 151 at r4](https://reviewable.io/reviews/pyomeca/bioptim/483#-N6xQa9iCB1-2MhQQ-s6:-N6xQa9iCB1-2MhQQ-s7:bz2p2pu) ([raw file](https://github.com/pyomeca/bioptim/blob/25f2926bb935c9e3e2e68319bbc3eb8a9093cd22/tests/test_dynamics.py#L151)):*
> ```Python
>     nlp.u_bounds = np.zeros((nlp.model.nbQ() * 2, 1))
>     ocp = OptimalControlProgram(nlp)
>     nlp.phase_mapping = None
> ```

You should be able to remove this also
___
*[`tests/test_dynamics.py` line 202 at r4](https://reviewable.io/reviews/pyomeca/bioptim/483#-N6xQajb9Hn5Mnf3qUMh:-N6xQajb9Hn5Mnf3qUMi:bz2p2pu) ([raw file](https://github.com/pyomeca/bioptim/blob/25f2926bb935c9e3e2e68319bbc3eb8a9093cd22/tests/test_dynamics.py#L202)):*
> ```Python
>     nlp.u_bounds = np.zeros((nlp.model.nbQ(), 1))
>     ocp = OptimalControlProgram(nlp)
>     nlp.phase_mapping = None
> ```

You should be able to remove this also
___
*[`tests/test_dynamics.py` line 318 at r4](https://reviewable.io/reviews/pyomeca/bioptim/483#-N6xQbO05bj8GSHIkgc4:-N6xQbO05bj8GSHIkgc5:bz2p2pu) ([raw file](https://github.com/pyomeca/bioptim/blob/25f2926bb935c9e3e2e68319bbc3eb8a9093cd22/tests/test_dynamics.py#L318)):*
> ```Python
>     nlp.u_bounds = np.zeros((nlp.model.nbQ(), 2))
>     ocp = OptimalControlProgram(nlp)
>     nlp.phase_mapping = None
> ```

You should be able to remove this also
___
*[`tests/test_dynamics.py` line 400 at r4](https://reviewable.io/reviews/pyomeca/bioptim/483#-N6xQbrW17muPTEA_AuP:-N6xQbrW17muPTEA_AuQ:bz2p2pu) ([raw file](https://github.com/pyomeca/bioptim/blob/25f2926bb935c9e3e2e68319bbc3eb8a9093cd22/tests/test_dynamics.py#L400)):*
> ```Python
>     nlp.u_bounds = np.zeros((nlp.model.nbQ() * 4, 1))
>     ocp = OptimalControlProgram(nlp)
>     nlp.phase_mapping = None
> ```

You should be able to remove this also
___
*[`tests/test_dynamics.py` line 478 at r4](https://reviewable.io/reviews/pyomeca/bioptim/483#-N6xQcHOEjzeREg3Yw_q:-N6xQcHOEjzeREg3Yw_r:bz2p2pu) ([raw file](https://github.com/pyomeca/bioptim/blob/25f2926bb935c9e3e2e68319bbc3eb8a9093cd22/tests/test_dynamics.py#L478)):*
> ```Python
>     nlp.u_bounds = np.zeros((nlp.model.nbQ() * 4, 1))
>     ocp = OptimalControlProgram(nlp)
>     nlp.phase_mapping = None
> ```

You should be able to remove this also
___
*[`tests/test_dynamics.py` line 510 at r4](https://reviewable.io/reviews/pyomeca/bioptim/483#-N6xQcoH5u4lUA7R-Pjt:-N6xQcoI-UK0QyauiFQG:bz2p2pu) ([raw file](https://github.com/pyomeca/bioptim/blob/25f2926bb935c9e3e2e68319bbc3eb8a9093cd22/tests/test_dynamics.py#L510)):*
> ```Python
>     nlp.u_bounds = np.zeros((nlp.model.nbQ() * 4, 1))
>     ocp = OptimalControlProgram(nlp)
>     nlp.phase_mapping = None
> ```

You should be able to remove this also
___
*[`tests/test_dynamics.py` line 541 at r4](https://reviewable.io/reviews/pyomeca/bioptim/483#-N6xQdQR6GkRm3oOHptE:-N6xQdQR6GkRm3oOHptF:bz2p2pu) ([raw file](https://github.com/pyomeca/bioptim/blob/25f2926bb935c9e3e2e68319bbc3eb8a9093cd22/tests/test_dynamics.py#L541)):*
> ```Python
>     nlp.u_bounds = np.zeros((nlp.model.nbQ(), 1))
>     ocp = OptimalControlProgram(nlp)
>     nlp.phase_mapping = None
> ```

You should be able to remove this also
___
*[`tests/test_dynamics.py` line 631 at r4](https://reviewable.io/reviews/pyomeca/bioptim/483#-N6xQdsR7jyvd4AQ9Lku:-N6xQdsR7jyvd4AQ9Lkv:bz2p2pu) ([raw file](https://github.com/pyomeca/bioptim/blob/25f2926bb935c9e3e2e68319bbc3eb8a9093cd22/tests/test_dynamics.py#L631)):*
> ```Python
> 
>     ocp = OptimalControlProgram(nlp)
>     nlp.phase_mapping = None
> ```

You should be able to remove this also
___
*[`tests/test_dynamics.py` line 1161 at r4](https://reviewable.io/reviews/pyomeca/bioptim/483#-N6xQeqw66K3WUNniuAd:-N6xQeqw66K3WUNniuAe:bz2p2pu) ([raw file](https://github.com/pyomeca/bioptim/blob/25f2926bb935c9e3e2e68319bbc3eb8a9093cd22/tests/test_dynamics.py#L1161)):*
> ```Python
>     nlp.u_bounds = np.zeros((nlp.model.nbQ(), 1))
>     ocp = OptimalControlProgram(nlp)
>     nlp.phase_mapping = None
> ```

You should be able to remove this also

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/483#-:-N7MDJT-DsryAJ0YsSj_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
