### PR TITLE
[RTM] IntegralApproximation -> QuadratureRule

### PR DESCRIPTION
**Pull request by 20chupin**
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/704)

### CODE REVIEW

**Comment by mickaelbegon** [comment]
Is is possible also to implement a quadrature rule that uses all intermediate points of the integration?

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/704)* status: all files reviewed, 3 unresolved discussions (waiting on @20chupin)

___
*[`bioptim/limits/objective_functions.py` line 60 at r2](https://reviewable.io/reviews/pyomeca/bioptim/704#-NZaiBD379Z5z1JiXyr5:-NZaiBD379Z5z1JiXyr6:bx0s13q) ([raw file](https://github.com/pyomeca/bioptim/blob/0cb5d75f4109e803729443ab14afcb8718649f77/bioptim/limits/objective_functions.py#L60)):*
> ```Python
>                     or params["integration_rule"] == QuadratureRule.RECTANGLE_RIGHT
>                 ):
>                     raise NotImplementedError(f"{params['integration_rule']} has not been implemented yet.")
> ```

```python3
           if "integration_rule" not in params.keys() or params["integration_rule"] == QuadratureRule.DEFAULT:
                params["integration_rule"] = QuadratureRule.RECTANGLE_LEFT
           if  not  params["integration_rule"] in (QuadratureRule. "implemented ones"):
                    raise NotImplementedError(f"{params['integration_rule']} has not been implemented yet for objective functions.")

```
___
*[`bioptim/misc/enums.py` line 143 at r2](https://reviewable.io/reviews/pyomeca/bioptim/704#-NZajAtqDjozbzwUSoO8:-NZajAtqDjozbzwUSoO9:b-xbamw6) ([raw file](https://github.com/pyomeca/bioptim/blob/0cb5d75f4109e803729443ab14afcb8718649f77/bioptim/misc/enums.py#L143)):*
> ```Python
> class QuadratureRule(Enum):
>     """
>     Selection of quadrature rule
> ```

Selection of quadrature rule to approximate integrals.
___
*[`tests/test_cost_function_integration.py` line 230 at r2](https://reviewable.io/reviews/pyomeca/bioptim/704#-NZajLOJ1zFznn6Ux14g:-NZajLOJ1zFznn6Ux14h:bt6ggyl) ([raw file](https://github.com/pyomeca/bioptim/blob/0cb5d75f4109e803729443ab14afcb8718649f77/tests/test_cost_function_integration.py#L230)):*
> ```Python
>         QuadratureRule.RECTANGLE_LEFT,
>         QuadratureRule.APPROXIMATE_TRAPEZOIDAL,
>         QuadratureRule.TRAPEZOIDAL,
> ```

Test overall QuadratureRule?

**Review by 20chupin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/704)* status: all files reviewed, 3 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/limits/objective_functions.py` line 60 at r2](https://reviewable.io/reviews/pyomeca/bioptim/704#-NZaiBD379Z5z1JiXyr5:-NZb6ihq35VM_2fIC0PY:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0cb5d75f4109e803729443ab14afcb8718649f77/bioptim/limits/objective_functions.py#L60)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

```python3
           if "integration_rule" not in params.keys() or params["integration_rule"] == QuadratureRule.DEFAULT:
                params["integration_rule"] = QuadratureRule.RECTANGLE_LEFT
           if  not  params["integration_rule"] in (QuadratureRule. "implemented ones"):
                    raise NotImplementedError(f"{params['integration_rule']} has not been implemented yet for objective functions.")

```
</blockquote></details>

Done.
___
*[`bioptim/misc/enums.py` line 143 at r2](https://reviewable.io/reviews/pyomeca/bioptim/704#-NZajAtqDjozbzwUSoO8:-NZb6xPrEbcbbA6D6qFk:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0cb5d75f4109e803729443ab14afcb8718649f77/bioptim/misc/enums.py#L143)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Selection of quadrature rule to approximate integrals.
</blockquote></details>

Done.
___
*[`tests/test_cost_function_integration.py` line 230 at r2](https://reviewable.io/reviews/pyomeca/bioptim/704#-NZajLOJ1zFznn6Ux14g:-NZb97AxBZFFU_TdYKMc:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0cb5d75f4109e803729443ab14afcb8718649f77/tests/test_cost_function_integration.py#L230)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Test overall QuadratureRule?
</blockquote></details>

Done.

**Review by Ipuch — DISMISSED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/704)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @20chupin)

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/704)* status: all files reviewed, 1 unresolved discussion (waiting on @20chupin)

___
*[`tests/test_cost_function_integration.py` line 257 at r3](https://reviewable.io/reviews/pyomeca/bioptim/704#-NZgHY4cEoBaW__mK3Ln:-NZgHY4cEoBaW__mK3Lo:b82hrdl) ([raw file](https://github.com/pyomeca/bioptim/blob/9133b7750651fa8c755cdf46e3f50f0fc9a0dda5/tests/test_cost_function_integration.py#L257)):*
> ```Python
>                 ode_solver=OdeSolver.COLLOCATION(),
>                 assume_phase_dynamics=assume_phase_dynamics,
>             )
> ```

add a `return`

and remove else

**Review by 20chupin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/704)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @Ipuch and @pariterre)

___
*[`tests/test_cost_function_integration.py` line 257 at r3](https://reviewable.io/reviews/pyomeca/bioptim/704#-NZgHY4cEoBaW__mK3Ln:-NZgN1qV0uPIau2iMCKj:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9133b7750651fa8c755cdf46e3f50f0fc9a0dda5/tests/test_cost_function_integration.py#L257)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

add a `return`

and remove else
</blockquote></details>

Done.

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/704#-:-NZgaLJcBv4qh_7VZdiF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @20chupin)

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/704#-:-NZgp9NmB44Dhk1TLyyA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @20chupin)

**Pull request merged**
