### PR TITLE
Implement manual graph display for pendulum test Issue 813

### PR DESCRIPTION
**Pull request by Alpha2Shahiri**
### All Submissions:

* [Y ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ Y] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ Y] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ Y] Does your submission pass the tests (if not please explain why this is intended)?
2. [Y ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ Y] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/827)

### CODE REVIEW

**Comment by EveCharbie** [comment]
@Alpha2Shahiri where are you at ? Do you need help, time a review?

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/827)* status: all files reviewed, 2 unresolved discussions (waiting on @Alpha2Shahiri)

___
*[`bioptim/examples/getting_started/pendulum.py` line 17 at r5](https://reviewable.io/reviews/pyomeca/bioptim/827#-Np_LFKC9p6-0iLD_UnY:-Np_LFKC9p6-0iLD_UnZ:b-3rlnyt) ([raw file](https://github.com/pyomeca/bioptim/blob/5204dc1164f96c7e5d2515059fbd1d813726c50d/bioptim/examples/getting_started/pendulum.py#L17)):*
> ```Python
> import matplotlib.pyplot as plt
> import matplotlib
> import numpy as np
> ```

Please only import 
```
import numpy as np  
from matplotlib import pyplot as plt
```
___
*[`bioptim/examples/getting_started/pendulum.py` line 291 at r5](https://reviewable.io/reviews/pyomeca/bioptim/827#-Np_LJoX1bnemJBmXS7f:-Np_LJoX1bnemJBmXS7g:bo2u23m) ([raw file](https://github.com/pyomeca/bioptim/blob/5204dc1164f96c7e5d2515059fbd1d813726c50d/bioptim/examples/getting_started/pendulum.py#L291)):*
> ```Python
> 
>     # Display the plot
>     plt.show()
> ```

Move these to a dedicated example (example_graph.py) 
and this can all be reduced to 


```
from bioptim import SolutionMerge, TimeAlignment  
  
\# Plotting the solution for decision  
decision\_time = sol.decision\_time(to\_merge\=SolutionMerge.NODES, time\_alignment\=TimeAlignment.STATES)  
decision\_states = sol.decision\_states()  
plt.step(decision\_time, decision\_states\["q"\].T, label\="Decision", where\='post')  
  
\# Retrieve stepwise states from the solution object.  
stepwise\_time = sol.stepwise\_time(to\_merge\=SolutionMerge.NODES, time\_alignment\=TimeAlignment.STATES)  
stepwise\_states = sol.stepwise\_states(to\_merge\=SolutionMerge.NODES)  
plt.plot(stepwise\_time, stepwise\_states\["q"\].T, label\="Stepwise")  
  
\# Plotting the solution for decision  
decision\_time = sol.decision\_time(to\_merge\=SolutionMerge.NODES, time\_alignment\=TimeAlignment.CONTROLS)  
decision\_controls = sol.decision\_controls(to\_merge\=SolutionMerge.NODES)  
plt.step(decision\_time, decision\_controls\["tau"\].T, label\="Decision", where\='post')  
  
\# Retrieve stepwise states from the solution object.  
stepwise\_time = sol.stepwise\_time(to\_merge\=SolutionMerge.NODES, time\_alignment\=TimeAlignment.CONTROLS)  
stepwise\_controls = sol.stepwise\_controls()  
plt.step(stepwise\_time, np.concatenate(stepwise\_controls\["tau"\], axis\=1).T, label\="Stepwise", where\='post')  
  
\# Display the plot  
plt.show()
```

**Comment by pariterre** [comment]
Time aligment is now implemented in bioptim thanks to #843 . The code snipped presented in the last comment should now work as is

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/827)* status: all files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/getting_started/pendulum.py` line 17 at r5](https://reviewable.io/reviews/pyomeca/bioptim/827#-Np_LFKC9p6-0iLD_UnY:-Nrvi6JH6ybYfxyrEqY4:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/5204dc1164f96c7e5d2515059fbd1d813726c50d/bioptim/examples/getting_started/pendulum.py#L17)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please only import 
```
import numpy as np  
from matplotlib import pyplot as plt
```
</blockquote></details>

done
___
*[`bioptim/examples/getting_started/pendulum.py` line 291 at r5](https://reviewable.io/reviews/pyomeca/bioptim/827#-Np_LJoX1bnemJBmXS7f:-Nrvk_tJ50qQ0A0Wz10t:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/5204dc1164f96c7e5d2515059fbd1d813726c50d/bioptim/examples/getting_started/pendulum.py#L291)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Move these to a dedicated example (example_graph.py) 
and this can all be reduced to 


```
from bioptim import SolutionMerge, TimeAlignment  
  
\# Plotting the solution for decision  
decision\_time = sol.decision\_time(to\_merge\=SolutionMerge.NODES, time\_alignment\=TimeAlignment.STATES)  
decision\_states = sol.decision\_states()  
plt.step(decision\_time, decision\_states\["q"\].T, label\="Decision", where\='post')  
  
\# Retrieve stepwise states from the solution object.  
stepwise\_time = sol.stepwise\_time(to\_merge\=SolutionMerge.NODES, time\_alignment\=TimeAlignment.STATES)  
stepwise\_states = sol.stepwise\_states(to\_merge\=SolutionMerge.NODES)  
plt.plot(stepwise\_time, stepwise\_states\["q"\].T, label\="Stepwise")  
  
\# Plotting the solution for decision  
decision\_time = sol.decision\_time(to\_merge\=SolutionMerge.NODES, time\_alignment\=TimeAlignment.CONTROLS)  
decision\_controls = sol.decision\_controls(to\_merge\=SolutionMerge.NODES)  
plt.step(decision\_time, decision\_controls\["tau"\].T, label\="Decision", where\='post')  
  
\# Retrieve stepwise states from the solution object.  
stepwise\_time = sol.stepwise\_time(to\_merge\=SolutionMerge.NODES, time\_alignment\=TimeAlignment.CONTROLS)  
stepwise\_controls = sol.stepwise\_controls()  
plt.step(stepwise\_time, np.concatenate(stepwise\_controls\["tau"\], axis\=1).T, label\="Stepwise", where\='post')  
  
\# Display the plot  
plt.show()
```
</blockquote></details>

Done

**Pull request closed without merging**
