### PR TITLE
[RTM when tests pass] changed reshape_to_vector/matrix for good (test breaking)

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/750)

### CODE REVIEW

**Comment by EveCharbie** [comment]
@pariterre once the other PR is merged, this could be reviewed/merged.

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/750)* status: all files reviewed, 9 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/ode_solver.py` line 152 at r2](https://reviewable.io/reviews/pyomeca/bioptim/750#-Nbyg9QO8p5FFroe7r7P:-Nbyq1yQ3iFco0mUa0fW:b-54ox8) ([raw file](https://github.com/pyomeca/bioptim/blob/bcdd0bb6c7bdce00f2b67c97f3eb01cc00504e02/bioptim/dynamics/ode_solver.py#L152)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I know it is a previous PR, but I still don't like this check... Could you add a "nlp.is_stochastic" that is set at the same time than motor_noise and sensory_noise? So to test if it is a stochastic nlp, it will feel more obvious
</blockquote></details>

Not really because when solving a stochastic problem, you need to call the dynamics with and without noise at different places in the code... We might need to discuss this.
But, his check is really for developers, I don't think it's possible to set these values on the user side.
___
*[`bioptim/dynamics/ode_solver.py` line 158 at r2](https://reviewable.io/reviews/pyomeca/bioptim/750#-NbygRQo7zmLjXKYhqHT:-NbyrI8u2_aS5VzaLFz5:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/bcdd0bb6c7bdce00f2b67c97f3eb01cc00504e02/bioptim/dynamics/ode_solver.py#L158)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Also, in order to prevent the else, define these prior to the if and override the values if with_noise is True
</blockquote></details>

Done.
___
*[`bioptim/dynamics/ode_solver.py` line 333 at r2](https://reviewable.io/reviews/pyomeca/bioptim/750#-NbygdsT2A-g2WnmznyD:-NbyrJOS0Fb86fzNZvsr:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/bcdd0bb6c7bdce00f2b67c97f3eb01cc00504e02/bioptim/dynamics/ode_solver.py#L333)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Same, move the content of the else before the if and remove the else
</blockquote></details>

Done.
___
*[`bioptim/dynamics/ode_solver.py` line 448 at r2](https://reviewable.io/reviews/pyomeca/bioptim/750#-NbygoNR9H5JdmXcFMnX:-NbyrK2i2nU2pFRe58Bl:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/bcdd0bb6c7bdce00f2b67c97f3eb01cc00504e02/bioptim/dynamics/ode_solver.py#L448)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Same, move the content of the else before the if and remove the else
</blockquote></details>

Done.
___
*[`bioptim/limits/constraints.py` line 728 at r2](https://reviewable.io/reviews/pyomeca/bioptim/750#-NbyhL197YBvA73GZtry:-NbysLUh7lSA_hXv7Dbt:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/bcdd0bb6c7bdce00f2b67c97f3eb01cc00504e02/bioptim/limits/constraints.py#L728)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

test if the nlp is stochastic?
</blockquote></details>

Done.
___
*[`bioptim/limits/multinode_penalty.py` line 599 at r2](https://reviewable.io/reviews/pyomeca/bioptim/750#-NbyhT93DPlKISdBv1Lk:-NbysN4p-izkJG4z3LcR:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/bcdd0bb6c7bdce00f2b67c97f3eb01cc00504e02/bioptim/limits/multinode_penalty.py#L599)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Test if the nlp is stochastic?
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_variable.py` line 157 at r2](https://reviewable.io/reviews/pyomeca/bioptim/750#-NbyiBla9dcWP-9l4EyU:-NbytoNoELS1y8Cew7P5:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/bcdd0bb6c7bdce00f2b67c97f3eb01cc00504e02/bioptim/optimization/optimization_variable.py#L157)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should not happen? If it is intended, I suggest to create another function, or at least document the expected types (currently it seems it was only expecting OptimizationVariable type as it is not specficied in the docstrincs. Is it an internal method? If so, convert it to a protected, otherwise it should be more thouroughly documented
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_variable.py` line 188 at r2](https://reviewable.io/reviews/pyomeca/bioptim/750#-NbyjPon0R1UfHQPYLS0:-Nbytq4oAhfOK6RlbThk:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/bcdd0bb6c7bdce00f2b67c97f3eb01cc00504e02/bioptim/optimization/optimization_variable.py#L188)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Same concerns:

This should not happen? If it is intended, I suggest to create another function, or at least document the expected types (currently it seems it was only expecting OptimizationVariable type as it is not specficied in the docstrincs. Is it an internal method? If so, convert it to a protected, otherwise it should be more thouroughly documented
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_variable.py` line 739 at r2](https://reviewable.io/reviews/pyomeca/bioptim/750#-NbyjTGH6pM194q0EWlW:-NbytqvJ1uvHTpcXKcKV:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/bcdd0bb6c7bdce00f2b67c97f3eb01cc00504e02/bioptim/optimization/optimization_variable.py#L739)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Same concerns:
This should not happen? If it is intended, I suggest to create another function, or at least document the expected types (currently it seems it was only expecting OptimizationVariable type as it is not specficied in the docstrincs. Is it an internal method? If so, convert it to a protected, otherwise it should be more thouroughly documented
</blockquote></details>

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/750)* status: all files reviewed, 9 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/dynamics/ode_solver.py` line 152 at r2](https://reviewable.io/reviews/pyomeca/bioptim/750#-Nbyg9QO8p5FFroe7r7P:-Nbyvb_08zMYvCXS0q0Y:b-ln2vxg) ([raw file](https://github.com/pyomeca/bioptim/blob/bcdd0bb6c7bdce00f2b67c97f3eb01cc00504e02/bioptim/dynamics/ode_solver.py#L152)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

Not really because when solving a stochastic problem, you need to call the dynamics with and without noise at different places in the code... We might need to discuss this.
But, his check is really for developers, I don't think it's possible to set these values on the user side.
</blockquote></details>

That would not be on the user side, but only on developer. The idea would be to set a flag as soon as it is possible to detect a stochastic ocp is being solve. The important bit is right now, the information that carries `is_stochastic == True` is `nlp.motor_noise is not None`, which is highly inconvenient

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/750)* status: 32 of 41 files reviewed, 9 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/ode_solver.py` line 152 at r2](https://reviewable.io/reviews/pyomeca/bioptim/750#-Nbyg9QO8p5FFroe7r7P:-Nc1k4ubBQVI2D-NtLbm:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/bcdd0bb6c7bdce00f2b67c97f3eb01cc00504e02/bioptim/dynamics/ode_solver.py#L152)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

That would not be on the user side, but only on developer. The idea would be to set a flag as soon as it is possible to detect a stochastic ocp is being solve. The important bit is right now, the information that carries `is_stochastic == True` is `nlp.motor_noise is not None`, which is highly inconvenient
</blockquote></details>

Done.

**Review by pariterre — DISMISSED** [review]
:lgtm:

> Reviewed 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/750#-:-Nc2dSjh1UGaCTDKgcLa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Comment by EveCharbie** [comment]
@pariterre ready :)

**Review by pariterre — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/750#-:-Nc3IvkE468IxAFY34x5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
