### PR TITLE
[RTM when #733 is merged] controls piecewise constant with last node

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/737)

### CODE REVIEW

**Comment by EveCharbie** [comment]
Answering to issue#710

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/737)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

___
*[`tests/test_cost_function_integration.py` line 520 at r1](https://reviewable.io/reviews/pyomeca/bioptim/737#-Navgdxd2p8XCwlwRlN7:-Navgdxd2p8XCwlwRlN8:b-cn91wn) ([raw file](https://github.com/pyomeca/bioptim/blob/80126a6d5106e472eaf4847b4ce69496dd6cbd56/tests/test_cost_function_integration.py#L520)):*
> ```Python
>     np.testing.assert_equal(f.shape, (1, 1))
>     if integration_rule == QuadratureRule.RECTANGLE_LEFT:
>         if control_type == ControlType.CONSTANT:
> ```

Add test if last control is nan
___
*[`tests/test_cost_function_integration.py` line 527 at r1](https://reviewable.io/reviews/pyomeca/bioptim/737#-NavffDQ0K-LwTUE1yGO:-NavffDQ0K-LwTUE1yGP:b-z36v90) ([raw file](https://github.com/pyomeca/bioptim/blob/80126a6d5106e472eaf4847b4ce69496dd6cbd56/tests/test_cost_function_integration.py#L527)):*
> ```Python
>                 np.testing.assert_almost_equal(f[0, 0], 69.3969483839429, decimal=4)  # for windows
>                 np.testing.assert_almost_equal(j_printed, 69.3969483839429, decimal=4)
>         elif control_type == ControlType.CONSTANT_WITH_LAST_NODE:
> ```

Add test if last control is not nan

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/737)* status: all files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`tests/test_cost_function_integration.py` line 520 at r1](https://reviewable.io/reviews/pyomeca/bioptim/737#-Navgdxd2p8XCwlwRlN7:-NavtAKjCG2jrgKNiOn3:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/80126a6d5106e472eaf4847b4ce69496dd6cbd56/tests/test_cost_function_integration.py#L520)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Add test if last control is nan
</blockquote></details>

Done.
___
*[`tests/test_cost_function_integration.py` line 527 at r1](https://reviewable.io/reviews/pyomeca/bioptim/737#-NavffDQ0K-LwTUE1yGO:-NavtBCi6Fv0Kv8G62MB:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/80126a6d5106e472eaf4847b4ce69496dd6cbd56/tests/test_cost_function_integration.py#L527)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Add test if last control is not nan
</blockquote></details>

Done.

**Comment by EveCharbie** [comment]
@pariterre Thanks :)
This one would be the next candidate to be merged.

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/737#-:-NawOiMk7pYNasHXvLsy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
