### PR TITLE
[RTM when tests pass] Time dependent test correction

### PR DESCRIPTION
**Pull request by Kev1CO**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/759)

### CODE REVIEW

**Comment by Kev1CO** [comment]
/!\ Warning /!\
Encountered an awkward behavior of use_sx: False or True not giving the same results
To comfirm it is either normal or an error was made

**Comment by Kev1CO** [comment]
Don't know why test control type none doesn't work.
The values given in test are different (slightly) then those on my computer.
Both tests are runed on windows

**Comment by Kev1CO** [comment]
Same for time_dependent_test but this time ubuntu and macos doesn't work
Where on my computer it does

**Comment by pariterre** [comment]
When tests pass on some architechture but not all, it usually means that the OCP is unstable due to a flat region near the optimal solution (as opposed to a convex region). This leads to the optimizer not know which direction to go, and stopping at random points as they are all equivalent. 
This can usually be overcome by adding objective with small weight on the decision variable (minimize_control and/or minimize_state) in ordre to convexify the region near the solution (in order words, making sure the solution is unique). 

If it is not possible to add such objectives, you can reduce the tolerance of the test in the np.assert (using decimal) or even skip the test comparison for some architechture (for instance, `if windows: skip`)

Just know that it is something we are aware of (casadi does not have the exact same behavior on all platform). This can be surprising (and worrying) but is not unexpected

**Comment by Kev1CO** [comment]
> When tests pass on some architechture but not all, it usually means that the OCP is unstable due to a flat region near the optimal solution (as opposed to a convex region). This leads to the optimizer not know which direction to go, and stopping at random points as they are all equivalent. This can usually be overcome by adding objective with small weight on the decision variable (minimize_control and/or minimize_state) in ordre to convexify the region near the solution (in order words, making sure the solution is unique).
> 
> If it is not possible to add such objectives, you can reduce the tolerance of the test in the np.assert (using decimal) or even skip the test comparison for some architechture (for instance, `if windows: skip`)
> 
> Just know that it is something we are aware of (casadi does not have the exact same behavior on all platform). This can be surprising (and worrying) but is not unexpected

Thank you for the clear precision, i'll update my tests to make them repeatable.

**Comment by Kev1CO** [comment]
Less but still problems

**Comment by Kev1CO** [comment]
Modified objective values (track, and quadratic), still differences between platforms

**Review by pariterre — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/759#-:-NfRz8oR1jr5IIFKq-oD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Kev1CO)

**Comment by Kev1CO** [comment]
Last failed test belongs to stochastic exemple

**Pull request merged**
