### PR TITLE
[RTM when answered] Add min power (joint and muscle) - typo in Readme - new strategy of CI

### PR DESCRIPTION
**Pull request by mickaelbegon**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/733)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 54 of 70 files at r1, 1 of 2 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/733)* status: all files reviewed, 4 unresolved discussions (waiting on @mickaelbegon)

___
*[`bioptim/dynamics/dynamics_functions.py` line 763 at r3](https://reviewable.io/reviews/pyomeca/bioptim/733#-Nav_U1EEbC5JFSUBV7C:-Nav_U1EEbC5JFSUBV7D:b-1nlp35) ([raw file](https://github.com/pyomeca/bioptim/blob/ed75777308e97acebde9192fe434785febdc831b/bioptim/dynamics/dynamics_functions.py#L763)):*
> ```Python
> 
>     @staticmethod
>     def compute_qddot(nlp: NonLinearProgram, qdot: MX | SX, qddot: MX | SX):
> ```

This method can be removed as it is not useful from qdot to qddot (unlike q to qdot which takes care of changes in dimension when quaternion are present)
___
*[`bioptim/limits/penalty.py` line 332 at r3](https://reviewable.io/reviews/pyomeca/bioptim/733#-NavZ4kgE6Jzgr-QhS-R:-NavZ4kgE6Jzgr-QhS-S:b4oddmr) ([raw file](https://github.com/pyomeca/bioptim/blob/ed75777308e97acebde9192fe434785febdc831b/bioptim/limits/penalty.py#L332)):*
> ```Python
>             # var.extend([controller.controls[key] for key in controller.controls])
>             # var.extend([controller.parameters[key] for key in controller.parameters])
>             # return controller.mx_to_cx("com_ddot", com_ddot, *var)
> ```

This can be removed (no longer useful)
___
*[`bioptim/limits/penalty.py` line 1340 at r3](https://reviewable.io/reviews/pyomeca/bioptim/733#-NavYu1t56VAs0xs652V:-NavYu1t56VAs0xs652W:b-xqys4p) ([raw file](https://github.com/pyomeca/bioptim/blob/ed75777308e97acebde9192fe434785febdc831b/bioptim/limits/penalty.py#L1340)):*
> ```Python
> 
>         Returns:
>             The acceleration of the specified markers or the CoM.
> ```

Update this according to the comments in #722 
___
*[`tests/shard3/test_global_getting_started.py` line 326 at r3](https://reviewable.io/reviews/pyomeca/bioptim/733#-NavZcjuDht5O1-UHr5l:-NavZcjuDht5O1-UHr5m:b-xsshk0) ([raw file](https://github.com/pyomeca/bioptim/blob/ed75777308e97acebde9192fe434785febdc831b/tests/shard3/test_global_getting_started.py#L326)):*
> ```Python
> def test_pendulum_save_and_load_rk8(use_sx):
>     #    if sys.platform == "win32":  # it works but not with the CI
>     #        return
> ```

This can be removed if it works

**Review by mickaelbegon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/733)* status: all files reviewed, 4 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/dynamics_functions.py` line 763 at r3](https://reviewable.io/reviews/pyomeca/bioptim/733#-Nav_U1EEbC5JFSUBV7C:-NavcAVWEiB_jYCbWNrI:ba3dfob) ([raw file](https://github.com/pyomeca/bioptim/blob/ed75777308e97acebde9192fe434785febdc831b/bioptim/dynamics/dynamics_functions.py#L763)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This method can be removed as it is not useful from qdot to qddot (unlike q to qdot which takes care of changes in dimension when quaternion are present)
</blockquote></details>

Removed
___
*[`bioptim/limits/penalty.py` line 332 at r3](https://reviewable.io/reviews/pyomeca/bioptim/733#-NavZ4kgE6Jzgr-QhS-R:-NavcT0oAT05mwhus5Jk:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/ed75777308e97acebde9192fe434785febdc831b/bioptim/limits/penalty.py#L332)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This can be removed (no longer useful)
</blockquote></details>

done

**Review by mickaelbegon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/733)* status: all files reviewed, 4 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/limits/penalty.py` line 1340 at r3](https://reviewable.io/reviews/pyomeca/bioptim/733#-NavYu1t56VAs0xs652V:-NavktSX4ITCOayApODJ:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/ed75777308e97acebde9192fe434785febdc831b/bioptim/limits/penalty.py#L1340)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Update this according to the comments in #722 
</blockquote></details>

done
___
*[`tests/shard3/test_global_getting_started.py` line 326 at r3](https://reviewable.io/reviews/pyomeca/bioptim/733#-NavZcjuDht5O1-UHr5l:-NavhiED2yQlAdYlUcb3:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/ed75777308e97acebde9192fe434785febdc831b/tests/shard3/test_global_getting_started.py#L326)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This can be removed if it works
</blockquote></details>

done

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/733#-:-Navpp890pjruy2uuNC4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mickaelbegon)

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/733#-:-NavqHAyAbWMVn_rT7W7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mickaelbegon)

**Pull request merged**
