### PR TITLE
[RTR] Refactor new_variable

### PR DESCRIPTION
**Pull request by Ipuch**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/730)

### CODE REVIEW

**Review by pariterre — APPROVED** [review]
Waiting for #733 

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/730#-:-NavoGAC6pIIj7G17TLP:bpl4dgd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Review by pariterre — DISMISSED** [review]
Waiting for #733

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/730#-:-Navol3fEfe0Pf0rzIgM:b-1gruzh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Comment by Ipuch** [comment]
@pariterre do you mind merging and black my PR ? 😇

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/730#-:-Nba1ffcCb2E5EZp13Qo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Pull request merged**
