### PR TITLE
Removed save and load

### PR DESCRIPTION
**Pull request by pariterre**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/804)

### CODE REVIEW

**Comment by pariterre** [comment]
@Ipuch and @EveCharbie 
Are you chill with this? (tests fail only because of transitifon towards biorbd 1.10.2)

**Review by EveCharbie — COMMENTED** [review]
Looks perfect to me :)
Maybe we should just update pendulum.py to show how we recommend saving the solution (using the del sol.ocp).

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/804#-:-NjILu5vElmPjpDc6mSI:bd7kvbc)* status: 0 of 36 files reviewed, 3 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py` line 187 at r2](https://reviewable.io/reviews/pyomeca/bioptim/804#-NjIKD-g2ayuUtoPuwJQ:-NjIKD-h0UQw5VaTnh8E:b-k6l3ge) ([raw file](https://github.com/pyomeca/bioptim/blob/305ec5046ec280d2b943c63448f2767e96a77188/bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py#L187)):*
> ```Python
>     objective_functions.add(ObjectiveFcn.Mayer.MINIMIZE_TIME, weight=1)
>     objective_functions.add(
>         ObjectiveFcn.Lagrange.MINIMIZE_CONTROL,
> ```

If it was possible to let it as before, it would better match the original paper.



_Code quote:_
```Python
     ObjectiveFcn.Lagrange.MINIMIZE_CONTROL,
```
___
*[`bioptim/models/biorbd/biorbd_model.py` line 34 at r2](https://reviewable.io/reviews/pyomeca/bioptim/804#-NjIK_Q_Bm4r2cDlRb9m:-NjIK_Q_Bm4r2cDlRb9n:b32vjw) ([raw file](https://github.com/pyomeca/bioptim/blob/305ec5046ec280d2b943c63448f2767e96a77188/bioptim/models/biorbd/biorbd_model.py#L34)):*
> ```Python
>     @property
>     def name(self) -> str:
>         # parse the path and split to get the .bioMod name
> ```

<3
___
*[`tests/shard5/test_global_stochastic_collocation.py` line 215 at r2](https://reviewable.io/reviews/pyomeca/bioptim/804#-NjILpJQ2GzMSgd5fbjd:-NjILpJQ2GzMSgd5fbje:beyyv05) ([raw file](https://github.com/pyomeca/bioptim/blob/305ec5046ec280d2b943c63448f2767e96a77188/tests/shard5/test_global_stochastic_collocation.py#L215)):*
> ```Python
>     f = np.array(sol.cost)
>     np.testing.assert_equal(f.shape, (1, 1))
>     np.testing.assert_almost_equal(f[0, 0], 4.099146411209181)
> ```

Please revert if you agree with my comment above

**Review by pariterre — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/804)* status: 0 of 36 files reviewed, 3 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py` line 187 at r2](https://reviewable.io/reviews/pyomeca/bioptim/804#-NjIKD-g2ayuUtoPuwJQ:-NjIMhYe8EUE_f4Mt2h7:byb9u5v) ([raw file](https://github.com/pyomeca/bioptim/blob/305ec5046ec280d2b943c63448f2767e96a77188/bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py#L187)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

If it was possible to let it as before, it would better match the original paper.
</blockquote></details>

Mayer.MINIMIZE_CONTROL was removed from bioptim in another PR. This is just so the tests pass (because for some reason it was not caught before)
___
*[`bioptim/models/biorbd/biorbd_model.py` line 34 at r2](https://reviewable.io/reviews/pyomeca/bioptim/804#-NjIK_Q_Bm4r2cDlRb9m:-NjIN-H64vWx-ZUSTImS:b-el33cg) ([raw file](https://github.com/pyomeca/bioptim/blob/305ec5046ec280d2b943c63448f2767e96a77188/bioptim/models/biorbd/biorbd_model.py#L34)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

<3
</blockquote></details>

Done. <3
___
*[`tests/shard5/test_global_stochastic_collocation.py` line 215 at r2](https://reviewable.io/reviews/pyomeca/bioptim/804#-NjILpJQ2GzMSgd5fbjd:-NjIN1Vn4NUfVZLHYpJB:b2nhjff) ([raw file](https://github.com/pyomeca/bioptim/blob/305ec5046ec280d2b943c63448f2767e96a77188/tests/shard5/test_global_stochastic_collocation.py#L215)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

Please revert if you agree with my comment above
</blockquote></details>

N/A

**Comment by pariterre** [comment]
> Looks perfect to me :)
Maybe we should just update pendulum.py to show how we recommend saving the solution (using the del sol.ocp).

I think some of the examples already do that, but more importantly, it looks messy when save and load is showcased... In order not to scare the beginning users, I think we should not add it in pendulum... 

This is just using the normal way to save and load data in Python anyway

**Comment by pariterre** [comment]
This is not already included

**Pull request closed without merging**
