### PR TITLE
[TO BE DELETED] min_max objective

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request? issue #591 and issue #492
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/672)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/672)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py` line 25 at r1](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVB--dbBGE7ZJlePZPM:-NVB--dbBGE7ZJlePZPN:b-2e5m9s) ([raw file](https://github.com/pyomeca/bioptim/blob/cfdf58f31564459e49719d5d97291b12c53532bf/bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py#L25)):*
> ```Python
> 
> 
> def custom_constraint_parameters(all_pn: PenaltyController) -> MX:
> ```

please call it controller
___
*[`bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py` line 72 at r1](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVB1kuN1Z5cTIusHHlY:-NVB1kuN1Z5cTIusHHlZ:b-ajywlg) ([raw file](https://github.com/pyomeca/bioptim/blob/cfdf58f31564459e49719d5d97291b12c53532bf/bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py#L72)):*
> ```Python
>     parameter_bounds = Bounds(0, tau_max, interpolation=InterpolationType.CONSTANT)
> 
>     parameter_objective_functions = Objective(minimize_parameters, weight=10000, quadratic=True, custom_type=ObjectiveFcn.Parameter)
> ```

Put this in a ParameterObjective/ParametersObjectiveList

**Comment by EveCharbie** [comment]
@pariterre I would like to have an extensive review of this PR with you on Thursday.
I think I found a bug in the old implementation of parameters, therefore I cannot count in the tests to make sure I am right.
Here is the problem

Current master version:
penalty.weighted_function[idx](x, u, np.array([0, 0, -9.81]), 1000, np.array([0, 0, -9.81]), 1)
Out[10]: DM([0, 0, 7.79512e+06])
penalty.weighted_function[idx](x, u, np.array([0, 0, 0]), 1000, np.array([0, 0, -9.81]), 1)
Out[11]: DM([0, 0, 96236.1])

My new version:
penalty.weighted_function[idx](x, u, np.array([0, 0, -9.81]), 1000, np.array([0, 0, -9.81]), 1)
Out[1]: DM([0, 0, 0])
penalty.weighted_function[idx](x, u, np.array([0, 0, 0]), 1000, np.array([0, 0, -9.81]), 1)
Out[2]: DM([0, 0, 96236.1])

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/672)* status: 0 of 26 files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py` line 25 at r1](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVB--dbBGE7ZJlePZPM:-NVkXHWc8E_G50iO1iaj:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/cfdf58f31564459e49719d5d97291b12c53532bf/bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py#L25)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

please call it controller
</blockquote></details>

Done.
___
*[`bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py` line 72 at r1](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVB1kuN1Z5cTIusHHlY:-NVkXLVa3sdKjQ1QSnA3:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/cfdf58f31564459e49719d5d97291b12c53532bf/bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py#L72)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Put this in a ParameterObjective/ParametersObjectiveList
</blockquote></details>

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 18 of 20 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/672)* status: all files reviewed, 15 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/examples/getting_started/custom_parameters.py` line 87 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkMBQk1dCop-L3Ztqq:-NVkMBQk1dCop-L3Ztqr:b-hk7n40) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/examples/getting_started/custom_parameters.py#L87)):*
> ```Python
>     elif key == "mass":
>         idx = 3
>     return controller.parameters.cx[idx]
> ```

controller.parameters["gravity_xzy"].cx
___
*[`bioptim/examples/getting_started/custom_parameters.py` line 195 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkM12h6rqiOav4q6CB:-NVkM12h6rqiOav4q6CC:b93x8nb) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/examples/getting_started/custom_parameters.py#L195)):*
> ```Python
>         )
>         parameter_objectives.add(
>             my_target_function,
> ```

my_target_function_gravity
___
*[`bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py` line 40 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkMvGv4ovB3jxg8E8a:-NVkMvGv4ovB3jxg8E8b:b-46ek4n) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py#L40)):*
> ```Python
> def custom_min_parameter(controller: PenaltyController) -> MX:
>     idx = controller.parameters.names.index("max_tau")  # this does not work if the parameters are not of size 1
>     return controller.parameters.cx[idx]
> ```

controller.parameters["max_tau"].cx
___
*[`bioptim/limits/penalty.py` line 971 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkOqlw4CdGMsE6EIzy:-NVkOqlw4CdGMsE6EIzz:bxo1hdr) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/limits/penalty.py#L971)):*
> ```Python
> 
>         @staticmethod
>         def minimize_parameter(penalty: PenaltyOption, controller: PenaltyController, key: str):
> ```

default "all"
___
*[`bioptim/limits/penalty.py` line 991 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkOk0Y1seYiMXz2e74:-NVkOk0Y1seYiMXz2e75:b-1f75b3) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/limits/penalty.py#L991)):*
> ```Python
> 
>             idx = controller.parameters.names.index(key)
>             return Function("minimize_parameter", [controller.parameters.cx], [controller.parameters.cx[idx]])(
> ```

controller.parameters[key].cx
___
*[`bioptim/limits/penalty_option.py` line 232 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkPBqH1dJfGrlT7RBr:-NVkPBqH1dJfGrlT7RBs:b2nhm5k) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/limits/penalty_option.py#L232)):*
> ```Python
> 
>         if self.name == "custom_min_parameter":
>             print("ici")
> ```

Là!
___
*[`bioptim/optimization/optimal_control_program.py` line 866 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkPrwrBb5cuNH5CpPe:-NVkPrwrBb5cuNH5CpPf:bt0iifo) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/optimal_control_program.py#L866)):*
> ```Python
> 
>         if isinstance(new_constraint, ParameterConstraint):
>             raise RuntimeError(
> ```

NotImplementedError
___
*[`bioptim/optimization/optimal_control_program.py` line 871 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkPo9x-H1qyn99WqjL:-NVkPo9x-H1qyn99WqjM:bt0iifo) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/optimal_control_program.py#L871)):*
> ```Python
>         elif isinstance(new_constraint, ParameterConstraintList):
>             if new_constraint.options != [[]]:
>                 raise RuntimeError(
> ```

NotImplementedError
___
*[`bioptim/optimization/optimal_control_program.py` line 888 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkQ3xb7MQtobMoAYZK:-NVkQ3xb7MQtobMoAYZL:b-amrbrx) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/optimal_control_program.py#L888)):*
> ```Python
> 
>         if isinstance(new_parameters, Parameter):
>             # self.__modify_penalty(new_parameters)
> ```

remove that method
___
*[`bioptim/optimization/optimal_control_program.py` line 1591 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkQIIs9Z9fAl9K0PEx:-NVkQIIs9Z9fAl9K0PEy:brskkfl) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/optimal_control_program.py#L1591)):*
> ```Python
>         self.program_changed = True
> 
>     def __modify_parameter_penalty(self, new_penalty: PenaltyOption | Parameter):
> ```

is this called?
___
*[`bioptim/optimization/optimization_vector.py` line 82 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkQPlE6BFq2S8jnsMN:-NVkQPlE6BFq2S8jnsMO:b4nz137) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/optimization_vector.py#L82)):*
> ```Python
>         self.n_phase_u = []
> 
>         # self.p_scaled: MX | SX | list = []
> ```

To be removed
___
*[`bioptim/optimization/optimization_vector.py` line 98 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkQRQt-yy_pztK0sQL:-NVkQRQt-yy_pztK0sQM:b4nz137) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/optimization_vector.py#L98)):*
> ```Python
>             self.n_phase_u.append(0)
> 
>         # self.p_scaled.append([])
> ```

To be removed
___
*[`bioptim/optimization/solution.py` line 1369 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkQfWE9s_t_7aoeWah:-NVkQfWE9s_t_7aoeWai:b-ixg8pl) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/solution.py#L1369)):*
> ```Python
>             nlp = self.ocp.nlp[idx_phase]
>             # for param in nlp.parameters:
>             #     if param.function:
> ```

We should keep that, add comment:
# This calls each of the function that modify the internal dynamic model based on the parameters
___
*[`tests/test_global_getting_started.py` line 718 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkROMR5ghHyw2NCWuE:-NVkROMR5ghHyw2NCWuF:bylak9s) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/tests/test_global_getting_started.py#L718)):*
> ```Python
>     f = np.array(sol.cost)
>     np.testing.assert_equal(f.shape, (1, 1))
>     np.testing.assert_almost_equal(f[0, 0], 1947.9530924905557, decimal=6)  # 78013.68624275683
> ```

To discuss
___
*[`tests/test_graph.py` line 218 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkRb_52gNx77vj0W_o:-NVkRb_52gNx77vj0W_p:b-1f75b3) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/tests/test_graph.py#L218)):*
> ```Python
>     elif key == "mass":
>         idx = 3
>     return controller.parameters.cx[idx]
> ```

controller.parameters[key].cx

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/672)* status: all files reviewed, 15 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/getting_started/custom_parameters.py` line 87 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkMBQk1dCop-L3Ztqq:-NVky0iA-HAikOJVwmkF:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/examples/getting_started/custom_parameters.py#L87)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

controller.parameters["gravity_xzy"].cx
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/custom_parameters.py` line 195 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkM12h6rqiOav4q6CB:-NVky5mHAZ8MB_f5IaNv:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/examples/getting_started/custom_parameters.py#L195)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

my_target_function_gravity
</blockquote></details>

Done.
___
*[`bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py` line 40 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkMvGv4ovB3jxg8E8a:-NVkyYie9Y3RR3M7FejI:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py#L40)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

controller.parameters["max_tau"].cx
</blockquote></details>

Done.

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/672)* status: all files reviewed, 15 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/limits/penalty.py` line 971 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkOqlw4CdGMsE6EIzy:-NVpAb2fEaR0QgfEQ9m6:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/limits/penalty.py#L971)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

default "all"
</blockquote></details>

Done.
___
*[`bioptim/limits/penalty.py` line 991 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkOk0Y1seYiMXz2e74:-NVpB86yDv2fVqqUPzfJ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/limits/penalty.py#L991)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

controller.parameters[key].cx
</blockquote></details>

Done.
___
*[`bioptim/limits/penalty_option.py` line 232 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkPBqH1dJfGrlT7RBr:-NVpBGuJ1YPncdMcz3DN:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/limits/penalty_option.py#L232)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Là!
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 866 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkPrwrBb5cuNH5CpPe:-NVpDtOe4tK8byOvyGys:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/optimal_control_program.py#L866)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

NotImplementedError
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 871 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkPo9x-H1qyn99WqjL:-NVpDtyp-1KdRq8QIch6:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/optimal_control_program.py#L871)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

NotImplementedError
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 888 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkQ3xb7MQtobMoAYZK:-NVpE6cjAijrig_26tOW:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/optimal_control_program.py#L888)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

remove that method
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 1591 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkQIIs9Z9fAl9K0PEx:-NVpEGt6B2uiyAUq6E4E:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/optimal_control_program.py#L1591)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

is this called?
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 82 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkQPlE6BFq2S8jnsMN:-NVpEOa68r4hLG4Bum1O:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/optimization_vector.py#L82)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be removed
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 98 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkQRQt-yy_pztK0sQL:-NVpEPK34N8l4X_jPMW_:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/optimization_vector.py#L98)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be removed
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution.py` line 1369 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkQfWE9s_t_7aoeWah:-NVpEepDBPOdcy5SNgYy:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/bioptim/optimization/solution.py#L1369)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

We should keep that, add comment:
# This calls each of the function that modify the internal dynamic model based on the parameters
</blockquote></details>

Done.
___
*[`tests/test_global_getting_started.py` line 718 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkROMR5ghHyw2NCWuE:-NVpEgLw8gZS4s6ExUaI:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/tests/test_global_getting_started.py#L718)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To discuss
</blockquote></details>

Done.
___
*[`tests/test_graph.py` line 218 at r3](https://reviewable.io/reviews/pyomeca/bioptim/672#-NVkRb_52gNx77vj0W_o:-NVpEqPdCVNE6JCoUmI1:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/dfcbf8ae39d6d930889132c9ac7c39af3feb0491/tests/test_graph.py#L218)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

controller.parameters[key].cx
</blockquote></details>

Done.

**Pull request closed without merging**
