### PR TITLE
[RTM] bug with states mapping  while using multimodel

### PR DESCRIPTION
**Pull request by lsechoir**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/647)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/647)* status: all files reviewed, 10 unresolved discussions (waiting on @lsechoir)

___
*[`bioptim/dynamics/configure_problem.py` line 978 at r2](https://reviewable.io/reviews/pyomeca/bioptim/647#-NTV-VcmBMSBwvZvsNZ_:-NTV-VcmBMSBwvZvsNZa:b-gho15h) ([raw file](https://github.com/pyomeca/bioptim/blob/6a4cdbcd280f59432fc8600b21f67bd8e0afc455/bioptim/dynamics/configure_problem.py#L978)):*
> ```Python
> 
>         if as_states:
>             # append nlp.variable_mappings['states'] ? @pariterre
> ```

Don't forget to remove



_Code quote:_
```Python
 append nlp.variable_mappings['states'] ? @pariterre
```
___
*[`bioptim/dynamics/dynamics_functions.py` line 667 at r2](https://reviewable.io/reviews/pyomeca/bioptim/647#-NTV1ROm-hbBSnUMo05r:-NTV1ROm-hbBSnUMo05s:b-56of68) ([raw file](https://github.com/pyomeca/bioptim/blob/6a4cdbcd280f59432fc8600b21f67bd8e0afc455/bioptim/dynamics/dynamics_functions.py#L667)):*
> ```Python
>         qddot_root_temporary = nlp.model.forward_dynamics_free_floating_base(q_temporary, qdot_temporary, qddot_joints_temporary)
> 
>         qddot_reordered = nlp.model.reorder_qddot_root_joints(qddot_root_temporary, qddot_joints_temporary)
> ```

Move this to BiorbdModel



_Code quote:_
```Python
        q_temporary = MX.sym('Q', nlp.model.nb_q)
        qdot_temporary = MX.sym('Qdot', nlp.model.nb_qdot)
        qddot_joints_temporary = MX.sym('Qddot_joints', nlp.model.nb_qddot - nlp.model.nb_root)
        qddot_root_temporary = nlp.model.forward_dynamics_free_floating_base(q_temporary, qdot_temporary, qddot_joints_temporary)

        qddot_reordered = nlp.model.reorder_qddot_root_joints(qddot_root_temporary, qddot_joints_temporary)
```
___
*[`bioptim/dynamics/integrator.py` line 83 at r2](https://reviewable.io/reviews/pyomeca/bioptim/647#-NTV0vZv70sRlPhkmADe:-NTV0vZv70sRlPhkmADf:bx3ijal) ([raw file](https://github.com/pyomeca/bioptim/blob/6a4cdbcd280f59432fc8600b21f67bd8e0afc455/bioptim/dynamics/integrator.py#L83)):*
> ```Python
>         self.h = self.step_time
>         self.function = None
>         self.states_mapping = ode_opt['states_mapping']
> ```

Revert "integrator.py"



_Code quote:_
```Python
     self.states_mapping = ode_opt['states_mapping']
```
___
*[`bioptim/dynamics/integrator.py` line 245 at r2](https://reviewable.io/reviews/pyomeca/bioptim/647#-NTV0r327LkNH4e5bptZ:-NTV0r327LkNH4e5bpt_:b-pi9dgi) ([raw file](https://github.com/pyomeca/bioptim/blob/6a4cdbcd280f59432fc8600b21f67bd8e0afc455/bioptim/dynamics/integrator.py#L245)):*
> ```Python
>         u = controls
>         x = self.cx(states.shape[0], self.n_step + 1)
>         #         x = self.cx(len(self.states_mapping.to_first.map_idx), self.n_step + 1)
> ```

remove that



_Code quote:_
```Python
    #         x = self.cx(len(self.states_mapping.to_first.map_idx), self.n_step + 1)
```
___
*[`bioptim/dynamics/integrator.py` line 402 at r2](https://reviewable.io/reviews/pyomeca/bioptim/647#-NTV0ncW6jlCO0WXEYy0:-NTV0ncW6jlCO0WXEYy1:b-l6hdjr) ([raw file](https://github.com/pyomeca/bioptim/blob/6a4cdbcd280f59432fc8600b21f67bd8e0afc455/bioptim/dynamics/integrator.py#L402)):*
> ```Python
>         # apply the states_mapping
>         x_prev_mapped = self.states_mapping.to_first.map(x_prev)
>         k1 = self.fun(x_prev, self.get_u(u, t), p)[:, self.idx] # Apply mapping'states_mapping' here ? @pariterre
> ```

revert



_Code quote:_
```Python
        # apply the states_mapping
        x_prev_mapped = self.states_mapping.to_first.map(x_prev)
        k1 = self.fun(x_prev, self.get_u(u, t), p)[:, self.idx] # Apply mapping'states_mapping' here ? @pariterre
```
___
*[`bioptim/dynamics/ode_solver.py` line 59 at r2](https://reviewable.io/reviews/pyomeca/bioptim/647#-NTV1-pZ79GbnKpFKHQh:-NTV1-pZ79GbnKpFKHQi:b1uedqw) ([raw file](https://github.com/pyomeca/bioptim/blob/6a4cdbcd280f59432fc8600b21f67bd8e0afc455/bioptim/dynamics/ode_solver.py#L59)):*
> ```Python
> 
>     @staticmethod
>     def prepare_dynamic_integrator(ocp, nlp, states_mapping):
> ```

Revert "ode_solver.py"



_Code quote:_
```Python
, states_mapping
```
___
*[`bioptim/interfaces/biorbd_model.py` line 276 at r2](https://reviewable.io/reviews/pyomeca/bioptim/647#-NTV2WatEO_pe0Da6X_C:-NTV2WatEO_pe0Da6X_D:b-s3iep2) ([raw file](https://github.com/pyomeca/bioptim/blob/6a4cdbcd280f59432fc8600b21f67bd8e0afc455/bioptim/interfaces/biorbd_model.py#L276)):*
> ```Python
>     #     for i in range(len(self.models)):
>     #         qddot[i] = qddot_joints[i]+qddot_rootself[i]
>     #     return qddot
> ```

Remove this if not needed



_Code quote:_
```Python
    # def multi_model_reorder_dynamics(self, qddot_joints, qddot_rootself):
    #     qddot = []
    #     for i in range(len(self.models)):
    #         qddot[i] = qddot_joints[i]+qddot_rootself[i]
    #     return qddot
```
___
*[`bioptim/limits/penalty.py` line 688 at r2](https://reviewable.io/reviews/pyomeca/bioptim/647#-NTV2_ox3EK6jgvd8csq:-NTV2_ox3EK6jgvd8csr:b22qu7y) ([raw file](https://github.com/pyomeca/bioptim/blob/6a4cdbcd280f59432fc8600b21f67bd8e0afc455/bioptim/limits/penalty.py#L688)):*
> ```Python
>             if nlp.ode_solver.is_direct_collocation:
>                 cx = horzcat(*([nlp.states.cx] + nlp.states.cx_intermediates_list))
>                 continuity -= nlp.dynamics[node_idx](x0=cx, p=u, params=nlp.parameters.cx)["xf"] # to mapp
> ```

Remove that



_Code quote:_
```Python
 # to mapp
```
___
*[`bioptim/limits/penalty.py` line 695 at r2](https://reviewable.io/reviews/pyomeca/bioptim/647#-NTV2bBl4iZYZqiBuLKP:-NTV2bBl4iZYZqiBuLKQ:b22qu7y) ([raw file](https://github.com/pyomeca/bioptim/blob/6a4cdbcd280f59432fc8600b21f67bd8e0afc455/bioptim/limits/penalty.py#L695)):*
> ```Python
> 
>             else:
>                 continuity -= nlp.dynamics[node_idx](x0=nlp.states.cx, p=u, params=nlp.parameters.cx)["xf"] # to mapp
> ```

Remove that



_Code quote:_
```Python
 # to mapp
```
___
*[`bioptim/optimization/optimal_control_program.py` line 514 at r2](https://reviewable.io/reviews/pyomeca/bioptim/647#-NTV2kmHEOllvuk_CfUa:-NTV2kmHEOllvuk_CfUb:blmtz06) ([raw file](https://github.com/pyomeca/bioptim/blob/6a4cdbcd280f59432fc8600b21f67bd8e0afc455/bioptim/optimization/optimal_control_program.py#L514)):*
> ```Python
>             self.nlp[i].initialize(self.cx)
>             ConfigureProblem.initialize(self, self.nlp[i])
>             self.nlp[i].ode_solver.prepare_dynamic_integrator(self, self.nlp[i], variable_mappings[0, 'q'])
> ```

change that for "i"



_Code quote:_
```Python
0
```

**Review by Ipuch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/647)* status: 1 of 10 files reviewed, 7 unresolved discussions (waiting on @lsechoir and @pariterre)

___
*[`bioptim/dynamics/integrator.py` line 249 at r7](https://reviewable.io/reviews/pyomeca/bioptim/647#-NUbv2N0BQbcwq0lONgt:-NUbv2N0BQbcwq0lONgu:btj3b6s) ([raw file](https://github.com/pyomeca/bioptim/blob/05c1cdb37ff230dce7506d49122c4aee1360eb01/bioptim/dynamics/integrator.py#L249)):*
> ```Python
>         for i in range(1, self.n_step + 1):
>             t_norm_init = (i - 1) / self.n_step  # normalized time
>             # send x full size
> ```

to remove
___
*[`bioptim/dynamics/integrator.py` line 608 at r7](https://reviewable.io/reviews/pyomeca/bioptim/647#-NUbv3vt07ET8ehl02x-:-NUbv3vt07ET8ehl02x0:btj3b6s) ([raw file](https://github.com/pyomeca/bioptim/blob/05c1cdb37ff230dce7506d49122c4aee1360eb01/bioptim/dynamics/integrator.py#L608)):*
> ```Python
> 
>             if self.defects_type == DefectType.EXPLICIT:
>                 # send full x
> ```

to remove
___
*[`bioptim/dynamics/integrator.py` line 685 at r7](https://reviewable.io/reviews/pyomeca/bioptim/647#-NUbv4_L1w65xYJGpVpp:-NUbv4_L1w65xYJGpVpq:btj3b6s) ([raw file](https://github.com/pyomeca/bioptim/blob/05c1cdb37ff230dce7506d49122c4aee1360eb01/bioptim/dynamics/integrator.py#L685)):*
> ```Python
> 
>         # Root-finding function, implicitly defines x_collocation_points as a function of x0 and p
>         # send full x
> ```

to remove
___
*[`bioptim/dynamics/ode_solver.py` line 70 at r7](https://reviewable.io/reviews/pyomeca/bioptim/647#-NUbv5x58lwgrM_1Mimz:-NUbv5x58lwgrM_1Min-:btj3b6s) ([raw file](https://github.com/pyomeca/bioptim/blob/05c1cdb37ff230dce7506d49122c4aee1360eb01/bioptim/dynamics/ode_solver.py#L70)):*
> ```Python
>             A reference to the current phase of the ocp
>         states_mapping: Mapping
>             The states mapping
> ```

to remove
___
*[`bioptim/dynamics/ode_solver.py` line 115 at r7](https://reviewable.io/reviews/pyomeca/bioptim/647#-NUbv6LlBJxvXgXqL9on:-NUbv6LlBJxvXgXqL9oo:btj3b6s) ([raw file](https://github.com/pyomeca/bioptim/blob/05c1cdb37ff230dce7506d49122c4aee1360eb01/bioptim/dynamics/ode_solver.py#L115)):*
> ```Python
>             A reference to the nlp
>         states_mapping:
>             The states mapping
> ```

to remove

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/647)* status: all files reviewed, 6 unresolved discussions (waiting on @lsechoir)

___
*[`bioptim/interfaces/biomodel.py` line 107 at r7](https://reviewable.io/reviews/pyomeca/bioptim/647#-NUbwDYtEPQVzU44Fgpw:-NUbwDYtEPQVzU44Fgpx:b-6mlwxl) ([raw file](https://github.com/pyomeca/bioptim/blob/05c1cdb37ff230dce7506d49122c4aee1360eb01/bioptim/interfaces/biomodel.py#L107)):*
> ```Python
>         """Get the muscle torque"""
> 
>     def forward_dynamics_free_floating_base(self) -> MX:
> ```

TODO for iPuch

**Review by Ipuch — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/647)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @lsechoir and @pariterre)

**Pull request merged**
