### PR TITLE
[RTR] SQP method interface

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/556)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/556)* status: all files reviewed, 6 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/interfaces/ipopt_interface.py` line 17 at r1](https://reviewable.io/reviews/pyomeca/bioptim/556#-NEquU2jD0ajDmXdC4oj:-NEquU2jD0ajDmXdC4ok:b-95wswn) ([raw file](https://github.com/pyomeca/bioptim/blob/6a95bdbe026462d66c0a885d6e223739bea7b43a/bioptim/interfaces/ipopt_interface.py#L17)):*
> ```Python
> 
> 
> class IpoptInterface(SolverInterface):
> ```

Copy-paste all this file and move common function if it makes sense
___
*[`bioptim/interfaces/solver_options.py` line 25 at r1](https://reviewable.io/reviews/pyomeca/bioptim/556#-NEqy3MbDiVy8_jTytsp:-NEqy3Mc331_GcCa1Ouj:b35nrll) ([raw file](https://github.com/pyomeca/bioptim/blob/6a95bdbe026462d66c0a885d6e223739bea7b43a/bioptim/interfaces/solver_options.py#L25)):*
> ```Python
>         # @abstractmethod
>         # def set_convergence_tolerance(self, tol: float):
>         #     """
> ```

do not comment, raise when called



_Code quote:_
```Python
        # @abstractmethod
        # def set_convergence_tolerance(self, tol: float):
        #     """
        #     This function set the convergence tolerance
        #
        #     Parameters
        #     ----------
        #     tol: float
        #         Global converge tolerance value
        #     """
```
___
*[`bioptim/interfaces/solver_options.py` line 35 at r1](https://reviewable.io/reviews/pyomeca/bioptim/556#-NEqy-WE0hbZgFT7ReGu:-NEqy-WF4djGV7sfnGnq:b35nrll) ([raw file](https://github.com/pyomeca/bioptim/blob/6a95bdbe026462d66c0a885d6e223739bea7b43a/bioptim/interfaces/solver_options.py#L35)):*
> ```Python
> 
>         # @abstractmethod
>         # def set_constraint_tolerance(self, tol: float):
> ```

do not comment, raise when called



_Code quote:_
```Python
        # @abstractmethod
        # def set_constraint_tolerance(self, tol: float):
        #     """
        #     This function set the constraint tolerance.
        #
        #     Parameters
        #     ----------
        #     tol: float
        #         Global constraint tolerance value
        #     """
```
___
*[`bioptim/interfaces/solver_options.py` line 68 at r1](https://reviewable.io/reviews/pyomeca/bioptim/556#-NEqy4Xa0TSlA1hdFX6A:-NEqy4Xa0TSlA1hdFX6B:b35nrll) ([raw file](https://github.com/pyomeca/bioptim/blob/6a95bdbe026462d66c0a885d6e223739bea7b43a/bioptim/interfaces/solver_options.py#L68)):*
> ```Python
> 
>         # @abstractmethod
>         # def set_print_level(self, num: int):
> ```

do not comment, raise when called



_Code quote:_
```Python
        # @abstractmethod
        # def set_print_level(self, num: int):
        #     """
        #     This function set Output verbosity level.
        #
        #     Parameters
        #     ----------
        #     num: int
        #         print_level
        #     """
```
___
*[`bioptim/interfaces/solver_options.py` line 387 at r1](https://reviewable.io/reviews/pyomeca/bioptim/556#-NEqy7Ii6xKAughm-O9q:-NEqy7Ii6xKAughm-O9r:b-75qbxz) ([raw file](https://github.com/pyomeca/bioptim/blob/6a95bdbe026462d66c0a885d6e223739bea7b43a/bioptim/interfaces/solver_options.py#L387)):*
> ```Python
>     @dataclass
>     class SQP_METHOD(Generic):
>         type: SolverType = SolverType.SQP_METHOD
> ```

type showld not be necessary
___
*[`bioptim/optimization/optimal_control_program.py` line 931 at r1](https://reviewable.io/reviews/pyomeca/bioptim/556#-NEqyQfj8lPeCROvPyQp:-NEqyQfj8lPeCROvPyQq:b5vhnos) ([raw file](https://github.com/pyomeca/bioptim/blob/6a95bdbe026462d66c0a885d6e223739bea7b43a/bioptim/optimization/optimal_control_program.py#L931)):*
> ```Python
> 
>             elif solver.type == SolverType.SQP_METHOD:
>                 from ..interfaces.ipopt_interface import IpoptInterface
> ```

SqpInterface

**Review by EveCharbie — COMMENTED** [review]
did not test it since I tried to reach convergence without success (tried many different number of nodes and even giving the  solution from IPOPT as initial guess).

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/556#-:-NErRJze5Vvp7eMQinoh:b-uawykj)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/interfaces/solver_options.py` line 25 at r1](https://reviewable.io/reviews/pyomeca/bioptim/556#-NEqy3MbDiVy8_jTytsp:-NErEJyg62ssaDfoZXRG:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/6a95bdbe026462d66c0a885d6e223739bea7b43a/bioptim/interfaces/solver_options.py#L25)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

do not comment, raise when called
</blockquote></details>

Done.
___
*[`bioptim/interfaces/solver_options.py` line 35 at r1](https://reviewable.io/reviews/pyomeca/bioptim/556#-NEqy-WE0hbZgFT7ReGu:-NErEKxk28hwDI8ZLDl4:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/6a95bdbe026462d66c0a885d6e223739bea7b43a/bioptim/interfaces/solver_options.py#L35)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

do not comment, raise when called
</blockquote></details>

Done.
___
*[`bioptim/interfaces/solver_options.py` line 68 at r1](https://reviewable.io/reviews/pyomeca/bioptim/556#-NEqy4Xa0TSlA1hdFX6A:-NErELbK129d8o1m9V1p:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/6a95bdbe026462d66c0a885d6e223739bea7b43a/bioptim/interfaces/solver_options.py#L68)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

do not comment, raise when called
</blockquote></details>

Done.
___
*[`bioptim/interfaces/solver_options.py` line 387 at r1](https://reviewable.io/reviews/pyomeca/bioptim/556#-NEqy7Ii6xKAughm-O9q:-NErJFFZBek1xNfqfy4B:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/6a95bdbe026462d66c0a885d6e223739bea7b43a/bioptim/interfaces/solver_options.py#L387)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

type showld not be necessary
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 931 at r1](https://reviewable.io/reviews/pyomeca/bioptim/556#-NEqyQfj8lPeCROvPyQp:-NErKHzH4KIHLuWZZS7c:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/6a95bdbe026462d66c0a885d6e223739bea7b43a/bioptim/optimization/optimal_control_program.py#L931)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

SqpInterface
</blockquote></details>

Done.

**Comment by pariterre** [comment]
@EveCharbie  hum.. okay.. if an example as simple as the pendulum can't converge, I must admit I am questionning the usefulness of the SQP method haha

**Comment by EveCharbie** [comment]
> @EveCharbie hum.. okay.. if an example as simple as the pendulum can't converge, I must admit I am questionning the usefulness of the SQP method haha

I totally agree, but I had to implement it to test. So now that it is implemented, we have to decide if we keep it. Form aceglia's experience with QP solver, we would have to fine-tune extensively the parameters of the solver in order to reach convergence, but it might be relevant to proceed this way in some specific cases.

**Comment by pariterre** [comment]
@EveCharbie 
Ok, anyway it makes sense to keep it, and I honestly don't really mind if the test converges or not, as long as it does this consistently (as the goal is to detect if the behavior changes). I feel sorry though that the example itself that we provide doesn't converge.. We can keep this for the future anyway!

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/556)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/interfaces/ipopt_interface.py` line 17 at r1](https://reviewable.io/reviews/pyomeca/bioptim/556#-NEquU2jD0ajDmXdC4oj:-NFG9mn04dsfeChuxx2y:b7leh57) ([raw file](https://github.com/pyomeca/bioptim/blob/6a95bdbe026462d66c0a885d6e223739bea7b43a/bioptim/interfaces/ipopt_interface.py#L17)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Copy-paste all this file and move common function if it makes sense
</blockquote></details>

Not sure I did it right but ok.

**Review by pariterre — APPROVED** [review]
@evecharbie RTM?
:lgtm:

> Reviewed 3 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/556#-:-NFJb33_E6wKUGlzsPlc:b-h4fg0r)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Comment by EveCharbie** [comment]
Yes RTM :)

**Pull request merged**
