### PR TITLE
[RTM if tests pass] implicit formulation of the SOCP

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/721)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 21 of 60 files at r1, 54 of 54 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/721)* status: all files reviewed, 1 unresolved discussion (waiting on @EveCharbie)

___
*[`OCP_equation.png` line 0 at r1](https://reviewable.io/reviews/pyomeca/bioptim/721#-N_e4exd-e1UoM790H0n:-N_e4exd-e1UoM790H0o:b-5920qm) ([raw file](https://github.com/pyomeca/bioptim/blob/36514422106f4fe39224c74b6f387498168c802c/OCP_equation.png#L0)):*
Please revert this file (ideally not from deleting it, but from reinserting commits

**Review by pariterre — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/721#-:-N_ifmSDEpSAnBnO1h9K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/721)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

___
*[`OCP_equation.png` line  at r1](https://reviewable.io/reviews/pyomeca/bioptim/721#-N_e4exd-e1UoM790H0n:-N_iyA5x5f19E1_fXiVf:b-v5z0wq) ([raw file](https://github.com/pyomeca/bioptim/blob/36514422106f4fe39224c74b6f387498168c802c/OCP_equation.png#L)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please revert this file (ideally not from deleting it, but from reinserting commits
</blockquote></details>

Cannot, was accepted in the last PR :(

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/721#-:-N_nHm_aE3z8NsF_H54B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
