### PR TITLE
[RTM] Pull master in crazydynamics

### PR DESCRIPTION
**Pull request by Ipuch**
- blacked
- all tests works
- implicit muscle driven handled with rigidbody dynamics enum

---
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/490)

### CODE REVIEW

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/490)* status: all files reviewed, 10 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 400 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x6BGm3YU-eGOhj02V:-N6xKwpl9Q2PJ5Hxafsu:bss4a2b) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/dynamics/configure_problem.py#L400)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is it RigidBodyDynamics.ODE or (EXPLICIT, IMPLICIT, SEMI_EXPLICIT)?  There is a mismatch with the parameter of the function
</blockquote></details>

Removed.
___
*[`bioptim/dynamics/configure_problem.py` line 410 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x6VIr8AfXf-0WGBRb:-N6xNZEs2YQLeYMENL7c:bfn6eir) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/dynamics/configure_problem.py#L410)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Should not this be a `if not ... ` and put what is allowed in the if. So we are making sure that if someone ever add a new dynamics this dynamics won't automatically be accepted (since it won't fail here)
</blockquote></details>

Not sure what you meant.
___
*[`bioptim/dynamics/dynamics_functions.py` line 407 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x6vIkDCUoyNq_oTJy:-N6xM0cr7r5h7yoZAbIw:b-hfpv0l) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/dynamics/dynamics_functions.py#L407)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please make sure the `()` are legit... actually I see no reason (apart from telling what is allowed to have anything explained in parenthesis here
</blockquote></details>

removed
___
*[`bioptim/examples/muscle_driven_ocp/muscle_activations_tracker.py` line 102 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x7IjQ4euaOznbRT2t:-N6xMQHx7T5gjgvWyN9-:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/examples/muscle_driven_ocp/muscle_activations_tracker.py#L102)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

please add the hints (something=something) so we understand the `False` refers to what
</blockquote></details>

Done
___
*[`bioptim/examples/muscle_driven_ocp/muscle_excitations_tracker.py` line 109 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x7UZJ8MwfAhd1F0Qd:-N6xMYZQA7Bv3ZNl9QUB:b-xkvm6q) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/examples/muscle_driven_ocp/muscle_excitations_tracker.py#L109)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Isn't it by default? If not, it should be
</blockquote></details>

it was not now done.
___
*[`bioptim/interfaces/acados_interface.py` line 664 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x7_ayEbNp9nubFrb1:-N6xMvA_2m5aHIvoWibh:bcgd09e) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/interfaces/acados_interface.py#L664)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please make sure to commit these kind of improvements in a separate and very fast to review/accept PR. The longer these lies in a PR, the more chances it creates conflict with other PR, especially in files that don't matter to you
</blockquote></details>

I'm not sure where it comes from. It's already pushed on the master.
I just merged the master on my branch to get updated.
___
*[`bioptim/interfaces/solver_options.py` line 370 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x86hRBxXvgIMfFuot:-N6xNDo75Wj-i9_Q1Yby:b-6zil83) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/interfaces/solver_options.py#L370)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This seems highly dangerous! Why would you only set an option if it was not already there and ignore the set otherwise? Also, what if this new key does not exist in Ipopt, we offer no waranty here... If you need this for some sort of hacking behind the bioptim wall, please be very specific in the title of the function (`set_option_unsafe` or something like that)
</blockquote></details>

Same, this comes from another PR.
___
*[`bioptim/interfaces/solver_options.py` line 464 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x8qE58DICSuf71l2b:-N6xNMJW2ZJOBqVjQU-Q:bmvy9a7) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/interfaces/solver_options.py#L464)):*
> Same, this comes from another PR.
___
*[`bioptim/interfaces/solver_options.py` line 570 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x93ZWAqfZxtLpewPm:-N6xNOkK7ufOkJS6ELAV:b-6zil83) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/interfaces/solver_options.py#L570)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I disagree with this. I understand why you made that, but what if someone change the order in the future. All the setter bellow can be called individually. There is no reason to force the user to know what order we decided (emphasised by the fact that there is no documentation on the method, which is normal because of the the fact it is an overloaded method if I recall well). Moreover, changing the signature of an overloaded method is bad practise (I did not open your PR in an editor, but this is probably overlighted saying exactly this). Please remove
</blockquote></details>

Same, this comes from another PR.
___
*[`bioptim/interfaces/solver_options.py` line 601 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6xA3vc8G9zX7EDqhU8:-N6xNRCBDeaKU4XjF2K_:b-rh43ft) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/interfaces/solver_options.py#L601)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please change this in the base class too
</blockquote></details>

Same, this comes from another PR. I think a new PR, should be open on the master to fix all theses related issues.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/490)* status: all files reviewed, 7 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 410 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x6VIr8AfXf-0WGBRb:-N6y4x6o5IBUKwXprXK2:b-10tn4r) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/dynamics/configure_problem.py#L410)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Not sure what you meant.
</blockquote></details>

We discussed verbally
___
*[`bioptim/dynamics/dynamics_functions.py` line 144 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6y53bnEXhjMFkcLK-J:-N6y53bnEXhjMFkcLK-K:blnf4wz) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/dynamics/dynamics_functions.py#L144)):*
> ```Python
>         defects = None
>         # todo: contacts and fatigue to be handled with implicit dynamics
>         if not with_contact and fatigue is None:
> ```

Is this intended?

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/490)* status: all files reviewed, 7 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 410 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x6VIr8AfXf-0WGBRb:-N6yL4Vu4lbHuGy8cmwA:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/dynamics/configure_problem.py#L410)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

We discussed verbally
</blockquote></details>

done
___
*[`bioptim/dynamics/dynamics_functions.py` line 144 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6y53bnEXhjMFkcLK-J:-N6yL1KA6ohhaXYWaOTV:b-qu6boy) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/dynamics/dynamics_functions.py#L144)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is this intended?
</blockquote></details>

no. restored
___
*[`bioptim/interfaces/solver_options.py` line 370 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x86hRBxXvgIMfFuot:-N6y9IWY9mmVGeYLR9x2:b-7zv7pn) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/interfaces/solver_options.py#L370)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Same, this comes from another PR.
</blockquote></details>

 in #493 
___
*[`bioptim/interfaces/solver_options.py` line 464 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x8qE58DICSuf71l2b:-N6y9HoV0vXbsaEd2a4M:b-7zv7pn) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/interfaces/solver_options.py#L464)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

> Same, this comes from another PR.
</blockquote></details>

 in #493 
___
*[`bioptim/interfaces/solver_options.py` line 570 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6x93ZWAqfZxtLpewPm:-N6y9GYu4iJd5L7CbW0C:b-ysjh4l) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/interfaces/solver_options.py#L570)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Same, this comes from another PR.
</blockquote></details>

 in #493  
___
*[`bioptim/interfaces/solver_options.py` line 601 at r1](https://reviewable.io/reviews/pyomeca/bioptim/490#-N6xA3vc8G9zX7EDqhU8:-N6y993k1hebj22IkXVF:bjya75g) ([raw file](https://github.com/pyomeca/bioptim/blob/da8cd71db6f3071412f9306bd475dc73c06ed24f/bioptim/interfaces/solver_options.py#L601)):*
> Please change this in the base class too
 in #493

**Comment by Ipuch** [comment]
RTM ?

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/490)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`bioptim/dynamics/configure_problem.py` line 407 at r3](https://reviewable.io/reviews/pyomeca/bioptim/490#-N7MENLc4-lhXBhwtwQo:-N7MENLc4-lhXBhwtwQp:bs5tph9) ([raw file](https://github.com/pyomeca/bioptim/blob/02bcd8213505f9f8fee035e35bd3d093ddcb22e3/bioptim/dynamics/configure_problem.py#L407)):*
> ```Python
> 
>         if (
>                 not rigidbody_dynamics == RigidBodyDynamics.DAE_INVERSE_DYNAMICS
> ```

this works but is a bit unusal. We usually use `!=` instead of `not`ing the ==
Could you change it?



_Code quote:_
```Python
not rigidbody_dynamics == RigidBodyDynamics.DAE_INVERSE_DYNAMICS
```

**Comment by Ipuch** [comment]
Tests should work fine now

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/490#-:-N85Ebo-5Ra1wEFW5dKg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Comment by Ipuch** [comment]
@pariterre mergeable?

**Pull request merged**
