### PR TITLE
[RTM_special] Update test and example according biorbd 1.9.5

### PR DESCRIPTION
**Pull request by aceglia**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/551)

### CODE REVIEW

**Comment by aceglia** [comment]
Acados build on Appveyor is broken since the PR #544 no idea why... @pariterre

**Review by pariterre — CHANGES_REQUESTED** [review]
Almost there :)

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/551#-:-NEa11tqCaT6Dv4ac-vK:b-iufuso)* status: all files reviewed, 3 unresolved discussions (waiting on @aceglia)

___
*[`bioptim/examples/muscle_driven_ocp/static_arm.py` line 29 at r1](https://reviewable.io/reviews/pyomeca/bioptim/551#-NEa0JT4BxR2aZppQYqM:-NEa0JT4BxR2aZppQYqN:bo3jvdr) ([raw file](https://github.com/pyomeca/bioptim/blob/aa744fe2a7349a3bbce0e824cd1566373908c8a1/bioptim/examples/muscle_driven_ocp/static_arm.py#L29)):*
> ```Python
>     n_shooting: int,
>     weight: float,
>     ode_solver: OdeSolver = OdeSolver.IRK(),
> ```

Is IRK necessary?
___
*[`external/acados_install_linux.sh` line 102 at r1](https://reviewable.io/reviews/pyomeca/bioptim/551#-NEa0bVjAthXPTOwiwN8:-NEa0bVjAthXPTOwiwN9:bf6fdtm) ([raw file](https://github.com/pyomeca/bioptim/blob/aa744fe2a7349a3bbce0e824cd1566373908c8a1/external/acados_install_linux.sh#L102)):*
> ```Shell
> #"CONDA_PREFIX" = $CONDA_PREFIX
> TO_REPLACE_ACADOS_SOURCE="    ACADOS_PATH = os.environ.get('ACADOS_SOURCE_DIR')"
> REPLACE_ACADOS_SOURCE_BY="    acados_template_path = os.path.dirname(os.path.abspath(__file__))\n    acados_path = os.path.join(acados_template_path, '..', '..', '..')\n    ACADOS_PATH = os.path.realpath(acados_path)[:-4]\n"
> ```

That's seem weird... Can you explain?



_Code quote:_
```Shell
REPLACE_ACADOS_SOURCE_BY="    acados_template_path = os.path.dirname(os.path.abspath(__file__))\n    acados_path = os.path.join(acados_template_path, '..', '..', '..')\n    ACADOS_PATH = os.path.realpath(acados_path)[:-4]\n"
```
___
*[`external/acados_install_mac.sh` line 97 at r1](https://reviewable.io/reviews/pyomeca/bioptim/551#-NEa0wuBErYJnRXZPocD:-NEa0wuBErYJnRXZPocE:bb73xfv) ([raw file](https://github.com/pyomeca/bioptim/blob/aa744fe2a7349a3bbce0e824cd1566373908c8a1/external/acados_install_mac.sh#L97)):*
> ```Shell
> # Change acados path
> TO_REPLACE_ACADOS_SOURCE="    ACADOS_PATH = os.environ.get('ACADOS_SOURCE_DIR')"
> REPLACE_ACADOS_SOURCE_BY="    acados_template_path = os.path.dirname(os.path.abspath(__file__))\n    acados_path = os.path.join(acados_template_path, '..', '..', '..')\n    ACADOS_PATH = os.path.realpath(acados_path)[:-4]\n"
> ```

Same



_Code quote:_
```Shell
REPLACE_ACADOS_SOURCE_BY="    acados_template_path = os.path.dirname(os.path.abspath(__file__))\n    acados_path = os.path.join(acados_template_path, '..', '..', '..')\n    ACADOS_PATH = os.path.realpath(acados_path)[:-4]\n"
```

**Review by aceglia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/551)* status: 9 of 12 files reviewed, 3 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/muscle_driven_ocp/static_arm.py` line 29 at r1](https://reviewable.io/reviews/pyomeca/bioptim/551#-NEa0JT4BxR2aZppQYqM:-NEb5awX0tnE4EfuKJLG:b-4yroef) ([raw file](https://github.com/pyomeca/bioptim/blob/aa744fe2a7349a3bbce0e824cd1566373908c8a1/bioptim/examples/muscle_driven_ocp/static_arm.py#L29)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is IRK necessary?
</blockquote></details>

Not at all, came back to collocation
___
*[`external/acados_install_linux.sh` line 102 at r1](https://reviewable.io/reviews/pyomeca/bioptim/551#-NEa0bVjAthXPTOwiwN8:-NEb5i6F12_NUZBUXTPE:bunnjgf) ([raw file](https://github.com/pyomeca/bioptim/blob/aa744fe2a7349a3bbce0e824cd1566373908c8a1/external/acados_install_linux.sh#L102)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

That's seem weird... Can you explain?
</blockquote></details>

I try a method used in an other place in the acados template to see if it will help for the appveyor build but seems to have no impact. 
___
*[`external/acados_install_mac.sh` line 97 at r1](https://reviewable.io/reviews/pyomeca/bioptim/551#-NEa0wuBErYJnRXZPocD:-NEb6-7zAQ9iSbU-ZnAN:bunnjgf) ([raw file](https://github.com/pyomeca/bioptim/blob/aa744fe2a7349a3bbce0e824cd1566373908c8a1/external/acados_install_mac.sh#L97)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Same
</blockquote></details>

I try a method used in an other place in the acados template to see if it will help for the appveyor build but seems to have no impact.

**Comment by aceglia** [comment]
I included the PR #559 if you want to merge only one time. But otherwise its RTR @pariterre

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/551)* status: all files reviewed, 2 unresolved discussions (waiting on @aceglia)

___
*[`external/acados_install_linux.sh` line 102 at r1](https://reviewable.io/reviews/pyomeca/bioptim/551#-NEa0bVjAthXPTOwiwN8:-NFP5E1B11luznC8Yhfm:bbqfk2m) ([raw file](https://github.com/pyomeca/bioptim/blob/aa744fe2a7349a3bbce0e824cd1566373908c8a1/external/acados_install_linux.sh#L102)):*
<details><summary><i>Previously, aceglia wrote…</i></summary><blockquote>

I try a method used in an other place in the acados template to see if it will help for the appveyor build but seems to have no impact. 
</blockquote></details>

Should we keep this? It seems much neater
___
*[`external/acados_install_mac.sh` line 97 at r1](https://reviewable.io/reviews/pyomeca/bioptim/551#-NEa0wuBErYJnRXZPocD:-NFP5i7_DsAtU3_HGALB:bbqfk2m) ([raw file](https://github.com/pyomeca/bioptim/blob/aa744fe2a7349a3bbce0e824cd1566373908c8a1/external/acados_install_mac.sh#L97)):*
<details><summary><i>Previously, aceglia wrote…</i></summary><blockquote>

I try a method used in an other place in the acados template to see if it will help for the appveyor build but seems to have no impact. 
</blockquote></details>

Should we keep this? It seems much neater

**Review by pariterre — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/551)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aceglia)

**Comment by pariterre** [comment]
This PR is effectively arlready merged

**Pull request closed without merging**
