### PR TITLE
[RTM] Continuity objective take2

### PR DESCRIPTION
**Pull request by Sciancisco**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

This is a second take on PR #480 .
Will write test once example is set in stone.

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/516)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/516)* status: all files reviewed, 12 unresolved discussions (waiting on @Sciancisco)

___
*[`bioptim/examples/getting_started/example_as_objective.py` line 3 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFP1YDX_ZelZdeoeh:-N9DFP1YDX_ZelZdeoei:b-y23040) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L3)):*
> ```Python
> """
> TODO: General cleaning
> A very simple yet meaningful optimal control program consisting in a pendulum starting downward and ending upward
> ```

It does look like a "Very simple" example to me!



_Code quote:_
```Python
A very simple yet meaningful
```
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 87 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFTg54YRNl2gQZAcV:-N9DFTg54YRNl2gQZAcW:bu45so3) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L87)):*
> ```Python
> 
>     # Path constraint
>     Ytrans = 0
> ```

please use camel_case
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 89 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFVZZ0lr_l5uhgc5Q:-N9DFVZZ0lr_l5uhgc5R:b-huuyx3) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L89)):*
> ```Python
>     Ytrans = 0
>     Xrot = 1
>     START = 0
> ```

Do not use capitalized variables
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 180 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFgd-9Pwb2BzqTZn1:-N9DFgd-9Pwb2BzqTZn2:b-apdmf1) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L180)):*
> ```Python
> 
>     # Path constraint
>     Ytrans = 0
> ```

Please use camel_case



_Code quote:_
```Python
    # Path constraint
    Ytrans = 0
    Xrot = 1
    START = 0
    END = -1
```
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 187 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFneL0sIfmxzAyq9l:-N9DFneL0sIfmxzAyq9m:bb7paeo) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L187)):*
> ```Python
>     x_bounds = QAndQDotBounds(biorbd_model)
>     x_bounds[:, START] = 0
>     x_bounds.min[Ytrans, END] = -0.01  # Give a little slack on the end position, otherwise to difficult
> ```

too?



_Code quote:_
```Python
to
```
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 204 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFuYo4kyRGrAqBEOR:-N9DFuYo4kyRGrAqBEOS:b46v4g2) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L204)):*
> ```Python
> 
>     constraints = ConstraintList()
>     # max_bound is practically at infinity
> ```

I think np.inf actually works 



_Code quote:_
```Python
 # max_bound is practically at infinity
```
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 246 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DG2Rg0foiZsRQXiXi:-N9DG2Rg0foiZsRQXiXj:b-1uwjf8) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L246)):*
> ```Python
>     solver_first.set_maximum_iterations(500)
> 
>     # Custom plots
> ```

Please make sure all these graphs actually make sense



_Code quote:_
```Python
    # Custom plots
    ocp_first.add_plot_penalty(CostType.ALL)
```
___
*[`bioptim/examples/getting_started/models/pendulum_maze.bioMod` line 1 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFDUp6NEsaSmdK5Ky:-N9DFDUp6NEsaSmdK5Kz:b-or4djd) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/models/pendulum_maze.bioMod#L1)):*
> ```
> version 4
> ```

I do not understand the name of the pendulum?
___
*[`bioptim/examples/getting_started/models/pendulum_maze.bioMod` line 56 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DGGQj-2GAZqvCjqaS:-N9DGGQj-2GAZqvCjqaT:b-cws56t) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/models/pendulum_maze.bioMod#L56)):*
> ```
>     mesh 0 $y1 $z1+$r1
>     mesh 0 $y1+(-$r1) $z1
>     mesh 0 $y1 $z1+(-$r1)  // TODO: $z-$r causes a segfault in biorbd
> ```

Good luck with that hahaha



_Code quote:_
```
// TODO: $z-$r causes a segfault in biorbd
```
___
*[`bioptim/examples/getting_started/models/pendulum_maze.bioMod` line 90 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DGdT6AwwG0heoaNuD:-N9DGdT6AwwG0heoaNuE:bqxjtau) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/models/pendulum_maze.bioMod#L90)):*
> ```
>     mesh 0 $y5 $z5+(-$r5)
>     mesh 0 $y5+$r5 $z5
> endsegment
> ```

Add a line carriage at the end of the file
___
*[`bioptim/limits/phase_transition.py` line 71 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DH2c31Eb20SkBkkYy:-N9DH2c31Eb20SkBkkYz:b-ijhy5w) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/limits/phase_transition.py#L71)):*
> ```Python
>             min_bound=min_bound,
>             max_bound=max_bound,
>             weight=weight if weight else 0,
> ```

I think it works, but recently PEP8 asked to be explicit when testing for a None so 
`weight if weight is not None else 0`



_Code quote:_
```Python
if weight
```
___
*[`bioptim/misc/enums.py` line 121 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DHI1TD8Nlk1CmS4gi:-N9DHI1UE37JA0_9-Mar:b-sqi5kj) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/misc/enums.py#L121)):*
> ```Python
> 
> 
> class PenaltyType(Enum):  # it's more of a "Category" than "Type"
> ```

I agree, I could not find a good word, it would have been a good idea. But now it is a bit too late...



_Code quote:_
```Python
# it's more of a "Category" than "Type"
```

**Review by Sciancisco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/516)* status: 0 of 11 files reviewed, 12 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/getting_started/example_as_objective.py` line 3 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFP1YDX_ZelZdeoeh:-NAA8dJEAFZs3keeJMEA:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L3)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

It does look like a "Very simple" example to me!
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 87 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFTg54YRNl2gQZAcV:-NAAOWdG4Dvb_RPpV-lB:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L87)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

please use camel_case
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 89 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFVZZ0lr_l5uhgc5Q:-NAAOX8z56FKs8v9MTYC:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L89)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Do not use capitalized variables
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 180 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFgd-9Pwb2BzqTZn1:-NAAOZ7pE7-_PZx5lgHE:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L180)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please use camel_case
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 187 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFneL0sIfmxzAyq9l:-NAA8m-31LzMbM0V6y03:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L187)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

too?
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 204 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFuYo4kyRGrAqBEOR:-NAA8oUh8lNDplfJmglD:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L204)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I think np.inf actually works 
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 246 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DG2Rg0foiZsRQXiXi:-NAAP-Vt0rkUrIJrGZZu:b499v3) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L246)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please make sure all these graphs actually make sense
</blockquote></details>

Meaning? Continuity does change from graph CONSTRAINTS to graph OBJECTIVES.
___
*[`bioptim/examples/getting_started/models/pendulum_maze.bioMod` line 1 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DFDUp6NEsaSmdK5Ky:-NAA8v6SCsgmqvZaalhR:b-jlmmue) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/models/pendulum_maze.bioMod#L1)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I do not understand the name of the pendulum?
</blockquote></details>

Originally it was supposed to be a big maze in which the pendulum would have had to navigate. Now it is a smaller "maze".
___
*[`bioptim/examples/getting_started/models/pendulum_maze.bioMod` line 56 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DGGQj-2GAZqvCjqaS:-NAA9K2d9A5upBJm9ooN:b-b9dqef) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/models/pendulum_maze.bioMod#L56)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Good luck with that hahaha
</blockquote></details>

I'll leave it there.
___
*[`bioptim/examples/getting_started/models/pendulum_maze.bioMod` line 90 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DGdT6AwwG0heoaNuD:-NAAOgep0WsFnTJ8Hi5Y:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/models/pendulum_maze.bioMod#L90)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Add a line carriage at the end of the file
</blockquote></details>

Done.
___
*[`bioptim/limits/phase_transition.py` line 71 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DH2c31Eb20SkBkkYy:-NAAOtpXBjfJDa6Z4Bqz:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/limits/phase_transition.py#L71)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I think it works, but recently PEP8 asked to be explicit when testing for a None so 
`weight if weight is not None else 0`
</blockquote></details>

Done.
___
*[`bioptim/misc/enums.py` line 121 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DHI1TD8Nlk1CmS4gi:-NAA9V964rD_0qT5AZLL:b651zy) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/misc/enums.py#L121)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I agree, I could not find a good word, it would have been a good idea. But now it is a bit too late...
</blockquote></details>

Should I remove or leave for the future devs to understand better?

**Review by pariterre — CHANGES_REQUESTED** [review]
Please make sure the tests passe and we are good to go ;)

> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/516#-:-NAKD5bp2vtfUwnvYGan:bv8pbw3)* status: all files reviewed, 7 unresolved discussions (waiting on @Sciancisco)

___
*[`bioptim/interfaces/ipopt_interface.py` line 343 at r3](https://reviewable.io/reviews/pyomeca/bioptim/516#-NAKCf1tASM_cMycuErF:-NAKCf1u5QsP2USAJBc_:b3vl9mm) ([raw file](https://github.com/pyomeca/bioptim/blob/716ed8eacf6949547e0f74fcbbcab7a789de31bc/bioptim/interfaces/ipopt_interface.py#L343)):*
> ```Python
>                     else:
>                         x, u = get_x_and_u_at_idx(penalty, idx)
>                     # for the future bioptim adventurer: here lies the reason that a constraint has weight = 0.
> ```

`has weight = 0` for what?
___
*[`bioptim/misc/enums.py` line 121 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DHI1TD8Nlk1CmS4gi:-NAKCyZk2rYFWY3R1Ev0:b-t9px1c) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/misc/enums.py#L121)):*
<details><summary><i>Previously, Sciancisco wrote…</i></summary><blockquote>

Should I remove or leave for the future devs to understand better?
</blockquote></details>

Yah, let's leave it there
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 246 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DG2Rg0foiZsRQXiXi:-NAKAwTt-qAn2q4NCtsT:b-erxvkh) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L246)):*
<details><summary><i>Previously, Sciancisco wrote…</i></summary><blockquote>

Meaning? Continuity does change from graph CONSTRAINTS to graph OBJECTIVES.
</blockquote></details>

I mean, this file should be a minimal example. Does it makes sense to actually show all these graphs. Maybe (probably) they are, I do not run the files while reviewing. It just seems a bit complicated as a minimal example, so I wanted to be sure
___
*[`bioptim/examples/getting_started/example_continuity_as_objective.py` line 6 at r3](https://reviewable.io/reviews/pyomeca/bioptim/516#-NAKAGtJ1a3IgJZFCpoU:-NAKAGtJ1a3IgJZFCpoV:undefined) ([raw file](https://github.com/pyomeca/bioptim/blob/716ed8eacf6949547e0f74fcbbcab7a789de31bc/bioptim/examples/getting_started/example_continuity_as_objective.py#L6)):*
> ```Python
> 
> There is a catch however: there are regions in which the weight of the pendulum cannot go.
> The problem is solved in two passes. In the first pass, continuity is an objective rather then a constraint.
> ```





_Suggestion:_
```Python
rather than
```
___
*[`bioptim/examples/getting_started/example_continuity_as_objective.py` line 25 at r3](https://reviewable.io/reviews/pyomeca/bioptim/516#-NAKAOuX-5GDd8i_H8MB:-NAKAOuX-5GDd8i_H8MC:b-8pqu9w) ([raw file](https://github.com/pyomeca/bioptim/blob/716ed8eacf6949547e0f74fcbbcab7a789de31bc/bioptim/examples/getting_started/example_continuity_as_objective.py#L25)):*
> ```Python
>     InterpolationType,
>     QAndQDotBounds,
>     NoisedInitialGuess,
> ```

Is there a reason to use `NoisedInitialGuess`? It seems that it will confuse the users that are solely interested in the continuity as objective?



_Code quote:_
```Python
NoisedInitialGuess,
```
___
*[`bioptim/examples/getting_started/example_continuity_as_objective.py` line 131 at r3](https://reviewable.io/reviews/pyomeca/bioptim/516#-NAKBviq6PPjjixASG3D:-NAKBviq6PPjjixASG3E:b7j66dp) ([raw file](https://github.com/pyomeca/bioptim/blob/716ed8eacf6949547e0f74fcbbcab7a789de31bc/bioptim/examples/getting_started/example_continuity_as_objective.py#L131)):*
> ```Python
>         n_threads=n_threads,
>         # change the weight to observe the impact on the continuity of the solution
>         # or comment to see how the constrained program would fare
> ```

I think the example should define a variable at the top of the function, because as a user when I look at the example file, I expect the relevant part to be highlighted. Right now, the most important bit feels actually burry in a highly complex OCP (I understand the scientific relevance of the example, but not so much as a minimal example...)



_Code quote:_
```Python
        # change the weight to observe the impact on the continuity of the solution
        # or comment to see how the constrained program would fare
        state_continuity_weight=1000000,
```
___
*[`bioptim/examples/getting_started/example_continuity_as_objective.py` line 192 at r3](https://reviewable.io/reviews/pyomeca/bioptim/516#-NAKApTt38FE59oPgTcw:-NAKApTt38FE59oPgTcx:b-ldgghx) ([raw file](https://github.com/pyomeca/bioptim/blob/716ed8eacf6949547e0f74fcbbcab7a789de31bc/bioptim/examples/getting_started/example_continuity_as_objective.py#L192)):*
> ```Python
>     constraints.add(out_of_sphere, y=-0.45, z=0, min_bound=0.35, max_bound=np.inf, node=Node.ALL_SHOOTING)
>     constraints.add(out_of_sphere, y=0.05, z=0, min_bound=0.35, max_bound=np.inf, node=Node.ALL_SHOOTING)
>     # HERE
> ```

What is that for?
EDIT: I just saw the comment before... Maybe add something like `(referenced in the first pass)`?



_Code quote:_
```Python
# HERE
```

**Review by Sciancisco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/516)* status: 4 of 13 files reviewed, 7 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/interfaces/ipopt_interface.py` line 343 at r3](https://reviewable.io/reviews/pyomeca/bioptim/516#-NAKCf1tASM_cMycuErF:-NALFNXz5ZDlptqFlfcH:bwft4am) ([raw file](https://github.com/pyomeca/bioptim/blob/716ed8eacf6949547e0f74fcbbcab7a789de31bc/bioptim/interfaces/ipopt_interface.py#L343)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`has weight = 0` for what?
</blockquote></details>

Moved the comment in `PenaltyOption` in `_set_penalty_function` where it is more relevant. Remember when I wanted to change the behaviour of `weight = 0`. This is to warn that it is much more fundamental than one might think.
___
*[`bioptim/misc/enums.py` line 121 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DHI1TD8Nlk1CmS4gi:-NALHXCp8ONjkLSxf131:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/misc/enums.py#L121)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Yah, let's leave it there
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_as_objective.py` line 246 at r1](https://reviewable.io/reviews/pyomeca/bioptim/516#-N9DG2Rg0foiZsRQXiXi:-NALFL9nAaMPNtjMoexW:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fde0fff95603e6bc555956eb93a0646fc35387d0/bioptim/examples/getting_started/example_as_objective.py#L246)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I mean, this file should be a minimal example. Does it makes sense to actually show all these graphs. Maybe (probably) they are, I do not run the files while reviewing. It just seems a bit complicated as a minimal example, so I wanted to be sure
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_continuity_as_objective.py` line 6 at r3](https://reviewable.io/reviews/pyomeca/bioptim/516#-NAKAGtJ1a3IgJZFCpoU:-NALAElZB4TWA56irDe5:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/716ed8eacf6949547e0f74fcbbcab7a789de31bc/bioptim/examples/getting_started/example_continuity_as_objective.py#L6)):*
> ```Python
> 
> There is a catch however: there are regions in which the weight of the pendulum cannot go.
> The problem is solved in two passes. In the first pass, continuity is an objective rather then a constraint.
> ```

Done.
___
*[`bioptim/examples/getting_started/example_continuity_as_objective.py` line 25 at r3](https://reviewable.io/reviews/pyomeca/bioptim/516#-NAKAOuX-5GDd8i_H8MB:-NALH_LK8z-neHaeIQ4L:b3hj5le) ([raw file](https://github.com/pyomeca/bioptim/blob/716ed8eacf6949547e0f74fcbbcab7a789de31bc/bioptim/examples/getting_started/example_continuity_as_objective.py#L25)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is there a reason to use `NoisedInitialGuess`? It seems that it will confuse the users that are solely interested in the continuity as objective?
</blockquote></details>

It allows to show that the solution with continuity constraints converges but the solution is bad. Without `NoisedInitialGuess`, it just fails.
___
*[`bioptim/examples/getting_started/example_continuity_as_objective.py` line 131 at r3](https://reviewable.io/reviews/pyomeca/bioptim/516#-NAKBviq6PPjjixASG3D:-NALEngF2T7phCCiuRjb:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/716ed8eacf6949547e0f74fcbbcab7a789de31bc/bioptim/examples/getting_started/example_continuity_as_objective.py#L131)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I think the example should define a variable at the top of the function, because as a user when I look at the example file, I expect the relevant part to be highlighted. Right now, the most important bit feels actually burry in a highly complex OCP (I understand the scientific relevance of the example, but not so much as a minimal example...)
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_continuity_as_objective.py` line 192 at r3](https://reviewable.io/reviews/pyomeca/bioptim/516#-NAKApTt38FE59oPgTcw:-NALFAmwBmZbhETzBxjG:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/716ed8eacf6949547e0f74fcbbcab7a789de31bc/bioptim/examples/getting_started/example_continuity_as_objective.py#L192)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

What is that for?
EDIT: I just saw the comment before... Maybe add something like `(referenced in the first pass)`?
</blockquote></details>

Done.

**Review by pariterre — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/516)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Sciancisco)

**Comment by pariterre** [comment]
LTGM had not appeared!! 
Still:
:LGTM: 
haha

**Pull request merged**
