### PR TITLE
[RTR] "Union" to "|"

### PR DESCRIPTION
**Pull request by 20chupin**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

Related to #585

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/613)

### CODE REVIEW

**Comment by 20chupin** [comment]
@pariterre

**Comment by pariterre** [comment]
Almost nothing to say ;)

**Comment by 20chupin** [comment]
I don't know how to resolve the discussion but I have corrected this missing space ! @pariterre

**Comment by pariterre** [comment]
@20chupin
You must type "Done" in "Reviewable" (See the button at the top of the discussion). Even though it is not useful, I'll let you write the "Done" so you see where it is!

**Review by 20chupin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/613)* status: 57 of 58 files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 1335 at r1](https://reviewable.io/reviews/pyomeca/bioptim/613#-NNhM83266TyS4XkkEoz:-NNm4FxkCFHt9eNXMrNg:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/b78cfda8d5265617fa847f0033e1063431957a3e/bioptim/dynamics/configure_problem.py#L1335)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

There is a space missing here
</blockquote></details>

Done.

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/613#-:-NNmFXRr0heokz0PUtDf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @20chupin)

**Pull request merged**
