### PR TITLE
Minimize marker acceleration [Will be automatically merged with #733]

### PR DESCRIPTION
**Pull request by mickaelbegon**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/722)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/722)* status: all files reviewed, 2 unresolved discussions (waiting on @mickaelbegon)

___
*[`.DS_Store` line 0 at r1](https://reviewable.io/reviews/pyomeca/bioptim/722#-N_d5AwUCqzJjlqfmnFq:-N_d5AwUCqzJjlqfmnFr:b-8imjtt) ([raw file](https://github.com/pyomeca/bioptim/blob/8c125726617929bab65660f2a9d1d5a2ed8a4468/.DS_Store#L0)):*
Please, do not version binary files
___
*[`tests/test_penalty.py` line 306 at r1](https://reviewable.io/reviews/pyomeca/bioptim/722#-N_d5SCt6uIBoh8Jzhnw:-N_d5SCt6uIBoh8Jzhnx:b-x0r7w0) ([raw file](https://github.com/pyomeca/bioptim/blob/8c125726617929bab65660f2a9d1d5a2ed8a4468/tests/test_penalty.py#L306)):*
> ```Python
> 
> 
> #TODO: add test for track_marker_acceleration and minimize_marker_acceleration
> ```

Yep :)

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/722)* status: all files reviewed, 3 unresolved discussions (waiting on @mickaelbegon)

___
*[`bioptim/examples/getting_started/custom_dynamics.py` line 34 at r2](https://reviewable.io/reviews/pyomeca/bioptim/722#-N_i7Brr570fsEIlMJzU:-N_i7Brr570fsEIlMJzV:b-vyuzed) ([raw file](https://github.com/pyomeca/bioptim/blob/45412e75ca9fdcdd7dc35de5975840086a6da7e6/bioptim/examples/getting_started/custom_dynamics.py#L34)):*
> ```Python
> 
> 
> def custom_dynamics(
> ```

Did you use the tools for changing all the call to that function before renaming?

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 108 of 118 files at r9, 10 of 10 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/722)* status: all files reviewed, 11 unresolved discussions (waiting on @mickaelbegon)

___
*[`bioptim/limits/penalty.py` line 38 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMIN3GE5OhOteFOhzi:-NaMIN3GE5OhOteFOhzj:bvfj262) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L38)):*
> ```Python
> 
>     @staticmethod
>     def _get_qddot(controller, attribute="mx"):
> ```

Please move this method at the end of the class. We usually put the API (what would be called by an external source) at first and internal ressources at the end. It makes things a little bit easier to find (and do not encourage users to call internal stuff)
___
*[`bioptim/limits/penalty.py` line 38 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMJ6tB5qba2LPrfIjF:-NaMJ6tB5qba2LPrfIjG:b6debke) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L38)):*
> ```Python
> 
>     @staticmethod
>     def _get_qddot(controller, attribute="mx"):
> ```

Do not put default value. It does not feel that mx (or any other) should preclude in that context. 
Add the type in the signature (e.g. `attribute: str` or `attribute: str = "mx" for those with default values) 
___
*[`bioptim/limits/penalty.py` line 46 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMHzgiA2l8ERpV-o2y:-NaMHzgiA2l8ERpV-o2z:b-epxfqo) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L46)):*
> ```Python
>         controller : object
>             The controller that has 'states', 'controls', 'parameters', and 'stochastic_variables' attributes.
> ```

remove the space here
___
*[`bioptim/limits/penalty.py` line 48 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMJl35AsPKM9qvNxGX:-NaMJl35AsPKM9qvNxGY:b7fudhl) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L48)):*
> ```Python
> 
>         attribute : str
>             Specifies which attribute ('cx' or 'mx') to use for the calculation.
> ```

cx does not seem to be a valid entry thanks to the guard below, while cx_start seems but is not written here
___
*[`bioptim/limits/penalty.py` line 52 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMI1YG3PFD5ClawurB:-NaMI1YG3PFD5ClawurC:bwhjmgy) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L52)):*
> ```Python
>         Returns:
>         np.ndarray
>             The computed generalized acceleration.
> ```

computed/extracted ?
___
*[`bioptim/limits/penalty.py` line 55 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMFEfr4Gb3CMn4JM7w:-NaMFEfr4Gb3CMn4JM7x:b-njzzql) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L55)):*
> ```Python
>         """
>         if attribute not in ["mx", "cx_start"]:
>             print("atrribute should be either mx or cx_start")  # probably not enough
> ```

It seems that it is a guard (a way to indicate the user they did something wrong. If so, it should raise : 
`raise ValueError("ERROR MESSAGE HERE")`

That said, this method seems weird. `getattr` is 99% of the time a code smell. Still I do not see now a better way to do it...
___
*[`bioptim/limits/penalty.py` line 69 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMIhgs7qUaq7xn7s-M:-NaMIhgs7qUaq7xn7s-N:bvfj262) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L69)):*
> ```Python
> 
>     @staticmethod
>     def _get_markers_acceleration(controller, markers, CoM=False):
> ```

Please move this method at the end of the class. We usually put the API (what would be called by an external source) at first and internal ressources at the end. It makes things a little bit easier to find (and do not encourage users to call internal stuff)
___
*[`bioptim/limits/penalty.py` line 332 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMIkIf3UR6zcvCkHoe:-NaMIkIf3UR6zcvCkHof:bf59n5s) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L332)):*
> ```Python
>             # var.extend([controller.controls[key] for key in controller.controls])
>             # var.extend([controller.parameters[key] for key in controller.parameters])
>             # return controller.mx_to_cx("com_ddot", com_ddot, *var)
> ```

Remove these comments when finished
___
*[`bioptim/limits/penalty.py` line 640 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMK2211grRGqE9mbev:-NaMK2211grRGqE9mbew:bm33k68) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L640)):*
> ```Python
>             qdot_mx = controller.states["qdot"].mx
>             qddot_mx = PenaltyFunctionAbstract._get_qddot(controller, "mx")
>             # TODO scaled?
> ```

Nope, this is done internally, unless you mean the output value (i.e. com_objective). In that case, the scaling should be dealt when creating the penaly casadi function (which can already be acheived using the weights) 
So in both case, scaling is not what should be done here

**Review by mickaelbegon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/722)* status: all files reviewed, 11 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/limits/penalty.py` line 38 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMIN3GE5OhOteFOhzi:-NaPbaOPABtTMB8aFuSw:b-6rk7nu) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L38)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please move this method at the end of the class. We usually put the API (what would be called by an external source) at first and internal ressources at the end. It makes things a little bit easier to find (and do not encourage users to call internal stuff)
</blockquote></details>

Done. I will think about it next time. 
___
*[`bioptim/limits/penalty.py` line 38 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMJ6tB5qba2LPrfIjF:-NaPblzuDgA8e1lzt19i:buqc6kz) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L38)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Do not put default value. It does not feel that mx (or any other) should preclude in that context. 
Add the type in the signature (e.g. `attribute: str` or `attribute: str = "mx" for those with default values) 
</blockquote></details>

Removed 
Added in the signature
___
*[`bioptim/limits/penalty.py` line 46 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMHzgiA2l8ERpV-o2y:-NaPeD-L6h5BxtW6xW5S:bsswh2k) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L46)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

remove the space here
</blockquote></details>

Done if understood correctly
___
*[`bioptim/limits/penalty.py` line 48 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMJl35AsPKM9qvNxGX:-NaPcU7RE4UM55IGGHEN:b-1dcph8) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L48)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

cx does not seem to be a valid entry thanks to the guard below, while cx_start seems but is not written here
</blockquote></details>

Corrected
___
*[`bioptim/limits/penalty.py` line 52 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMI1YG3PFD5ClawurB:-NaPc_fH5G208nBg2Whl:b-lbv3b6) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L52)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

computed/extracted ?
</blockquote></details>

Change for extracted
___
*[`bioptim/limits/penalty.py` line 55 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMFEfr4Gb3CMn4JM7w:-NaPeQAeB12wR2fYlSlA:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L55)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

It seems that it is a guard (a way to indicate the user they did something wrong. If so, it should raise : 
`raise ValueError("ERROR MESSAGE HERE")`

That said, this method seems weird. `getattr` is 99% of the time a code smell. Still I do not see now a better way to do it...
</blockquote></details>

Done
___
*[`bioptim/limits/penalty.py` line 69 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMIhgs7qUaq7xn7s-M:-NaPeSj64JgxfqauDM33:b-9r6vfd) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L69)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please move this method at the end of the class. We usually put the API (what would be called by an external source) at first and internal ressources at the end. It makes things a little bit easier to find (and do not encourage users to call internal stuff)
</blockquote></details>

Done and added docstring
___
*[`bioptim/limits/penalty.py` line 332 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMIkIf3UR6zcvCkHoe:-NaPeX4D2hGgijGCS6Yl:b-skef37) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L332)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Remove these comments when finished
</blockquote></details>

In fact, those lines were in the previous version, but I don't know what there were for. 
___
*[`bioptim/limits/penalty.py` line 640 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMK2211grRGqE9mbev:-NaPegFq-QA30GU1fenr:b8g2e5m) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L640)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Nope, this is done internally, unless you mean the output value (i.e. com_objective). In that case, the scaling should be dealt when creating the penaly casadi function (which can already be acheived using the weights) 
So in both case, scaling is not what should be done here
</blockquote></details>

past comment that I kept. I removed it.

**Comment by mickaelbegon** [comment]
Most comments have been answered. The tests did not pass. Probably the other PR should fix it.

**Review by mickaelbegon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/722)* status: all files reviewed, 3 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/getting_started/custom_dynamics.py` line 34 at r2](https://reviewable.io/reviews/pyomeca/bioptim/722#-N_i7Brr570fsEIlMJzU:-NavctJABEWK8pBvivnt:b-x87iy3) ([raw file](https://github.com/pyomeca/bioptim/blob/45412e75ca9fdcdd7dc35de5975840086a6da7e6/bioptim/examples/getting_started/custom_dynamics.py#L34)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Did you use the tools for changing all the call to that function before renaming?
</blockquote></details>

Next time
___
*[`bioptim/limits/penalty.py` line 332 at r10](https://reviewable.io/reviews/pyomeca/bioptim/722#-NaMIkIf3UR6zcvCkHoe:-NavczrK4g-e0A2yGwLM:b-hfpv0l) ([raw file](https://github.com/pyomeca/bioptim/blob/9ce0223d7c12ec2a68a7ead01779765810f62a7a/bioptim/limits/penalty.py#L332)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I see this is legacy code. does not make sense anymore
</blockquote></details>

removed
___
*[`bioptim/limits/penalty.py` line 1288 at r12](https://reviewable.io/reviews/pyomeca/bioptim/722#-NavUIzDCh4gSdjwi9iQ:-NavfPUgEOsuwN4J115I:b-wahx80) ([raw file](https://github.com/pyomeca/bioptim/blob/a0e5be2f35dd5fadb0b7db7ecc4e3de11e4cfa11/bioptim/limits/penalty.py#L1288)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Did you mean Parameters? It seems that it was automatically generated. If so, it probably means you did not setup your PyCharm to Numpy style docstring. It is important because if we want to use automatized documentation at some point, docstring must be standardized
</blockquote></details>

done. I have to configure pycharm for next time
___
*[`.DS_Store` line  at r1](https://reviewable.io/reviews/pyomeca/bioptim/722#-N_d5AwUCqzJjlqfmnFq:-Navg09MEtgAqLFxxMWK:b-hfpv0l) ([raw file](https://github.com/pyomeca/bioptim/blob/8c125726617929bab65660f2a9d1d5a2ed8a4468/.DS_Store#L)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please, do not version binary files
</blockquote></details>

removed

**Comment by pariterre** [comment]
Closed as #733 takes care of this

**Pull request closed without merging**
