### PR TITLE
Multi-start module

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request? -> Issue #393
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/555)

### CODE REVIEW

**Review by Ipuch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/555)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @EveCharbie)

___
*[`bioptim/optimization/multi_start.py` line 67 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqt9Lh9ap-QDAoHNTt:-NEqt9Lh9ap-QDAoHNTu:bdezpcz) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/optimization/multi_start.py#L67)):*
> ```Python
>                         else:
>                             list_out += list_now
> ```

from itertools import product
list_out = [instance for instance in product(*self.args_dict.values())]

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/555)* status: all files reviewed, 12 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/examples/getting_started/example_multistart.py` line 113 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqptyh51W9t-kBXNhX:-NEqptyh51W9t-kBXNhY:bmxtw6b) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/examples/getting_started/example_multistart.py#L113)):*
> ```Python
> 
> 
> def solve_ocp(args: list = None):
> ```

Remove this function



_Code quote:_
```Python
def solve_ocp(args: list = None):
```
___
*[`bioptim/examples/getting_started/example_multistart.py` line 130 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqq5xvEieZaewDx7bZ:-NEqq5xvEieZaewDx7b_:b-mfyl66) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/examples/getting_started/example_multistart.py#L130)):*
> ```Python
> 
>     biorbd_model_path = args[0]
>     final_time = args[1]
> ```

All this should be in prepare_multistart (as suggested later)



_Code quote:_
```Python
    biorbd_model_path = args[0]
    final_time = args[1]
    n_shooting = args[2]
    seed = args[3]

    ocp = prepare_ocp(biorbd_model_path, final_time, n_shooting)
    ocp.add_plot_penalty(CostType.ALL)
    sol = ocp.solve(Solver.IPOPT(show_online_optim=False))  # You cannot use show_online_optim with multi-start
```
___
*[`bioptim/examples/getting_started/example_multistart.py` line 136 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqqL4i9vfvg7Vk-2pr:-NEqqL4i9vfvg7Vk-2ps:b-e7mrhq) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/examples/getting_started/example_multistart.py#L136)):*
> ```Python
>     ocp = prepare_ocp(biorbd_model_path, final_time, n_shooting)
>     ocp.add_plot_penalty(CostType.ALL)
>     sol = ocp.solve(Solver.IPOPT(show_online_optim=False))  # You cannot use show_online_optim with multi-start
> ```

This should be called by the `run()`



_Code quote:_
```Python
sol = ocp.solve(Solver.IPOPT(show_online_optim=False))  # You cannot use show_online_optim with multi-start
```
___
*[`bioptim/examples/getting_started/example_multistart.py` line 137 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqqqJQ0uj2mKCRQluc:-NEqqqJQ0uj2mKCRQlud:bnmhdgk) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/examples/getting_started/example_multistart.py#L137)):*
> ```Python
>     ocp.add_plot_penalty(CostType.ALL)
>     sol = ocp.solve(Solver.IPOPT(show_online_optim=False))  # You cannot use show_online_optim with multi-start
>     ocp.save(sol, f"solutions/pendulum_multi_start_random{seed}.bo", stand_alone=True)
> ```

The user can do this with the output from `.run()`



_Code quote:_
```Python
ocp.save(sol, f"solutions/pendulum_multi_start_random{seed}.bo", stand_alone=True)
```
___
*[`bioptim/examples/getting_started/example_multistart.py` line 144 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqpa0u1U4LZKDb7fv2:-NEqpa0u1U4LZKDb7fv3:undefined) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/examples/getting_started/example_multistart.py#L144)):*
> ```Python
>         solve_ocp,
>         n_random=10,
>         n_pools=4,
> ```





_Suggestion:_
```Python
    ocp = solve_ocp(biorbd_model_path, final_time, n_shooting, seed=42)
    ocp.add_plot_penalty(CostType.ALL)
    return MultiStart(
        ocp,
        n_random=10,
        n_pools=4,
    )
```
___
*[`bioptim/examples/getting_started/example_multistart.py` line 155 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqqmKvBkLNd3DSoNqO:-NEqqmKvBkLNd3DSoNqP:b-sfvstl) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/examples/getting_started/example_multistart.py#L155)):*
> ```Python
>         biorbd_model_path=["models/pendulum.bioMod"], final_time=[1], n_shooting=[30, 40, 50]
>     )
>     multi_start.run()
> ```

This should returns all the solution

multi_start.solve(solver=Solver.IPOPT(show_online_optim=False))



_Suggestion:_
```Python
multi_start.solve(Solver.IPOPT(show_online_optim=False))
```
___
*[`bioptim/optimization/multi_start.py` line 23 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqsSJ66JVmlqWRkYDX:-NEqsSJ66JVmlqWRkYDY:undefined) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/optimization/multi_start.py#L23)):*
> ```Python
>         n_random: int = 1,
>         n_pools: int = 1,
>         args_dict: dict = None,
> ```





_Suggestion:_
```Python
    def __init__(
        self,
        ocp,
        n_random: int = 1,
        n_pools: int = 1,
        **kwargs,
    ):
```
___
*[`bioptim/optimization/multi_start.py` line 38 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqrcfw7hhcHBAyXeRD:-NEqrcfw7hhcHBAyXeRE:btzajbn) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/optimization/multi_start.py#L38)):*
> ```Python
>         """
> 
>         self.solve_ocp = solve_ocp
> ```

self.ocp = ocp
self.solver = solver
___
*[`bioptim/optimization/multi_start.py` line 41 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqt3Dd1RYyS8sLyfPl:-NEqt3Dd1RYyS8sLyfPm:undefined) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/optimization/multi_start.py#L41)):*
> ```Python
>         self.n_random = n_random
>         self.n_pools = n_pools
>         self.args_dict = args_dict
> ```





_Suggestion:_
```Python
self.args_dict = **kwargs
```
___
*[`bioptim/optimization/multi_start.py` line 79 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqtIv28mhinEkAYD9a:-NEqtIv28mhinEkAYD9b:undefined) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/optimization/multi_start.py#L79)):*
> ```Python
>         """
>         with Pool(self.n_pools) as p:
>             p.map(self.solve_ocp, self.combined_args_to_list)
> ```





_Suggestion:_
```Python
p.map(self.ocp.solve, self.combined_args_to_list)
```
___
*[`tests/test_global_getting_started.py` line 1146 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqte-V81DB60kM4GsU:-NEqte-V81DB60kM4GsV:b-l44dpl) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/tests/test_global_getting_started.py#L1146)):*
> ```Python
>         biorbd_model_path=[bioptim_folder + "/models/pendulum.bioMod"], final_time=[1], n_shooting=[5, 10]
>     )
>     multi_start.run()
> ```

.solve()

**Review by EveCharbie — COMMENTED** [review]
It is not exactly what you asked for, but I think it respects the idea the most possible

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/555#-:-NEwPnlR-8bBpGZvir1H:b-qh8lju)* status: 3 of 5 files reviewed, 12 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/examples/getting_started/example_multistart.py` line 113 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqptyh51W9t-kBXNhX:-NEwPBQoCzCH83Fvt7RK:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/examples/getting_started/example_multistart.py#L113)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Remove this function
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_multistart.py` line 130 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqq5xvEieZaewDx7bZ:-NEwPH1c0ncojdldwTF4:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/examples/getting_started/example_multistart.py#L130)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

All this should be in prepare_multistart (as suggested later)
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_multistart.py` line 136 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqqL4i9vfvg7Vk-2pr:-NEwPPFC3SZ0qUz1-0d7:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/examples/getting_started/example_multistart.py#L136)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should be called by the `run()`
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_multistart.py` line 137 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqqqJQ0uj2mKCRQluc:-NEuu22G7A1RLZdu6O2G:b-qnrevt) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/examples/getting_started/example_multistart.py#L137)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

The user can do this with the output from `.run()`
</blockquote></details>

Not possible to return sol because it cannot be pickled.
___
*[`bioptim/examples/getting_started/example_multistart.py` line 144 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqpa0u1U4LZKDb7fv2:-NEuu_oq-fUwl7TaL92v:b7ocgvs) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/examples/getting_started/example_multistart.py#L144)):*
> ```Python
>         solve_ocp,
>         n_random=10,
>         n_pools=4,
> ```

I cannot put ocp since the arguments would be fixed, but I put prepare_ocp
___
*[`bioptim/examples/getting_started/example_multistart.py` line 155 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqqmKvBkLNd3DSoNqO:-NEuviLU5YIjmrK1hgGz:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/examples/getting_started/example_multistart.py#L155)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should returns all the solution

multi_start.solve(solver=Solver.IPOPT(show_online_optim=False))
</blockquote></details>

Done.
___
*[`bioptim/optimization/multi_start.py` line 23 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqsSJ66JVmlqWRkYDX:-NEuw-e_Ej-7nLmp04nt:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/optimization/multi_start.py#L23)):*
> ```Python
>         n_random: int = 1,
>         n_pools: int = 1,
>         args_dict: dict = None,
> ```

Done.
___
*[`bioptim/optimization/multi_start.py` line 38 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqrcfw7hhcHBAyXeRD:-NEuw4i15O5Fqp6NncbY:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/optimization/multi_start.py#L38)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

self.ocp = ocp
self.solver = solver
</blockquote></details>

Done.
___
*[`bioptim/optimization/multi_start.py` line 41 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqt3Dd1RYyS8sLyfPl:-NEuwIRL15hlQUqgMowe:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/optimization/multi_start.py#L41)):*
> ```Python
>         self.n_random = n_random
>         self.n_pools = n_pools
>         self.args_dict = args_dict
> ```

Done.
___
*[`bioptim/optimization/multi_start.py` line 67 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqt9Lh9ap-QDAoHNTt:-NEwPjIp4fZKO8M4kAK9:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/optimization/multi_start.py#L67)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

from itertools import product
list_out = [instance for instance in product(*self.args_dict.values())]


</blockquote></details>

Done
___
*[`bioptim/optimization/multi_start.py` line 79 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqtIv28mhinEkAYD9a:-NEuwRv-1ZfbTI7_hMKG:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/bioptim/optimization/multi_start.py#L79)):*
> ```Python
>         """
>         with Pool(self.n_pools) as p:
>             p.map(self.solve_ocp, self.combined_args_to_list)
> ```

Done.
___
*[`tests/test_global_getting_started.py` line 1146 at r1](https://reviewable.io/reviews/pyomeca/bioptim/555#-NEqte-V81DB60kM4GsU:-NEuwTK60CR-iIvAfS0R:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d654b60015626f0055f057de708d7c9c9f2beb77/tests/test_global_getting_started.py#L1146)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

.solve()
</blockquote></details>

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/555)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @EveCharbie and @Ipuch)

___
*[`bioptim/examples/getting_started/example_multistart.py` line 85 at r3](https://reviewable.io/reviews/pyomeca/bioptim/555#-NFPgL1IDazZV_GR8e7n:-NFPgL1IDazZV_GR8e7o:bb7462z) ([raw file](https://github.com/pyomeca/bioptim/blob/0138d28f3cc7127d9035eafe2c3d7eef32892578/bioptim/examples/getting_started/example_multistart.py#L85)):*
> ```Python
>     u_bounds[1, :] = 0  # Prevent the model from actively rotate
> 
>     # To be changed when the issue on NoisedInitialGuess is fixed
> ```

TODO
___
*[`bioptim/examples/getting_started/example_multistart.py` line 143 at r3](https://reviewable.io/reviews/pyomeca/bioptim/555#-NFPhbCbDQxFXo4dwCKM:-NFPhbCbDQxFXo4dwCKN:b-hgxv3i) ([raw file](https://github.com/pyomeca/bioptim/blob/0138d28f3cc7127d9035eafe2c3d7eef32892578/bioptim/examples/getting_started/example_multistart.py#L143)):*
> ```Python
>         prepare_ocp,
>         solver=Solver.IPOPT(show_online_optim=False),  # You cannot use show_online_optim with multi-start
>         callback_function=save_results,
> ```

`post_optimization_callback=save_results,`



_Code quote:_
```Python
callback_function
```
___
*[`bioptim/optimization/multi_start.py` line 46 at r3](https://reviewable.io/reviews/pyomeca/bioptim/555#-NFPi7TCBHQnlK1b4OEX:-NFPi7TCBHQnlK1b4OEY:bit2wcd) ([raw file](https://github.com/pyomeca/bioptim/blob/0138d28f3cc7127d9035eafe2c3d7eef32892578/bioptim/optimization/multi_start.py#L46)):*
> ```Python
>         self.prepare_ocp = prepare_ocp
>         self.solver = solver
>         self.callback_function = callback_function
> ```

post_optimization_callback



_Code quote:_
```Python
.callback_function = callback_function
```

**Comment by pariterre** [comment]
@EveCharbie I rebased this PR to integrate the new tests. Please use reset --hard (don't merge) to move to that PR if you need to push something later. Call me if needed

**Comment by pariterre** [comment]
@EveCharbie 
Tests fails so renaming to normal name!

**Review by pariterre — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/555)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

**Pull request merged**
