### PR TITLE
[RTM if tests pass] inverse OCP

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/635)

### CODE REVIEW

**Comment by EveCharbie** [comment]
@pariterre I will not create a full test because it would be too long.
But, do I create smaller tests to make sure that this example evolves with the rest of bioptim? If yes, is ti an inconvenience if we now have to install pygmo?

**Comment by EveCharbie** [comment]
@pariterre, we might need to change the dependencies in conda-forge?

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/635)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

___
*[`README.md` line 114 at r3](https://reviewable.io/reviews/pyomeca/bioptim/635#-NQeZZwh35gliglhWyMR:-NQeZZwh35gliglhWyMS:b5iyce7) ([raw file](https://github.com/pyomeca/bioptim/blob/9d6a8f63f5c38198fa531e11d571704b3df307e2/README.md#L114)):*
> ```Markdown
> - [Moving estimation horizon](#moving-estimation-horizon)
> - [Acados](#acados)
> - [Inverse_optimal_control](#inverse_optimal_control)
> ```

Normal casing? make sure this links work



_Code quote:_
```Markdown
Inverse_optimal_control
```
___
*[`tests/test_all_examples.py` line 499 at r3](https://reviewable.io/reviews/pyomeca/bioptim/635#-NQe_3Y9DkFLLtYL13M8:-NQe_3Y9DkFLLtYL13M9:b45h) ([raw file](https://github.com/pyomeca/bioptim/blob/9d6a8f63f5c38198fa531e11d571704b3df307e2/tests/test_all_examples.py#L499)):*
> ```Python
> 
> 
> def test__inverse_optimal_control__doublep_endulum_torque_driven_IOCP():
> ```





_Suggestion:_
```Python
double_pendulum
```

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/635)* status: all files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`README.md` line 114 at r3](https://reviewable.io/reviews/pyomeca/bioptim/635#-NQeZZwh35gliglhWyMR:-NQeuZtP3aMA8cqwW6Nv:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9d6a8f63f5c38198fa531e11d571704b3df307e2/README.md#L114)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Normal casing? make sure this links work
</blockquote></details>

Done.
___
*[`tests/test_all_examples.py` line 499 at r3](https://reviewable.io/reviews/pyomeca/bioptim/635#-NQe_3Y9DkFLLtYL13M8:-NQeuefI0y0yXqko4Rj8:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9d6a8f63f5c38198fa531e11d571704b3df307e2/tests/test_all_examples.py#L499)):*
> ```Python
> 
> 
> def test__inverse_optimal_control__doublep_endulum_torque_driven_IOCP():
> ```

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/635)* status: all files reviewed, 1 unresolved discussion (waiting on @EveCharbie)

___
*[`README.md` line 114 at r3](https://reviewable.io/reviews/pyomeca/bioptim/635#-NQeZZwh35gliglhWyMR:-NQeuzHoElQQIDRPnw2g:bwuvr39) ([raw file](https://github.com/pyomeca/bioptim/blob/9d6a8f63f5c38198fa531e11d571704b3df307e2/README.md#L114)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the difference

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/635#-:-NQeyTjc6feE_Vjr3YXg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @EveCharbie)

**Pull request merged**
