### PR TITLE
[RTM] collocations for SOCP

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request? issues #521 (Not directly related, but might have fixed it)
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/744)

### CODE REVIEW

**Review by EveCharbie — COMMENTED** [review]
@pariterre I think you did not publish you comments

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/744#-:-NbJn8CF9285ZhpTMEhy:b-mudss7)* status: 0 of 23 files reviewed, all discussions resolved

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/744)* status: 15 of 24 files reviewed, 9 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/dynamics/configure_problem.py` line 648 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFNT3k4eCyVzlv3HJO:-NbFNT3lDVwxXPM2UxkS:b-lmj6wf) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/dynamics/configure_problem.py#L648)):*
> ```Python
>                 nlp.stochastic_variables.mx,
>                 nlp.cx(),
>                 nlp.cx(),
> ```

Probable MX.sym()
___
*[`bioptim/dynamics/configure_problem.py` line 677 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFNZlrA8obS6dx5vn_:-NbFNZlrA8obS6dx5vna:bj8tiq2) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/dynamics/configure_problem.py#L677)):*
> ```Python
>                     nlp.states_dot.scaled.mx_reduced,
>                     nlp.cx(),
>                     nlp.cx(),
> ```

MX.sym()
___
*[`bioptim/dynamics/integrator.py` line 767 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFOckl4C9bvQx-51Dr:-NbFOckl4C9bvQx-51Ds:bpzz9k1) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/dynamics/integrator.py#L767)):*
> ```Python
>                 self.stochastic_variables_sym,
>                 self.motor_noise,
>                 self.sensory_noise,
> ```

If possible named arguments?
___
*[`bioptim/interfaces/interface_utils.py` line 55 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFQZ0x9hNcmKW24Uwi:-NbFQZ0x9hNcmKW24Uwj:b-2evq8w) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/interfaces/interface_utils.py#L55)):*
> ```Python
>     v_bounds_max = v_bounds[1]
>     v_init_init = v_init
>     if hasattr(interface.ocp.nlp[0], "motor_noise"):
> ```

This should always be true (it must be added to NLP structure). Test if it is None



_Code quote:_
```Python
interface.ocp.nlp[0], "motor_noise"
```
___
*[`bioptim/interfaces/interface_utils.py` line 329 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFQmhJ7PamDE8MpIxP:-NbFQmhJ7PamDE8MpIxQ:b-i5woup) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/interfaces/interface_utils.py#L329)):*
> ```Python
>         return _x, _u, _s
> 
>     if hasattr(interface.ocp.nlp[0], "motor_noise"):
> ```

same here (test if None)
___
*[`bioptim/limits/multinode_penalty.py` line 357 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFT9PKDOFpS1ucjrOl:-NbFT9PKDOFpS1ucjrOm:brmnbq5) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/limits/multinode_penalty.py#L357)):*
> ```Python
>                 controllers[0].stochastic_variables.cx_start,
>                 controllers[0].get_nlp,
>                 controllers[0].get_nlp.motor_noise,
> ```

add motor_noise to the controller (and sensory_noise)
i.e. : controllers[0].motor_noise
___
*[`bioptim/limits/multinode_penalty.py` line 721 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFTLvFAKVeBmLq-tkr:-NbFTLvFAKVeBmLq-tks:bs0y7uk) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/limits/multinode_penalty.py#L721)):*
> ```Python
>                     controllers[0].stochastic_variables.cx_start,
>                     controllers[0].get_nlp.motor_noise,
>                     controllers[0].get_nlp.sensory_noise,
> ```

do not use nlp
___
*[`bioptim/limits/penalty_option.py` line 490 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFU_tGBdotqSy5HXF2:-NbFU_tGBdotqSy5HXF3:buj3uxi) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/limits/penalty_option.py#L490)):*
> ```Python
> 
>         # Do not use nlp.add_casadi_func because all functions must be registered
>         if hasattr(controller.get_nlp, "motor_noise"):
> ```

use None
___
*[`bioptim/optimization/non_linear_program.py` line 131 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFUi365zMo4Rk1xBJh:-NbFUi365zMo4Rk1xBJi:b-gub7ww) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/optimization/non_linear_program.py#L131)):*
> ```Python
>         self.dynamics_evaluation = DynamicsEvaluation()
>         self.dynamics_func = None
>         self.noised_dynamics_func = None
> ```

add here (for the hasattrb)

**Comment by pariterre** [comment]
indeed... Done!

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/744)* status: 15 of 24 files reviewed, 9 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 648 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFNT3k4eCyVzlv3HJO:-NbKIb1d6mty7eT9kETl:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/dynamics/configure_problem.py#L648)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Probable MX.sym()
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 677 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFNZlrA8obS6dx5vn_:-NbKIbQ42FjG-3kD60tP:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/dynamics/configure_problem.py#L677)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

MX.sym()
</blockquote></details>

Done.
___
*[`bioptim/dynamics/integrator.py` line 767 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFOckl4C9bvQx-51Dr:-NbKIeaKCZjeQ7pVCfPJ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/dynamics/integrator.py#L767)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

If possible named arguments?
</blockquote></details>

Done.
___
*[`bioptim/interfaces/interface_utils.py` line 55 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFQZ0x9hNcmKW24Uwi:-NbKJsFgE5Vb0HNDoQu3:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/interfaces/interface_utils.py#L55)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should always be true (it must be added to NLP structure). Test if it is None
</blockquote></details>

Done.
___
*[`bioptim/interfaces/interface_utils.py` line 329 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFQmhJ7PamDE8MpIxP:-NbKUrnC-OiSxgFG4gUR:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/interfaces/interface_utils.py#L329)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

same here (test if None)
</blockquote></details>

Done.
___
*[`bioptim/limits/multinode_penalty.py` line 357 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFT9PKDOFpS1ucjrOl:-NbKW3UR38vzMWNd58z4:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/limits/multinode_penalty.py#L357)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

add motor_noise to the controller (and sensory_noise)
i.e. : controllers[0].motor_noise
</blockquote></details>

Done.
___
*[`bioptim/limits/multinode_penalty.py` line 721 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFTLvFAKVeBmLq-tkr:-NbKWTbJ9kJkJtt0GjcL:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/limits/multinode_penalty.py#L721)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

do not use nlp
</blockquote></details>

Done.
___
*[`bioptim/limits/penalty_option.py` line 490 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFU_tGBdotqSy5HXF2:-NbKWUXRBbVF-DsUowmA:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/limits/penalty_option.py#L490)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

use None
</blockquote></details>

Done.
___
*[`bioptim/optimization/non_linear_program.py` line 131 at r1](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbFUi365zMo4Rk1xBJh:-NbKWeVo7X9VDCbPloNq:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92b7cff76ec20070fed8201d2e20d18a19c2363c/bioptim/optimization/non_linear_program.py#L131)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

add here (for the hasattrb)
</blockquote></details>

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2, 28 of 28 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/744)* status: all files reviewed, 3 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/interfaces/interface_utils.py` line 455 at r3](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbUwrXe7OUErDt7iHNz:-NbUwrXe7OUErDt7iHO-:b2kxtuk) ([raw file](https://github.com/pyomeca/bioptim/blob/80b729d991bc6ec9bf23abac27203cbd2c352d91/bioptim/interfaces/interface_utils.py#L455)):*
> ```Python
> # state_cx_scaled = horzcat(
> #     *([controller.states_scaled.cx_start] + controller.states_scaled.cx_intermediates_list)
> # )
> ```

To be removed?



_Code quote:_
```Python
# state_cx_scaled = horzcat(
#     *([controller.states_scaled.cx_start] + controller.states_scaled.cx_intermediates_list)
# )
```
___
*[`bioptim/optimization/optimization_variable.py` line 712 at r3](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbUxTzj-aBVNcdzP7u1:-NbUxTzj-aBVNcdzP7u2:b-7pmwja) ([raw file](https://github.com/pyomeca/bioptim/blob/80b729d991bc6ec9bf23abac27203cbd2c352d91/bioptim/optimization/optimization_variable.py#L712)):*
> ```Python
>         for s0 in range(shape_0):
>             for s1 in range(shape_1):
>                 # vector[shape_0 * s0 + s1] = matrix[s0, s1]
> ```

haha!



_Code quote:_
```Python
# vector[shape_0 * s0 + s1] = matrix[s0, s1]
```
___
*[`bioptim/optimization/optimization_vector.py` line 184 at r3](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbUxdzWCePgtkPI5sbV:-NbUxdzWCePgtkPI5sbW:bt8aulf) ([raw file](https://github.com/pyomeca/bioptim/blob/80b729d991bc6ec9bf23abac27203cbd2c352d91/bioptim/optimization/optimization_vector.py#L184)):*
> ```Python
>                 OptimizationVectorHelper._set_node_index(nlp, k)
>                 for p in range(repeat if k != nlp.ns else 1):
>                     point = k if k != 0 else 0 if p == 0 else 1
> ```

add comment that explains that it is okay because we are dealing with bounds

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/744)* status: 28 of 33 files reviewed, 3 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/interfaces/interface_utils.py` line 455 at r3](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbUwrXe7OUErDt7iHNz:-NbYpYmV9FnmVK3g8G5X:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/80b729d991bc6ec9bf23abac27203cbd2c352d91/bioptim/interfaces/interface_utils.py#L455)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be removed?
</blockquote></details>

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/744)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/interfaces/solve_ivp_interface.py` line 179 at r5](https://reviewable.io/reviews/pyomeca/bioptim/744#-Nbp1bfu4Gh4HcaxIcbY:-Nbp1bfu4Gh4HcaxIcbZ:b-kgv0v9) ([raw file](https://github.com/pyomeca/bioptim/blob/326d3fdbf005c7ed718351aa58576779d3cd80bd/bioptim/interfaces/solve_ivp_interface.py#L179)):*
> ```Python
>     t_span = [t_eval[0], t_eval[-1]]
>     integrated_sol = solve_ivp(
>         lambda t, x: np.array(dynamics_func(x, control_function(t), params, s, 0, 0))[:, 0],
> ```

Is 0 the same as [] ? I feel that it may be dangerous to feed 0 as value?
___
*[`bioptim/optimization/solution.py` line 2027 at r5](https://reviewable.io/reviews/pyomeca/bioptim/744#-Nbp28SSAAuxIQA11_Yc:-Nbp28SSAAuxIQA11_Yd:b7crfsz) ([raw file](https://github.com/pyomeca/bioptim/blob/326d3fdbf005c7ed718351aa58576779d3cd80bd/bioptim/optimization/solution.py#L2027)):*
> ```Python
>                 x_reshaped = x
>                 if len(x.shape) > 1:
>                     if x.shape[1] != 1:
> ```

Usually two consecutive "if" with one embedded in the other can be joined into a single if with an "and" statement. I did not have a deep look here, but if it is the case, merge them as it is slightly more readable

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/744)* status: 38 of 40 files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/interfaces/solve_ivp_interface.py` line 179 at r5](https://reviewable.io/reviews/pyomeca/bioptim/744#-Nbp1bfu4Gh4HcaxIcbY:-NbpYXpg-9Rqzt51Unow:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/326d3fdbf005c7ed718351aa58576779d3cd80bd/bioptim/interfaces/solve_ivp_interface.py#L179)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is 0 the same as [] ? I feel that it may be dangerous to feed 0 as value?
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution.py` line 2027 at r5](https://reviewable.io/reviews/pyomeca/bioptim/744#-Nbp28SSAAuxIQA11_Yc:-NbpZ0qkEDz1-gUZV1eq:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/326d3fdbf005c7ed718351aa58576779d3cd80bd/bioptim/optimization/solution.py#L2027)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Usually two consecutive "if" with one embedded in the other can be joined into a single if with an "and" statement. I did not have a deep look here, but if it is the case, merge them as it is slightly more readable
</blockquote></details>

Done.

**Comment by EveCharbie** [comment]
@pariterre I am done :)

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/744)* status: all files reviewed, 5 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/optimization/optimization_variable.py` line 151 at r6](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbuxPwwD59XIV_Yhjwz:-NbuxPwwD59XIV_Yhjx-:byzscoi) ([raw file](https://github.com/pyomeca/bioptim/blob/244bfae50714627a7ac05b50b73a34f0d4c50217/bioptim/optimization/optimization_variable.py#L151)):*
> ```Python
>                 # TODO: Charbie -> will change the order in a separate PR
>                 vector[shape_0 * s0 + s1] = matrix[s0, s1]
>                 # vector[shape_0 * s1 + s0] = matrix[s0, s1]
> ```

I suggest:
```
if np.random.rand() > 0.5:
    vector[shape_0 * s0 + s1] = matrix[s0, s1]
else
    vector[shape_0 * s1 + s0] = matrix[s0, s1]
```
:P
___
*[`bioptim/optimization/solution.py` line 1952 at r6](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbuxpWD89ia2uoneMQg:-NbuxpWD89ia2uoneMQh:b-hhv96v) ([raw file](https://github.com/pyomeca/bioptim/blob/244bfae50714627a7ac05b50b73a34f0d4c50217/bioptim/optimization/solution.py#L1952)):*
> ```Python
>                         )
> 
>                     x = np.hstack((_x_0, _x_1))
> ```

Doesn't hstack creates the same problem discussed before?
___
*[`bioptim/optimization/solution.py` line 2042 at r6](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbuxxKy-9482Ewwjc9i:-NbuxxKy-9482Ewwjc9j:b4wz06p) ([raw file](https://github.com/pyomeca/bioptim/blob/244bfae50714627a7ac05b50b73a34f0d4c50217/bioptim/optimization/solution.py#L2042)):*
> ```Python
>                 # ):
>                 #     val.append(penalty.function[idx](x[:, 0], u[:, 0], p, s[:, 0], 0, 0))
>                 # else:
> ```

Reinstroduce?
___
*[`bioptim/optimization/solution.py` line 2084 at r6](https://reviewable.io/reviews/pyomeca/bioptim/744#-Nbuy-n0CLmv2yPhV3v4:-Nbuy-n0CLmv2yPhV3v5:bk6c4tq) ([raw file](https://github.com/pyomeca/bioptim/blob/244bfae50714627a7ac05b50b73a34f0d4c50217/bioptim/optimization/solution.py#L2084)):*
> ```Python
>                             else self._controls["scaled"][phase_idx][key][:, col_u_idx]
>                         )
>                     u = np.hstack((u, _u.reshape(nlp.controls.shape, len(col_u_idx))))
> ```

Same question (hstack vs vstack)?
___
*[`tests/shard3/test_global_getting_started.py` line 713 at r6](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbuyGi50pOYaxMmD91H:-NbuyGi50pOYaxMmD91I:b-pqdhrg) ([raw file](https://github.com/pyomeca/bioptim/blob/244bfae50714627a7ac05b50b73a34f0d4c50217/tests/shard3/test_global_getting_started.py#L713)):*
> ```Python
>     from bioptim.examples.getting_started import custom_parameters as ocp_module
> 
>     return  # TODO: Fix parameter scaling :(
> ```

I'll take care of this

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/744)* status: all files reviewed, 5 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/optimization/optimization_variable.py` line 151 at r6](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbuxPwwD59XIV_Yhjwz:-NbwbAJc2U0EYtQmRy4v:b-ap8dyw) ([raw file](https://github.com/pyomeca/bioptim/blob/244bfae50714627a7ac05b50b73a34f0d4c50217/bioptim/optimization/optimization_variable.py#L151)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I suggest:
```
if np.random.rand() > 0.5:
    vector[shape_0 * s0 + s1] = matrix[s0, s1]
else
    vector[shape_0 * s1 + s0] = matrix[s0, s1]
```
:P
</blockquote></details>

Haha --'
I am sure now than it wasn't the right order, but I need to change the values of the tests, so I will do a separate PR just to make sure I do not mess up anything.
___
*[`bioptim/optimization/solution.py` line 1952 at r6](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbuxpWD89ia2uoneMQg:-NbwbVve-aQdEijW0dQF:b-9kcr8l) ([raw file](https://github.com/pyomeca/bioptim/blob/244bfae50714627a7ac05b50b73a34f0d4c50217/bioptim/optimization/solution.py#L1952)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Doesn't hstack creates the same problem discussed before?
</blockquote></details>

Yes, so I had to create empty variables to keep the right dimensions.
Vstack was not possible because multi-threading is "doing hstack" underneath.
___
*[`bioptim/optimization/solution.py` line 2042 at r6](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbuxxKy-9482Ewwjc9i:-NbwcEV09Nt5eI0XIDTQ:bwdth6u) ([raw file](https://github.com/pyomeca/bioptim/blob/244bfae50714627a7ac05b50b73a34f0d4c50217/bioptim/optimization/solution.py#L2042)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Reinstroduce?
</blockquote></details>

sorry for that
___
*[`bioptim/optimization/solution.py` line 2084 at r6](https://reviewable.io/reviews/pyomeca/bioptim/744#-Nbuy-n0CLmv2yPhV3v4:-NbwcHNx6PXhoPTkmgCv:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/244bfae50714627a7ac05b50b73a34f0d4c50217/bioptim/optimization/solution.py#L2084)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Same question (hstack vs vstack)?
</blockquote></details>

Done.
___
*[`tests/shard3/test_global_getting_started.py` line 713 at r6](https://reviewable.io/reviews/pyomeca/bioptim/744#-NbuyGi50pOYaxMmD91H:-NbwcJfE9jUUak17KSOP:b-orqlw2) ([raw file](https://github.com/pyomeca/bioptim/blob/244bfae50714627a7ac05b50b73a34f0d4c50217/tests/shard3/test_global_getting_started.py#L713)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I'll take care of this
</blockquote></details>

You're the best!

**Comment by EveCharbie** [comment]
@pariterre mergable ?

**Pull request merged**
