### PR TITLE
[RTM after push] Provide two examples of minmax OCP with extra parameters 

### PR DESCRIPTION
**Pull request by mickaelbegon**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/835)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
Not sure to understand why pendulum.py was removed though..

> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/835#-:-Np_VMRMBNcr80UFKJeA:b-4a9tel)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mickaelbegon)

___
*[`bioptim/examples/getting_started/pendulum.py` line 10 at r1](https://reviewable.io/reviews/pyomeca/bioptim/835#-Np_UvsR5ilPQgIDlsEq:-Np_UvsS36V7uq20qFEG:bh59pcv) ([raw file](https://github.com/pyomeca/bioptim/blob/d65e846e241af1f54f78d5453ca468a920b7d169/bioptim/examples/getting_started/pendulum.py#L10)):*
> ```Python
> During the optimization process, the graphs are updated real-time (even though it is a bit too fast and short to really
> appreciate it). Finally, once it finished optimizing, it animates the model using the optimal solution
> """
> ```

Why did you remove pendulum.py?

**Review by pariterre — DISMISSED** [review]
:lgtm: 
@mickaelbegon  I see quite a few changes in the main file (minimize and minmax) is this mergeable?

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/835#-:-Npe14r_8S_FaJmDYKEn:b-purzvu)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mickaelbegon)

**Review by mickaelbegon — COMMENTED** [review]
solve conflicts ... should be ready to merge

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/835#-:-NqBn_jH1PlE8xDCKJRf:bld1oif)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @pariterre)

___
*[`bioptim/examples/getting_started/pendulum.py` line 10 at r1](https://reviewable.io/reviews/pyomeca/bioptim/835#-Np_UvsR5ilPQgIDlsEq:-NqBnU03DsCJodEDrUqe:b-4nh75z) ([raw file](https://github.com/pyomeca/bioptim/blob/d65e846e241af1f54f78d5453ca468a920b7d169/bioptim/examples/getting_started/pendulum.py#L10)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Why did you remove pendulum.py?
</blockquote></details>

it was my mistake

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/835#-:-NqD7dUsCmRicpj2Z8OI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mickaelbegon)

**Pull request merged**
