### PR TITLE
[RTM when ping] SOCP_COLLOCATION corrections to make it right :)

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/771)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, 8 of 21 files at r2, 10 of 17 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/771)* status: all files reviewed, 12 unresolved discussions (waiting on @EveCharbie)

___
*[`.gitignore` line 121 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPMVlJ3omJyaLZQWqr:-NgPMVlK1PPPj7yC1OH4:b-1mct6s) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/.gitignore#L121)):*
> ```ignore
> *.DS_store
> 
> bioptim/examples/stochastic_optimal_control/output.png
> ```

*.png should do the trick
___
*[`bioptim/dynamics/integrator.py` line 933 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPNEv400uoFlNBTUfU:-NgPNEv400uoFlNBTUfV:bwrsjic) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/dynamics/integrator.py#L933)):*
> ```Python
>             param_scaling=self.param_scaling,
>             stochastic_variables=self.s_sym,
>         )
> ```

Useless?
___
*[`bioptim/interfaces/stochastic_bio_model.py` line 43 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPPBf89ugFuIAjj3vu:-NgPPBf89ugFuIAjj3vv:bn4njbk) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/interfaces/stochastic_bio_model.py#L43)):*
> ```Python
>             matrix = np.zeros((shape_0, shape_1))
>         else:
>             matrix = type(var).zeros(shape_0, shape_1)
> ```

Does this make reshape_sym_to_matrix obsolete?
___
*[`bioptim/interfaces/stochastic_bio_model.py` line 101 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPPGxH6jE3WMSJC6r0:-NgPPGxH6jE3WMSJC6r1:b-oz8lh6) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/interfaces/stochastic_bio_model.py#L101)):*
> ```Python
>             vector = np.zeros(shape_0 * shape_1)
>         else:
>             vector = type(matrix).zeros(shape_0 * shape_1)
> ```

Does this make reshape_to_vector_sym obsolete (if it exists)
___
*[`bioptim/limits/constraints.py` line 754 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPPYVzBTO_iUnHRd6t:-NgPPYVzBTO_iUnHRd6u:b3nmsvg) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/limits/constraints.py#L754)):*
> ```Python
>             collocation_method = controller.get_nlp.ode_solver.method
>             polynomial_degree = controller.get_nlp.ode_solver.polynomial_degree
>             Mc, _ = ConstraintFunction.Functions.collocation_fun_jac(
> ```

Based on discussion: check the naming
___
*[`bioptim/limits/constraints.py` line 875 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPPvd-4EN1xTh1sZnm:-NgPPvd-4EN1xTh1sZnn:btdveuf) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/limits/constraints.py#L875)):*
> ```Python
> 
>         @staticmethod
>         def semidefinite_positive_matrix(
> ```

Check naming and make a better docstring (add to readme as well)
___
*[`bioptim/limits/constraints.py` line 1042 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPQ8xhEdPAzyKN7boq:-NgPQ8xhEdPAzyKN7bor:bo7qysc) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/limits/constraints.py#L1042)):*
> ```Python
>                 ],
>                 [m_matrix @ (Gdx @ cov_matrix @ Gdx.T + Gdw @ sigma_ww @ Gdw.T) @ m_matrix.T],
>             ).expand()
> ```

Should this be controllable from outside?
___
*[`bioptim/limits/constraints.py` line 1065 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPQbJjDBDcauyztu-W:-NgPQbJjDBDcauyztu-X:blyr3lc) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/limits/constraints.py#L1065)):*
> ```Python
>     """
> 
>     CONTINUITY = (PenaltyFunctionAbstract.Functions.state_continuity,)
> ```

Sould "CONTINUITY" be changed as well?
___
*[`bioptim/limits/penalty.py` line 1173 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPR2aP7uKoZALjoJ3M:-NgPR2aP7uKoZALjoJ3N:bi6dlbl) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/limits/penalty.py#L1173)):*
> ```Python
> 
>         @staticmethod
>         def first_collocation_helper_equals_final_state(penalty: PenaltyOption, controller: PenaltyController | list):
> ```

Do not use "helper" as it has a meaning in programming which is not related to what is intended here
change "final" for "initial"
___
*[`bioptim/optimization/problem_type.py` line 47 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPS30-7Ct9mVst4d4y:-NgPS30-7Ct9mVst4d4z:b-6pwpgl) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/optimization/problem_type.py#L47)):*
> ```Python
> 
>         def __init__(self, polynomial_degree: int = 4, method: str = "legendre"):
>             self.polynomial_degree = polynomial_degree
> ```

Make sure with_cholesky is removed everywhere
___
*[`bioptim/optimization/solution.py` line 1139 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPS_A-E6723keX4dcr:-NgPS_A-E6723keX4dcs:brdrs4f) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/optimization/solution.py#L1139)):*
> ```Python
>         for p, nlp in enumerate(self.ocp.nlp):
>             is_direct_collocation = nlp.ode_solver.is_direct_collocation
>             add_initial_collocation_point = False
> ```

check if better naming is possible as "initial" does not refer to "starting" anywhere else
include instead of add?

"include_starting_collocation_point"
___
*[`bioptim/optimization/stochastic_optimal_control_program.py` line 340 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPT9pCB4RJdXEEhXPW:-NgPT9pCB4RJdXEEhXPX:bd38zrd) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/optimization/stochastic_optimal_control_program.py#L340)):*
> ```Python
>         if "ref" in self.nlp[0].stochastic_variables:
>             constraints.add(ConstraintFcn.STOCHASTIC_MEAN_SENSORY_INPUT_EQUALS_REFERENCE, node=Node.ALL)
>             # @pariterre This seems dangerous ?
> ```

seems good

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/771)* status: all files reviewed, 12 unresolved discussions (waiting on @pariterre)

___
*[`.gitignore` line 121 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPMVlJ3omJyaLZQWqr:-NgPl-b62nu_756FEIra:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/.gitignore#L121)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

*.png should do the trick
</blockquote></details>

Done.
___
*[`bioptim/dynamics/integrator.py` line 933 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPNEv400uoFlNBTUfU:-NgPl1zN8exGNfO27Y_b:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/dynamics/integrator.py#L933)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Useless?
</blockquote></details>

Done.
___
*[`bioptim/interfaces/stochastic_bio_model.py` line 43 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPPBf89ugFuIAjj3vu:-NgPl37iB49jWQjKdpbG:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/interfaces/stochastic_bio_model.py#L43)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Does this make reshape_sym_to_matrix obsolete?
</blockquote></details>

Done.
___
*[`bioptim/interfaces/stochastic_bio_model.py` line 101 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPPGxH6jE3WMSJC6r0:-NgPl4hjBnU_5Tagg74i:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/interfaces/stochastic_bio_model.py#L101)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Does this make reshape_to_vector_sym obsolete (if it exists)
</blockquote></details>

Done.
___
*[`bioptim/limits/constraints.py` line 754 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPPYVzBTO_iUnHRd6t:-NgPlCtq4xAg_Lutv001:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/limits/constraints.py#L754)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Based on discussion: check the naming
</blockquote></details>

Done.
___
*[`bioptim/limits/constraints.py` line 875 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPPvd-4EN1xTh1sZnm:-NgPlz946CwrtCESaKQ5:b-837lwk) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/limits/constraints.py#L875)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Check naming and make a better docstring (add to readme as well)
</blockquote></details>

Please elaborate,  I find it clear.
___
*[`bioptim/limits/constraints.py` line 1042 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPQ8xhEdPAzyKN7boq:-NgPm9rX0DzEkBFi18WX:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/limits/constraints.py#L1042)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Should this be controllable from outside?
</blockquote></details>

Done.
___
*[`bioptim/limits/constraints.py` line 1065 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPQbJjDBDcauyztu-W:-NgPnWMsA3pYTOOzIMDo:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/limits/constraints.py#L1065)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Sould "CONTINUITY" be changed as well?
</blockquote></details>

Done.
___
*[`bioptim/limits/penalty.py` line 1173 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPR2aP7uKoZALjoJ3M:-NgPnp5c1PlInP9sN8wL:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/limits/penalty.py#L1173)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Do not use "helper" as it has a meaning in programming which is not related to what is intended here
change "final" for "initial"
</blockquote></details>

Done.
___
*[`bioptim/optimization/problem_type.py` line 47 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPS30-7Ct9mVst4d4y:-NgPo6ljCU4f6J4P7rd8:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/optimization/problem_type.py#L47)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Make sure with_cholesky is removed everywhere
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution.py` line 1139 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPS_A-E6723keX4dcr:-NgPoEAR67HbT1kouvaG:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/optimization/solution.py#L1139)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

check if better naming is possible as "initial" does not refer to "starting" anywhere else
include instead of add?

"include_starting_collocation_point"
</blockquote></details>

Done.
___
*[`bioptim/optimization/stochastic_optimal_control_program.py` line 340 at r4](https://reviewable.io/reviews/pyomeca/bioptim/771#-NgPT9pCB4RJdXEEhXPW:-NgPoF1N9ANsaf1Jgblr:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d5d537c6ec738737bf4a2c2086fd64ae3ea8c794/bioptim/optimization/stochastic_optimal_control_program.py#L340)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

seems good
</blockquote></details>

Done.

**Comment by EveCharbie** [comment]
@pariterre should be good :)

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 21 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/771#-:-NgTzqPQ4bHiGZEBfO-Z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
