### PR TITLE
[RTM] New multi-start debug options

### PR DESCRIPTION
**Pull request by lsechoir**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/634)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
gg so far

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/634#-:-NQejdYMEW_mzyexeKJ1:b-oym5si)* status: all files reviewed, 9 unresolved discussions (waiting on @lsechoir)

___
*[`bioptim/examples/getting_started/example_multistart.py` line 22 at r1](https://reviewable.io/reviews/pyomeca/bioptim/634#-NQeekuEDUvAGCyc1sW4:-NQeekuEDUvAGCyc1sW5:btxy66n) ([raw file](https://github.com/pyomeca/bioptim/blob/3bf65a1ad4e77c6aaadc7f394d23aa8d87d0e2db/bioptim/examples/getting_started/example_multistart.py#L22)):*
> ```Python
>     MagnitudeType,
> )
> import os
> ```

`import` of builtin python  package should appear first with an extra space after



_Code quote:_
```Python
import os
```
___
*[`bioptim/optimization/multi_start.py` line 7 at r1](https://reviewable.io/reviews/pyomeca/bioptim/634#-NQefac25zrOymZdTGwx:-NQefac25zrOymZdTGwy:b-g2tl9s) ([raw file](https://github.com/pyomeca/bioptim/blob/3bf65a1ad4e77c6aaadc7f394d23aa8d87d0e2db/bioptim/optimization/multi_start.py#L7)):*
> ```Python
> from ..optimization.optimal_control_program import OptimalControlProgram
> from ..interfaces.solver_options import Solver
> import os
> ```

idem for import os



_Code quote:_
```Python
from ..interfaces.solver_options import Solver
import os
```
___
*[`bioptim/optimization/multi_start.py` line 31 at r1](https://reviewable.io/reviews/pyomeca/bioptim/634#-NQeftk369RMum4WTh0j:-NQeftk369RMum4WTh0k:bluce2k) ([raw file](https://github.com/pyomeca/bioptim/blob/3bf65a1ad4e77c6aaadc7f394d23aa8d87d0e2db/bioptim/optimization/multi_start.py#L31)):*
> ```Python
>         post_optimization_callback: Callable = None,
>         n_pools: int = 1,
>         already_done_filenames: list = None,
> ```

Add: so user can overwrite the files

`should_solve: Function() = None`

If `None`, then it overwrites all, otherwise it calls the function that returns True or False



_Code quote:_
```Python
        already_done_filenames: list = None,
        single_process_debug_flag: bool = False,
```
___
*[`bioptim/optimization/multi_start.py` line 32 at r1](https://reviewable.io/reviews/pyomeca/bioptim/634#-NQehQWf3BGyaEg8vNuf:-NQehQWf3BGyaEg8vNug:bfca934) ([raw file](https://github.com/pyomeca/bioptim/blob/3bf65a1ad4e77c6aaadc7f394d23aa8d87d0e2db/bioptim/optimization/multi_start.py#L32)):*
> ```Python
>         n_pools: int = 1,
>         already_done_filenames: list = None,
>         single_process_debug_flag: bool = False,
> ```

Change that for `multi_process` or `use_multi_process`



_Code quote:_
```Python
single_process_debug_flag
```
___
*[`bioptim/optimization/multi_start.py` line 47 at r1](https://reviewable.io/reviews/pyomeca/bioptim/634#-NQehiK4EFQKO_VWxKMo:-NQehiK4EFQKO_VWxKMp:b-81u9kx) ([raw file](https://github.com/pyomeca/bioptim/blob/3bf65a1ad4e77c6aaadc7f394d23aa8d87d0e2db/bioptim/optimization/multi_start.py#L47)):*
> ```Python
>             The number of pools to be used for multi-threading
>         already_done_filenames:
>             List of all the filenames that are in the designated folder
> ```

remove that argument



_Code quote:_
```Python
        already_done_filenames:
            List of all the filenames that are in the designated folder
```
___
*[`bioptim/optimization/multi_start.py` line 53 at r1](https://reviewable.io/reviews/pyomeca/bioptim/634#-NQeholF7tpZUzBO-jdh:-NQeholF7tpZUzBO-jdi:b-pi9dgi) ([raw file](https://github.com/pyomeca/bioptim/blob/3bf65a1ad4e77c6aaadc7f394d23aa8d87d0e2db/bioptim/optimization/multi_start.py#L53)):*
> ```Python
>             The dictionary of arguments to be passed to the solve_ocp function
>         combined_args_to_list :
>             ??
> ```

remove that



_Code quote:_
```Python
        combined_args_to_list :
            ??
```
___
*[`bioptim/optimization/multi_start.py` line 66 at r1](https://reviewable.io/reviews/pyomeca/bioptim/634#-NQehxw95VfzcO1N-4ki:-NQehxw95VfzcO1N-4kj:b-102cwk) ([raw file](https://github.com/pyomeca/bioptim/blob/3bf65a1ad4e77c6aaadc7f394d23aa8d87d0e2db/bioptim/optimization/multi_start.py#L66)):*
> ```Python
> 
> 
>     def check_already_done(self, args):
> ```

This method should not appear here, but should be the callback provided by the user



_Code quote:_
```Python
check_already_done
```
___
*[`bioptim/optimization/multi_start.py` line 85 at r1](https://reviewable.io/reviews/pyomeca/bioptim/634#-NQeil3l-FyxvB5InNsq:-NQeil3l-FyxvB5InNsr:blrgvfs) ([raw file](https://github.com/pyomeca/bioptim/blob/3bf65a1ad4e77c6aaadc7f394d23aa8d87d0e2db/bioptim/optimization/multi_start.py#L85)):*
> ```Python
> 
>     def solve_ocp_func(self, args):
>         check_already_done = self.check_already_done(args)
> ```

This should be the call to the user callback if not None

(combine the variable with the next if)



_Code quote:_
```Python
check_already_done = self.check_already_done(args)
```
___
*[`bioptim/optimization/multi_start.py` line 89 at r1](https://reviewable.io/reviews/pyomeca/bioptim/634#-NQeipHT5YomHJIs5JIv:-NQeipHT5YomHJIs5JIw:bsd5v84) ([raw file](https://github.com/pyomeca/bioptim/blob/3bf65a1ad4e77c6aaadc7f394d23aa8d87d0e2db/bioptim/optimization/multi_start.py#L89)):*
> ```Python
>             sol = self.prepare_ocp(*args).solve(self.solver)
>             self.post_optimization_callback(sol, *args)
>         else:
> ```

Remove this else as the user knows



_Code quote:_
```Python
        else:
            print("This OCP already has a saved solution in the designated folder.")
```

**Review by pariterre — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/634)* status: all files reviewed, 9 unresolved discussions (waiting on @lsechoir)

___
*[`bioptim/optimization/multi_start.py` line 32 at r1](https://reviewable.io/reviews/pyomeca/bioptim/634#-NQehQWf3BGyaEg8vNuf:-NQejljU-x1cMhXSTkBx:bxei3nn) ([raw file](https://github.com/pyomeca/bioptim/blob/3bf65a1ad4e77c6aaadc7f394d23aa8d87d0e2db/bioptim/optimization/multi_start.py#L32)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Change that for `multi_process` or `use_multi_process`
</blockquote></details>

actually `multi_threading`if it is multi_threading (check for the import, adjust the docstring in solve if it is the case

**Review by pariterre — APPROVED** [review]
Just need to update the example and tests

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/634#-:-NREoWlkCC0Ww7HC-3Cq:b-qbho56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lsechoir)

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/634)* status: all files reviewed, 11 unresolved discussions (waiting on @lsechoir)

___
*[`bioptim/examples/getting_started/example_multistart.py` line 8 at r4](https://reviewable.io/reviews/pyomeca/bioptim/634#-NRnyxuX9DZUm3WnWSrb:-NRnyxuX9DZUm3WnWSrc:bl6pj6k) ([raw file](https://github.com/pyomeca/bioptim/blob/333c4eda5b451d36d02a5ba4dc7bde8856d56bd9/bioptim/examples/getting_started/example_multistart.py#L8)):*
> ```Python
> import os
> 
> from typing import Callable, Any
> ```

Do not put space between os and typing



_Code quote:_
```Python
from typing import Callable, Any
```
___
*[`bioptim/examples/getting_started/example_multistart.py` line 111 at r4](https://reviewable.io/reviews/pyomeca/bioptim/634#-NRnz3Xt-Q1VMPvscTRX:-NRnz3XvCm7kF3YdQITx:bmql78w) ([raw file](https://github.com/pyomeca/bioptim/blob/333c4eda5b451d36d02a5ba4dc7bde8856d56bd9/bioptim/examples/getting_started/example_multistart.py#L111)):*
> ```Python
>     sol: Solution,
>     biorbd_model_path: str,
>     final_time: int,
> ```

This should be a float



_Code quote:_
```Python
 int
```
___
*[`bioptim/examples/getting_started/example_multistart.py` line 139 at r4](https://reviewable.io/reviews/pyomeca/bioptim/634#-NRnz9zc7nrzwowk-nsM:-NRnz9zc7nrzwowk-nsN:b-nqargr) ([raw file](https://github.com/pyomeca/bioptim/blob/333c4eda5b451d36d02a5ba4dc7bde8856d56bd9/bioptim/examples/getting_started/example_multistart.py#L139)):*
> ```Python
>         return filename
>     states = sol.states["all"]
>     save_folder = "/home/laseche/Documents/Stage_Lisa/Lisa/Sol"
> ```

This was definitely a mistake. Personal folder should not be used!
```python
save_folder = "./temporary_results/"
os.path.mkfolder(save_folder)
...
os.delete(save_folder)
```
Don't forget to add `temporary_results` in the `.gitignore` file



_Code quote:_
```Python
"/home/laseche/Documents/Stage_Lisa/Lisa/Sol"
```
___
*[`bioptim/examples/getting_started/example_multistart.py` line 144 at r4](https://reviewable.io/reviews/pyomeca/bioptim/634#-NRo-qcYAATxwPb1YjQ0:-NRo-qcZEIX-4S4w3R3o:b-i85ccr) ([raw file](https://github.com/pyomeca/bioptim/blob/333c4eda5b451d36d02a5ba4dc7bde8856d56bd9/bioptim/examples/getting_started/example_multistart.py#L144)):*
> ```Python
>         pickle.dump(states, file)
> 
> def should_solve(args,save_results=save_results):
> ```

add `save_folder` parameter
___
*[`bioptim/examples/getting_started/example_multistart.py` line 148 at r4](https://reviewable.io/reviews/pyomeca/bioptim/634#-NRo-6dy8TC1dOYMHtqc:-NRo-6dy8TC1dOYMHtqd:b-gtywdk) ([raw file](https://github.com/pyomeca/bioptim/blob/333c4eda5b451d36d02a5ba4dc7bde8856d56bd9/bioptim/examples/getting_started/example_multistart.py#L148)):*
> ```Python
>     Check if the filename already appears in the folder where files are saved, if not ocp must be solved
>     """
>     save_folder = "/home/laseche/Documents/Stage_Lisa/Lisa/Sol"
> ```

Do not use absolute path



_Code quote:_
```Python
"/home/laseche/Documents/Stage_Lisa/Lisa/Sol"
```
___
*[`bioptim/examples/getting_started/example_multistart.py` line 164 at r4](https://reviewable.io/reviews/pyomeca/bioptim/634#-NRo-j6LApcUVXKxkXJp:-NRo-j6LApcUVXKxkXJq:btdn8o1) ([raw file](https://github.com/pyomeca/bioptim/blob/333c4eda5b451d36d02a5ba4dc7bde8856d56bd9/bioptim/examples/getting_started/example_multistart.py#L164)):*
> ```Python
>         prepare_ocp_callback=prepare_ocp,
>         post_optimization_callback=save_results,
>         should_solve_callback=should_solve,
> ```

use a lambda function to pass the `save_folder`
`should_solve_callback = lambda *args, **kwargs: should_solve(*args, **kwargs, save_folder=save_folder),`



_Code quote:_
```Python
should_solve_callback=should_solve
```
___
*[`bioptim/examples/getting_started/example_multistart.py` line 174 at r4](https://reviewable.io/reviews/pyomeca/bioptim/634#-NRo-DiF3-H-fDzWLBYH:-NRo-DiF3-H-fDzWLBYI:bu1up3k) ([raw file](https://github.com/pyomeca/bioptim/blob/333c4eda5b451d36d02a5ba4dc7bde8856d56bd9/bioptim/examples/getting_started/example_multistart.py#L174)):*
> ```Python
> 
> 
>     global save_folder
> ```

Do not use global variables



_Code quote:_
```Python
global save_folder
```
___
*[`bioptim/examples/getting_started/example_multistart.py` line 175 at r4](https://reviewable.io/reviews/pyomeca/bioptim/634#-NRo-HCFEcOSJIVidlQD:-NRo-HCFEcOSJIVidlQE:bei60ip) ([raw file](https://github.com/pyomeca/bioptim/blob/333c4eda5b451d36d02a5ba4dc7bde8856d56bd9/bioptim/examples/getting_started/example_multistart.py#L175)):*
> ```Python
> 
>     global save_folder
>     save_folder = "/home/laseche/Documents/Stage_Lisa/Lisa/Sol"
> ```

Do not use absolute folder



_Code quote:_
```Python
save_folder = "/home/laseche/Documents/Stage_Lisa/Lisa/Sol"
```
___
*[`bioptim/optimization/multi_start.py` line 52 at r4](https://reviewable.io/reviews/pyomeca/bioptim/634#-NRo0zFg3GK8ySukkr2k:-NRo0zFg3GK8ySukkr2l:b-vbf2h9) ([raw file](https://github.com/pyomeca/bioptim/blob/333c4eda5b451d36d02a5ba4dc7bde8856d56bd9/bioptim/optimization/multi_start.py#L52)):*
> ```Python
>         """
>         # errors : post, prep,
>        # if prepare_ocp_callback ==
> ```

Do not forget to remove



_Code quote:_
```Python
        # errors : post, prep,
       # if prepare_ocp_callback ==
```
___
*[`tests/test_global_getting_started.py` line 1297 at r4](https://reviewable.io/reviews/pyomeca/bioptim/634#-NRo12bf3pYFMBEK70S3:-NRo12bf3pYFMBEK70S4:b-gtywdk) ([raw file](https://github.com/pyomeca/bioptim/blob/333c4eda5b451d36d02a5ba4dc7bde8856d56bd9/tests/test_global_getting_started.py#L1297)):*
> ```Python
>     multi_start.solve()
> 
>     with open("/home/laseche/Documents/Stage_Lisa/Lisa/Sol/pendulum_multi_start_random_states_5_2.pkl", "rb") as file:
> ```

Do not use absolute path



_Code quote:_
```Python
/home/laseche/Documents/Stage_Lisa/Lisa/Sol/
```
___
*[`tests/test_global_getting_started.py` line 1445 at r4](https://reviewable.io/reviews/pyomeca/bioptim/634#-NRo1J9UB-66ZF_ESZ0N:-NRo1J9UB-66ZF_ESZ0O:b-vbf2h9) ([raw file](https://github.com/pyomeca/bioptim/blob/333c4eda5b451d36d02a5ba4dc7bde8856d56bd9/tests/test_global_getting_started.py#L1445)):*
> ```Python
>     #     SelectionMapping(1, (3, 4, 5))
>     # with pytest.raises(ValueError, match="nb_dof should be an 'int'"):
>     #     SelectionMapping((0, 1, 2), 3)
> ```

Do not forget to remove



_Code quote:_
```Python
    # multistart_1= Multistart(
    # )
    # assert len(combinatorial_parameters) == 4
    #
    #
    # with pytest.raises(ValueError, match="independent_indices must not contain more elements than nb_elements"):
    #     SelectionMapping(1, (3, 4, 5))
    # with pytest.raises(ValueError, match="nb_dof should be an 'int'"):
    #     SelectionMapping((0, 1, 2), 3)
```

**Comment by lsechoir** [comment]
It is impossible to give a lambda local function as arguments for the Multistart, the solution we wanted to use to avoid writing save_folder several time is then not working.

Ad solutions we propose to use either save_folder as an argument in prepare_multistart :

```python 
return Multistart(..., 
        prepare_ocp_callback=prepare_ocp,
        post_optimization_callback=save_results,
        should_solve_callback=should_solve,
        save_folder= save_folder, 
        )

```
Then use save_folder as an argument for save_results and should solve 

The other solution would be to give a tuple with the callable function and save_folder 
```python
return Multistart(..., 
        prepare_ocp_callback=prepare_ocp,
        post_optimization_callback=(save_results,save_folder),
        should_solve_callback=(should_solve, save_folder),
        )
        ```
Let me know what you think is best

**Comment by pariterre** [comment]
What do you mean: "It is impossible"?

**Comment by lsechoir** [comment]
> What do you mean: "It is impossible"?

When using lambda functions, an error appears because lambda local function can't be pickled 
```python
return Multistart(..., 
        prepare_ocp_callback=prepare_ocp,
        post_optimization_callback= lambda *args, **kwargs: save_results(*args, **kwargs, save_folder=save_folder),
    ... 
        )
        ```
        The pickle error is done in multi_start

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/634)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @lsechoir)

___
*[`bioptim/examples/getting_started/example_multistart.py` line 168 at r5](https://reviewable.io/reviews/pyomeca/bioptim/634#-NSMlz537Oi26g__0Ri-:-NSMlz537Oi26g__0Ri0:b-yxyy2c) ([raw file](https://github.com/pyomeca/bioptim/blob/e2d1d7ca7cc49bffbc0b938f5c462021d982e5b4/bioptim/examples/getting_started/example_multistart.py#L168)):*
> ```Python
>         combinatorial_parameters=combinatorial_parameters,
>         prepare_ocp_callback=prepare_ocp,
>         post_optimization_callback=save_results,
> ```

Change : `post_optimization_callback=save_results,` for 
`post_optimization_callback=[save_results, {'save_results': 'my_path'}],`


INTERNALLY
if function signature:  `post_optimization_callback=[save_results, {'elem': 1}]`
when called: `post_optimization_callback[0](normal_args, **post_optimization_callback[1])`



_Code quote:_
```Python
post_optimization_callback=save_results,
```

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/634#-:-NSvt33M6Q1KdHJ04-qs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lsechoir)

**Pull request merged**
