### PR TITLE
[RTM when tests pass] Including custom functions as built-ins for stochastic problems

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/743)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/743)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py` line 129 at r1](https://reviewable.io/reviews/pyomeca/bioptim/743#-NbFLOMu-4qRAXi_YgNC:-NbFLOMu-4qRAXi_YgND:bwx2gm5) ([raw file](https://github.com/pyomeca/bioptim/blob/38c716bfec2468be5791502746e947afb73934aa/bioptim/examples/stochastic_optimal_control/arm_reaching_torque_driven_implicit.py#L129)):*
> ```Python
>         k_matrix = k_matrix.T
> 
>         hand_pos = nlp.model.markers(q)[2][:2]
> ```

end_effector? marker?
velocity = nlp.model.stochastic_dynamics_target? ... 
___
*[`bioptim/limits/penalty_option.py` line 373 at r1](https://reviewable.io/reviews/pyomeca/bioptim/743#-NbFKC0pEw9ki4pDQVpd:-NbFKC0pEw9ki4pDQVpe:b-2hb79h) ([raw file](https://github.com/pyomeca/bioptim/blob/38c716bfec2468be5791502746e947afb73934aa/bioptim/limits/penalty_option.py#L373)):*
> ```Python
>                     self.target = np.concatenate((self.target, np.nan * np.zeros((self.target.shape[0], 1))), axis=1)
> 
>     def transform_penalty_to_stochastic(self, controller: PenaltyController, fcn, state_cx_scaled):
> ```

protected (_)

**Review by pariterre — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/743)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

**Review by pariterre — DISMISSED** [review]
:lgtm:

> Reviewed 14 of 47 files at r3, 10 of 21 files at r4, 24 of 27 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/743#-:-NcSmyl_A0ow7rzdYjZt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Comment by EveCharbie** [comment]
Fixes issue #747

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/743#-:-NcXy2nP0FapvMvAxpXC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
