### PR TITLE
[RTM] Restoring bounds on graphs

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request? Issue #716
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/724)

### CODE REVIEW

**Comment by Ipuch** [comment]
Great ! Are there any means to test more stuff around, so we don't break it anymore?

At least that
```python3 
nlp.plot[f"{key}_states"].bounds = ...
```
is well filled by the end of prepare ocp

**Comment by EveCharbie** [comment]
@Ipuch yes, but I will not spend time on adding this test since nothing on the graph part of bioptim is tested anyway.
I think @aceglia has found a better way of testing, we just need someone to put time on it :/

**Comment by Ipuch** [comment]
I'll do it then this is a 10 line test.
Goal is not to test the whole plot but just this lines that are essential to preserve the feature.

**Comment by EveCharbie** [comment]
I think if you only test this specific thing, we will have a false security feeling. We should instead always run an example with graphs when we merge a PR.

**Review by pariterre — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/724#-:-N_iZxTABRydPEbpSR6-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
