### PR TITLE
[RTM] add trapezoidal integrator

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/738)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
Nice :)

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/738#-:-NavkWLL3wXNjiq4d8mC:bo5cpot)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/dynamics/integrator.py` line 529 at r1](https://reviewable.io/reviews/pyomeca/bioptim/738#-NavkBgpARY3ND036ART:-NavkBgpARY3ND036ARU:bb4v9vj) ([raw file](https://github.com/pyomeca/bioptim/blob/e5433e6691a4f592c3928d769f9ec38da46581f0/bioptim/dynamics/integrator.py#L529)):*
> ```Python
>     """
>     Numerical integration using trapezoidal method.
>     Not that it is only possible to have one step using trapezoidal.
> ```

Explain somehow this is implicit integration
___
*[`bioptim/dynamics/ode_solver.py` line 282 at r1](https://reviewable.io/reviews/pyomeca/bioptim/738#-NavkRbI3l0jXplU3VC2:-NavkRbI3l0jXplU3VC3:b-1k3v9s) ([raw file](https://github.com/pyomeca/bioptim/blob/e5433e6691a4f592c3928d769f9ec38da46581f0/bioptim/dynamics/ode_solver.py#L282)):*
> ```Python
>             #                        "ControlType.CONSTANT_WITH_LAST_NODE or ControlType.LINEAR_CONTINUOUS instead")
>             # if ocp.assume_phase_dynamics is True:
>             #     raise RuntimeError("Trapezoidal integration cannot be used with assume_phase_dynamics = True")
> ```

no need

**Review by pariterre — COMMENTED** [review]
Can you add a test on this ;)

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/738#-:-Navk_tU4ORVsUcujzfr:b-9p2ayf)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/738)* status: all files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/integrator.py` line 529 at r1](https://reviewable.io/reviews/pyomeca/bioptim/738#-NavkBgpARY3ND036ART:-Navrbrf7trXPcZNq424:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/e5433e6691a4f592c3928d769f9ec38da46581f0/bioptim/dynamics/integrator.py#L529)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Explain somehow this is implicit integration
</blockquote></details>

Done.
___
*[`bioptim/dynamics/ode_solver.py` line 282 at r1](https://reviewable.io/reviews/pyomeca/bioptim/738#-NavkRbI3l0jXplU3VC2:-Navri6GBQgZKjV_aQ9p:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/e5433e6691a4f592c3928d769f9ec38da46581f0/bioptim/dynamics/ode_solver.py#L282)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

no need
</blockquote></details>

Done.

**Comment by EveCharbie** [comment]
Just have to add a test + wait for tests to pass.

**Comment by EveCharbie** [comment]
@pariterre should be good :)

**Pull request merged**
