### PR TITLE
Muscle implicit dynamics

### PR DESCRIPTION
**Pull request by aceglia**
No handle the fatigue and the activation dynamics.

---
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/459)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/459)* status: all files reviewed, 2 unresolved discussions (waiting on @aceglia)

___
*[`bioptim/examples/acados/pendulum.py` line 116 at r1](https://reviewable.io/reviews/pyomeca/bioptim/459#-N0fBsP750qVcV-ruzvY:-N0fBsP750qVcV-ruzvZ:b-od40dy) ([raw file](https://github.com/pyomeca/bioptim/blob/5490a8cccfddf1001b6aad8124479d4e95c6b8fb/bioptim/examples/acados/pendulum.py#L116)):*
> ```Python
> 
>     # --- Show results --- #
>     sol.print_cost()
> ```

Is there a reason to showcase only print_cost?
___
*[`bioptim/interfaces/solver_options.py` line 569 at r1](https://reviewable.io/reviews/pyomeca/bioptim/459#-N0fCA1mC00QNRdv50Pa:-N0fCA1mC00QNRdv50Pb:b-s1ym6r) ([raw file](https://github.com/pyomeca/bioptim/blob/5490a8cccfddf1001b6aad8124479d4e95c6b8fb/bioptim/interfaces/solver_options.py#L569)):*
> ```Python
>             self.set_has_tolerance_changed(True)
> 
>         def set_convergence_tolerance(self, val):
> ```

`val: Union[float, int, list, tuple]`
Please add documentation for this method

**Review by aceglia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/459)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/acados/pendulum.py` line 116 at r1](https://reviewable.io/reviews/pyomeca/bioptim/459#-N0fBsP750qVcV-ruzvY:-N0fFoICCvVYngJDsfQi:b-19q1xa) ([raw file](https://github.com/pyomeca/bioptim/blob/5490a8cccfddf1001b6aad8124479d4e95c6b8fb/bioptim/examples/acados/pendulum.py#L116)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is there a reason to showcase only print_cost?
</blockquote></details>

there was a sol.print() before, to make the example work I simply replaced it with a sol.print_cost(). No deeper reason. 
___
*[`bioptim/interfaces/solver_options.py` line 569 at r1](https://reviewable.io/reviews/pyomeca/bioptim/459#-N0fCA1mC00QNRdv50Pa:-N0fFN9h9QL5q9pG-Toy:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/5490a8cccfddf1001b6aad8124479d4e95c6b8fb/bioptim/interfaces/solver_options.py#L569)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`val: Union[float, int, list, tuple]`
Please add documentation for this method
</blockquote></details>

Done.

**Comment by aceglia** [comment]
@pariterre tests ok!

**Review by pariterre — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/459)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aceglia)

**Pull request merged**
