### PR TITLE
Selection Mapping (to simplify BiMapping of variables call)

### PR DESCRIPTION
**Pull request by lsechoir**
### All Submissions:

* [ x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ x] Have you opened/linked the issue related to your pull request? issue #389
* [x ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x ] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/619)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/619)* status: all files reviewed, 8 unresolved discussions (waiting on @lsechoir)

___
*[`bioptim/examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle_excitations.py` line 35 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzzB0U8goTgPQ7vI7c:-NOzzB0U8goTgPQ7vI7d:b5cjzuf) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle_excitations.py#L35)):*
> ```Python
>     activation_min, activation_max, activation_init = 0, 1, 0.5
>     dof_mapping = BiMappingList()
>     # dof_mapping.add("tau", [None, None, None, 0], [3])
> ```

Keep this as an example, but do not put it in comment (chose from in the input parameters)
___
*[`bioptim/examples/symmetrical_torque_driven_ocp/symmetry_by_mapping.py` line 71 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzyOjE03gvlVxVSZHY:-NOzyOjE03gvlVxVSZHZ:b5cjzuf) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/examples/symmetrical_torque_driven_ocp/symmetry_by_mapping.py#L71)):*
> ```Python
>     tau_min, tau_max, tau_init = -100, 100, 0
>     dof_mappings = BiMappingList()
>     # dof_mappings.add("q", to_second=[0, 1, None, 2, 2], to_first=[0, 1, 3], oppose_to_second=4)
> ```

Keep this as an example, but do not put it in comment (chose from in the input parameters)



_Code quote:_
```Python
# dof_mappings.add("q", to_second=[0, 1, None, 2, 2], to_first=[0, 1, 3], oppose_to_second=4
```
___
*[`bioptim/misc/mapping.py` line 177 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzxR131gzuzLlGWkNE:-NOzxR131gzuzLlGWkNF:b8e9ner) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/misc/mapping.py#L177)):*
> ```Python
>     """
> 
>     def __init__(self, nb_dof: int = None, list_kept_dof: list[int] = None, dependant_dof: list = None, **params):
> ```

SelectionMapping(
	nb_elements=bio_model.nb_dof, 
	independent_indices=(0, 1, 3), 
	dependencies=(
		Dependency(dependent_index=4, reference_index=3, factor=-1),
	)
)



_Suggestion:_
```Python
__init__(self, nb_elements: int = None, independent_indices: tuple[int] = None, dependencies: tuple[Dependency, ...] = None, **params):
```
___
*[`bioptim/misc/mapping.py` line 179 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzysAY-ATkHO4D9v8C:-NOzysAY-ATkHO4D9v8D:bl943st) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/misc/mapping.py#L179)):*
> ```Python
>     def __init__(self, nb_dof: int = None, list_kept_dof: list[int] = None, dependant_dof: list = None, **params):
>         """
>         Parameters :
> ```

Please use numpy doc



_Code quote:_
```Python
Parameters :
```
___
*[`bioptim/misc/mapping.py` line 183 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzy0UADHbN031C-1Oy:-NOzy0UADHbN031C-1Oz:b-r4oxqi) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/misc/mapping.py#L183)):*
> ```Python
>         nb_dof: int
>             The number of dof in the model
>         list_kept_dof: list
> ```

Prefer tuple whenever possible



_Code quote:_
```Python
list
```
___
*[`bioptim/misc/mapping.py` line 250 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzyiVi0su8Ehfbq-yj:-NOzyiVi0su8Ehfbq-yk:b5cluh1) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/misc/mapping.py#L250)):*
> ```Python
>                 matrix[i] = int(abs(first[i]) - 1)
> 
>         def build_to_second(x, u):
> ```

Add docstring
___
*[`bioptim/misc/mapping.py` line 256 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzyfKo4-W5PaMjG-0E:-NOzyfKo4-W5PaMjG-0F:b-kp98g9) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/misc/mapping.py#L256)):*
> ```Python
>                         x[i] = j
>                 # if x[i] is not None:
>                 #    if x[i] < 0:
> ```

Clean up



_Code quote:_
```Python
                # if x[i] is not None:
                #    if x[i] < 0:
                #    oppose.append(i)
```
___
*[`bioptim/misc/mapping.py` line 275 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzy_Co0cZ_3lt7LNeO:-NOzy_Co0cZ_3lt7LNeP:b-aa5nwy) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/misc/mapping.py#L275)):*
> ```Python
> 
>         to_second = build_to_second(matrix, list_kept_dof)
>         # to_second_bis=build_vector_mapping(nb_dof=nb_dof, list_kept_dof=list_kept_dof)
> ```

Is this line useful?

**Review by lsechoir — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/619)* status: all files reviewed, 8 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle_excitations.py` line 35 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzzB0U8goTgPQ7vI7c:-NPJJG1n0_NQ_WGkFB5D:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle_excitations.py#L35)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Keep this as an example, but do not put it in comment (chose from in the input parameters)
</blockquote></details>

Done.
___
*[`bioptim/examples/symmetrical_torque_driven_ocp/symmetry_by_mapping.py` line 71 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzyOjE03gvlVxVSZHY:-NPJJcXTCh2CxHZFyOZI:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/examples/symmetrical_torque_driven_ocp/symmetry_by_mapping.py#L71)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Keep this as an example, but do not put it in comment (chose from in the input parameters)
</blockquote></details>

Done.
___
*[`bioptim/misc/mapping.py` line 179 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzysAY-ATkHO4D9v8C:-NPJiSOI-CqqLxglQfWE:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/misc/mapping.py#L179)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please use numpy doc
</blockquote></details>

Done.
___
*[`bioptim/misc/mapping.py` line 183 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzy0UADHbN031C-1Oy:-NPJiTe_27ojl7yKWWNt:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/misc/mapping.py#L183)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Prefer tuple whenever possible
</blockquote></details>

Done.
___
*[`bioptim/misc/mapping.py` line 250 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzyiVi0su8Ehfbq-yj:-NPJiV8u8lSSIgXVkmrf:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/misc/mapping.py#L250)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Add docstring
</blockquote></details>

Done.
___
*[`bioptim/misc/mapping.py` line 256 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzyfKo4-W5PaMjG-0E:-NPJiVuD2vGNNqYvoHbb:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/misc/mapping.py#L256)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Clean up
</blockquote></details>

Done.
___
*[`bioptim/misc/mapping.py` line 275 at r2](https://reviewable.io/reviews/pyomeca/bioptim/619#-NOzy_Co0cZ_3lt7LNeO:-NPJicmM6qZtYAL9NaQC:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d2d2d214bf0d0752a8a6b7c9eaa90df2aaca334b/bioptim/misc/mapping.py#L275)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is this line useful?
</blockquote></details>

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/619)* status: all files reviewed, 15 unresolved discussions (waiting on @Ipuch and @lsechoir)

___
*[`README.md` line 1589 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYhWFC1nWBkw7eWjci:-NPYhWFC1nWBkw7eWjcj:b-yjdm1h) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/README.md#L1589)):*
> ```Markdown
> 
> The SelectionMapping is a subclass of BiMapping where you only have to precise the size of matrix a and the mapping to get
> the linked matrix b :`SelectionMapping(size(a), b_to_a)`
> ```

I don't understand this signature

SelectionMapping(size: int, b_to_a: tuple[int, int, bool])



_Code quote:_
```Markdown
SelectionMapping(size(a), b_to_a)
```
___
*[`bioptim/__init__.py` line 204 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYhuwp1EVAlkyHYpMg:-NPYhuwp1EVAlkyHYpMh:b-x475ss) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/bioptim/__init__.py#L204)):*
> ```Python
> from .misc.mapping import BiMappingList, BiMapping, Mapping, NodeMapping, NodeMappingList, SelectionMapping, Dependency
> 
> # from .misc.selection_mapping import SelectionMapping, Dependency
> ```

Do not leave unnecessary comments
___
*[`bioptim/examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle_excitations.py` line 35 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYi1Q65W5EZcdLgto4:-NPYi1Q65W5EZcdLgto5:b-6iug9j) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/bioptim/examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle_excitations.py#L35)):*
> ```Python
>     activation_min, activation_max, activation_init = 0, 1, 0.5
>     dof_mapping = BiMappingList()
>     # adds a bimapping to bimappinglist
> ```

Add a space before that line
___
*[`bioptim/examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle_excitations.py` line 40 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYiAM38wYFMKdnaPpp:-NPYiAM38wYFMKdnaPpq:be0ge24) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/bioptim/examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle_excitations.py#L40)):*
> ```Python
>     bimap = SelectionMapping(
>         nb_elements=bio_model.nb_dof,
>         independent_indices=(3),
> ```

(3,) ?



_Code quote:_
```Python
(3)
```
___
*[`bioptim/examples/symmetrical_torque_driven_ocp/symmetry_by_mapping.py` line 72 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYiU3m7zcP5uq3XK1t:-NPYiU3m7zcP5uq3XK1u:bf248t2) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/bioptim/examples/symmetrical_torque_driven_ocp/symmetry_by_mapping.py#L72)):*
> ```Python
>     tau_min, tau_max, tau_init = -100, 100, 0
>     dof_mappings = BiMappingList()
>     # adds a bimapping to bimappinglist
> ```

Add a line before this
___
*[`bioptim/misc/mapping.py` line 294 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYjWXn7SgGusSjUd0B:-NPYjWXn7SgGusSjUd0C:b-7szmih) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/bioptim/misc/mapping.py#L294)):*
> ```Python
>     Mapping of two index sets according to the indexes that are independent
> 
>     Attributes
> ```

These are not attributes specific to SelectionMapping



_Code quote:_
```Python
 Attributes
```
___
*[`bioptim/misc/mapping.py` line 301 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYj6bT62E6HgU0YRTQ:-NPYj6bUAQEASKueHJg3:b-2jwa7k) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/bioptim/misc/mapping.py#L301)):*
> ```Python
>         The mapping that links the second variable to the first
>     oppose_to_second : int | list
>         Index to multiply by -1 of the to_second mapping
> ```

Update this



_Code quote:_
```Python
    Attributes
    ----------
    to_second: Mapping
        The mapping that links the first variable to the second
    to_first: Mapping
        The mapping that links the second variable to the first
    oppose_to_second : int | list
        Index to multiply by -1 of the to_second mapping
```
___
*[`bioptim/misc/mapping.py` line 316 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYjBGR5Ghng_X8uyyH:-NPYjBGR5Ghng_X8uyyI:b-hxstbq) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/bioptim/misc/mapping.py#L316)):*
> ```Python
>         ----------
>         nb_elements : int
>             the number of elements, such as the number of dof in a model
> ```

Please starts sentences with a capital letters



_Code quote:_
```Python
the
```
___
*[`bioptim/misc/mapping.py` line 321 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYjIjw8EFmhzcULl-D:-NPYjIjw8EFmhzcULl-E:b-hhshpq) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/bioptim/misc/mapping.py#L321)):*
> ```Python
>         dependencies : Dependency class
>             contains the dependencies of the elements between them and the factor
>         they are multiplied by if needed,only 1 or -1 is acceptable for now
> ```

make sure you indent properly
___
*[`bioptim/misc/mapping.py` line 322 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYjHwc5BOCY8zvstcy:-NPYjHwc5BOCY8zvstcz:ba3dfna) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/bioptim/misc/mapping.py#L322)):*
> ```Python
>             contains the dependencies of the elements between them and the factor
>         they are multiplied by if needed,only 1 or -1 is acceptable for now
>         params
> ```

Remove?



_Code quote:_
```Python
params
```
___
*[`bioptim/misc/mapping.py` line 327 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYjRr68KtOnlOl_Qb5:-NPYjRr68KtOnlOl_Qb6:b7uuxmf) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/bioptim/misc/mapping.py#L327)):*
> ```Python
>         -------
>         build_to_second(dependency_matrix: list, independent_indices: list) -> list
>             build the to_second vector used in BiMapping
> ```

This does not make sense in a method docstring



_Code quote:_
```Python
        Methods
        -------
        build_to_second(dependency_matrix: list, independent_indices: list) -> list
            build the to_second vector used in BiMapping
```
___
*[`bioptim/misc/mapping.py` line 402 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYk-Q577dq2XTBNsSJ:-NPYk-Q577dq2XTBNsSK:b-mjcr2r) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/bioptim/misc/mapping.py#L402)):*
> ```Python
>                     if dependency_matrix[i] == independent_indices[j]:
>                         dependency_matrix[i] = j
>             return dependency_matrix
> ```

This could be a static protected method (note the "_" before the name of the method):

```
@staticmethod
def _build_to_second(...):
    ...
````



_Code quote:_
```Python
        def build_to_second(dependency_matrix: list, independent_indices: list):
            """
            Build the to_second vector used in BiMapping thanks to the dependency matrix of the elements in the system
            and the vector of independent indices

            Parameters
            ----------
            dependency_matrix : list
                the matrix of dependencies
            independent_indices : list
                the list of indexes of the independent elements in the system

            Returns
            ----------
            the to_second usual vector in BiMapping

            """
            for i in range(len(dependency_matrix)):
                for j in range(len(independent_indices)):
                    if dependency_matrix[i] == independent_indices[j]:
                        dependency_matrix[i] = j
            return dependency_matrix
```
___
*[`bioptim/misc/selection_mapping.py` line 2 at r3](https://reviewable.io/reviews/pyomeca/bioptim/619#-NPYinz67P3qiAOHgF9F:-NPYinz67P3qiAOHgF9G:by97t53) ([raw file](https://github.com/pyomeca/bioptim/blob/ca52b6e2aa13871461d65bcaf83550f9aa2b8f46/bioptim/misc/selection_mapping.py#L2)):*
> ```Python
> import numpy as np
> from .mapping import BiMapping
> ```

Remove this file



_Code quote:_
```Python
from .mapping import BiMapping
```

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/619)* status: all files reviewed, 2 unresolved discussions (waiting on @Ipuch and @lsechoir)

___
*[`tests/test_mappings.py` line 41 at r4](https://reviewable.io/reviews/pyomeca/bioptim/619#-NQ6gt-G8yMo1RiEpD2J:-NQ6gt-G8yMo1RiEpD2K:btyie1t) ([raw file](https://github.com/pyomeca/bioptim/blob/e3e349078b34009ed480c2f0355132bd782013b2/tests/test_mappings.py#L41)):*
> ```Python
>     mapping = SelectionMapping(5, (0, 1, 3), (Dependency(4, 3),))
> 
>     np.testing.assert_almost_equal(len(mapping.to_first.map_idx), 3)
> ```

use 
`assert a == b` when comparing integer



_Code quote:_
```Python
np.test
```

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/619#-:-NQ6rZkY3n_VzrWpyjcI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Pull request merged**
