### PR TITLE
[WIP] Partial nodeMapping

### PR DESCRIPTION
**Pull request by lsechoir**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/616)

### CODE REVIEW

**Comment by EveCharbie** [comment]
I will follow up on the merge issues soon.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/616)* status: all files reviewed, 22 unresolved discussions (waiting on @lsechoir)

___
*[`TechOpt83_multi_model_boucle.py` line 47 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOA9DIoE_dg5eR7cHsG:-NOA9DIoE_dg5eR7cHsH:b-x6c2y8) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/TechOpt83_multi_model_boucle.py#L47)):*
> ```Python
> except ImportError:
>     print("No IPython.")
>     IPYTHON = False
> ```

Please use snake_case variables
___
*[`TechOpt83_multi_model_boucle.py` line 115 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOA9NJg7TnpE5uKXX6Q:-NOA9NJg7TnpE5uKXX6R:b-mf7vab) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/TechOpt83_multi_model_boucle.py#L115)):*
> ```Python
>     x_bounds.add(bounds=QAndQDotBounds(biorbd_model[9]))
> 
>     # Pour la lisibilite
> ```

Please make sure you code in english
___
*[`TechOpt83_multi_model_boucle.py` line 116 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOA9SIv7s9cyMXuC5aN:-NOA9SIv7s9cyMXuC5aO:bqmg62t) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/TechOpt83_multi_model_boucle.py#L116)):*
> ```Python
> 
>     # Pour la lisibilite
>     DEBUT, MILIEU, FIN = 0, 1, 2
> ```

Please use Enum for this kind of variables (and snake_case)
___
*[`TechOpt83_multi_model_boucle.py` line 120 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOA9bno0QwmgkRgiPbd:-NOA9bno0QwmgkRgiPbe:b-ncolva) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/TechOpt83_multi_model_boucle.py#L120)):*
> ```Python
>     #
>     # Contraintes de position: PHASE 0 la montee en carpe
>     #
> ```

Please do not multiline comments apart for very specific reasons
Most of the time, these comments can be replaced by a function call



_Code quote:_
```Python
    #
    # Contraintes de position: PHASE 0 la montee en carpe
    #
```
___
*[`TechOpt83_multi_model_boucle.py` line 729 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAA96TAMJYW0C8taoI:-NOAA96TAMJYW0C8taoJ:b-ua32lj) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/TechOpt83_multi_model_boucle.py#L729)):*
> ```Python
>     borne_inf = (x_bounds[5].min[fancy_names_index["vX"]:fancy_names_index["vZ"] + 1, DEBUT] + np.cross(r,
>                                                                                                         x_bounds[5].min[
>                                                                                                         fancy_names_index[
> ```

Don't forget to black the code at some point ;)



_Code quote:_
```Python
    borne_inf = (x_bounds[5].min[fancy_names_index["vX"]:fancy_names_index["vZ"] + 1, DEBUT] + np.cross(r,
                                                                                                        x_bounds[5].min[
                                                                                                        fancy_names_index[
                                                                                                            "vXrot"]:
                                                                                                        fancy_names_index[
                                                                                                            "vZrot"] + 1,
                                                                                                        DEBUT]))[0]
```
___
*[`TechOpt83_multi_model_boucle.py` line 1312 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAAHiN31eB-h4MhJU8:-NOAAHiN31eB-h4MhJU9:b-x6c2y8) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/TechOpt83_multi_model_boucle.py#L1312)):*
> ```Python
>                      biorbd.Model(biorbd_model_path_JeCh),
>                      biorbd.Model(biorbd_model_path_JeCh),
>                      biorbd.Model(biorbd_model_path_JeCh),
> ```

Please use snake_case variables



_Code quote:_
```Python
    biorbd_model = ( biorbd.Model(biorbd_model_path_AuJo),
                     biorbd.Model(biorbd_model_path_AuJo),
                     biorbd.Model(biorbd_model_path_AuJo),
                     biorbd.Model(biorbd_model_path_AuJo),
                     biorbd.Model(biorbd_model_path_AuJo),
                     biorbd.Model(biorbd_model_path_JeCh),
                     biorbd.Model(biorbd_model_path_JeCh),
                     biorbd.Model(biorbd_model_path_JeCh),
                     biorbd.Model(biorbd_model_path_JeCh),
                     biorbd.Model(biorbd_model_path_JeCh),
```
___
*[`TechOpt83_multi_model_boucle.py` line 1450 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAAZIe1N1mhPYTpksh:-NOAAZIe1N1mhPYTpksi:b-vwpim9) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/TechOpt83_multi_model_boucle.py#L1450)):*
> ```Python
>     #u_init.add([qddot_joints_init] * nb_qddot_joints)
>    # u_init.add([qddot_joints_init] * nb_qddot_joints)
>     #u_init.add([qddot_joints_init] * nb_qddot_joints)
> ```

Why not using a for loop?



_Code quote:_
```Python
    # Dynamics
    dynamics = DynamicsList()
    dynamics.add(DynamicsFcn.JOINTS_ACCELERATION_DRIVEN)
    dynamics.add(DynamicsFcn.JOINTS_ACCELERATION_DRIVEN)
    dynamics.add(DynamicsFcn.JOINTS_ACCELERATION_DRIVEN)
    dynamics.add(DynamicsFcn.JOINTS_ACCELERATION_DRIVEN)
    dynamics.add(DynamicsFcn.JOINTS_ACCELERATION_DRIVEN)
    dynamics.add(DynamicsFcn.JOINTS_ACCELERATION_DRIVEN)
    dynamics.add(DynamicsFcn.JOINTS_ACCELERATION_DRIVEN)
    dynamics.add(DynamicsFcn.JOINTS_ACCELERATION_DRIVEN)
    dynamics.add(DynamicsFcn.JOINTS_ACCELERATION_DRIVEN)
    dynamics.add(DynamicsFcn.JOINTS_ACCELERATION_DRIVEN)

    x_bounds = set_x_bounds(biorbd_model, fancy_names_index, final_time)

    qddot_joints_min, qddot_joints_max, qddot_joints_init = -500, 500, 0
    u_bounds = BoundsList()
    u_bounds.add([qddot_joints_min] * nb_qddot_joints, [qddot_joints_max] * nb_qddot_joints)
    u_bounds.add([qddot_joints_min] * nb_qddot_joints, [qddot_joints_max] * nb_qddot_joints)
    u_bounds.add([qddot_joints_min] * nb_qddot_joints, [qddot_joints_max] * nb_qddot_joints)
    u_bounds.add([qddot_joints_min] * nb_qddot_joints, [qddot_joints_max] * nb_qddot_joints)
    u_bounds.add([qddot_joints_min] * nb_qddot_joints, [qddot_joints_max] * nb_qddot_joints)
    u_bounds.add([qddot_joints_min] * nb_qddot_joints, [qddot_joints_max] * nb_qddot_joints)
    u_bounds.add([qddot_joints_min] * nb_qddot_joints, [qddot_joints_max] * nb_qddot_joints)
    u_bounds.add([qddot_joints_min] * nb_qddot_joints, [qddot_joints_max] * nb_qddot_joints)
    u_bounds.add([qddot_joints_min] * nb_qddot_joints, [qddot_joints_max] * nb_qddot_joints)
    u_bounds.add([qddot_joints_min] * nb_qddot_joints, [qddot_joints_max] * nb_qddot_joints)

    u_init = InitialGuessList()
    u_init.add([qddot_joints_init] * nb_qddot_joints)
    u_init.add([qddot_joints_init] * nb_qddot_joints)
    u_init.add([qddot_joints_init] * nb_qddot_joints)
    u_init.add([qddot_joints_init] * nb_qddot_joints)
    u_init.add([qddot_joints_init] * nb_qddot_joints)
   # u_init.add([qddot_joints_init] * nb_qddot_joints)
   # u_init.add([qddot_joints_init] * nb_qddot_joints)
    #u_init.add([qddot_joints_init] * nb_qddot_joints)
   # u_init.add([qddot_joints_init] * nb_qddot_joints)
    #u_init.add([qddot_joints_init] * nb_qddot_joints)
```
___
*[`TechOpt83_multi_model_boucle.py` line 1503 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAAcXx3v2DIoydRp9k:-NOAAcXx3v2DIoydRp9l:biu4m50) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/TechOpt83_multi_model_boucle.py#L1503)):*
> ```Python
>     model_path_JeCh = "Models/JeCh_TechOpt83.bioMod"
>     n_threads = 4
>     print_ocp_FLAG = False  # True.
> ```

There is no point specifying that it is a FLAG (also not in capital letters). `should_print_ocp` is more explicit on your intend



_Code quote:_
```Python
print_ocp_FLAG = False  # True.
```
___
*[`TechOpt83_multi_model_boucle.py` line 1505 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAAryR9walat7CtGHw:-NOAAryR9walat7CtGHx:b-g3mmj0) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/TechOpt83_multi_model_boucle.py#L1505)):*
> ```Python
>     print_ocp_FLAG = False  # True.
> 
>     show_online_FLAG = False  # True
> ```

`should_show_online` Also, there is no point to keep the comment #True next to it 



_Code quote:_
```Python
show_online_FLAG = False  # True
```
___
*[`TechOpt83_multi_model_boucle.py` line 1506 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAB1NH-B5cIJf9w_lh:-NOAB1NH-B5cIJf9w_li:bb7od0r) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/TechOpt83_multi_model_boucle.py#L1506)):*
> ```Python
> 
>     show_online_FLAG = False  # True
>     HSL_FLAG = True
> ```

same



_Code quote:_
```Python
HSL_FLAG = True
```
___
*[`TechOpt83_multi_model_boucle.py` line 1507 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAB41WEy2KpZZHA-NG:-NOAB41WEy2KpZZHA-NH:bb7od0r) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/TechOpt83_multi_model_boucle.py#L1507)):*
> ```Python
>     show_online_FLAG = False  # True
>     HSL_FLAG = True
>     save_sol_FLAG = True
> ```

same



_Code quote:_
```Python
 save_sol_FLAG = True
```
___
*[`bioptim/interfaces/interface_utils.py` line 47 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOABGt_4E2DJF-V_zBs:-NOABGt_4E2DJF-V_zBt:bo4h8c1) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/bioptim/interfaces/interface_utils.py#L47)):*
> ```Python
>         interface.online_optim(interface.ocp, interface.opts.show_options)
> 
>     interface.sqp_nlp = {"x": interface.ocp.v.vector, "f": sum1(all_objectives), "g": all_g} # all_g : 2696  x : 2712
> ```

What is that comment for?



_Code quote:_
```Python
# all_g : 2696  x : 2712
```
___
*[`bioptim/interfaces/interface_utils.py` line 136 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOABMPf1--C2od4R2lF:-NOABMPf1--C2od4R2lG:b53iayb) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/bioptim/interfaces/interface_utils.py#L136)):*
> ```Python
>             print(g)
>             for _ in g.node_idx:
>                 print(g.node_idx)
> ```

Please do not push print statement in the code base



_Code quote:_
```Python
        print(interface.get_all_penalties(nlp, nlp.g_internal))
        print(interface.get_all_penalties(nlp, nlp.g_internal).shape)
        print(interface.get_all_penalties(nlp, nlp.g_internal)[0])
        for g in nlp.g_internal:
            print(g)
            for _ in g.node_idx:
                print(g.node_idx)
```
___
*[`bioptim/misc/mapping.py` line 254 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOABS3G9IVn15zKFTmU:-NOABS3G9IVn15zKFTmV:b-usw8oe) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/bioptim/misc/mapping.py#L254)):*
> ```Python
>         phase_pre: int = None,
>         phase_post: int = None,
>         index : list = [],
> ```

This is a common Python bug. You should never instanciate a list in the parameter list as it is declared at the function loading point.
Consider the following code: 
```python
class MyIllClass:
    def __init__(self, my_wrong_list: list[int, ...] = []):
        self.ill_list = my_wrong_list


my_ill_instance = MyIllClass()
my_ill_instance.ill_list.append(2)

my_second_instance = MyIllClass()
print(my_second_instance.ill_list)
```
If you expected the `ill_list` of `my_second_instance` to be empty, you'd be wrong. It is filled with the `2` of `my_ill_instance` because they share the same list object.

The solution is to declare the empty list as a None and to assign a new list inside the function if it is None, as such:
```python
class MyIllClass:
    def __init__(self, my_wrong_list: list[int, ...] = None):
        self.ill_list = my_wrong_list if my_wrong_list is not None else []


my_ill_instance = MyIllClass()
my_ill_instance.ill_list.append(2)

my_second_instance = MyIllClass()
print(my_second_instance.ill_list)
```
Now the `ill_list` of `my_second_instance` is empty as expected. 

P.S. please note that since Python 3.10, we can specify what list it is (for instance list[int, ...], would be a list of unknown number of int. Also, please prefer tuple which are not prone to the error I just described here. Therefore, my suggestion is to change index to: 
`index: tuple[int, ...] = ()`
or to use the None trick
`index: list[int, ...] = None  # with somewhere in the function: index = index if index is not None else []`



_Code quote:_
```Python
list = [],
```
___
*[`bioptim/misc/mapping.py` line 278 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOADoD31vT1rz7avdv-:-NOADoD31vT1rz7avdv0:b-a41yxz) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/bioptim/misc/mapping.py#L278)):*
> ```Python
>             self.index = index
>         else :
>             self.index = []
> ```

Please avoid else statement whenever possible or use ternary statements. One solution could be:
```python
self.index = []
if index is not None:
    self.index = index
```
P.S. Do not rely on `if x:` unless you are completely sure noone will send `np.array` as testing like this will crash. 

The other solution would be:
```python
self.index = index if index is not None else []
```

That said, if `index` is a tuple instead of a list, you can simply do: `self.index = index`



_Code quote:_
```Python
        if index :
            self.index = index
        else :
            self.index = []
```
___
*[`bioptim/optimization/optimization_vector.py` line 110 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAEq7M77KXqx2Fs9hl:-NOAEq7M77KXqx2Fs9hm:b-ayanzi) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/bioptim/optimization/optimization_vector.py#L110)):*
> ```Python
>         #######
> 
>         # si on veut toutes les variables sans les doublons (mapping)
> ```

Please do not leave french in comment or in variable names
___
*[`bioptim/optimization/optimization_vector.py` line 120 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAF6ZO5uoZ_0AgFwX4:-NOAF6ZO5uoZ_0AgFwX5:b-i0qgd2) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/bioptim/optimization/optimization_vector.py#L120)):*
> ```Python
>             index_u = nlp.index_u
>             index_x = [6,7,8,9,10,11,12,13,14,15,22,23,24,25,26,27,28,29,30,31] # indices des degres de liberté qui son mappés
>             index_u = [0,1,2,3,4,5,6,7,8,9]
> ```

Please do not push this content in the code base if you have an ongoing review



_Code quote:_
```Python
            index_x = [6,7,8,9,10,11,12,13,14,15,22,23,24,25,26,27,28,29,30,31] # indices des degres de liberté qui son mappés
            index_u = [0,1,2,3,4,5,6,7,8,9]
```
___
*[`bioptim/optimization/optimization_vector.py` line 453 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAFHJw1_rqWaPqJuEb:-NOAFHJw1_rqWaPqJuEc:b-o3ikbx) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/bioptim/optimization/optimization_vector.py#L453)):*
> ```Python
> 
>             index_u = nlp.index_u
>             index_u = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
> ```

Please do not push this kind of content if you have an active pull-request



_Code quote:_
```Python
            index_x = nlp.index_x
            index_x = [6,7,8,9,10,11,12,13,14,15,22,23,24,25,26,27,28,29,30,31] # indices des degres de liberté qui son mappés

            index_u = nlp.index_u
            index_u = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```
___
*[`bioptim/optimization/optimization_vector.py` line 577 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAFV2_BL6lb3Nplak4:-NOAFV2_BL6lb3Nplak5:b-defasm) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/bioptim/optimization/optimization_vector.py#L577)):*
> ```Python
> 
>            # = u[nlp.phase_idx]
>             #self.x[nlp.phase_idx] = x[nlp.phase_idx]  # pas de vertcat car on a besoin des indices
> ```

I just write it here, but it is useless to comment these use block. Please just remove them, and bring them back using git if needed. It makes things impossible to review otherwise



_Code quote:_
```Python
                                   #if liberty > 0:
                                     #   vertcat(u[nlp.phase_idx][0], u[nlp.phase_idx][1])
                            # else:
                                  #  u[nlp.phase_idx][k].append(
                                   #     nlp.cx.sym("U_" + str(nlp.phase_idx) + "_" + str(k) + '_' + str(liberty), 1, 1)
                                  #  )
                                  #  if len(index_u) != nlp.controls.shape:
                                       # self.u[nlp.phase_idx][k].append(u[nlp.phase_idx][k][liberty])
                                  #  self.u[nlp.phase_idx][k] = vertcat(self.u[nlp.phase_idx][k][0],self.u[nlp.phase_idx][k][1])
                                    #if liberty > 0:
                                     #   vertcat(u[nlp.phase_idx][k][0], u[nlp.phase_idx][k][1])

                     #   self.u[nlp.phase_idx][k] = vertcat(*self.u[nlp.phase_idx][k])

                    #u[nlp.phase_idx][k] = vertcat(*[z for z in u[nlp.phase_idx][k]])
                #x[nlp.phase_idx][k] = vertcat(*[z for z in x[nlp.phase_idx][k]]) # vertcat(*x[nlp.phase_idx][k])

           # = u[nlp.phase_idx]
            #self.x[nlp.phase_idx] = x[nlp.phase_idx]  # pas de vertcat car on a besoin des indices
```
___
*[`bioptim/optimization/optimization_vector.py` line 658 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAFkZw0bTzrq49TdUG:-NOAFkZw0bTzrq49TdUH:b714lnu) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/bioptim/optimization/optimization_vector.py#L658)):*
> ```Python
>                 nlp.x_bounds.check_and_adjust_dimensions(nlp.states.shape, nlp.ns)
>             else :
>                 nlp.x_bounds.check_and_adjust_dimensions(nlp.states.shape, nlp.ns)
> ```

You can simply remove the if...



_Code quote:_
```Python
            else :
                nlp.x_bounds.check_and_adjust_dimensions(nlp.states.shape, nlp.ns)
```
___
*[`bioptim/optimization/optimization_vector.py` line 777 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAFpR340v3L_yyFvww:-NOAFpR340v3L_yyFvwx:b-e2asw9) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/bioptim/optimization/optimization_vector.py#L777)):*
> ```Python
> 
>         ocp = self.ocp
>         index_roots_x = [0,1,2,3,4,5,16,17,18,19,20,21] #indices des nouvelles variables /non mappées
> ```

Please do not push this kind of content with an active pull-request



_Code quote:_
```Python
        index_roots_x = [0,1,2,3,4,5,16,17,18,19,20,21] #indices des nouvelles variables /non mappées
        index_roots_u = []
```
___
*[`bioptim/optimization/optimization_vector.py` line 863 at r1](https://reviewable.io/reviews/pyomeca/bioptim/616#-NOAFvih5-vk7fJnU4Pi:-NOAFvih5-vk7fJnU4Pj:b-60s05p) ([raw file](https://github.com/pyomeca/bioptim/blob/07854486667327faa52be67c806a8aad94f78dc7/bioptim/optimization/optimization_vector.py#L863)):*
> ```Python
> 
>                 #probleme ici sur self.x_init
>                 # il y a nlp.ns+1 elements pour chaque phase, il faut pareil partout
> ```

Please do not leave french comment



_Code quote:_
```Python
                #probleme ici sur self.x_init
                # il y a nlp.ns+1 elements pour chaque phase, il faut pareil partout
```

**Comment by EveCharbie** [comment]
We only opened the PR so that I can work on it. Please do not spend time commenting on it since the code will change dramatically until thursday.

**Comment by pariterre** [comment]
@EveCharbie 
Should we keep this open?

**Comment by EveCharbie** [comment]
You can close it, I will not have time to finish this in the next month :(

**Pull request closed without merging**
