### PR TITLE
[RTR] Fix sol.integrate shooting.single continuity

### PR DESCRIPTION
**Pull request by Kev1CO**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/859)

### CODE REVIEW

**Comment by Kev1CO** [comment]
Last blocking test are the dimension comparation between sol.integrate and sol.stepwise_time because sol.stepwise_time as still redundant nodes compared to sol.integrate.
Should I give an argument to sol.stepwise_time(remove_redundant=True) and adjust the dimension here or in the tests compare time and states from sol.integrate(return_time=True)?

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/859)* status: all files reviewed, 9 unresolved discussions (waiting on @Kev1CO)

___
*[`bioptim/interfaces/solve_ivp_interface.py` line 51 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshyZ5v7XbL_-1ldacB:-NshyZ5w4Hu7GBezGRN6:b1ondt6) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/interfaces/solve_ivp_interface.py#L51)):*
> ```Python
>     y = []
>     control_type = nlp.control_type
>     integration_time_vector = []
> ```

All the changes are no longer needed anymore
___
*[`bioptim/optimization/solution/solution.py` line 240 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshnzO_53YK5c-Yil1J:-NshnzO_53YK5c-Yil1K:bsdzp66) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L240)):*
> ```Python
>                 [
>                     len(s) != len(all_ns) if p != 3 and len(sol[p + 1].keys()) != 0 else False
>                     for p, s in enumerate(sol[:1])
> ```

Remove the list comprehension so it is easier to read `is_right_size`
___
*[`bioptim/optimization/solution/solution.py` line 300 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-Nshnun65vW0xEqPxZxC:-Nshnun71lJL7q8tErIl:bb71kmx) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L300)):*
> ```Python
>                     vector = np.concatenate((vector, np.repeat(ss[key].init, 1)[:, np.newaxis]))
>                     # TODO : ask pariterre about this modification (the previous version did not enable the parameters
>                     #  to be taken into consideration for each phase)
> ```

Okay
___
*[`bioptim/optimization/solution/solution.py` line 705 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshyEb3Cspf__AtiFQK:-NshyEb3Cspf__AtiFQL:b-63i4hp) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L705)):*
> ```Python
>         integrator: SolutionIntegrator = SolutionIntegrator.OCP,
>         to_merge: SolutionMerge | list[SolutionMerge] = None,
>         return_time: bool = False,
> ```

add `duplicated_times: bool = True`

Please add docstring

Please add `duplicated_times` in `stepwise_time`
___
*[`bioptim/optimization/solution/solution.py` line 755 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshrWEeARSOvgYpC1BJ:-NshrWEeARSOvgYpC1BK:be39fs9) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L755)):*
> ```Python
>                 out[p][key] = [None] * nlp.n_states_nodes
>                 for ns, sol_ns in enumerate(integrated_sol):
>                     out[p][key][ns] = sol_ns[nlp.states[key].index, :]
> ```

```python
        out[p] = {}
            for key in nlp.states.keys():
                out[p][key] = [None] * nlp.n_states_nodes
                for ns, sol_ns in enumerate(integrated_sol):
                    if duplicated_times:
                        out[p][key][ns] = sol_ns[nlp.states[key].index, :]
                    else:
                        out[p][key][ns] = sol_ns[nlp.states[key].index, :-1]
                        
        if to_merge:
            out = SolutionData.from_unscaled(self.ocp, out, "x").to_dict(to_merge=to_merge, scaled=False)

        if return_time:
            return self.stepwise_time(to_merge=to_merge, duplicated_times=duplicated_times), out
        else:
            return out if len(out) > 1 else out[0]
```
___
*[`bioptim/optimization/solution/solution.py` line 759 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshptQJEVaeSau1xI1c:-NshptQJEVaeSau1xI1d:b5j68r0) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L759)):*
> ```Python
>         if to_merge:
>             out = SolutionData.from_unscaled(self.ocp, out, "x").to_dict(to_merge=to_merge, scaled=False)
>             time_vector, out = self._remove_integrated_duplicates(time_vector, out, shooting_type, to_merge)
> ```

remove this method
___
*[`bioptim/optimization/solution/solution.py` line 759 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-Nshq89X8EK2-Ix2Rxdv:-Nshq89Y0p0hpNGVAtDt:b7unwim) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L759)):*
> ```Python
>         if to_merge:
>             out = SolutionData.from_unscaled(self.ocp, out, "x").to_dict(to_merge=to_merge, scaled=False)
>             time_vector, out = self._remove_integrated_duplicates(time_vector, out, shooting_type, to_merge)
> ```

add `if return_time` so it is not performed if time is not returned anyway
___
*[`bioptim/optimization/solution/solution.py` line 846 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshogUt7aY1ZK1IDSIl:-NshogUt7aY1ZK1IDSIm:b-s1u89p) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L846)):*
> ```Python
>             to_merge == SolutionMerge.NODES or SolutionMerge.NODES in to_merge
>         ):
>             if (isinstance(to_merge, list) and SolutionMerge.PHASES in to_merge) or to_merge == SolutionMerge.PHASES:
> ```

Remove the test `to_merge` isinstance but add: 

```
    if to_merge is None or isinstance(to_merge, SolutionMerge):  
        to_merge = [to_merge]
```
at the beggining of `integrate`


EDIT:
This method is probably useless
___
*[`bioptim/optimization/solution/solution.py` line 915 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshoK4C1AYsGRBMQd2-:-NshoK4C1AYsGRBMQd20:b-mpax0l) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L915)):*
> ```Python
>         unscaled: list = [None] * len(self.ocp.nlp)
>         for p, nlp in enumerate(self.ocp.nlp):
>             phase_times, integrated_sol = solve_ivp_interface(
> ```

solve_ivp_interface should not be returned anymore

**Comment by Kev1CO** [comment]
Do not know how to fix last failed tests

**Review by Kev1CO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/859)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/optimization/solution/solution.py` line 240 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshnzO_53YK5c-Yil1J:-NsmzobKEHmbgMszy4YB:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L240)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Remove the list comprehension so it is easier to read `is_right_size`
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 300 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-Nshnun65vW0xEqPxZxC:-Nsmzp6A0yMEBUN99Wq-:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L300)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Okay
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 705 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshyEb3Cspf__AtiFQK:-Nsmzpbv-p6C0XI-Jhaw:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L705)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

add `duplicated_times: bool = True`

Please add docstring

Please add `duplicated_times` in `stepwise_time`
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 755 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshrWEeARSOvgYpC1BJ:-NsmzqMVDGenV1zmFoNy:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L755)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

```python
        out[p] = {}
            for key in nlp.states.keys():
                out[p][key] = [None] * nlp.n_states_nodes
                for ns, sol_ns in enumerate(integrated_sol):
                    if duplicated_times:
                        out[p][key][ns] = sol_ns[nlp.states[key].index, :]
                    else:
                        out[p][key][ns] = sol_ns[nlp.states[key].index, :-1]
                        
        if to_merge:
            out = SolutionData.from_unscaled(self.ocp, out, "x").to_dict(to_merge=to_merge, scaled=False)

        if return_time:
            return self.stepwise_time(to_merge=to_merge, duplicated_times=duplicated_times), out
        else:
            return out if len(out) > 1 else out[0]
```
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 759 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshptQJEVaeSau1xI1c:-NsmzqkkCkHdyisQfCtT:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L759)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

remove this method
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 759 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-Nshq89X8EK2-Ix2Rxdv:-Nsmzr3d3kQpKn3j9VeT:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L759)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

add `if return_time` so it is not performed if time is not returned anyway
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 846 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshogUt7aY1ZK1IDSIl:-NsmzrRX3pHHvFKHPRrV:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L846)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Remove the test `to_merge` isinstance but add: 

```
    if to_merge is None or isinstance(to_merge, SolutionMerge):  
        to_merge = [to_merge]
```
at the beggining of `integrate`


EDIT:
This method is probably useless
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 915 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshoK4C1AYsGRBMQd2-:-Nsmzrv80Edi6MGiUJFJ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L915)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

solve_ivp_interface should not be returned anymore
</blockquote></details>

Done.
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 51 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshyZ5v7XbL_-1ldacB:-NsmzsSNCL9ptSxCTcjx:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/interfaces/solve_ivp_interface.py#L51)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

All the changes are no longer needed anymore
</blockquote></details>

Done.

**Comment by Kev1CO** [comment]
When returning time sol.integrate(return_time=True), should the time vector be concatenated in one array (array([0, 0.1, 0.2])) instead of keeping its initial shape of array([[0],
                                   [0.1],
                                   [0.2]])

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/859)* status: all files reviewed, 5 unresolved discussions (waiting on @Kev1CO)

___
*[`bioptim/optimization/solution/solution.py` line 705 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshyEb3Cspf__AtiFQK:-NsnGBc-0Yqa5yngPgGb:bl27xy8) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L705)):*
<details><summary><i>Previously, Kev1CO wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Docstring was not added
___
*[`bioptim/optimization/solution/solution.py` line 489 at r4](https://reviewable.io/reviews/pyomeca/bioptim/859#-NsnFzPsB53xgzje0gJ1:-NsnFzPsB53xgzje0gJ2:b2eki2y) ([raw file](https://github.com/pyomeca/bioptim/blob/e9cdff0940326bb27bd05ef050d78bfb3168ef77/bioptim/optimization/solution/solution.py#L489)):*
> ```Python
>             for i in range(len(times)):
>                 for j in range(len(times[i])):
>                     keep_condition = times[i][j].shape[0] == 1 and i == len(times) - 1
> ```

When does this happens?
___
*[`bioptim/optimization/solution/solution.py` line 765 at r4](https://reviewable.io/reviews/pyomeca/bioptim/859#-NsnGJfaBQDmI2I9wPtr:-NsnGJfb5V69gqB8bdL1:b-jovuup) ([raw file](https://github.com/pyomeca/bioptim/blob/e9cdff0940326bb27bd05ef050d78bfb3168ef77/bioptim/optimization/solution/solution.py#L765)):*
> ```Python
>                         out[p][key][ns] = sol_ns[nlp.states[key].index, :]
>                     else:
>                         duplicated_times_condition = p == len(self.ocp.nlp) - 1 and ns == nlp.ns
> ```

When is that not the case?
___
*[`tests/shard4/test_simulate.py` line 613 at r4](https://reviewable.io/reviews/pyomeca/bioptim/859#-NsnGsfP5p8jERYHZUNY:-NsnGsfP5p8jERYHZUNZ:bn6fkh) ([raw file](https://github.com/pyomeca/bioptim/blob/e9cdff0940326bb27bd05ef050d78bfb3168ef77/tests/shard4/test_simulate.py#L613)):*
> ```Python
>         "integrator": integrator,
>         "to_merge": [SolutionMerge.PHASES, SolutionMerge.NODES],
>     }
> ```

it works but this is a bit confusing.
just call `sol.integrate(shooting_type=shooting, integrator=integrator, to_merge=[SolutionMerge.PHASES, SolutionMerge.NODES], duplicated_times=False, return_time=True)`

**Review by Kev1CO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/859)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/optimization/solution/solution.py` line 705 at r2](https://reviewable.io/reviews/pyomeca/bioptim/859#-NshyEb3Cspf__AtiFQK:-NsnMZRf3i04ALA8hlfz:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/58ed59a9fc7fac95baca9eaea2a5978639d3c1fc/bioptim/optimization/solution/solution.py#L705)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Docstring was not added
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 489 at r4](https://reviewable.io/reviews/pyomeca/bioptim/859#-NsnFzPsB53xgzje0gJ1:-NsnKaHsEAoYxGfd0WKS:b-7zr61w) ([raw file](https://github.com/pyomeca/bioptim/blob/e9cdff0940326bb27bd05ef050d78bfb3168ef77/bioptim/optimization/solution/solution.py#L489)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

When does this happens?
</blockquote></details>

at last phase integration node
therefore, we can not remove it like other last node phases
___
*[`bioptim/optimization/solution/solution.py` line 765 at r4](https://reviewable.io/reviews/pyomeca/bioptim/859#-NsnGJfaBQDmI2I9wPtr:-NsnMgx_4ERVfbmEcyrV:bntav5t) ([raw file](https://github.com/pyomeca/bioptim/blob/e9cdff0940326bb27bd05ef050d78bfb3168ef77/bioptim/optimization/solution/solution.py#L765)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

When is that not the case?
</blockquote></details>

same than time duplicates
not removing last phase last node for each key
___
*[`tests/shard4/test_simulate.py` line 613 at r4](https://reviewable.io/reviews/pyomeca/bioptim/859#-NsnGsfP5p8jERYHZUNY:-NsnOEveDxr18xTtpmLZ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/e9cdff0940326bb27bd05ef050d78bfb3168ef77/tests/shard4/test_simulate.py#L613)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

it works but this is a bit confusing.
just call `sol.integrate(shooting_type=shooting, integrator=integrator, to_merge=[SolutionMerge.PHASES, SolutionMerge.NODES], duplicated_times=False, return_time=True)`
</blockquote></details>

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/859)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Kev1CO)

___
*[`bioptim/optimization/solution/solution.py` line 798 at r6](https://reviewable.io/reviews/pyomeca/bioptim/859#-NsnuyxqA00uWfyxnOoj:-NsnuyxqA00uWfyxnOok:b-7wa52b) ([raw file](https://github.com/pyomeca/bioptim/blob/448aafbb08e713395dfde871d798431e5768f960/bioptim/optimization/solution/solution.py#L798)):*
> ```Python
> 
>         if return_time:
>             time_vector = np.concatenate(self.stepwise_time(to_merge=to_merge, duplicated_times=duplicated_times))
> ```

This won't work for not merged values

**Review by Kev1CO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/859)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/optimization/solution/solution.py` line 798 at r6](https://reviewable.io/reviews/pyomeca/bioptim/859#-NsnuyxqA00uWfyxnOoj:-NsoO8lHDDSQwr_hjwih:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/448aafbb08e713395dfde871d798431e5768f960/bioptim/optimization/solution/solution.py#L798)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This won't work for not merged values
</blockquote></details>

Done.

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/859#-:-Nt2a9F11UQUZyrro4o1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Kev1CO)

**Pull request merged**
