### PR TITLE
Time vector returned by integrate

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
Issue #441
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

---
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/453)

### CODE REVIEW

**Comment by EveCharbie** [comment]
@pariterre  I think we are good :)

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/453)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

___
*[bioptim/optimization/solution.py, line 552 at r1](https://reviewable.io/reviews/pyomeca/bioptim/453#-MzQ2DOxDlrxwmS4q7bZ:-MzQ2DOxDlrxwmS4q7b_:b5jfghh) ([raw file](https://github.com/pyomeca/bioptim/blob/9e14a6c835622bb6a730d9033db9530467768b50/bioptim/optimization/solution.py#L552)):*
> ```Python
>         return out
> 
>     def generate_time_vector(
> ```

Is this supposed to be called by any users or internally? If it is any users, you can call the method: `get_time_vector` or `time_vector`. If it is the latter, please add a underscore before `_generate_time_vector`
___
*[bioptim/optimization/solution.py, line 718 at r1](https://reviewable.io/reviews/pyomeca/bioptim/453#-MzQ2v2b1TLDY7yyrpvx:-MzQ2v2b1TLDY7yyrpvy:b-bngjjd) ([raw file](https://github.com/pyomeca/bioptim/blob/9e14a6c835622bb6a730d9033db9530467768b50/bioptim/optimization/solution.py#L718)):*
> ```Python
>             raise ValueError(
>                 "The number of output states is different from the time vector for integration.There is a bug introduced "
>                 "by @EveCharbie, please report it"
> ```

This is not necessary but having test in the test suite would happily replaces this :)
You can tap into the test_solution and add the time vector over there. If you want to have your name in the code base, you can leave the check there :P



_Code quote:_
```Python
        if sum_states_len != len(out.time_vector):
            raise ValueError(
                "The number of output states is different from the time vector for integration.There is a bug introduced "
                "by @EveCharbie, please report it"
```

**Comment by EveCharbie** [comment]
@pariterre should be good this time :)

**Review by pariterre — CHANGES_REQUESTED** [review]
One last comment, and we should understand why your version of black do not match the one from AppVeyor... Are you on black-22.3.0  ?

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/453#-:-N-YP-2JC0zWdTl5LFEx:bbzik7b)* status: all files reviewed, 1 unresolved discussion (waiting on @EveCharbie)

___
*[bioptim/optimization/solution.py, line 453 at r2](https://reviewable.io/reviews/pyomeca/bioptim/453#-N-YO4N4EuIqh2beS0JD:-N-YO4N4EuIqh2beS0JE:b-1mytky) ([raw file](https://github.com/pyomeca/bioptim/blob/33e2f0687a0d034cbf66e0f8cd75cfb38d9937ae/bioptim/optimization/solution.py#L453)):*
> ```Python
> 
>         if hasattr(self, "time_vector"):
>             new.time_vector = deepcopy(self.time_vector)
> ```

99% of the time, testing for `hasattr` is a design flaw. Please define `time_vector` as a `None` in the initialization to make sure this variable always exists. (You can deepcopy a None without issues)



_Code quote:_
```Python
        if hasattr(self, "time_vector"):
            new.time_vector = deepcopy(self.time_vector)
```

**Review by pariterre — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/453#-:-N0fCmtF3pXHwraBWA-F:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @EveCharbie)

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/453#-:-N1KrRwd17BxLsWVDNbU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Comment by pariterre** [comment]
The bug from AppVeyor is acceptable

**Pull request merged**
