### PR TITLE
Testing the tests on windows

### PR DESCRIPTION
**Pull request by pariterre**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/897)

### CODE REVIEW

**Comment by pariterre** [comment]
@Ipuch

**Comment by Ipuch** [comment]
@Kev1CO Can you run your tests on a new environment locally ?

**Comment by Kev1CO** [comment]
I ran the test on my laptop and had only 1 error on test_continuity_as_objective. The values weren't the same as the one in the test. 
Here is my env:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/COKEVI~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/COKEVI~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Git hub action | Local
-- | --
biorbd   1.11.2     py312heded1f7_1   conda-forge | biorbd   1.11.2   py312heded1f7_1   conda-forge
numpy   2.1.2     py312hf10105a_0   conda-forge | numpy   2.1.2   py312hf10105a_0   conda-forge
scipy   1.14.1     py312h337df96_1   conda-forge | scipy   1.14.1   py312h337df96_1   conda-forge
casadi   3.6.7     py312hb567ab1_0   conda-forge | casadi   3.6.7   py312hb567ab1_0   conda-forge
platform win32   -- Python 3.12.7, pytest-8.3.3 | pytest   8.3.3   pyhd8ed1ab_0   conda-forge



</body>

</html>

The only difference is that my python is on version 3.10 instead of 3.12 in github action.

**Comment by Ipuch** [comment]
Minor differences with the PR #895 were all tests were fine 
image
image
image

**Pull request merged**
