### PR TITLE
[RTR] Multi Biorbd Model 

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/625)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/625)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/interfaces/biomodel.py` line 17 at r1](https://reviewable.io/reviews/pyomeca/bioptim/625#-NOzouTe6EoW8_DVRv40:-NOzouTe6EoW8_DVRv41:b-8xr23f) ([raw file](https://github.com/pyomeca/bioptim/blob/7122fbf5706dee5d3d9d1ecd0eae9b678eec2154/bioptim/interfaces/biomodel.py#L17)):*
> ```Python
>     """Get the gravity vector"""
> 
>     def set_gravity(self, new_gravity, model_index: int = 0):
> ```

Change those for not implemented when required



_Code quote:_
```Python
y, model_index: int = 0
```
___
*[`bioptim/interfaces/biorbd_model.py` line 4 at r1](https://reviewable.io/reviews/pyomeca/bioptim/625#-NOzp2rL5VGLlaR_hWrI:-NOzp2rL5VGLlaR_hWrJ:bcalm5k) ([raw file](https://github.com/pyomeca/bioptim/blob/7122fbf5706dee5d3d9d1ecd0eae9b678eec2154/bioptim/interfaces/biorbd_model.py#L4)):*
> ```Python
> 
> from ..misc.utils import check_version
> from .multi_biorbd_model import MultiBiorbdModel
> ```

Keep them in a single file



_Code quote:_
```Python
from ..misc.utils import check_version
from .multi_biorbd_model import MultiBiorbdModel
```

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/625)* status: 1 of 14 files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/interfaces/biomodel.py` line 17 at r1](https://reviewable.io/reviews/pyomeca/bioptim/625#-NOzouTe6EoW8_DVRv40:-NP2u3yq8Q4yJGvOvYUU:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/7122fbf5706dee5d3d9d1ecd0eae9b678eec2154/bioptim/interfaces/biomodel.py#L17)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Change those for not implemented when required
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biorbd_model.py` line 4 at r1](https://reviewable.io/reviews/pyomeca/bioptim/625#-NOzp2rL5VGLlaR_hWrI:-NP2u9JJB1wkMWkoCh2t:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/7122fbf5706dee5d3d9d1ecd0eae9b678eec2154/bioptim/interfaces/biorbd_model.py#L4)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Keep them in a single file
</blockquote></details>

Done.

**Comment by EveCharbie** [comment]
@pariterre I think we are good to go :)
Please verify that you agree with which functions I decided to overwritte in BiorbdModel (which for me does not make sens for multiple models)

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/625)* status: all files reviewed, 3 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/interfaces/biorbd_model.py` line 479 at r2](https://reviewable.io/reviews/pyomeca/bioptim/625#-NP4JXrc4vTskru8XZ6_:-NP4JXrc4vTskru8XZ6a:b-93fzvf) ([raw file](https://github.com/pyomeca/bioptim/blob/ef5c335494d5bd13c29d9c3a99e158cf916115a0/bioptim/interfaces/biorbd_model.py#L479)):*
> ```Python
>             raise ValueError("Wrong index")
>         # raise NotImplementedError("rigid_contact_acceleration is not implemented yet for multi models") # @pariterre I think we should remove it if we know it is broken!
>         return self.model.rigidContactAcceleration(q, qdot, qddot, 0, True).to_mx()[index_direction]
> ```

Can we not just change this "0" for "index"? If this fails (for instance Segmentation Fault), I would vote for removing this method altogether



_Code quote:_
```Python
0
```
___
*[`tests/test_biorbd_multi_model.py` line 82 at r2](https://reviewable.io/reviews/pyomeca/bioptim/625#-NP4Jwvz7EPtp3PSbxno:-NP4Jwvz7EPtp3PSbxnp:bw8bw9o) ([raw file](https://github.com/pyomeca/bioptim/blob/ef5c335494d5bd13c29d9c3a99e158cf916115a0/tests/test_biorbd_multi_model.py#L82)):*
> ```Python
>     models.set_gravity(np.array([0, 0, -3]))
>     model_gravity_modified = Function("Gravity", [], [models.gravity])()["o0"]
>     # segment_index = models.segment_index("Seg1")
> ```

This should expect a raise 
```python
with pytest.raise(RuntimeError, match="error message"):
    segment_index = models.segment_index("Seg1")
```
Those below as well!



_Code quote:_
```Python
 # segment_index = models.segment_index("Seg1")
```
___
*[`tests/test_global_torque_driven_ocp.py` line 583 at r2](https://reviewable.io/reviews/pyomeca/bioptim/625#-NP4KReFDLx03xvIudVS:-NP4KReFDLx03xvIudVT:b1mi154) ([raw file](https://github.com/pyomeca/bioptim/blob/fe0d8c04621d8fc06f608b58132b602156931e7b/tests/test_global_torque_driven_ocp.py#L583)):*
> ```Python
>     return  # TODO: when it is not broken anymore, the following results should be good
> 
>     sol = ocp.solve()
> ```

What was the reason to remove those?



_Code quote:_
```Python
    np.testing.assert_almost_equal(g, np.zeros((40, 1)), decimal=6)

    # Check some of the results
    states, controls, states_no_intermediate = sol.states, sol.controls, sol.states_no_intermediate

    # initial and final position
    np.testing.assert_almost_equal(states[0]["q"][:, 0], np.array([-3.14159265, 0.0]), decimal=6)
    np.testing.assert_almost_equal(states[0]["q"][:, -1], np.array([3.04159296, 0.0]), decimal=3)
    np.testing.assert_almost_equal(states[1]["q"][:, 0], np.array([-3.14159265, 0.0]), decimal=6)
    np.testing.assert_almost_equal(states[1]["q"][:, -1], np.array([3.04159271, 0.0]), decimal=6)
    # initial and final velocities
    np.testing.assert_almost_equal(states[0]["qdot"][:, 0], np.array([11.47768245, 26.16790572]), decimal=6)
    np.testing.assert_almost_equal(states[0]["qdot"][:, -1], np.array([11.52232512, 26.06343438]), decimal=6)
    np.testing.assert_almost_equal(states[1]["qdot"][:, 0], np.array([10.54030594, 28.30202101]), decimal=6)
    np.testing.assert_almost_equal(states[1]["qdot"][:, -1], np.array([10.594124, 28.17553337]), decimal=6)
    # initial and final controls
    np.testing.assert_almost_equal(controls[0]["tau"][:, 0], np.array([0.01906557]), decimal=6)
    np.testing.assert_almost_equal(controls[0]["tau"][:, -2], np.array([-0.00619146]), decimal=6)
    np.testing.assert_equal(controls[1], {})
```

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/625)* status: all files reviewed, 3 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/interfaces/biorbd_model.py` line 479 at r2](https://reviewable.io/reviews/pyomeca/bioptim/625#-NP4JXrc4vTskru8XZ6_:-NP5HXqP4wTLXabTX1Tc:bsm4p2i) ([raw file](https://github.com/pyomeca/bioptim/blob/ef5c335494d5bd13c29d9c3a99e158cf916115a0/bioptim/interfaces/biorbd_model.py#L479)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Can we not just change this "0" for "index"? If this fails (for instance Segmentation Fault), I would vote for removing this method altogether
</blockquote></details>

Fatal Python error: Segmentation fault
But it is used in the DAE_INVERSE_DYNAMICS with contact.
Do we let it as is ?
___
*[`tests/test_biorbd_multi_model.py` line 82 at r2](https://reviewable.io/reviews/pyomeca/bioptim/625#-NP4Jwvz7EPtp3PSbxno:-NP5Fxr2EewAQhqD1sXq:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ef5c335494d5bd13c29d9c3a99e158cf916115a0/tests/test_biorbd_multi_model.py#L82)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should expect a raise 
```python
with pytest.raise(RuntimeError, match="error message"):
    segment_index = models.segment_index("Seg1")
```
Those below as well!
</blockquote></details>

Done.
___
*[`tests/test_global_torque_driven_ocp.py` line 583 at r2](https://reviewable.io/reviews/pyomeca/bioptim/625#-NP4KReFDLx03xvIudVS:-NP4OSRmBgqtV8ox00fF:b-dkgkn9) ([raw file](https://github.com/pyomeca/bioptim/blob/fe0d8c04621d8fc06f608b58132b602156931e7b/tests/test_global_torque_driven_ocp.py#L583)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

What was the reason to remove those?
</blockquote></details>

Was not tested anyway, but yeah I can put it back.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/625)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`bioptim/interfaces/biorbd_model.py` line 479 at r2](https://reviewable.io/reviews/pyomeca/bioptim/625#-NP4JXrc4vTskru8XZ6_:-NPI6KH8AL3Rygn9Q8zG:by9ed89) ([raw file](https://github.com/pyomeca/bioptim/blob/ef5c335494d5bd13c29d9c3a99e158cf916115a0/bioptim/interfaces/biorbd_model.py#L479)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

Fatal Python error: Segmentation fault
But it is used in the DAE_INVERSE_DYNAMICS with contact.
Do we let it as is ?
</blockquote></details>

@Ipuch 
Is this expected?

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/625)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/interfaces/biorbd_model.py` line 479 at r2](https://reviewable.io/reviews/pyomeca/bioptim/625#-NP4JXrc4vTskru8XZ6_:-NPYVbPx8m_P0r-KcEMa:b-aj1lg4) ([raw file](https://github.com/pyomeca/bioptim/blob/ef5c335494d5bd13c29d9c3a99e158cf916115a0/bioptim/interfaces/biorbd_model.py#L479)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

@Ipuch 
Is this expected?
</blockquote></details>

This is expected as there is only one contact in the model. But yes, we should specify the index instead of 0. And remove the TODO.

**Review by Ipuch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/625)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @EveCharbie and @pariterre)

___
*[`bioptim/interfaces/biorbd_model.py` line 337 at r2](https://reviewable.io/reviews/pyomeca/bioptim/625#-NPYWOSI4LEfCYuQFYEi:-NPYWOSI4LEfCYuQFYEj:buegzw5) ([raw file](https://github.com/pyomeca/bioptim/blob/ef5c335494d5bd13c29d9c3a99e158cf916115a0/bioptim/interfaces/biorbd_model.py#L337)):*
> ```Python
>             out = vertcat(
>                 out,
>                 model.InverseDynamics(
> ```

```python3 
for i, model in enumerate(self.models):
       q = q[self.models.index(variable: str = "q", model_index: int = i)]
       ...
```

So don't have to track q, qdot and qddot, **Disccussed with benjamin**. Variable is expected to receive "q", "qdot", "qddot", "markers", "contact", etc...

Need to be applied everywhere you felt the need of tracking. plus this function should be useful for the objective or constraint definition.



_Suggestion:_
```Python
seDynamics( 
```

**Review by pariterre — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/625)* status: all files reviewed, 2 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/interfaces/biorbd_model.py` line 337 at r2](https://reviewable.io/reviews/pyomeca/bioptim/625#-NPYWOSI4LEfCYuQFYEi:-NPYaTrp84IOcRW65vh2:beqbxei) ([raw file](https://github.com/pyomeca/bioptim/blob/ef5c335494d5bd13c29d9c3a99e158cf916115a0/bioptim/interfaces/biorbd_model.py#L337)):*
> self.models.index(variable: str = "q", model_index: int = i)

self.variable_index(variable: str, model_index: int) -> slice

for instance: return slice(init_index, final_index)

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/625)* status: all files reviewed, 2 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/interfaces/biorbd_model.py` line 337 at r2](https://reviewable.io/reviews/pyomeca/bioptim/625#-NPYWOSI4LEfCYuQFYEi:-NPZhudP3ScaEGXbnlrS:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ef5c335494d5bd13c29d9c3a99e158cf916115a0/bioptim/interfaces/biorbd_model.py#L337)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

> self.models.index(variable: str = "q", model_index: int = i)

self.variable_index(variable: str, model_index: int) -> slice

for instance: return slice(init_index, final_index)
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biorbd_model.py` line 479 at r2](https://reviewable.io/reviews/pyomeca/bioptim/625#-NP4JXrc4vTskru8XZ6_:-NPZhwcO6xcGLc0cCEnk:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ef5c335494d5bd13c29d9c3a99e158cf916115a0/bioptim/interfaces/biorbd_model.py#L479)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

This is expected as there is only one contact in the model. But yes, we should specify the index instead of 0. And remove the TODO.
</blockquote></details>

Done.

**Comment by EveCharbie** [comment]
@pariterre I think it is ready to merge :)

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/625#-:-NQ6dwdTEKwjhw1u57bI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

**Review by Ipuch — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/625)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
