### PR TITLE
[RTM after next push] SOCP: Making the noise dependant on the states + controls

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/809)

### CODE REVIEW

**Comment by EveCharbie** [comment]
Will rebase when other PRs are merged

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 5 of 36 files at r1, 1 of 7 files at r2, 21 of 34 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/809)* status: all files reviewed, 5 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/dynamics/dynamics_functions.py` line 645 at r4](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np1mnPz0-uUlWO94lyT:-Np1mnPz0-uUlWO94lyU:btka4r2) ([raw file](https://github.com/pyomeca/bioptim/blob/33225a1fb438dc942f17e18b65b8724093532a81/bioptim/dynamics/dynamics_functions.py#L645)):*
> ```Python
>         """
> 
>         q = nlp.get_var_from_states_or_controls("q", states, controls)
> ```

add the capability to send algebraic too
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py` line 711 at r4](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np1nDgj72okPfS8ynTr:-Np1nDgk-hHuRQKausiV:b-83ohku) ([raw file](https://github.com/pyomeca/bioptim/blob/33225a1fb438dc942f17e18b65b8724093532a81/bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py#L711)):*
> ```Python
>         nlp = socp.nlp[0]
>         out = stochastic_forward_dynamics(
>             None,
> ```

None?
___
*[`bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py` line 133 at r4](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np1nkYe-F_JWHL6zNNt:-Np1nkYe-F_JWHL6zNNu:b-ez0ier) ([raw file](https://github.com/pyomeca/bioptim/blob/33225a1fb438dc942f17e18b65b8724093532a81/bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py#L133)):*
> ```Python
>     x_init = InitialGuessList()
>     x_init.add(key="q_roots", initial_guess=[0] * n_root, phase=0)
>     x_init.add(key="q_jointss", initial_guess=[0] * n_tau, phase=0)
> ```

Typo? Remove the capability to declare unused variable?
___
*[`bioptim/models/protocols/biomodel.py` line 88 at r4](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np1pziE52ksPDUwnkg0:-Np1pziE52ksPDUwnkg1:b-ojpqs4) ([raw file](https://github.com/pyomeca/bioptim/blob/33225a1fb438dc942f17e18b65b8724093532a81/bioptim/models/protocols/biomodel.py#L88)):*
> ```Python
>         return ()
> 
>     def biorbd_homogeneous_matrices_in_global(self, q, segment_id, inverse=False) -> tuple:
> ```

This should not be in the Protocol

nlp.model: BiorbdModel
___
*[`bioptim/optimization/non_linear_program.py` line 521 at r4](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np1qEMLCJjT2pjkD_Fu:-Np1qEMLCJjT2pjkD_Fv:b-xxfxqe) ([raw file](https://github.com/pyomeca/bioptim/blob/33225a1fb438dc942f17e18b65b8724093532a81/bioptim/optimization/non_linear_program.py#L521)):*
> ```Python
>         return self.tf / self.ns * node_idx
> 
>     def get_var_from_states_or_controls(self, key: str, states: MX.sym, controls: MX.sym) -> MX:
> ```

Add the capability to send algebraic

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/809)* status: 36 of 47 files reviewed, 4 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/dynamics_functions.py` line 645 at r4](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np1mnPz0-uUlWO94lyT:-NpWU-187lJL0R5pw2uE:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/33225a1fb438dc942f17e18b65b8724093532a81/bioptim/dynamics/dynamics_functions.py#L645)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

add the capability to send algebraic too
</blockquote></details>

Done.
___
*[`bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py` line 711 at r4](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np1nDgj72okPfS8ynTr:-NpWV7780wX9evKa_och:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/33225a1fb438dc942f17e18b65b8724093532a81/bioptim/examples/stochastic_optimal_control/arm_reaching_muscle_driven.py#L711)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

None?
</blockquote></details>

Done.
___
*[`bioptim/models/protocols/biomodel.py` line 88 at r4](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np1pziE52ksPDUwnkg0:-NpWYg3h-pNHXx-PNOai:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/33225a1fb438dc942f17e18b65b8724093532a81/bioptim/models/protocols/biomodel.py#L88)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should not be in the Protocol

nlp.model: BiorbdModel
</blockquote></details>

Done.
___
*[`bioptim/optimization/non_linear_program.py` line 521 at r4](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np1qEMLCJjT2pjkD_Fu:-NpWXbDM3vUsZiOl_SqS:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/33225a1fb438dc942f17e18b65b8724093532a81/bioptim/optimization/non_linear_program.py#L521)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Add the capability to send algebraic
</blockquote></details>

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 58 of 58 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/809)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/gui/plot.py` line 388 at r5](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np_9mPH7H_xcD-KX-ro:-Np_9mPH7H_xcD-KX-rp:b-pafc5z) ([raw file](https://github.com/pyomeca/bioptim/blob/45c3cb629d3600b65579ae3bd54a6a07e9dfb966/bioptim/gui/plot.py#L388)):*
> ```Python
>                             )
>                             if variable in nlp.plot
>                             else 0
> ```

Verify that
___
*[`tests/shard5/test_global_stochastic_collocation.py` line 384 at r5](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np_Bfox2HgkcnoH4Xmu:-Np_Bfox2HgkcnoH4Xmv:b-qp33vi) ([raw file](https://github.com/pyomeca/bioptim/blob/e2725f0cac9f60c7140272af86b7fa17d682719d/tests/shard5/test_global_stochastic_collocation.py#L384)):*
> ```Python
> 
>     # First collocation state is equal to the states at node
>     const = socp.nlp[0].g_internal[1]
> ```

constraint

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/809)* status: all files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/gui/plot.py` line 388 at r5](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np_9mPH7H_xcD-KX-ro:-NpeEKfIEY4Q7AXKL9T_:bcvptb4) ([raw file](https://github.com/pyomeca/bioptim/blob/45c3cb629d3600b65579ae3bd54a6a07e9dfb966/bioptim/gui/plot.py#L388)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Verify that
</blockquote></details>

reverted deleted lines
___
*[`tests/shard5/test_global_stochastic_collocation.py` line 384 at r5](https://reviewable.io/reviews/pyomeca/bioptim/809#-Np_Bfox2HgkcnoH4Xmu:-NpeFF2g2zFY5quqPyJW:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/e2725f0cac9f60c7140272af86b7fa17d682719d/tests/shard5/test_global_stochastic_collocation.py#L384)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

constraint
</blockquote></details>

Done.

**Review by pariterre — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/809#-:-NpeG2R48jYu_JbawkuO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Comment by EveCharbie** [comment]
@pariterre should be fine

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/809#-:-NpeZHob1sS7YJ50p_9D:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/809#-:-NpfCkrFEChq9L6TTj30:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
