### PR TITLE
feat: pyorerun interfaced

### PR DESCRIPTION
**Pull request by Ipuch**
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/882)

### CODE REVIEW

**Comment by Ipuch** [comment]
@EveCharbie if you like to review, you can do it, otherwise it can wait for @pariterre returns.

**Review by EveCharbie — CHANGES_REQUESTED** [review]
Do you handle quaternions? If not, please raise an error.

> Reviewed 17 of 27 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/882#-:-O0yNYKS2xCTI8UEdtZk:b-v2vcf2)* status: 18 of 28 files reviewed, 5 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/examples/getting_started/pendulum.py` line 131 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yLYA402aOfCmVkHmr:-O0yLYA402aOfCmVkHms:b-hay66i) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/examples/getting_started/pendulum.py#L131)):*
> ```Python
> 
>     # --- Prepare the ocp --- #
>     ocp = prepare_ocp(biorbd_model_path="models/pendulum.bioMod", final_time=1, n_shooting=30, n_threads=2)
> ```

revert?



_Code quote:_
```Python
30
```
___
*[`bioptim/examples/getting_started/pendulum.py` line 160 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yLe9B4JdJ5DGPXmJi:-O0yLe9B4JdJ5DGPXmJj:bxbu8o7) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/examples/getting_started/pendulum.py#L160)):*
> ```Python
> 
>     # --- Animate the solution --- #
>     viewer = "bioviz"
> ```

make an enum



_Code quote:_
```Python
"bioviz"
```
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 229 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yLtrL2uTeATogjCL0:-O0yLtrL2uTeATogjCL1:b-8r1kwu) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/examples/holonomic_constraints/two_pendulums.py#L229)):*
> ```Python
>         viz.add_animated_model(pyorerun.BiorbdModel(model_path), q=q)
> 
>         viz.rerun("double_pendulum")
> ```

Super clean!
___
*[`bioptim/models/biorbd/biorbd_model.py` line 810 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yMmWA2uObQ8AiqHfO:-O0yMmWA2uObQ8AiqHfP:b6smnqb) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/models/biorbd/biorbd_model.py#L810)):*
> ```Python
>             raise RuntimeError("pyorerun must be install to animate the model")
> 
>         # check_version(pyorerun, "1.2.3", max_version="1.2.99")
> ```

Do we need this? If yes, uncomment please



_Code quote:_
```Python
check_version(pyorerun, "1.2.3", max_version="1.2.99")
```
___
*[`bioptim/models/biorbd/viewer_bioviz.py` line 116 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yN9nH01amYTML4cpp:-O0yN9nH01amYTML4cpq:be5et8l) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/models/biorbd/viewer_bioviz.py#L116)):*
> ```Python
>             else:
>                 b_is_visible[i] = False
>     return None
> ```

Was it like that? I think viz.exec() does this 



_Code quote:_
```Python
def play_bioviz_animation(all_bioviz: list) -> None:
    """Play the animation of the list of bioviz objects"""
    b_is_visible = [True] * len(all_bioviz)
    while sum(b_is_visible):
        for i, b in enumerate(all_bioviz):
            if b.vtk_window.is_active:
                b.update()
            else:
                b_is_visible[i] = False
    return None
```

**Comment by EveCharbie** [comment]
Thanks @Ipuch, this will be very helpful and clean!

**Review by Ipuch — COMMENTED** [review]
Quaternions are handled by biorbd so yes :)

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/882#-:-O0ynhPJ2K5MinbW3hoF:b-2s0oan)* status: 17 of 29 files reviewed, 5 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/examples/getting_started/pendulum.py` line 131 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yLYA402aOfCmVkHmr:-O0yRLyg8CxzsnLTnyv_:bgl39xg) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/examples/getting_started/pendulum.py#L131)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

revert?
</blockquote></details>

revert to 300 ?
___
*[`bioptim/examples/getting_started/pendulum.py` line 160 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yLe9B4JdJ5DGPXmJi:-O0yROzb9pKyk0-Q1s7g:b-lpvprx) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/examples/getting_started/pendulum.py#L160)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

make an enum
</blockquote></details>

Ouin, I didn't want one more enum...
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 229 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yLtrL2uTeATogjCL0:-O0yRj1e0WpmkQdu1hwA:bnputky) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/examples/holonomic_constraints/two_pendulums.py#L229)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

Super clean!
</blockquote></details>

Done. Thanks
___
*[`bioptim/models/biorbd/biorbd_model.py` line 810 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yMmWA2uObQ8AiqHfO:-O0ynriu06YbTTUw92s8:bfzstfd) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/models/biorbd/biorbd_model.py#L810)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

Do we need this? If yes, uncomment please
</blockquote></details>

Method deleted as I moved everything in viewer scripts
___
*[`bioptim/models/biorbd/viewer_bioviz.py` line 116 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yN9nH01amYTML4cpp:-O0ySJ-4-n6Ya_cDf-xJ:bsih3ts) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/models/biorbd/viewer_bioviz.py#L116)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

Was it like that? I think viz.exec() does this
</blockquote></details>

Yes it was like that because, bioviz doesn't natively handle multiphase animations.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 9 of 27 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/882)* status: all files reviewed, 10 unresolved discussions (waiting on @EveCharbie and @Ipuch)

___
*[`bioptim/examples/getting_started/pendulum.py` line 160 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yLe9B4JdJ5DGPXmJi:-O262f5gA_qf8KJ77rVS:b1jtsl0) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/examples/getting_started/pendulum.py#L160)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Ouin, I didn't want one more enum...
</blockquote></details>

viewer should not be in sol.animate
___
*[`bioptim/examples/getting_started/pendulum.py` line 77 at r3](https://reviewable.io/reviews/pyomeca/bioptim/882#-O262ZZa79I34itIRx8B:-O262ZZa79I34itIRx8C:b-nb6j0h) ([raw file](https://github.com/pyomeca/bioptim/blob/58ee4395ed9fa3376676c409de5976e4f5a3795e/bioptim/examples/getting_started/pendulum.py#L77)):*
> ```Python
>     """
> 
>     bio_model = BiorbdModel(biorbd_model_path)
> ```

Add the viewer here (and not when calling sol.animate)
___
*[`bioptim/examples/getting_started/pendulum.py` line 162 at r3](https://reviewable.io/reviews/pyomeca/bioptim/882#-O263Fz77ZBQaZS9LWv8:-O263Fz77ZBQaZS9LWv9:b-vclytt) ([raw file](https://github.com/pyomeca/bioptim/blob/58ee4395ed9fa3376676c409de5976e4f5a3795e/bioptim/examples/getting_started/pendulum.py#L162)):*
> ```Python
>     viewer = "bioviz"
>     # viewer = "pyorerun"
>     sol.animate(n_frames=0, viewer=viewer, show_now=True)
> ```

```
model = BiorbdModel(PATH, viewer=BiorbdModelViewer.BIOVIZ)
ocp = prepare_ocp(...)
...
ocp.nlp[0].model.viewer = BiorbdModelViewer.PYORERUN
sol.animate(n_frames=0, show_now=True)
```
___
*[`bioptim/examples/torque_driven_ocp/example_multi_biorbd_model.py` line 100 at r3](https://reviewable.io/reviews/pyomeca/bioptim/882#-O264KmYBndgPKaMWP5X:-O264KmYBndgPKaMWP5Y:b-2jwa7k) ([raw file](https://github.com/pyomeca/bioptim/blob/58ee4395ed9fa3376676c409de5976e4f5a3795e/bioptim/examples/torque_driven_ocp/example_multi_biorbd_model.py#L100)):*
> ```Python
> 
>     # --- Animate results with pyorerun --- #
>     sol.animate(viewer="pyorerun")
> ```

Update this
___
*[`bioptim/optimization/solution/solution.py` line 1225 at r3](https://reviewable.io/reviews/pyomeca/bioptim/882#-O266ugM3TdsNHl6ypEH:-O266ugM3TdsNHl6ypEI:b1rve4p) ([raw file](https://github.com/pyomeca/bioptim/blob/58ee4395ed9fa3376676c409de5976e4f5a3795e/bioptim/optimization/solution/solution.py#L1225)):*
> ```Python
>         show_now: bool = True,
>         show_tracked_markers: bool = False,
>         viewer: str = "bioviz",
> ```

Move this to BiorbdModel interface
___
*[`bioptim/optimization/solution/solution.py` line 1264 at r3](https://reviewable.io/reviews/pyomeca/bioptim/882#-O268Y2w8ktT9pJJnsoM:-O268Y2w8ktT9pJJnsoN:bi066lx) ([raw file](https://github.com/pyomeca/bioptim/blob/58ee4395ed9fa3376676c409de5976e4f5a3795e/bioptim/optimization/solution/solution.py#L1264)):*
> ```Python
> 
>         if viewer == "bioviz":
>             return animate_with_bioviz_for_loop(self.ocp, self, show_now, show_tracked_markers, n_frames, **kwargs)
> ```

`type(self.ocp.nlp[0].model).animate()`

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/882)* status: 25 of 30 files reviewed, 10 unresolved discussions (waiting on @EveCharbie and @pariterre)

___
*[`bioptim/examples/getting_started/pendulum.py` line 131 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yLYA402aOfCmVkHmr:-O26PiAS-dTc70eM4BS2:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/examples/getting_started/pendulum.py#L131)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

revert to 300 ?
</blockquote></details>

Done
___
*[`bioptim/examples/getting_started/pendulum.py` line 160 at r2](https://reviewable.io/reviews/pyomeca/bioptim/882#-O0yLe9B4JdJ5DGPXmJi:-O26Q3VB2QPmVdN1tfYu:bwfsoz1) ([raw file](https://github.com/pyomeca/bioptim/blob/73f209cf2edc27ce79a3fffd781f9c58fd269869/bioptim/examples/getting_started/pendulum.py#L160)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

viewer should not be in sol.animate
</blockquote></details>

gave up
___
*[`bioptim/examples/getting_started/pendulum.py` line 77 at r3](https://reviewable.io/reviews/pyomeca/bioptim/882#-O262ZZa79I34itIRx8B:-O26Q6wB817XIB0a-imt:bwfsoz1) ([raw file](https://github.com/pyomeca/bioptim/blob/58ee4395ed9fa3376676c409de5976e4f5a3795e/bioptim/examples/getting_started/pendulum.py#L77)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Add the viewer here (and not when calling sol.animate)
</blockquote></details>

gave up
___
*[`bioptim/examples/getting_started/pendulum.py` line 162 at r3](https://reviewable.io/reviews/pyomeca/bioptim/882#-O263Fz77ZBQaZS9LWv8:-O26Q5R9AK1jJa4DPObl:bwfsoz1) ([raw file](https://github.com/pyomeca/bioptim/blob/58ee4395ed9fa3376676c409de5976e4f5a3795e/bioptim/examples/getting_started/pendulum.py#L162)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

```
model = BiorbdModel(PATH, viewer=BiorbdModelViewer.BIOVIZ)
ocp = prepare_ocp(...)
...
ocp.nlp[0].model.viewer = BiorbdModelViewer.PYORERUN
sol.animate(n_frames=0, show_now=True)
```
</blockquote></details>

gave up
___
*[`bioptim/examples/torque_driven_ocp/example_multi_biorbd_model.py` line 100 at r3](https://reviewable.io/reviews/pyomeca/bioptim/882#-O264KmYBndgPKaMWP5X:-O26T-3C3o45l4pknN5t:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/58ee4395ed9fa3376676c409de5976e4f5a3795e/bioptim/examples/torque_driven_ocp/example_multi_biorbd_model.py#L100)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Update this
</blockquote></details>

Done
___
*[`bioptim/optimization/solution/solution.py` line 1225 at r3](https://reviewable.io/reviews/pyomeca/bioptim/882#-O266ugM3TdsNHl6ypEH:-O26QEJM8WzUZ-by7gy7:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/58ee4395ed9fa3376676c409de5976e4f5a3795e/bioptim/optimization/solution/solution.py#L1225)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Move this to BiorbdModel interface
</blockquote></details>

Done
___
*[`bioptim/optimization/solution/solution.py` line 1264 at r3](https://reviewable.io/reviews/pyomeca/bioptim/882#-O268Y2w8ktT9pJJnsoM:-O26QFcSCoYE0kK1g3jj:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/58ee4395ed9fa3376676c409de5976e4f5a3795e/bioptim/optimization/solution/solution.py#L1264)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`type(self.ocp.nlp[0].model).animate()`
</blockquote></details>

Done

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/882#-:-O2BGLGFE3i5w37LfUp4:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @EveCharbie)

**Pull request merged**
