### PR TITLE
[RTR] Torque driven free floating base dynamics

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request? Issue # 773
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/803)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/803)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/dynamics/dynamics_functions.py` line 597 at r1](https://reviewable.io/reviews/pyomeca/bioptim/803#-NjDaosCElOlTieUg_jf:-NjDaosD7UTl8dKS5U2K:bchueb7) ([raw file](https://github.com/pyomeca/bioptim/blob/e0c7a0b664f45d588879dd8220e48c4d495a318b/bioptim/dynamics/dynamics_functions.py#L597)):*
> ```Python
>             else:
>                 raise RuntimeError(f"{key} not found in states or controls")
>             return out
> ```

Should this be used everywhere?
___
*[`bioptim/limits/penalty_controller.py` line 366 at r1](https://reviewable.io/reviews/pyomeca/bioptim/803#-NjDcfGe91j2aFQ9MJNh:-NjDcfGe91j2aFQ9MJNi:bvgwh81) ([raw file](https://github.com/pyomeca/bioptim/blob/e0c7a0b664f45d588879dd8220e48c4d495a318b/bioptim/limits/penalty_controller.py#L366)):*
> ```Python
> 
>     @property
>     def qdot(self) -> OptimizationVariable:
> ```

Since q, qdot and tau are canonical in bioptim, I suggest that since you added q and qdot, that "tau" should be added as well for consistency

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/803)* status: all files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/dynamics_functions.py` line 597 at r1](https://reviewable.io/reviews/pyomeca/bioptim/803#-NjDaosCElOlTieUg_jf:-NjIQ3wQ-m8A_Gd_lOrP:b-w8c92h) ([raw file](https://github.com/pyomeca/bioptim/blob/e0c7a0b664f45d588879dd8220e48c4d495a318b/bioptim/dynamics/dynamics_functions.py#L597)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Should this be used everywhere?
</blockquote></details>

I think yes. Can I put this function as a method of nlp?
___
*[`bioptim/limits/penalty_controller.py` line 366 at r1](https://reviewable.io/reviews/pyomeca/bioptim/803#-NjDcfGe91j2aFQ9MJNh:-NjISsBZ-bHyuyLVJLao:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/e0c7a0b664f45d588879dd8220e48c4d495a318b/bioptim/limits/penalty_controller.py#L366)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Since q, qdot and tau are canonical in bioptim, I suggest that since you added q and qdot, that "tau" should be added as well for consistency
</blockquote></details>

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/803)* status: all files reviewed, 1 unresolved discussion (waiting on @EveCharbie)

___
*[`bioptim/dynamics/dynamics_functions.py` line 597 at r1](https://reviewable.io/reviews/pyomeca/bioptim/803#-NjDaosCElOlTieUg_jf:-NjITYMS4-Uk6xMvL9Yc:b-c32si0) ([raw file](https://github.com/pyomeca/bioptim/blob/e0c7a0b664f45d588879dd8220e48c4d495a318b/bioptim/dynamics/dynamics_functions.py#L597)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

I think yes. Can I put this function as a method of nlp?
</blockquote></details>

Sounds like a good idea!

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/803)* status: 11 of 23 files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/dynamics/dynamics_functions.py` line 597 at r1](https://reviewable.io/reviews/pyomeca/bioptim/803#-NjDaosCElOlTieUg_jf:-NjJmU3F1v9caFriwg6a:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/e0c7a0b664f45d588879dd8220e48c4d495a318b/bioptim/dynamics/dynamics_functions.py#L597)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Sounds like a good idea!
</blockquote></details>

Done.

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/803#-:-NjO_bTk5b-fHJu_OkAt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Comment by EveCharbie** [comment]
@pariterre I need help for either:
- Fixing the tests on Ubuntu/Mac
- Or if you have any ideas on how to make the test more stable on Windows

**Comment by pariterre** [comment]
Close as it is a duplicate of #809

**Pull request closed without merging**
