### PR TITLE
#746 Issue Fixed  [get_nlp in controller could be renamed to nlp ]

### PR DESCRIPTION
**Pull request by Alpha2Shahiri**
### All Submissions:

* [YES] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [YES] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [NO #746] Have you opened/linked the issue related to your pull request?
* [NO] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [YES] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [#746] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/802)

### CODE REVIEW

**Comment by Alpha2Shahiri** [comment]
Regarding our last meeting (Removing some lines of Mayer (Track_Force and Control), seems that ../../bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation is using Mayer: 
    "ObjectiveFcn.Mayer.MINIMIZE_CONTROL" Probably this test: def test_obstacle_avoidance_direct_collocation()
The other test were passed and rename was done. [get_nlp to nlp]

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/802#-:-NjDdKITCtCGBGkMthBN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alpha2Shahiri)

___
*[`bioptim/interfaces/solver_options.py` line 685 at r2](https://reviewable.io/reviews/pyomeca/bioptim/802#-NjDd3mHC-Phba3qGVJH:-NjDd3mHC-Phba3qGVJI:brqzlg0) ([raw file](https://github.com/pyomeca/bioptim/blob/842dc4169eca9f0ce30c23f64490aeb2427454b9/bioptim/interfaces/solver_options.py#L685)):*
> ```Python
>         type: SolverType = SolverType.ACADOS
>         _qp_solver: str = "PARTIAL_CONDENSING_HPIPM"  # FULL_CONDENSING_QPOASES
>         _hessian_approximation: str = "GAUSS_NEWTON"
> ```

Please do not mix pull requests together

**Comment by pariterre** [comment]
This PR won't merge because of the conflict, please resolve :)

**Comment by pariterre** [comment]
This will not merge as the changes for 3.2.0 are too major.

**Pull request closed without merging**
