### PR TITLE
[RTM] continuity constraints are well displayed

### PR DESCRIPTION
**Pull request by Ipuch**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

related to #447

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/513)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/513)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`bioptim/optimization/optimal_control_program.py` line 774 at r2](https://reviewable.io/reviews/pyomeca/bioptim/513#-N9DIx5sEURsN_0ugpzt:-N9DIx5sEURsN_0ugpzu:b9gkbsn) ([raw file](https://github.com/pyomeca/bioptim/blob/691071887cac3d4bd650bd85f7e501c9ff95b2c5/bioptim/optimization/optimal_control_program.py#L774)):*
> ```Python
> 
>             elif penalty.derivative or penalty.explicit_derivative:
>                 if not np.all(x == 0): # initialization
> ```

Please state that this is a hack and explain what it does

**Review by pariterre — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/513)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

**Review by pariterre — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/513)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

**Comment by Ipuch** [comment]
RTM ?

**Review by pariterre — APPROVED** [review]
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/513)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Pull request merged**
