### PR TITLE
[RTR] FIX: example which had an unexpected behavior, and a new that new implementation should pass

### PR DESCRIPTION
**Pull request by Mart1t1**
Todo:
- Remove MINIMIZE TIME from the example and test in 3.1 and 3.2
- Get the results in 3.1 version from #825
- Verify we get the same in version 3.2
- Merge

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/826)

### CODE REVIEW

**Comment by Ipuch** [comment]
link to #825

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/826)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch and @Mart1t1)

___
*[`tests/shard1/test_continuity_as_objective.py` line 51 at r2](https://reviewable.io/reviews/pyomeca/bioptim/826#-Np_FR6a3vuzYsz07Dop:-Np_FR6b3iewb1iXN_lx:b-tjmbzg) ([raw file](https://github.com/pyomeca/bioptim/blob/1cb04f61009165cc04e3fb78718a98830476400b/tests/shard1/test_continuity_as_objective.py#L51)):*
> ```Python
>     #     [0.0, 0.0, 0.0, np.nan],
>     # ]
>     #
> ```

Values should be reinstated

**Review by EveCharbie — COMMENTED** [review]
Thanks @Ipuch 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/826#-:-Ns9VIZu-tjxyAdjCfH6:b60iggr)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Ipuch, @Mart1t1, and @pariterre)

___
*[`tests/shard1/test_continuity_as_objective.py` line 126 at r4](https://reviewable.io/reviews/pyomeca/bioptim/826#-Ns9U_Ee-IhlXoz86Ll8:-Ns9U_Ee-IhlXoz86Ll9:b1fcf5k) ([raw file](https://github.com/pyomeca/bioptim/blob/51f79dbe0a3aee5c4fc1409b6d0a0871b7e40e4b/tests/shard1/test_continuity_as_objective.py#L126)):*
> ```Python
>         }
>     ]
>     expected_iterations = range(5, 35)  # 20 on my laptop @ipuch
> ```

I think this should be removed



_Code quote:_
```Python
expected_iterations = range(5, 35)  # 20 on my laptop @ipuch
```
___
*[`tests/shard1/test_continuity_as_objective.py` line 134 at r4](https://reviewable.io/reviews/pyomeca/bioptim/826#-Ns9UxOk8XD0Z0c-WKur:-Ns9UxOk8XD0Z0c-WKus:b-7a40zu) ([raw file](https://github.com/pyomeca/bioptim/blob/51f79dbe0a3aee5c4fc1409b6d0a0871b7e40e4b/tests/shard1/test_continuity_as_objective.py#L134)):*
> ```Python
>     np.testing.assert_almost_equal(sol_second_pass.vector, np.array([expected_vector]).T, decimal=4)
>     np.testing.assert_almost_equal(sol_second_pass.constraints, np.array([expected_constraints]).T, decimal=4)
>     np.testing.assert_almost_equal(float(sol_second_pass.cost), expected_cost, decimal=2)
> ```

The test seems to still be really sensitive :(
Do you think we should test it with less n_shooting or just make another example?



_Code quote:_
```Python
np.testing.assert_almost_equal(float(sol_second_pass.cost), expected_cost, decimal=2)
```

**Review by Ipuch — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/826)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @EveCharbie and @pariterre)

___
*[`tests/shard1/test_continuity_as_objective.py` line 51 at r2](https://reviewable.io/reviews/pyomeca/bioptim/826#-Np_FR6a3vuzYsz07Dop:-Ns9lB_E3SGQ97v3JJ1s:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/1cb04f61009165cc04e3fb78718a98830476400b/tests/shard1/test_continuity_as_objective.py#L51)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Values should be reinstated
</blockquote></details>

Done
___
*[`tests/shard1/test_continuity_as_objective.py` line 126 at r4](https://reviewable.io/reviews/pyomeca/bioptim/826#-Ns9U_Ee-IhlXoz86Ll8:-Ns9lE9-D1lljTcZ4n2A:b-7psctr) ([raw file](https://github.com/pyomeca/bioptim/blob/51f79dbe0a3aee5c4fc1409b6d0a0871b7e40e4b/tests/shard1/test_continuity_as_objective.py#L126)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

I think this should be removed
</blockquote></details>

I think this is good to know the number of iteration is not the same on CI and local computers, in case we have to debug.
___
*[`tests/shard1/test_continuity_as_objective.py` line 134 at r4](https://reviewable.io/reviews/pyomeca/bioptim/826#-Ns9UxOk8XD0Z0c-WKur:-Ns9lM857U3w91QJ5ZEs:b-eflxr6) ([raw file](https://github.com/pyomeca/bioptim/blob/51f79dbe0a3aee5c4fc1409b6d0a0871b7e40e4b/tests/shard1/test_continuity_as_objective.py#L134)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

The test seems to still be really sensitive :(
Do you think we should test it with less n_shooting or just make another example?
</blockquote></details>

Solved. I forgot, I increased the precision.

**Comment by Ipuch** [comment]
Acados not working on MacOS CI. It Should be solved in another PR.

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/826#-:-Nsi2tOd5v1WzjHg6BxS:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

**Pull request merged**
