### PR TITLE
[RTM] Added more complex example of optimal estimation 

### PR DESCRIPTION
**Pull request by EveCharbie**
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/784)

### CODE REVIEW

**Comment by EveCharbie** [comment]
@pariterre What do you think of this example. If it is acceptable, I will add a test.

**Review by pariterre — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/784#-:-Nhh4fwd5EYjoccT3Ohu:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/examples/track/optimal_estimation.py` line 200 at r1](https://reviewable.io/reviews/pyomeca/bioptim/784#-Nhh5Tk3Dzo--PyG0h3e:-Nhh5Tk3Dzo--PyG0h3f:b4nz137) ([raw file](https://github.com/pyomeca/bioptim/blob/0b0d283a8cb39ad29353de977d8956d21c93455b/bioptim/examples/track/optimal_estimation.py#L200)):*
> ```Python
>     # x_init = InitialGuessList()
>     # x_init.add("q", initial_guess=q_ref, interpolation=InterpolationType.EACH_FRAME)
>     # x_init.add("qdot", initial_guess=qdot_ref, interpolation=InterpolationType.EACH_FRAME)
> ```

To be removed
___
*[`bioptim/optimization/solution.py` line 1905 at r1](https://reviewable.io/reviews/pyomeca/bioptim/784#-Nhh589u7nlzLDRGFVGZ:-Nhh589u7nlzLDRGFVG_:b-myw90w) ([raw file](https://github.com/pyomeca/bioptim/blob/0b0d283a8cb39ad29353de977d8956d21c93455b/bioptim/optimization/solution.py#L1905)):*
> ```Python
>                         # all_bioviz[-1].load_experimental_markers(target_3D)
>                         # n_frames = target_3D.shape[2]
>                         # #######################################
> ```

This can be removed

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/784)* status: all files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/track/optimal_estimation.py` line 200 at r1](https://reviewable.io/reviews/pyomeca/bioptim/784#-Nhh5Tk3Dzo--PyG0h3e:-NhhXMHv3-LJmrPDfjGz:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0b0d283a8cb39ad29353de977d8956d21c93455b/bioptim/examples/track/optimal_estimation.py#L200)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be removed
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution.py` line 1905 at r1](https://reviewable.io/reviews/pyomeca/bioptim/784#-Nhh589u7nlzLDRGFVGZ:-NhhXTL2BoqRpcyXt5Z1:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0b0d283a8cb39ad29353de977d8956d21c93455b/bioptim/optimization/solution.py#L1905)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This can be removed
</blockquote></details>

Done.

**Comment by EveCharbie** [comment]
@pariterre can be merged :)

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/784#-:-Nhl8i3QARijPGwuQH5y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
