### PR TITLE
[RTM when answered] Solution integration for control_type.NONE problems

### PR DESCRIPTION
**Pull request by Kev1CO**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/799)

### CODE REVIEW

**Comment by Kev1CO** [comment]
Also includes result.merge_phases() for control_type.NONE

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/799)* status: all files reviewed, 13 unresolved discussions (waiting on @Kev1CO)

___
*[`bioptim/interfaces/solve_ivp_interface.py` line 369 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikOnTB1luZYHm3dzbZ:-NikOnTB1luZYHm3dzb_:b22quet) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/interfaces/solve_ivp_interface.py#L369)):*
> ```Python
>     dynamics_output = "xall" if keep_intermediate_points else "xf"
> 
>     # NOT SURE OF THIS FIX                                 # NOT SURE OF THIS FIX n°2
> ```

Remove this
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 370 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikPFn2DohveBajNal_:-NikPFn2DohveBajNala:b7rbm1u) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/interfaces/solve_ivp_interface.py#L370)):*
> ```Python
> 
>     # NOT SURE OF THIS FIX                                 # NOT SURE OF THIS FIX n°2
>     if len(x0.shape) != len(u.shape) and len(x0.shape) < 2 or shooting_type.name == 'SINGLE' and len(x0.shape) != (
> ```

shooting_type == Shooting.SINGLE
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 371 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikPaycC7_YpZFZ7ElU:-NikPaycC7_YpZFZ7ElV:bwvdbix) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/interfaces/solve_ivp_interface.py#L371)):*
> ```Python
>     # NOT SURE OF THIS FIX                                 # NOT SURE OF THIS FIX n°2
>     if len(x0.shape) != len(u.shape) and len(x0.shape) < 2 or shooting_type.name == 'SINGLE' and len(x0.shape) != (
>     x0.shape, 1):
> ```

```python
if len(x0.shape) < 2 and (len(x0.shape) != len(u.shape) or shooting_type == Shooting.SINGLE):
```

simplify?
test?
```python
if len(x0.shape) < 2:
```

test this earlier in the code?
```python
if len(x0.shape) < 2:
    # do something to x
if (len(u.shape) < 2:
    # do something to u
```



_Code quote:_
```Python
    if len(x0.shape) != len(u.shape) and len(x0.shape) < 2 or shooting_type.name == 'SINGLE' and len(x0.shape) != (
    x0.shape, 1):
```
___
*[`bioptim/optimization/solution/solution.py` line 322 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikSXtr7JGgWr4W4Bjm:-NikSXtr7JGgWr4W4Bjn:by9bn3z) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L322)):*
> ```Python
>             raise ValueError("The InitialGuessList len must match the number of phases")
>         if n_param != 0:
>             # if len(_sol) != 3 and len(_sol[3]) != 1 and _sol[3][0].shape != (n_param, 1):  # TODO : Check if it's a mistake _sol[3] as parameter
> ```

Remove this line
___
*[`bioptim/optimization/solution/solution.py` line 323 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikSRwe2lobfV1vixT-:-NikSRwe2lobfV1vixT0:b7mvsbk) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L323)):*
> ```Python
>         if n_param != 0:
>             # if len(_sol) != 3 and len(_sol[3]) != 1 and _sol[3][0].shape != (n_param, 1):  # TODO : Check if it's a mistake _sol[3] as parameter
>             if len(_sol) != 3 and len(_sol[2]) != 1 and len(_sol[2][0]) != n_param:
> ```

Add a test for this
___
*[`bioptim/optimization/solution/solution.py` line 348 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikS_1bDzXypIKvuU43:-NikS_1bDzXypIKvuU44:bj0h1cv) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L348)):*
> ```Python
>         for p, ss in enumerate(sol_controls):
>             control_type = ocp.nlp[p].control_type
>             if control_type == ControlType.CONSTANT or control_type == ControlType.NONE:
> ```

control_type in (ControlType.CONSTANT, ControlType.NONE)
___
*[`bioptim/optimization/solution/solution.py` line 361 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikTQzvD6UXe4amNX_V:-NikTQzvD6UXe4amNX_W:byyf4q3) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L361)):*
> ```Python
>                 else:
>                     ocp.nlp[p].controls[key].node_index = 0
>                     ss[key].init.check_and_adjust_dimensions(len(ocp.nlp[p].controls[key]), all_ns[p], "controls")
> ```

This should not be necessary at all as "ss.keys()" should be empty



_Suggestion:_
```Python
ocp.nlp[p].controls.node_index = 0
dimension = 0 if control_type == ControlType.NONE else len(ocp.nlp[p].controls[key])
ss[key].init.check_and_adjust_dimensions(dimension, all_ns[p], "controls")
```
___
*[`bioptim/optimization/solution/solution.py` line 373 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikU9bd3vdoCsv5Zpwo:-NikU9bd3vdoCsv5Zpwp:bfmn9g2) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L373)):*
> ```Python
>                 if control_type == ControlType.NONE:
>                     for key in ss.keys():
>                         vector = np.concatenate((vector, np.repeat(ss[key].init, all_ns[p] + 1)[:, np.newaxis]))
> ```

This is peculiar, I think this is a bug on the designing of your OCP
___
*[`bioptim/optimization/solution/solution.py` line 390 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikUQne8spAT9qnmRzt:-NikUQne8spAT9qnmRzu:blds45e) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L390)):*
> ```Python
>                     ss[key].init.check_and_adjust_dimensions(
>                         len(ocp.nlp[p].stochastic_variables[key]), all_ns[p], "stochastic_variables"
>                     )
> ```

This is definitely not something related to ControlType.NONE
___
*[`bioptim/optimization/solution/solution.py` line 565 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikcsoY9Kr4WHpuef2w:-NikcsoY9Kr4WHpuef2x:b5o83fy) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L565)):*
> ```Python
>         new = Solution.from_ocp(self.ocp)
>         # TODO : ask why we go through this therefore loosing vector value ? As from_ocp method sets vector value to None by default
>         #  This will later result in a loss of empty 'scaled' _stochastic_variables and crash when merge is wanted
> ```

Not the actual problem
___
*[`bioptim/optimization/solution/solution.py` line 1474 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-Nikd0hgCkCGMSTev8cd:-Nikd0hgCkCGMSTev8ce:b-x90s28) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L1474)):*
> ```Python
>                 else None
>             )
>             if self.ocp.nlp[0].control_type.name == 'NONE' or skip_controls:
> ```

control_type == ControlType.NONE
___
*[`bioptim/optimization/solution/solution.py` line 1481 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikddkoCWtxyjVJGVdT:-NikddkoCWtxyjVJGVdU:b-mmpt4t) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L1481)):*
> ```Python
>         ns = [sum(self.ns)]
> 
>         if len(self._stochastic_variables["scaled"]) == 1:  # TODO correct this when stochastic variables doesn't have a 'scaled' key or it should never happen
> ```

self._states = {"scaled": None, "unscaled": None}  
self._controls = {"scaled": {}, "unscaled": {}}  
self.parameters = {"scaled": {}, "unscaled": {}}  
self._stochastic_variables = {"scaled": {}, "unscaled": {}}
___
*[`tests/shard1/test_controltype_none.py` line 7 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikdhqcCgy6p1Zp-w0P:-NikdhqcCgy6p1Zp-w0Q:b1r2mf7) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/tests/shard1/test_controltype_none.py#L7)):*
> ```Python
> from typing import Callable
> 
> import matplotlib.pyplot as plt
> ```

Do not include plt

**Comment by Kev1CO** [comment]
*[`bioptim/interfaces/solve_ivp_interface.py` line 369 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikOnTB1luZYHm3dzbZ:-Nil-4tY71uTDptMLD4f:bo7le80) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/interfaces/solve_ivp_interface.py#L369)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Remove this
</blockquote></details>

only len(x0.shape) < 2 was necessary, all offline tests went through

**Review by Kev1CO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/799)* status: all files reviewed, 13 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/interfaces/solve_ivp_interface.py` line 369 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikOnTB1luZYHm3dzbZ:-Nil-Dvw8BMAm6eW0D0s:bs7wumb) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/interfaces/solve_ivp_interface.py#L369)):*
<details><summary><i>Previously, Kev1CO wrote…</i></summary><blockquote>

only len(x0.shape) < 2 was necessary, all offline tests went through
</blockquote></details>

Done.
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 370 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikPFn2DohveBajNal_:-Nil-Fzz1GU2frbEU69_:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/interfaces/solve_ivp_interface.py#L370)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

shooting_type == Shooting.SINGLE
</blockquote></details>

Done.
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 371 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikPaycC7_YpZFZ7ElU:-Nil-Hcf6ahb4mWlFRKE:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/interfaces/solve_ivp_interface.py#L371)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

```python
if len(x0.shape) < 2 and (len(x0.shape) != len(u.shape) or shooting_type == Shooting.SINGLE):
```

simplify?
test?
```python
if len(x0.shape) < 2:
```

test this earlier in the code?
```python
if len(x0.shape) < 2:
    # do something to x
if (len(u.shape) < 2:
    # do something to u
```
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 322 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikSXtr7JGgWr4W4Bjm:-Nil-JHz8MIvEgeYwl8e:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L322)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Remove this line
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 348 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikS_1bDzXypIKvuU43:-Nil-OKoBU3wFhLBSeuH:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L348)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

control_type in (ControlType.CONSTANT, ControlType.NONE)
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 361 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikTQzvD6UXe4amNX_V:-Nil-Q-9-INxsYqk565A:brpmqc3) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L361)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should not be necessary at all as "ss.keys()" should be empty
</blockquote></details>

removed.
___
*[`bioptim/optimization/solution/solution.py` line 373 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikU9bd3vdoCsv5Zpwo:-Nil-T5H1zb0SWzwjXKc:b-rca3u2) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L373)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This is peculiar, I think this is a bug on the designing of your OCP
</blockquote></details>

ss.init was I belive a mistake, its ss[key].init. All offline tests went through.
Done.
___
*[`bioptim/optimization/solution/solution.py` line 390 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikUQne8spAT9qnmRzt:-Nil-gei1-I3xuoVx4rU:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L390)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This is definitely not something related to ControlType.NONE
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 565 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikcsoY9Kr4WHpuef2w:-Nil-iKRAYzXmMnSskVp:bqog7zb) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L565)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Not the actual problem
</blockquote></details>

Agree.

**Review by Kev1CO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/799)* status: 0 of 3 files reviewed, 13 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/optimization/solution/solution.py` line 323 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikSRwe2lobfV1vixT-:-Niosq9qEEhaHZDem3dg:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L323)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Add a test for this
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 1474 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-Nikd0hgCkCGMSTev8cd:-NiotQVJAFa86TWeHI6x:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L1474)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

control_type == ControlType.NONE
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 1481 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikddkoCWtxyjVJGVdT:-Niox8WfEmBDNfBSvQg0:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L1481)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

self._states = {"scaled": None, "unscaled": None}  
self._controls = {"scaled": {}, "unscaled": {}}  
self.parameters = {"scaled": {}, "unscaled": {}}  
self._stochastic_variables = {"scaled": {}, "unscaled": {}}
</blockquote></details>

Done.

**Review by Kev1CO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/799)* status: all files reviewed, 6 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/optimization/solution/solution.py` line 322 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikSXtr7JGgWr4W4Bjm:-NjEbzd2Do9UG8wwDj12:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/bioptim/optimization/solution/solution.py#L322)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Line is still there but commented
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 1018 at r4](https://reviewable.io/reviews/pyomeca/bioptim/799#-NjDek4nBrlZTt8tU7Fr:-NjEc0nJ9oERQ2ikRjLs:b46esii) ([raw file](https://github.com/pyomeca/bioptim/blob/857dd3ed7fa669043c9a5ab00b59d5230ff05ea5/bioptim/optimization/solution/solution.py#L1018)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Seems fair, I guess.. not sure why sol and self are not the same actually...
</blockquote></details>

Lets discuss about it during PR review, might have missed something
___
*[`tests/shard1/test_controltype_none.py` line 7 at r1](https://reviewable.io/reviews/pyomeca/bioptim/799#-NikdhqcCgy6p1Zp-w0P:-NjEbNt81jimjhxfy4GH:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0a939368cca01833437b54a041ca1c7e77f6df64/tests/shard1/test_controltype_none.py#L7)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Do not include plt
</blockquote></details>

Done.
___
*[`tests/shard1/test_controltype_none.py` line 377 at r4](https://reviewable.io/reviews/pyomeca/bioptim/799#-NjDgUbSBLbH-bapjor9:-NjEbOwNAWAZYJjcdlnk:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/857dd3ed7fa669043c9a5ab00b59d5230ff05ea5/tests/shard1/test_controltype_none.py#L377)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is this curently the case? If so, please remove. Otherwise make sure you don't messed up the tabulation. It seems p was moved left
</blockquote></details>

Done.
___
*[`tests/shard4/test_solution.py` line 451 at r4](https://reviewable.io/reviews/pyomeca/bioptim/799#-NjDevNyEhdtQ1US6y1e:-NjEbhSB0ZcEhtOvEpR-:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/857dd3ed7fa669043c9a5ab00b59d5230ff05ea5/tests/shard4/test_solution.py#L451)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This is probably legacy for when someone wanted to test the graphs, before we know it is impossible. This can be removed
</blockquote></details>

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/799)* status: all files reviewed, 1 unresolved discussion (waiting on @Kev1CO)

___
*[`bioptim/optimization/solution/solution.py` line 1018 at r4](https://reviewable.io/reviews/pyomeca/bioptim/799#-NjDek4nBrlZTt8tU7Fr:-NjOV-9WBIo9l3XIGWrp:b-hyp1v3) ([raw file](https://github.com/pyomeca/bioptim/blob/857dd3ed7fa669043c9a5ab00b59d5230ff05ea5/bioptim/optimization/solution/solution.py#L1018)):*
<details><summary><i>Previously, Kev1CO wrote…</i></summary><blockquote>

Lets discuss about it during PR review, might have missed something
</blockquote></details>

Discussed verbally...

**Comment by pariterre** [comment]
Any ideas for the failing tests?

**Comment by Kev1CO** [comment]
*[`bioptim/optimization/solution/solution.py` line 1018 at r4](https://reviewable.io/reviews/pyomeca/bioptim/799#-NjDek4nBrlZTt8tU7Fr:-NjOgSRB4m3ywnZIforX:bmuw65) ([raw file](https://github.com/pyomeca/bioptim/blob/857dd3ed7fa669043c9a5ab00b59d5230ff05ea5/bioptim/optimization/solution/solution.py#L1018)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Discussed verbally...
</blockquote></details>

Increases to much the computation time by removing skip data.
Invert self with out instead.
If tests goes through, ready to merge

**Comment by Kev1CO** [comment]
Don't know, seems that for other pr the tests fails aswell. In local, tests goes through.

**Comment by pariterre** [comment]
Closed as the major refactor makes this impossible to merge

**Pull request closed without merging**
