### PR TITLE
[DO NOT MERGE] Stochastic plots, noisy_integrate, and other plot shits

### PR DESCRIPTION
**Pull request by EveCharbie**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request? Issue #812, Issue #695, Issue #594, Issue #579, Issue #693
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/853)

### CODE REVIEW

**Comment by EveCharbie** [comment]
@pariterre I need help handling matplotlib in a multiprocess, it seems like it is blocking somewhere. ChatGPT says it is because I try to update the plots outside of the main thread, but we do it for the regular live plots, so you know how to do it. 
* Please do not open reviewable before I am online with you.

**Comment by pariterre** [comment]
@EveCharbie Yep! We can discuss this today!

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/853)* status: all files reviewed, 15 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/examples/getting_started/pendulum.py` line 139 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvNYVaA8sGge97_xCZ:-NrvNYVaA8sGge97_xC_:b-wml7yl) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/examples/getting_started/pendulum.py#L139)):*
> ```Python
> 
>     import sys
>     sys.stdout = open('/home/charbie/Documents/Programmation/BiorbdOptim/bioptim/optimization/ipopt_output.txt', 'w')
> ```

Don't forget to remove this
___
*[`bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py` line 377 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvNqHH5ZnKHML4aZSZ:-NrvNqHH5ZnKHML4aZS_:bn545k8) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py#L377)):*
> ```Python
>     filename = "obstacle.pkl"
>     # if os.path.exists(filename):
>     #     # Open the file and load the content
> ```

Reinstate? Remove!
___
*[`bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py` line 479 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvOMl00hS23EqgfF3C:-NrvOMl00hS23EqgfF3D:b-kab8g6) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py#L479)):*
> ```Python
>                 np.random.normal(loc=0, scale=motor_noise_magnitude[1], size=(1, n_shooting, iter)),
>             ]
>         )
> ```

Move this in a function
___
*[`bioptim/gui/plot.py` line 418 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvQfK_-JP6ojSsbjyu:-NrvQfK_-JP6ojSsbjyv:b-bl058s) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/gui/plot.py#L418)):*
> ```Python
>                 mapping_to_first_index = nlp.plot[variable].phase_mappings.to_first.map_idx
>                 for ctr in mapping_to_first_index:
>                     if not nlp.plot[variable].all_variables_in_one_subplot:
> ```

Test using the mapping to see if we can get rid of the use of all_variables_in_one_subplot
___
*[`bioptim/gui/plot.py` line 434 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvR5xO01J4MMLquJAW:-NrvR5xO01J4MMLquJAX:bqgog0n) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/gui/plot.py#L434)):*
> ```Python
>                         self.show_bounds
>                         and nlp.plot[variable].bounds
>                         and not nlp.plot[variable].all_variables_in_one_subplot
> ```

see if nlp.plot[variable].bounds can be empty for your case
___
*[`bioptim/interfaces/ipopt_options.py` line 95 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvUkn3AiafuloH9FB9:-NrvUkn3AiafuloH9FBA:bfv0pna) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/interfaces/ipopt_options.py#L95)):*
> ```Python
>     _print_level: int = 5
>     _c_compile: bool = False
>     _check_derivatives_for_naninf: str = "no"  # "no", "yes"
> ```

Add test
___
*[`bioptim/interfaces/ipopt_options.py` line 269 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvUoDZAUOPXr7Pj8g8:-NrvUoDZAUOPXr7Pj8g9:botp0j7) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/interfaces/ipopt_options.py#L269)):*
> ```Python
>         self._c_compile = val
> 
>     def set_check_derivatives_for_naninf(self, val: str):
> ```

Pass a bool
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 20 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvWpIY6VBgtOELlin_:-NrvWpIZ725foxaAVvhi:b-pvaa3m) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/interfaces/solve_ivp_interface.py#L20)):*
> ```Python
>     a: list[np.ndarray],
>     method: SolutionIntegrator = SolutionIntegrator.SCIPY_RK45,
>     noised: bool = False,
> ```

Do not pass `is_noised` but the actual list of dynamics to integrate
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 82 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvWhYzESMn4uvcdUHO:-NrvWhYzESMn4uvcdUHP:bjxfm44) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/interfaces/solve_ivp_interface.py#L82)):*
> ```Python
>             if noised:
>                 func = (
>                     nlp.dynamics_func[1]
> ```

extra_dynamics should have its own attribute
Compute the p outside using a casadi.Function
___
*[`bioptim/limits/penalty_option.py` line 427 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvZ4ycCADUN9nasDL_:-NrvZ4ycCADUN9nasDLa:b-qgwowm) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/limits/penalty_option.py#L427)):*
> ```Python
>         if len(sub_fcn.shape) > 1:
>             if sub_fcn.shape[0] != 1 and sub_fcn.shape[1] != 1:  # @pariterre: is it only the first condition or both?
>                 raise RuntimeError("The penalty must return a vector not a matrix.")
> ```

should be used as such: `sub_func[:, 0]`
___
*[`bioptim/limits/penalty_option.py` line 856 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvZIc21aN3dH2VsY3m:-NrvZIc21aN3dH2VsY3n:b-7f0hfc) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/limits/penalty_option.py#L856)):*
> ```Python
>             if self.integrate and self.target is not None:
>                 self.node_idx = controllers[0].t[:-1]
>                 if node not in self.node_idx:
> ```

Yes this going to change the value of some test
___
*[`bioptim/optimization/optimal_control_program.py` line 1306 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-Nrv_-gx4HSGEUdld5Gh:-Nrv_-gx4HSGEUdld5Gi:byzujvj) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/optimization/optimal_control_program.py#L1306)):*
> ```Python
>         return
> 
>     def add_plot_ipopt_outputs(self):
> ```

Recompute
___
*[`bioptim/optimization/solution/solution.py` line 765 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-Nrv_5Gn1XbKkIlThVxC:-Nrv_5Gn1XbKkIlThVxD:b-l7h4i3) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/optimization/solution/solution.py#L765)):*
> ```Python
>         """
>         TODO: Charbie!
>         """
> ```

You can import here
___
*[`bioptim/optimization/solution/solution.py` line 766 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-Nrv_8xW7cqBqgg6-FxB:-Nrv_8xW7cqBqgg6-FxC:b-l4mncz) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/optimization/solution/solution.py#L766)):*
> ```Python
>         TODO: Charbie!
>         """
>         if "cov" not in self.ocp.nlp[0].algebraic_states.keys():
> ```

use isinstance
___
*[`bioptim/optimization/solution/solution_data.py` line 253 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-Nrva9N78GVmNKemeUeV:-Nrva9N78GVmNKemeUeW:b-eaxcjr) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/optimization/solution/solution_data.py#L253)):*
> ```Python
>                     else:
>                         value = unscaled[phase][key][node]
>                         scaled[phase][key][node] = value / scale_factor.to_array(value.shape[1])
> ```

np.repeat the denomimator instead of using a for loop

**Review by EveCharbie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/853)* status: 13 of 16 files reviewed, 15 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/getting_started/pendulum.py` line 139 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvNYVaA8sGge97_xCZ:-Nrvvtin7GrPXLdxkWVc:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/examples/getting_started/pendulum.py#L139)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Don't forget to remove this
</blockquote></details>

Done.
___
*[`bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py` line 377 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvNqHH5ZnKHML4aZSZ:-Nrvw5Rf0LbbtEwUoGdQ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py#L377)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Reinstate? Remove!
</blockquote></details>

Done.
___
*[`bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py` line 479 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvOMl00hS23EqgfF3C:-NrvwkCb2r5anevcMVxx:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py#L479)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Move this in a function
</blockquote></details>

Done.
___
*[`bioptim/gui/plot.py` line 418 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvQfK_-JP6ojSsbjyu:-Nrw-XaqEFGcudnWvB6L:b-83797w) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/gui/plot.py#L418)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Test using the mapping to see if we can get rid of the use of all_variables_in_one_subplot
</blockquote></details>

Tried it but it did not work :(
I tried to fix it, but it seems a lot of work.
___
*[`bioptim/gui/plot.py` line 434 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvR5xO01J4MMLquJAW:-Nrw-gjPA1NpK86fgS5E:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/gui/plot.py#L434)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

see if nlp.plot[variable].bounds can be empty for your case
</blockquote></details>

Done.
___
*[`bioptim/interfaces/ipopt_options.py` line 95 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvUkn3AiafuloH9FB9:-Ns8qMD33joQS5mpA2BS:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/interfaces/ipopt_options.py#L95)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Add test
</blockquote></details>

Done.
___
*[`bioptim/interfaces/ipopt_options.py` line 269 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvUoDZAUOPXr7Pj8g8:-Nrw1TG91gKsJtDKV8eX:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/interfaces/ipopt_options.py#L269)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Pass a bool
</blockquote></details>

Done.
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 20 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvWpIY6VBgtOELlin_:-Ns9VobNDvFuCN1dBwfA:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/interfaces/solve_ivp_interface.py#L20)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Do not pass `is_noised` but the actual list of dynamics to integrate
</blockquote></details>

Done.
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 82 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvWhYzESMn4uvcdUHO:-Ns9Vqfj3yqrA5b17xO0:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/interfaces/solve_ivp_interface.py#L82)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

extra_dynamics should have its own attribute
Compute the p outside using a casadi.Function
</blockquote></details>

Done.
___
*[`bioptim/limits/penalty_option.py` line 427 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvZ4ycCADUN9nasDL_:-Nrw1tJb6erCldo-qDAE:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/limits/penalty_option.py#L427)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

should be used as such: `sub_func[:, 0]`
</blockquote></details>

Done.
___
*[`bioptim/limits/penalty_option.py` line 856 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvZIc21aN3dH2VsY3m:-Nrw2C24EmljW75OZhZb:bd9btni) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/limits/penalty_option.py#L856)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Yes this going to change the value of some test
</blockquote></details>

Will not do it in this PR then
___
*[`bioptim/optimization/optimal_control_program.py` line 1306 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-Nrv_-gx4HSGEUdld5Gh:-NsAx8Sg0j1rlUc55akK:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/optimization/optimal_control_program.py#L1306)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Recompute
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 765 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-Nrv_5Gn1XbKkIlThVxC:-Nrw2yNVBcIsFVKexd32:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/optimization/solution/solution.py#L765)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

You can import here
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution.py` line 766 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-Nrv_8xW7cqBqgg6-FxB:-Nrw2ycz7fP0VcfoJ48a:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/optimization/solution/solution.py#L766)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

use isinstance
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution/solution_data.py` line 253 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-Nrva9N78GVmNKemeUeV:-Ns8lDYb5oPD1ewfzYoM:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/optimization/solution/solution_data.py#L253)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

np.repeat the denomimator instead of using a for loop
</blockquote></details>

Done.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 9 of 20 files at r3, 23 of 26 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/853)* status: 40 of 41 files reviewed, 11 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/gui/plot.py` line 418 at r1](https://reviewable.io/reviews/pyomeca/bioptim/853#-NrvQfK_-JP6ojSsbjyu:-NtMzRw7DE6xB_VQejAL:b9qlx86) ([raw file](https://github.com/pyomeca/bioptim/blob/c2d4094835001ae6a6220c1d273e953a023c48de/bioptim/gui/plot.py#L418)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

Tried it but it did not work :(
I tried to fix it, but it seems a lot of work.
</blockquote></details>

Add a todo?
___
*[`bioptim/interfaces/interface_utils.py` line 232 at r5](https://reviewable.io/reviews/pyomeca/bioptim/853#-NtN0DjZ2SSo5b1HXdAu:-NtN0DjZ2SSo5b1HXdAv:b-l6hdjr) ([raw file](https://github.com/pyomeca/bioptim/blob/57a7d1309858b5b9bb5a9d9b90beadbcbb2340e8/bioptim/interfaces/interface_utils.py#L232)):*
> ```Python
>     all_objectives = interface.ocp.cx()
>     all_objectives = vertcat(all_objectives, interface.get_all_penalties(interface.ocp, interface.ocp.J_internal))
>     all_objectives = vertcat(all_objectives, interface.get_all_penalties(interface.ocp, interface.ocp.J))
> ```

revert
___
*[`bioptim/limits/constraints.py` line 135 at r5](https://reviewable.io/reviews/pyomeca/bioptim/853#-NtN0R_0EmSbcrScnu18:-NtN0R_0EmSbcrScnu19:b2kxtuk) ([raw file](https://github.com/pyomeca/bioptim/blob/57a7d1309858b5b9bb5a9d9b90beadbcbb2340e8/bioptim/limits/constraints.py#L135)):*
> ```Python
>         #         self.list_index = len(pool) - 1
>         #     else:
>         #         raise RuntimeError(f"The penalty index {self.list_index} is already used.")
> ```

To be removed?
___
*[`bioptim/limits/constraints.py` line 1240 at r5](https://reviewable.io/reviews/pyomeca/bioptim/853#-NtN0Y3t6nTSqvqx6WyT:-NtN0Y3t6nTSqvqx6WyU:b2kxtuk) ([raw file](https://github.com/pyomeca/bioptim/blob/57a7d1309858b5b9bb5a9d9b90beadbcbb2340e8/bioptim/limits/constraints.py#L1240)):*
> ```Python
>         #     pool[-1] = self
>         # else:
>         #     pool.append(self)
> ```

To be removed?
___
*[`bioptim/limits/multinode_penalty.py` line 95 at r5](https://reviewable.io/reviews/pyomeca/bioptim/853#-NtN1SShDX-HAYJm92GB:-NtN1SSiAn4gExTBY212:b2kxtuk) ([raw file](https://github.com/pyomeca/bioptim/blob/57a7d1309858b5b9bb5a9d9b90beadbcbb2340e8/bioptim/limits/multinode_penalty.py#L95)):*
> ```Python
>         #     pool[-1] = self
>         # else:
>         #     pool.append(self)
> ```

To be removed?
___
*[`bioptim/limits/objective_functions.py` line 97 at r5](https://reviewable.io/reviews/pyomeca/bioptim/853#-NtN1kNu7SmNQe4Y9s9k:-NtN1kNu7SmNQe4Y9s9l:b2kxtuk) ([raw file](https://github.com/pyomeca/bioptim/blob/57a7d1309858b5b9bb5a9d9b90beadbcbb2340e8/bioptim/limits/objective_functions.py#L97)):*
> ```Python
>         #     pool[-1] = self
>         # else:
>         #     pool.append(self)
> ```

To be removed?
___
*[`bioptim/limits/objective_functions.py` line 511 at r5](https://reviewable.io/reviews/pyomeca/bioptim/853#-NtN1mM66HGZ_boUnONf:-NtN1mM66HGZ_boUnONg:b2kxtuk) ([raw file](https://github.com/pyomeca/bioptim/blob/57a7d1309858b5b9bb5a9d9b90beadbcbb2340e8/bioptim/limits/objective_functions.py#L511)):*
> ```Python
>         #     pool[-1] = self
>         # else:
>         #     pool.append(self)
> ```

To be removed?
___
*[`bioptim/limits/penalty.py` line 238 at r5](https://reviewable.io/reviews/pyomeca/bioptim/853#-NtN1pZu7KOPA8LAMYa5:-NtN1pZu7KOPA8LAMYa6:b-l6hdjr) ([raw file](https://github.com/pyomeca/bioptim/blob/57a7d1309858b5b9bb5a9d9b90beadbcbb2340e8/bioptim/limits/penalty.py#L238)):*
> ```Python
>             # else:
>             expectedEffort_fb_mx = trace_jac_p_jack + trace_k_sensor_k
>             # penalty.quadratic = False
> ```

revert
___
*[`tests/shard6/test_global_stochastic_except_collocation.py` line 33 at r5](https://reviewable.io/reviews/pyomeca/bioptim/853#-NtN35I16wH_pUacCic4:-NtN35I16wH_pUacCic5:b4go7ja) ([raw file](https://github.com/pyomeca/bioptim/blob/45ff4320fc1a8ebf9ef9e671310dfc9e27c68a65/tests/shard6/test_global_stochastic_except_collocation.py#L33)):*
> ```Python
> 
>     if use_sx:
>         with pytest.raises(RuntimeError, match=".*eval_sx not defined for LinsolQr"):
> ```

(revert back these)
___
*[`tests/shard6/test_global_stochastic_except_collocation.py` line 41 at r5](https://reviewable.io/reviews/pyomeca/bioptim/853#-NtN2nFp18I5f2I0UQKZ:-NtN2nFp18I5f2I0UQK_:b4gd841) ([raw file](https://github.com/pyomeca/bioptim/blob/57a7d1309858b5b9bb5a9d9b90beadbcbb2340e8/tests/shard6/test_global_stochastic_except_collocation.py#L41)):*
> ```Python
>                 ".../casadi/core/linsol_internal.cpp:65: eval_sx not defined for LinsolQr"
>             )
>         with pytest.raises(RuntimeError, match=match):
> ```

Revert back my changes
___
*[`tests/shard6/test_global_stochastic_except_collocation.py` line 288 at r5](https://reviewable.io/reviews/pyomeca/bioptim/853#-NtN2k096UciNSKvIfZa:-NtN2k096UciNSKvIfZb:b4gd841) ([raw file](https://github.com/pyomeca/bioptim/blob/57a7d1309858b5b9bb5a9d9b90beadbcbb2340e8/tests/shard6/test_global_stochastic_except_collocation.py#L288)):*
> ```Python
>                 ".../casadi/core/linsol_internal.cpp:65: eval_sx not defined for LinsolQr"
>             )
>         with pytest.raises(RuntimeError, match=match):
> ```

Revert back my changes

**Comment by EveCharbie** [comment]
@pariterre I think we are good to merge if all the tests pass :)

**Comment by EveCharbie** [comment]
@pariterre shard 1 is really slow to run on Ubuntu.

**Comment by EveCharbie** [comment]
@pariterre it's good now :)

**Comment by pariterre** [comment]
Closed as merged in #867

**Pull request closed without merging**
